// Generated by scripts/import-ct-curriculum.ts. Do not edit by hand.
import type { RangePack } from '../types';

const expand = (value: string): string[] => value.split(' ');

const pack: RangePack = {
  slug: '3-bet-pot-sb-btn-flop-baseline',
  title: '3-bet pot: SB vs BTN - Flop (40bb)',
  description: 'Board-aware postflop practice in three-bet pots.',
  scenario: '3BET_POT',
  street: 'flop',
  tier: 'advanced',
  methodology: 'gto_cev',
  source: {
    kind: 'brand_neutralized_snapshot_config',
    capturedAt: '2026-07-18',
    path: 'research/ct-trainer-2026-07-18/',
    sha256: 'ea304f2040692ed8cacbf164542ffea26782c1a1bef03da995a4eceba4f126d2'
  },
  cells: [
    {
      position: 'SB',
      stackBb: 40,
      villainPosition: 'BTN',
      board: [
        '8h',
        '6h',
        '5d'
      ],
      heroStackSize: 31.4,
      villainStackSize: 31.4,
      actionLine: 'preflop: BTN raises 2.3bb, SB raises 8.6bb, BTN calls 8.6bb',
      dealCombos: expand('4d4c 4s4c 4s4d 5h5c 5s5c 5s5h 6d6c 6s6c 6s6d 7d7c 7h7c 7h7d 7s7c 7s7d 7s7h 8d8c 8s8c 8s8d 9d9c 9h9c 9h9d 9s9c 9s9d 9s9h Ac5h Ac5s Ac6d Ac6s Ac7d Ac7h Ac7s Ac8d Ac9d Ac9h Ac9s AcJc AcJd AcJh AcJs AcKc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad5c Ad5h Ad5s Ad6c Ad6s Ad7c Ad7h Ad7s Ad8c Ad8d Ad8s Ad9c Ad9h Ad9s AdAc AdJc AdJd AdJh AdJs AdKc AdKd AdKh AdKs AdQd AdQh AdTc AdTd AdTs Ah5c Ah5s Ah6c Ah6d Ah6s Ah7c Ah7d Ah7s Ah8c Ah8d Ah8s Ah9c Ah9d Ah9s AhAc AhAd AhJc AhJd AhJh AhJs AhKc AhKd AhKh AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs As5c As5h As6c As6d As7c As7d As7h As8d As9c As9d As9h AsAc AsAd AsAh AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs JcTd JcTh JcTs Jd8d JdJc JdTc JdTh JdTs JhJc JhJd JhTc JhTd JhTs JsJc JsJd JsJh JsTc JsTd JsTh Kc3c Kc4c Kc6c Kc9s KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTd KcTh KcTs Kd3d Kd4d Kd6d Kd9h KdJc KdJh KdJs KdKc KdQc KdQd KdQh KdQs KdTc KdTd KdTh KdTs Kh3h Kh4h KhJc KhJd KhJs KhKc KhKd KhQc KhQd KhQh KhQs KhTc KhTd KhTh KhTs Ks3s Ks4s Ks6s Ks9c KsJc KsJd KsJh KsKc KsKd KsKh KsQc KsQd KsQh KsQs KsTc KsTd KsTh Qc6c Qc7c QcJc QcJd QcJh QcJs QcTd QcTh QcTs Qd6d Qd7d QdJc QdJd QdJh QdJs QdQc QdTc QdTh QdTs Qh7h QhJc QhJd QhJh QhJs QhQc QhQd QhTc QhTd QhTs Qs6s Qs7s QsJc QsJd QsJh QsJs QsQc QsQd QsQh QsTc QsTd QsTh TdTc ThTc ThTd TsTc TsTd TsTh'),
      buckets: [
        {
          actions: [
            'bet_10pct'
          ],
          combos: expand('8d8c 8s8c 8s8d Ac7d Ac7s AcJc AcKh AcTc Ad7c Ad7s AdAc AdJc AdJd AdJs AdKd AdKh AdTd Ah7c Ah7d Ah7s AhAc AhAd AhJd AhJh AhKh AhQh AhTh As7c As7d AsAc AsAd AsAh AsJs AsKh AsTs JhTd KcJh KcQc KcQd KcQh KcQs KdJh KdQc KdQd KdQh KdQs KhJd KhKc KhKd KhQc KhQd KhQh KhQs KsJh KsKh KsQc KsQd KsQh KsQs Qc7c Qd6d Qd7d QdJd Qs7s')
        },
        {
          actions: [
            'bet_25pct'
          ],
          combos: expand('4d4c 4s4c 4s4d 5h5c 5s5c 5s5h 6d6c 6s6c 6s6d 8d8c 8s8c 8s8d Ac7d Ac7s Ac9d Ac9s AcJc AcJh AcJs AcKc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTs Ad7c Ad7s Ad9c Ad9s AdAc AdJd AdJh AdKc AdKd AdKh AdKs AdQd AdQh AdTd Ah5c Ah5s Ah7c Ah7d Ah7s Ah9c Ah9d Ah9s AhAc AhAd AhJc AhJd AhJh AhJs AhKc AhKd AhKh AhKs AhQc AhQd AhQh AhQs AhTh As7c As7d As9c As9d AsAc AsAd AsAh AsJc AsJh AsJs AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTc AsTs JcTh JdTh JhJc JhJd JhTc JhTd JhTs JsJh JsTh Kc4c KcJd KcJh KcJs KcQc KcQd KcQh KcTd KcTh KcTs Kd3d Kd4d Kd6d KdJc KdJh KdJs KdKc KdQc KdQh KdQs KdTc KdTh KdTs Kh3h Kh4h KhJc KhJd KhJs KhKc KhKd KhQd KhTc KhTd KhTh KhTs Ks4s KsJc KsJd KsJh KsKc KsKd KsKh KsQd KsQh KsQs KsTc KsTd KsTh Qc6c Qc7c QcJd QcJh QcTd QcTh QcTs Qd6d Qd7d QdJc QdJd QdJh QdJs QdQc QdTc QdTh QdTs Qh7h QhJc QhJd QhJh QhJs QhQc QhQd QhTc QhTd QhTs Qs6s Qs7s QsJd QsJh QsQc QsQd QsQh QsTc QsTd QsTh')
        },
        {
          actions: [
            'bet_50pct'
          ],
          combos: expand('7d7c 7h7c 7h7d 7s7c 7s7d 7s7h 9d9c 9h9c 9h9d 9s9c 9s9d 9s9h Ac5h Ac5s Ac6d Ac6s Ac7d Ac7h Ac7s Ac8d Ac9d Ac9h Ac9s AcJc AcJd AcJs AcKc AcKd AcKh AcKs AcQc AcTc AcTd AcTh AcTs Ad5c Ad5h Ad5s Ad6c Ad6s Ad7c Ad7h Ad7s Ad8c Ad8d Ad8s Ad9c Ad9h Ad9s AdJc AdJd AdJs AdKc AdKh AdKs AdTc AdTd AdTs Ah5c Ah5s Ah6c Ah6d Ah6s Ah7c Ah7d Ah7s Ah8c Ah8d Ah8s Ah9c Ah9d Ah9s AhTc AhTd AhTs As5c As5h As6c As6d As7c As7d As7h As8d As9c As9d As9h AsJc AsJd AsJs AsKc AsKd AsKh AsKs AsQs AsTc AsTd AsTh AsTs JcTd JcTh Jd8d JdJc JdTc JdTs JhJc JhJd JhTc JhTs JsJc JsJd JsJh JsTd JsTh Kc3c Kc6c KcJd KcJh KcTd KcTh KcTs Kd6d KdJc KdJh KdJs KdTc KdTh KdTs KhJc KhJs Ks3s Ks6s KsJd KsJh KsTc KsTd KsTh Qc6c QcJc QcJd QcJh QcJs QcTd QcTh QcTs Qd6d QdJc QdJh QdJs QdQc QdTc QdTh QdTs QhJc QhJd QhJs Qs6s QsJc QsJd QsJh QsJs QsQc QsQd QsTc QsTd QsTh TdTc ThTc ThTd TsTc TsTd TsTh')
        },
        {
          actions: [
            'check'
          ],
          combos: expand('6s6c 8d8c 8s8c 8s8d 9d9c 9s9d Ac7d Ac7s Ac9d Ac9s AcJc AcJd AcJh AcJs AcKc AcKh AcKs AcQc AcTc AcTd AcTh AcTs Ad7c Ad7s Ad9c Ad9s AdAc AdJc AdJd AdJh AdJs AdKc AdKd AdKh AdKs AdQd AdTd Ah7c Ah7d Ah7s AhAc AhAd AhJc AhJd AhJh AhJs AhKc AhKd AhKh AhKs AhQh AhTh As7c As7d As9c As9d AsAc AsAd AsAh AsJc AsJd AsJh AsJs AsKc AsKh AsKs AsQs AsTc AsTd AsTh AsTs JcTd JcTh JcTs JdJc JdTc JdTh JdTs JhTc JhTd JhTs JsJc JsJd JsTc JsTd JsTh Kc9s KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTd KcTs Kd9h KdJc KdJh KdJs KdKc KdQc KdQd KdQh KdQs KdTc KdTd KdTs Kh3h Kh4h KhJc KhJd KhJs KhKc KhKd KhQc KhQd KhQh KhQs KhTc KhTd KhTh KhTs Ks9c KsJc KsJd KsJh KsKc KsKd KsKh KsQc KsQd KsQh KsQs KsTc KsTd Qc6c Qc7c QcJc QcJd QcJs QcTd QcTs Qd6d Qd7d QdJc QdJd QdJs QdQc QdTc QdTs QhJc QhJh QhJs QhQc QhQd QhTc QhTd QhTs Qs6s Qs7s QsJc QsJd QsJs QsQc QsQd QsQh QsTc QsTd')
        }
      ]
    },
    {
      position: 'SB',
      stackBb: 40,
      villainPosition: 'BTN',
      board: [
        '9h',
        '8d',
        '7c'
      ],
      heroStackSize: 31.4,
      villainStackSize: 31.4,
      actionLine: 'preflop: BTN raises 2.3bb, SB raises 8.6bb, BTN calls 8.6bb',
      dealCombos: expand('4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6d6c 6h6c 6h6d 6s6c 6s6d 6s6h 7h7d 7s7d 7s7h 8h8c 8s8c 8s8h 9d9c 9s9c 9s9d Ac5d Ac5h Ac5s Ac6d Ac6h Ac6s Ac7d Ac7h Ac7s Ac8c Ac8h Ac8s Ac9d Ac9s AcJc AcJd AcJh AcJs AcKc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad5c Ad5h Ad5s Ad6c Ad6h Ad6s Ad7h Ad7s Ad8c Ad8h Ad8s Ad9c Ad9s AdAc AdJc AdJd AdJh AdJs AdKc AdKd AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah5c Ah5d Ah5s Ah6c Ah6d Ah6s Ah7d Ah7s Ah8c Ah8h Ah8s Ah9c Ah9d Ah9s AhAc AhAd AhJc AhJd AhJh AhJs AhKc AhKd AhKh AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs As5c As5d As5h As6c As6d As6h As7d As7h As8c As8h As8s As9c As9d AsAc AsAd AsAh AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc8c JcTd JcTh JcTs JdJc JdTc JdTh JdTs Jh8h JhJc JhJd JhTc JhTd JhTs Js8s JsJc JsJd JsJh JsTc JsTd JsTh Kc3c Kc4c Kc6c Kc9d Kc9s KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc KcTd KcTh KcTs Kd3d Kd4d Kd6d Kd9c Kd9s KdJc KdJh KdJs KdKc KdQc KdQd KdQh KdQs KdTc KdTd KdTh KdTs Kh3h Kh4h Kh6h Kh9c Kh9d Kh9s KhJc KhJd KhJs KhKc KhKd KhQc KhQd KhQh KhQs KhTc KhTd KhTh KhTs Ks3s Ks4s Ks6s Ks9c Ks9d KsJc KsJd KsJh KsKc KsKd KsKh KsQc KsQd KsQh KsQs KsTc KsTd KsTh KsTs Qc5c Qc6c QcJc QcJd QcJh QcJs QcTd QcTh QcTs Qd5d Qd6d Qd7d QdJc QdJd QdJh QdJs QdQc QdTc QdTh QdTs Qh5h Qh6h Qh7h QhJc QhJd QhJh QhJs QhQc QhQd QhTc QhTd QhTs Qs5s Qs6s Qs7s QsJc QsJd QsJh QsJs QsQc QsQd QsQh QsTc QsTd QsTh TdTc ThTc ThTd TsTc TsTd TsTh'),
      buckets: [
        {
          actions: [
            'all_in'
          ],
          combos: expand('6d6c 6h6c 6h6d 6s6c 6s6d 6s6h 9d9c Ac6d Ac6h Ac6s Ac7h Ac7s Ac8c Ac8h Ac8s Ac9d Ac9s AcJc AcJd AcJh AcJs AcKc AcQc AcTc Ad6c Ad6h Ad6s Ad8c Ad8h Ad8s Ad9c Ad9s AdAc AdJc AdJd AdJh AdJs AdKd AdQd AdTd Ah6c Ah6d Ah6s Ah7s Ah8c Ah8h Ah8s Ah9c Ah9d Ah9s AhAc AhJc AhJd AhJh AhJs AhKh AhQh AhTh As6c As6d As6h As7h As8c As8h As8s As9c As9d AsAc AsAd AsAh AsJc AsJd AsJh AsJs AsKs AsTs Jc8c JdJc Jh8h JhJc JhJd Js8s JsJc JsJd JsJh Kc6c Kc9d Kc9s KcJs KcTc KcTd KcTh KcTs Kd6d Kd9c Kd9s KdJs KdKc KdTc KdTd KdTh KdTs Kh6h Kh9c Kh9d Kh9s KhJc KhJs KhKc KhKd KhTc KhTd KhTh KhTs KsJc KsJd KsKc KsTc KsTd KsTh KsTs QcTh QcTs QdQc QdTc QdTh QdTs QhQc QhQd QhTc QhTd QhTs QsQc QsQd QsQh QsTc QsTd QsTh TdTc ThTc ThTd TsTc TsTd TsTh')
        },
        {
          actions: [
            'bet_75pct'
          ],
          combos: expand('6s6c 6s6d Ac6d Ac6h Ac7d Ac7s Ac8h Ac8s AcJd AcJh AcKc AcQc Ad8c Ad8h Ad8s AdAc AdKd AdQd Ah6c Ah7s Ah8c Ah8s AhAc AhQh As7h As8c As8h As9d AsKs Jc8c JdJc Jh8h Js8s JsJd Kd6d Kh6h KhJs Ks6s Ks9d KsJc KsJd KsKc KsKd KsKh QcTh QhTd')
        },
        {
          actions: [
            'check'
          ],
          combos: expand('4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 7h7d 7s7d 7s7h 8h8c 8s8c 8s8h 9d9c 9s9c 9s9d Ac5d Ac5h Ac5s Ac7d AcKd AcKh AcKs AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad5c Ad5h Ad5s Ad7h Ad7s AdAc AdKc AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah5c Ah5d Ah5s Ah7d Ah7s AhAc AhAd AhKc AhKd AhKs AhQc AhQd AhQs AhTc AhTd AhTh AhTs As5c As5d As5h As7d As7h AsAc AsAd AsAh AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs JcTd JcTh JcTs JdTc JdTh JdTs JhTc JhTd JhTs JsTc JsTd JsTh Kc3c Kc4c KcJd KcJh KcJs KcQc KcQd KcQh KcQs Kd3d Kd4d KdJc KdJh KdJs KdKc KdQc KdQd KdQh KdQs Kh3h Kh4h KhJc KhJd KhJs KhKc KhKd KhQc KhQd KhQh KhQs Ks3s Ks4s Ks6s Ks9c KsJc KsJd KsJh KsKc KsKd KsKh KsQc KsQd KsQh KsQs Qc5c Qc6c QcJc QcJd QcJh QcJs QcTd QcTh QcTs Qd5d Qd6d Qd7d QdJc QdJd QdJh QdJs QdTc QdTh QdTs Qh5h Qh6h Qh7h QhJc QhJd QhJh QhJs QhTd Qs5s Qs6s Qs7s QsJc QsJd QsJh QsJs QsQc QsQd QsQh TdTc ThTc ThTd TsTc TsTd TsTh')
        }
      ]
    },
    {
      position: 'SB',
      stackBb: 40,
      villainPosition: 'BTN',
      board: [
        'Ah',
        '6h',
        '3h'
      ],
      heroStackSize: 31.4,
      villainStackSize: 31.4,
      actionLine: 'preflop: BTN raises 2.3bb, SB raises 8.6bb, BTN calls 8.6bb',
      dealCombos: expand('4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6d6c 6s6c 6s6d 7d7c 7h7c 7h7d 7s7c 7s7d 7s7h 8d8c 8h8c 8h8d 8s8c 8s8d 8s8h 9d9c 9h9c 9h9d 9s9c 9s9d 9s9h Ac5d Ac5h Ac5s Ac6d Ac6s Ac7d Ac7h Ac7s Ac8c Ac8d Ac8h Ac8s Ac9d Ac9h Ac9s AcJc AcJd AcJh AcJs AcKc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad5c Ad5h Ad5s Ad6c Ad6s Ad7c Ad7h Ad7s Ad8c Ad8d Ad8h Ad8s Ad9c Ad9h Ad9s AdAc AdJc AdJd AdJh AdJs AdKc AdKd AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs As5c As5d As5h As6c As6d As7c As7d As7h As8c As8d As8h As8s As9c As9d As9h AsAc AsAd AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc8c JcTd JcTh JcTs Jd8d JdJc JdTc JdTh JdTs Jh8h JhJc JhJd JhTc JhTd JhTs Js8s JsJc JsJd JsJh JsTc JsTd JsTh Kc3c Kc4c Kc6c Kc9d Kc9h Kc9s KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc KcTd KcTh KcTs Kd3d Kd4d Kd6d Kd9c Kd9h Kd9s KdJc KdJh KdJs KdKc KdQc KdQd KdQh KdQs KdTc KdTd KdTh KdTs Kh4h Kh9c Kh9d Kh9s KhJc KhJd KhJs KhKc KhKd KhQc KhQd KhQh KhQs KhTc KhTd KhTh KhTs Ks3s Ks4s Ks6s Ks9c Ks9d Ks9h KsJc KsJd KsJh KsKc KsKd KsKh KsQc KsQd KsQh KsQs KsTc KsTd KsTh KsTs Qc6c Qc7c QcJc QcJd QcJh QcJs QcTd QcTh QcTs Qd6d Qd7d QdJc QdJd QdJh QdJs QdQc QdTc QdTh QdTs Qh5h Qh7h QhJc QhJd QhJh QhJs QhQc QhQd QhTc QhTd QhTs Qs6s Qs7s QsJc QsJd QsJh QsJs QsQc QsQd QsQh QsTc QsTd QsTh TdTc ThTc ThTd TsTc TsTd TsTh'),
      buckets: [
        {
          actions: [
            'bet_10pct'
          ],
          combos: expand('4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6d6c 6s6c 6s6d 7d7c 7h7c 7h7d 7s7c 7s7d 7s7h 8d8c 8h8c 8h8d 8s8c 8s8d 8s8h 9d9c 9h9c 9h9d 9s9c 9s9d 9s9h Ac5d Ac5h Ac5s Ac6d Ac6s Ac7d Ac7h Ac7s Ac8c Ac8d Ac8h Ac8s Ac9d Ac9h Ac9s AcJc AcJd AcJh AcJs AcKc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad5c Ad5h Ad5s Ad6c Ad6s Ad7c Ad7h Ad7s Ad8c Ad8d Ad8h Ad8s Ad9c Ad9h Ad9s AdAc AdJc AdJd AdJh AdJs AdKc AdKd AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs As5c As5d As5h As6c As6d As7c As7d As7h As8c As8d As8h As8s As9c As9d As9h AsAc AsAd AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc8c JcTd JcTh JcTs Jd8d JdJc JdTc JdTh JdTs Jh8h JhJc JhJd JhTc JhTd JhTs Js8s JsJc JsJd JsJh JsTc JsTd JsTh Kc3c Kc4c Kc6c Kc9d Kc9h Kc9s KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc KcTd KcTh KcTs Kd3d Kd4d Kd6d Kd9c Kd9h Kd9s KdJc KdJh KdJs KdKc KdQc KdQd KdQh KdQs KdTc KdTd KdTh KdTs Kh4h Kh9c Kh9d Kh9s KhJc KhJd KhJs KhKc KhKd KhQc KhQd KhQh KhQs KhTc KhTd KhTh KhTs Ks3s Ks4s Ks6s Ks9c Ks9d Ks9h KsJc KsJd KsJh KsKc KsKd KsKh KsQc KsQd KsQh KsQs KsTc KsTd KsTh KsTs Qc6c Qc7c QcJc QcJd QcJh QcJs QcTd QcTh QcTs Qd6d Qd7d QdJc QdJd QdJh QdJs QdQc QdTc QdTh QdTs Qh5h Qh7h QhJc QhJd QhJh QhJs QhQc QhQd QhTc QhTd QhTs Qs6s Qs7s QsJc QsJd QsJh QsJs QsQc QsQd QsQh QsTc QsTd QsTh TdTc ThTc ThTd TsTc TsTd TsTh')
        },
        {
          actions: [
            'bet_25pct'
          ],
          combos: expand('4h4c 4h4d 4s4h 6d6c 6s6c 6s6d 9h9c 9h9d 9s9h Ac7h Ac9h AcJc AcJd AcJs AcKc AcKd AcKs AcQc AcTc AcTh Ad7h Ad9h AdJc AdJd AdJs AdKc AdKd AdKs AdQd AdTd AdTh As7h As9h AsJc AsJd AsJs AsKc AsKd AsKs AsQs AsTh AsTs JcTd JcTh JcTs JdTc JdTh JdTs JhTc JhTd JhTs JsTc JsTd JsTh Kc4c Kd4d KhJc KhJd KhJs KhTc KhTd KhTs Ks4s Qc6c Qc7c QcJc QcJd QcJh QcJs QcTd QcTh QcTs Qd6d Qd7d QdJc QdJd QdJh QdJs QdTc QdTh QdTs QhJc QhJd QhJs QhTc QhTd QhTs Qs6s Qs7s QsJc QsJd QsJh QsJs QsTc QsTd QsTh ThTc ThTd TsTh')
        },
        {
          actions: [
            'check'
          ],
          combos: expand('5h5c 5h5d 5s5h 9d9c 9s9c 9s9d Ac5d Ac5h Ac5s Ac7d Ac7h Ac7s Ac8c Ac8d Ac8h Ac8s Ac9d Ac9s AcJh AcKc AcKd AcKs AcTc Ad5c Ad5h Ad5s Ad7c Ad7h Ad7s Ad8c Ad8d Ad8h Ad8s Ad9c Ad9s AdAc AdJh AdKc AdKd AdKs AdTd As5c As5d As5h As7c As7d As7h As8c As8d As8h As8s As9c As9d AsAc AsAd AsJh AsKc AsKd AsKs AsTs JdJc Jh8h JhJc JhJd JsJc JsJd JsJh KcJd KcJh KcJs KcQc KcQd KcQs KcTd KcTh KcTs KdJc KdJh KdJs KdKc KdQc KdQd KdQs KdTc KdTh KdTs Kh4h KhKc KhKd KhQh KhTh KsJc KsJd KsJh KsKc KsKd KsKh KsQc KsQd KsQs KsTc KsTd KsTh Qc6c QcTd QcTs Qd6d QdQc QdTc QdTs QhJc QhJd QhJh QhJs QhQc QhQd Qs6s QsQc QsQd QsQh QsTc QsTd TdTc ThTc ThTd TsTc TsTd TsTh')
        }
      ]
    },
    {
      position: 'SB',
      stackBb: 40,
      villainPosition: 'BTN',
      board: [
        'Ah',
        'Kh',
        '4d'
      ],
      heroStackSize: 31.4,
      villainStackSize: 31.4,
      actionLine: 'preflop: BTN raises 2.3bb, SB raises 8.6bb, BTN calls 8.6bb',
      dealCombos: expand('4h4c 4s4c 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6d6c 6h6c 6h6d 6s6c 6s6d 6s6h 7d7c 7h7c 7s7c 7s7d 7s7h 8d8c 8h8c 8h8d 8s8c 8s8d 8s8h 9d9c 9h9c 9h9d 9s9c 9s9d 9s9h Ac5d Ac5h Ac5s Ac6d Ac6h Ac6s Ac7d Ac7h Ac7s Ac8c Ac8d Ac8h Ac8s Ac9d Ac9h Ac9s AcJc AcJd AcJh AcJs AcKc AcKd AcKs AcQc AcQd AcQs AcTc AcTd AcTh AcTs Ad5c Ad5h Ad5s Ad6c Ad6h Ad6s Ad7c Ad7h Ad7s Ad8c Ad8d Ad8h Ad8s Ad9c Ad9h Ad9s AdAc AdJc AdJd AdJh AdJs AdKc AdKd AdKs AdQc AdQd AdQs AdTc AdTd AdTh AdTs As5c As5d As5h As6c As6d As6h As7c As7d As7h As8c As8d As8h As8s As9c As9d As9h AsAc AsAd AsJc AsJd AsJh AsJs AsKc AsKd AsKs AsQc AsQd AsQs AsTc AsTd AsTh AsTs Jc8c JcTd JcTh JcTs Jd8d JdJc JdTc JdTh JdTs Jh8h JhJc JhJd JhTc JhTd JhTs Js8s JsJc JsJd JsJh JsTc JsTd JsTh Kc3c Kc4c Kc6c Kc9h KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc KcTd KcTh KcTs Kd3d Kd6d Kd9h KdJc KdJh KdJs KdKc KdQc KdQd KdQh KdQs KdTc KdTd KdTh KdTs Ks3s Ks4s Ks6s Ks9h KsJc KsJd KsJh KsKc KsKd KsQc KsQd KsQh KsQs KsTc KsTd KsTh KsTs Qc6c Qc7c QcJc QcJd QcJh QcJs QcTd QcTh QcTs Qd6d Qd7d QdJc QdJd QdJh QdJs QdQc QdTc QdTh QdTs Qh6h Qh7h QhJc QhJd QhJh QhJs QhQc QhQd QhTc QhTd QhTs Qs6s Qs7s QsJc QsJd QsJh QsJs QsQc QsQd QsQh QsTc QsTd QsTh TdTc ThTc ThTd TsTc TsTd TsTh'),
      buckets: [
        {
          actions: [
            'bet_10pct'
          ],
          combos: expand('5d5c 5s5c 5s5d 6d6c 6s6c 6s6d 7d7c 7s7c 7s7d 8d8c 8h8d 8s8d 9d9c 9h9c 9h9d 9s9d 9s9h Ac8h AcJh AcKc AcKd AcKs AcTh Ad8h AdAc AdJh AdKc AdKd AdKs AdTh As8h AsAc AsAd AsJh AsKc AsKd AsKs AsTh JcTh JdJc JdTh Jh8h JhJc JhJd JhTc JhTd JhTs JsJc JsJd JsJh JsTh Kc6c KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTd KcTh KcTs Kd6d KdJc KdJh KdJs KdKc KdQc KdQd KdQh KdQs KdTc KdTh KdTs Ks6s KsJc KsJd KsJh KsKc KsKd KsQc KsQd KsQh KsQs KsTc KsTd KsTh Qc6c QcJs Qd6d Qd7d QdJd QdQc Qh6h Qh7h QhJh QhQc QhQd Qs6s QsJc QsQc QsQd QsQh TdTc ThTc ThTd TsTc TsTd TsTh')
        },
        {
          actions: [
            'bet_25pct'
          ],
          combos: expand('4h4c 4s4c 4s4h 5h5c 5h5d 5s5h 6h6d 8h8c 8s8h 9h9c 9s9c 9s9h AcJh AcKc AcKd AcKs AcTh AdAc AdJh AdKc AdKd AdKs AdTh AsAc AsAd AsJh AsKc AsKd AsKs AsTh JcTh JdJc JdTh JhJc JhJd JhTd JsJc JsJd JsJh JsTh KcJd KcJh KcJs KcQc KcQd KcTh KdJc KdJh KdJs KdQc KdQh KdQs KsJc KsJd KsJh KsQd KsQs KsTh QcJc QcJd QcJs QcTs QdJc QdJs QdQc Qh6h Qh7h QhQc QhQd QsJc QsJd QsJs QsQc QsQd QsQh QsTc TdTc ThTc ThTd TsTc TsTd TsTh')
        },
        {
          actions: [
            'bet_50pct'
          ],
          combos: expand('5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6d6c 6h6c 6h6d 6s6c 6s6d 6s6h 8d8c 8h8c 8h8d 8s8c 8s8d 8s8h 9d9c 9h9c 9h9d 9s9c 9s9d 9s9h Ac5d Ac5h Ac5s Ac6d Ac6h Ac6s Ac7d Ac7h Ac7s Ac8c Ac8d Ac8h Ac8s Ac9d Ac9h Ac9s AcJc AcJd AcJh AcJs AcKc AcKd AcKs AcQc AcQd AcQs AcTc AcTd AcTh AcTs Ad5c Ad5h Ad5s Ad6c Ad6h Ad6s Ad7c Ad7h Ad7s Ad8c Ad8d Ad8h Ad8s Ad9c Ad9h Ad9s AdJc AdJd AdJh AdJs AdKc AdKd AdKs AdQc AdQd AdQs AdTc AdTd AdTh AdTs As5c As5d As5h As6c As6d As6h As7c As7d As7h As8c As8d As8h As8s As9c As9d As9h AsJc AsJd AsJh AsJs AsKc AsKd AsKs AsQc AsQd AsQs AsTc AsTd AsTh AsTs Jc8c JcTd JcTh JcTs Jd8d JdTc JdTh JdTs JhJc JhJd JhTc JhTd JhTs Js8s JsJh JsTc JsTd JsTh Kc4c KcJd KcJs KcTc KcTd KcTs KdJc KdJs KdTc KdTs Ks4s KsJc KsJd KsTc KsTd KsTs Qc6c QcJc QcJd QcJh QcJs QcTd QcTh QcTs Qd6d Qd7d QdJc QdJh QdJs QdTc QdTh QdTs Qh6h QhJc QhJd QhJs QhQc QhQd QhTc QhTd QhTs Qs6s QsJc QsJd QsJh QsJs QsQh QsTc QsTd QsTh TdTc ThTc ThTd TsTd TsTh')
        },
        {
          actions: [
            'check'
          ],
          combos: expand('5d5c 5s5c 5s5d 6d6c 6s6c 6s6d 7h7c 7s7c 7s7h 8d8c 8h8c 8h8d 8s8c 8s8d 8s8h 9d9c 9h9c 9h9d 9s9c 9s9d 9s9h Ac8h Ac9h AcJh AcKc AcKs Ad8h Ad9h AdAc AdJh AdKc AdKd AdKs As8h As9h AsAc AsAd AsJh AsKc AsKs Jc8c JcTh JdJc Jh8h JhJc JhJd Js8s JsJc JsJd JsJh JsTh Kc3c Kc6c Kc9h KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTd KcTh KcTs Kd3d Kd6d Kd9h KdJc KdJh KdJs KdKc KdQc KdQd KdQh KdQs KdTc KdTd KdTh KdTs Ks3s Ks6s Ks9h KsJc KsJd KsJh KsKc KsKd KsQc KsQd KsQh KsQs KsTc KsTd KsTh Qc6c Qc7c QcJc QcJd QcJs QcTd QcTh QcTs Qd6d Qd7d QdJc QdJd QdJs QdQc QdTc QdTs Qh6h Qh7h QhJh QhQc QhQd Qs6s Qs7s QsJc QsJd QsJs QsQc QsQd QsQh QsTc QsTd QsTh TdTc ThTc ThTd TsTc TsTd TsTh')
        }
      ]
    },
    {
      position: 'SB',
      stackBb: 40,
      villainPosition: 'BTN',
      board: [
        'Ah',
        'Qd',
        '8c'
      ],
      heroStackSize: 31.4,
      villainStackSize: 31.4,
      actionLine: 'preflop: BTN raises 2.3bb, SB raises 8.6bb, BTN calls 8.6bb',
      dealCombos: expand('4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6d6c 6h6c 6h6d 6s6c 6s6d 6s6h 7d7c 7h7c 7h7d 7s7c 7s7d 7s7h 8h8d 8s8d 8s8h 9d9c 9h9c 9h9d 9s9c 9s9d 9s9h Ac5d Ac5h Ac5s Ac6d Ac6h Ac6s Ac7d Ac7h Ac7s Ac8d Ac8h Ac8s Ac9d Ac9h Ac9s AcJc AcJd AcJh AcJs AcKc AcKd AcKh AcKs AcQc AcQh AcQs AcTc AcTd AcTh AcTs Ad5c Ad5h Ad5s Ad6c Ad6h Ad6s Ad7c Ad7h Ad7s Ad8d Ad8h Ad8s Ad9c Ad9h Ad9s AdAc AdJc AdJd AdJh AdJs AdKc AdKd AdKh AdKs AdQc AdQh AdQs AdTc AdTd AdTh AdTs As5c As5d As5h As6c As6d As6h As7c As7d As7h As8d As8h As8s As9c As9d As9h AsAc AsAd AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsKs AsQc AsQh AsQs AsTc AsTd AsTh AsTs JcTd JcTh JcTs Jd8d JdJc JdTc JdTh JdTs Jh8h JhJc JhJd JhTc JhTd JhTs Js8s JsJc JsJd JsJh JsTc JsTd JsTh Kc3c Kc4c Kc6c KcJd KcJh KcJs KcQc KcQh KcQs KcTd KcTh KcTs Kd3d Kd4d Kd6d Kd9c Kd9h KdJc KdJh KdJs KdKc KdQc KdQh KdQs KdTc KdTd KdTh KdTs Kh3h Kh4h Kh6h Kh9c Kh9d KhJc KhJd KhJs KhKc KhKd KhQc KhQh KhQs KhTc KhTd KhTs Ks3s Ks4s Ks6s Ks9c Ks9h KsJc KsJd KsJh KsKc KsKd KsKh KsQc KsQh KsQs KsTc KsTd KsTh KsTs Qc6c Qc7c QcJc QcJd QcJh QcJs QcTd QcTh QcTs Qh6h Qh7h QhJc QhJd QhJh QhJs QhQc QhTc QhTd QhTs Qs6s Qs7s QsJc QsJd QsJh QsJs QsQc QsQh QsTc QsTd QsTh TdTc ThTc ThTd TsTc TsTd TsTh'),
      buckets: [
        {
          actions: [
            'bet_10pct'
          ],
          combos: expand('5d5c 5h5c 5h5d 6d6c 6h6c 6h6d 7d7c 7h7c 7h7d 8h8d 8s8d 8s8h 9d9c 9h9c 9s9c 9s9d 9s9h Ac8h Ad8d AdAc AdTd As8h AsAc AsAd Jd8d JdJc Jh8h JhJc JhJd JhTs JsJc JsJd JsJh Kc4c Kc6c KcJd KcJh KcJs KcQc KcQh KcQs Kd4d Kd6d KdJh KdKc KdQc KdQh KdQs KdTd Kh4h Kh6h KhJc KhJs KhKc KhKd KhQc KhQh KhQs Ks4s Ks6s KsJc KsJd KsJh KsKc KsKd KsKh KsQc KsQh KsQs Qc6c Qc7c QcJc QcJd QcJh QcTd QcTh QcTs Qh6h Qh7h QhJd QhJh QhJs QhQc QhTc QhTd QhTs Qs6s Qs7s QsJd QsJh QsQc QsQh QsTc QsTd QsTh TdTc ThTc ThTd TsTc TsTd TsTh')
        },
        {
          actions: [
            'bet_25pct'
          ],
          combos: expand('6s6c 8h8d 8s8d 8s8h 9d9c 9h9c 9h9d 9s9c 9s9d 9s9h Ac8d Ac8h AcQc AcTc Ad8d Ad8h AdAc AdTd AdTh As8d As8h AsAc AsAd AsQs AsTh AsTs JcTd JcTh Jd8d JdJc JdTc JdTh Jh8h JhJc JhJd JhTc JhTd JsJc JsJd JsJh JsTd JsTh KcJd KcJh KcJs KcQc KcQh KcQs KdJc KdJh KdJs KdKc KdQc KdQh KdQs KdTs KhJc KhJd KhJs KhKc KhKd KhQc KhQh KhQs KhTs Ks6s KsJc KsJd KsJh KsKc KsKd KsKh KsQc KsQh KsQs KsTc KsTd KsTh Qc6c Qc7c QcJc QcJd QcJh QcJs QcTd QcTh QcTs Qh6h Qh7h QhJc QhJd QhJh QhQc QhTc QhTd QhTs Qs6s Qs7s QsJc QsJd QsJh QsQc QsQh QsTc QsTd QsTh TdTc ThTc ThTd TsTc TsTd TsTh')
        },
        {
          actions: [
            'bet_50pct'
          ],
          combos: expand('4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6d6c 6h6c 6h6d 6s6c 6s6d 6s6h 7d7c 7h7c 7h7d 7s7c 7s7d 7s7h 8s8d 8s8h 9d9c 9h9c 9h9d 9s9c 9s9d 9s9h Ac5d Ac5h Ac5s Ac6d Ac6h Ac6s Ac7d Ac7h Ac7s Ac8d Ac8h Ac8s Ac9d Ac9h Ac9s AcJc AcJd AcJh AcJs AcKc AcKd AcKh AcKs AcQc AcQh AcQs AcTc AcTd AcTh AcTs Ad5c Ad5h Ad5s Ad6c Ad6h Ad6s Ad7c Ad7h Ad7s Ad8d Ad8h Ad8s Ad9c Ad9h Ad9s AdJc AdJd AdJh AdJs AdKc AdKd AdKh AdKs AdQc AdQh AdQs AdTc AdTd AdTh AdTs As5c As5d As5h As6c As6d As6h As7c As7d As7h As8d As8h As8s As9c As9d As9h AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsKs AsQc AsQh AsQs AsTc AsTd AsTh AsTs JcTd JcTh JcTs Jd8d JdJc JdTc JdTh JdTs Jh8h JhJc JhJd JhTc JhTd JhTs Js8s JsJc JsJd JsJh JsTc JsTd JsTh Kc3c Kc4c Kc6c KcJd KcJh KcJs KcQc KcQh KcQs KcTd KcTh KcTs Kd3d Kd4d Kd6d Kd9c Kd9h KdJc KdJh KdJs KdKc KdQc KdQh KdQs KdTc KdTh KdTs Kh3h Kh4h Kh6h Kh9c Kh9d KhJc KhJd KhJs KhKc KhKd KhQc KhQh KhQs KhTc KhTd KhTs Ks3s Ks4s Ks6s Ks9c Ks9h KsJc KsJd KsJh KsKc KsKd KsKh KsQc KsQh KsQs KsTc KsTd KsTh KsTs Qc6c QcJc QcJd QcJh QcJs QcTd QcTh QcTs Qh6h QhJc QhJd QhJh QhJs QhTc QhTd QhTs Qs6s Qs7s QsJc QsJd QsJh QsJs QsTc QsTd QsTh TdTc ThTc ThTd TsTc TsTd TsTh')
        },
        {
          actions: [
            'check'
          ],
          combos: expand('JsJh QhQc QsQc QsQh')
        }
      ]
    },
    {
      position: 'SB',
      stackBb: 40,
      villainPosition: 'BTN',
      board: [
        'Jh',
        '5h',
        '5d'
      ],
      heroStackSize: 31.4,
      villainStackSize: 31.4,
      actionLine: 'preflop: BTN raises 2.3bb, SB raises 8.6bb, BTN calls 8.6bb',
      dealCombos: expand('4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5s5c 6d6c 6h6c 6h6d 6s6c 6s6d 6s6h 7d7c 7h7c 7h7d 7s7c 7s7d 7s7h 8d8c 8h8c 8h8d 8s8c 8s8d 8s8h 9d9c 9h9c 9h9d 9s9c 9s9d 9s9h Ac5s Ac6d Ac6h Ac6s Ac7d Ac7h Ac7s Ac8c Ac8d Ac8h Ac8s Ac9d Ac9h Ac9s AcJc AcJd AcJs AcKc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad5c Ad5s Ad6c Ad6h Ad6s Ad7c Ad7h Ad7s Ad8c Ad8d Ad8h Ad8s Ad9c Ad9h Ad9s AdAc AdJc AdJd AdJs AdKc AdKd AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah5c Ah5s Ah6c Ah6d Ah6s Ah7c Ah7d Ah7s Ah8c Ah8d Ah8h Ah8s Ah9c Ah9d Ah9s AhAc AhAd AhJc AhJd AhJs AhKc AhKd AhKh AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs As5c As6c As6d As6h As7c As7d As7h As8c As8d As8h As8s As9c As9d As9h AsAc AsAd AsAh AsJc AsJd AsJs AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc8c JcTd JcTh JcTs Jd8d JdJc JdTc JdTh JdTs Js8s JsJc JsJd JsTc JsTd JsTh Kc3c Kc4c Kc6c Kc9d Kc9h Kc9s KcJd KcJs KcQc KcQd KcQh KcQs KcTc KcTd KcTh KcTs Kd3d Kd4d Kd6d Kd9c Kd9h Kd9s KdJc KdJs KdKc KdQc KdQd KdQh KdQs KdTc KdTd KdTh KdTs Kh3h Kh4h Kh6h Kh9c Kh9d Kh9s KhJc KhJd KhJs KhKc KhKd KhQc KhQd KhQh KhQs KhTc KhTd KhTh KhTs Ks3s Ks4s Ks6s Ks9c Ks9d Ks9h KsJc KsJd KsKc KsKd KsKh KsQc KsQd KsQh KsQs KsTc KsTd KsTh KsTs Qc5c Qc6c Qc7c QcJc QcJd QcJs QcTd QcTh QcTs Qd6d Qd7d QdJc QdJd QdJs QdQc QdTc QdTh QdTs Qh6h Qh7h QhJc QhJd QhJs QhQc QhQd QhTc QhTd QhTs Qs5s Qs6s Qs7s QsJc QsJd QsJs QsQc QsQd QsQh QsTc QsTd QsTh TdTc ThTc ThTd TsTc TsTd TsTh'),
      buckets: [
        {
          actions: [
            'bet_10pct'
          ],
          combos: expand('5s5c 6s6c 9d9c 9h9c 9h9d 9s9c 9s9d 9s9h Ac7s Ac8s Ac9s AcKc AcKh AcKs AcQc AcTc Ad9c Ad9s AdAc AdKd AdQd AdTd Ah9c Ah9d Ah9s AhAc AhAd AhKh AhTh As7c As8c As9c AsAc AsAd AsAh AsKc AsKh AsKs AsQs AsTs JdJc JsJc JsJd KcQc KcTs KdQd KdQh KhKd KhQd KhQh KsQs KsTc QcTs QdJc QdJd QdJs Qh6h Qh7h QhJc QhJd QhJs QsTc TdTc ThTc ThTd TsTc TsTd TsTh')
        },
        {
          actions: [
            'bet_25pct'
          ],
          combos: expand('4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5s5c 6d6c 6h6c 6h6d 6s6c 6s6d 6s6h 7d7c 7h7c 7h7d 7s7c 7s7d 7s7h 8d8c 8h8c 8h8d 8s8c 8s8d 8s8h 9d9c 9h9c 9h9d 9s9c 9s9d 9s9h Ac5s Ac6d Ac6h Ac6s Ac7d Ac7h Ac7s Ac8c Ac8d Ac8h Ac8s Ac9d Ac9h Ac9s AcJc AcJd AcJs AcKc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad5c Ad5s Ad6c Ad6h Ad6s Ad7c Ad7h Ad7s Ad8c Ad8d Ad8h Ad8s Ad9c Ad9h Ad9s AdAc AdJc AdJd AdJs AdKc AdKd AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah5c Ah5s Ah6c Ah6d Ah6s Ah7c Ah7d Ah7s Ah8c Ah8d Ah8h Ah8s Ah9c Ah9d Ah9s AhAc AhAd AhJc AhJd AhJs AhKc AhKd AhKh AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs As5c As6c As6d As6h As7c As7d As7h As8c As8d As8h As8s As9c As9d As9h AsAc AsAd AsAh AsJc AsJd AsJs AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc8c JcTd JcTh JcTs Jd8d JdJc JdTc JdTh JdTs Js8s JsJc JsJd JsTc JsTd JsTh Kc3c Kc4c Kc6c Kc9d Kc9h Kc9s KcJd KcJs KcQc KcQd KcQh KcQs KcTc KcTd KcTh KcTs Kd3d Kd4d Kd6d Kd9c Kd9h Kd9s KdJc KdJs KdKc KdQc KdQd KdQh KdQs KdTc KdTd KdTh KdTs Kh3h Kh4h Kh6h Kh9c Kh9d Kh9s KhJc KhJd KhJs KhKc KhKd KhQc KhQd KhQh KhQs KhTc KhTd KhTh KhTs Ks3s Ks4s Ks6s Ks9c Ks9d Ks9h KsJc KsJd KsKc KsKd KsKh KsQc KsQd KsQh KsQs KsTc KsTd KsTh KsTs Qc5c Qc6c Qc7c QcJc QcJd QcJs QcTd QcTh QcTs Qd6d Qd7d QdJc QdJd QdJs QdQc QdTc QdTh QdTs Qh6h Qh7h QhJc QhJd QhJs QhQc QhQd QhTc QhTd QhTs Qs5s Qs6s Qs7s QsJc QsJd QsJs QsQc QsQd QsQh QsTc QsTd QsTh TdTc ThTc ThTd TsTc TsTd TsTh')
        },
        {
          actions: [
            'bet_50pct'
          ],
          combos: expand('8h8c 8s8h Ac6s Ac7h Ac7s Ac8c Ac8h AcJc AcJd AcJs AcKc AcKh AcKs Ad6c Ad6s Ad7c Ad7h Ad7s Ad9h AdJc AdJs AdKc AdKs Ah7c Ah7d Ah7s Ah8c Ah8d Ah8s Ah9c Ah9d Ah9s As6c As7c As7h As8h As8s AsJc AsJd AsJs AsKc AsKh AsKs JcTd JcTh JcTs JdTc JdTh JdTs JsTc JsTd JsTh Kc3c Kc4c Kc6c KcJd KcJs KcQc KcQd KcQs KcTd KcTh KdJc KdJs KdKc Ks3s Ks4s Ks6s KsJc KsJd KsKc KsKd KsQc KsQd KsQs KsTd KsTh Qc6c Qc7c QcTd QcTh QcTs QdQc QdTh QhQc QhQd Qs6s Qs7s QsQc QsQd QsQh QsTc QsTd QsTh')
        }
      ]
    },
    {
      position: 'SB',
      stackBb: 40,
      villainPosition: 'BTN',
      board: [
        'Jh',
        'Td',
        '7c'
      ],
      heroStackSize: 31.4,
      villainStackSize: 31.4,
      actionLine: 'preflop: BTN raises 2.3bb, SB raises 8.6bb, BTN calls 8.6bb',
      dealCombos: expand('4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6d6c 6h6c 6h6d 6s6c 6s6d 6s6h 7h7d 7s7d 7s7h 8d8c 8h8c 8h8d 8s8c 8s8d 8s8h 9d9c 9h9c 9h9d 9s9c 9s9d 9s9h Ac5d Ac5h Ac5s Ac6d Ac6h Ac6s Ac7d Ac7h Ac7s Ac8c Ac8d Ac8h Ac8s Ac9d Ac9h Ac9s AcJc AcJd AcJs AcKc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTh AcTs Ad5c Ad5h Ad5s Ad6c Ad6h Ad6s Ad7h Ad7s Ad8c Ad8d Ad8h Ad8s Ad9c Ad9h Ad9s AdAc AdJc AdJd AdJs AdKc AdKd AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTh AdTs Ah5c Ah5d Ah5s Ah6c Ah6d Ah6s Ah7d Ah7s Ah8c Ah8d Ah8h Ah8s Ah9c Ah9d Ah9s AhAc AhAd AhJc AhJd AhJs AhKc AhKd AhKh AhKs AhQc AhQd AhQh AhQs AhTc AhTh AhTs As5c As5d As5h As6c As6d As6h As7d As7h As8c As8d As8h As8s As9c As9d As9h AsAc AsAd AsAh AsJc AsJd AsJs AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTc AsTh AsTs Jc8c JcTh JcTs Jd8d JdJc JdTc JdTh JdTs Js8s JsJc JsJd JsTc JsTh Kc3c Kc4c Kc6c Kc9d Kc9h Kc9s KcJd KcJs KcQc KcQd KcQh KcQs KcTc KcTh KcTs Kd3d Kd4d Kd6d Kd9c Kd9h Kd9s KdJc KdJs KdKc KdQc KdQd KdQh KdQs KdTc KdTh KdTs Kh3h Kh4h Kh6h Kh9c Kh9d KhJc KhJd KhJs KhKc KhKd KhQc KhQd KhQh KhQs KhTc KhTh KhTs Ks3s Ks4s Ks6s Ks9d Ks9h KsJc KsJd KsKc KsKd KsKh KsQc KsQd KsQh KsQs KsTc KsTh KsTs Qc6c QcJc QcJd QcJs QcTh QcTs Qd6d Qd7d QdJc QdJd QdJs QdQc QdTc QdTh QdTs Qh6h Qh7h QhJc QhJd QhJs QhQc QhQd QhTc QhTs Qs5s Qs6s Qs7s QsJc QsJd QsJs QsQc QsQd QsQh QsTc QsTh ThTc TsTc TsTh'),
      buckets: [
        {
          actions: [
            'all_in'
          ],
          combos: expand('Ac8c Ac8d Ac8h Ac8s Ac9h Ac9s AcJc AcJd AcJs AcKd AcKh AcKs AcTh Ad8c Ad8d Ad8h Ad8s Ad9c Ad9s AdAc AdJc AdJd AdJs AdKc AdKh AdKs Ah8c Ah8d Ah8h Ah8s Ah9c Ah9s AhAc AhAd AhJc AhJd AhJs AhKc AhKd AhKs As8c As8d As8h As8s As9c As9h AsAc AsAd AsAh AsJc AsJd AsJs AsKc AsKd AsKh AsKs AsTc AsTh AsTs Js8s KcJd KcJs KcQd KcQh KcQs KdJc KdJs KdKc KdQc KdQh KdQs KhJc KhJd KhJs KhKc KhKd KhQc KhQd KhQs KsJc KsJd KsKc KsKd KsKh KsQc KsQd KsQh KsQs QcJd QcJs QdJc QdJs QdQc QhJc QhJd QhJs QhQc QhQd QsJc QsJd QsJs QsQc QsQd QsQh')
        },
        {
          actions: [
            'bet_25pct'
          ],
          combos: expand('Ac8d Ac9d Ac9h AcJc AcKc AcTc AcTh AcTs Ad8c Ad8h Ad9c Ad9h Ad9s AdJd AdKd AdKs AdTc AdTh Ah9c Ah9d AhKh AhTc AhTh AhTs As9d As9h AsAh AsKs AsTs Jc8c Jd8d JdJc JsJc JsJd KcQc KdQd KhKc KhQh KsQs Qc6c QcJc QdJd Qs7s')
        },
        {
          actions: [
            'bet_50pct'
          ],
          combos: expand('AcJc AcKd AdJd AsTs Js8s Kc3c Kd3d KdKc Kh3h KhKc KhKd KsKc KsKd KsKh')
        },
        {
          actions: [
            'check'
          ],
          combos: expand('4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6d6c 6h6c 6h6d 6s6c 6s6d 6s6h 7h7d 7s7d 7s7h 8d8c 8h8c 8h8d 8s8c 8s8d 8s8h 9d9c 9h9c 9h9d 9s9c 9s9d 9s9h Ac5d Ac5h Ac5s Ac6d Ac6h Ac6s Ac7d Ac7h Ac7s Ac8d Ac8h Ac8s Ac9d Ac9h Ac9s AcJc AcKc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTh AcTs Ad5c Ad5h Ad5s Ad6c Ad6h Ad6s Ad7h Ad7s Ad8c Ad8h Ad8s Ad9c Ad9h Ad9s AdAc AdJd AdKc AdKd AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTh AdTs Ah5c Ah5d Ah5s Ah6c Ah6d Ah6s Ah7d Ah7s Ah8c Ah8d Ah8s Ah9c Ah9d Ah9s AhAc AhAd AhKc AhKd AhKh AhKs AhQc AhQd AhQh AhQs AhTc AhTh AhTs As5c As5d As5h As6c As6d As6h As7d As7h As8c As8d As8h As9c As9d As9h AsAc AsAd AsAh AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTc AsTh AsTs Jc8c JcTh JcTs Jd8d JdJc JdTc JdTh JdTs JsJc JsJd JsTc JsTh Kc4c Kc6c Kc9d Kc9h Kc9s KcQc KcQd KcQh KcQs KcTc KcTh KcTs Kd4d Kd6d Kd9c Kd9h Kd9s KdKc KdQc KdQd KdQh KdQs KdTc KdTh KdTs Kh4h Kh6h Kh9c Kh9d KhKc KhKd KhQc KhQd KhQh KhQs KhTc KhTh KhTs Ks3s Ks4s Ks6s Ks9d Ks9h KsQc KsQd KsQh KsQs KsTc KsTh KsTs Qc6c QcJc QcTh QcTs Qd6d Qd7d QdJd QdQc QdTc QdTh QdTs Qh6h Qh7h QhQc QhQd QhTc QhTs Qs5s Qs6s Qs7s QsQc QsQd QsQh QsTc QsTh ThTc TsTc TsTh')
        }
      ]
    },
    {
      position: 'SB',
      stackBb: 40,
      villainPosition: 'BTN',
      board: [
        'Th',
        '4h',
        '2h'
      ],
      heroStackSize: 31.4,
      villainStackSize: 31.4,
      actionLine: 'preflop: BTN raises 2.3bb, SB raises 8.6bb, BTN calls 8.6bb',
      dealCombos: expand('4d4c 4s4c 4s4d 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6d6c 6h6c 6h6d 6s6c 6s6d 6s6h 7d7c 7h7c 7h7d 7s7c 7s7d 7s7h 8d8c 8h8c 8h8d 8s8c 8s8d 8s8h 9d9c 9h9c 9h9d 9s9c 9s9d 9s9h Ac5d Ac5h Ac5s Ac6d Ac6h Ac6s Ac7d Ac7h Ac7s Ac8c Ac8d Ac8h Ac8s Ac9d Ac9h Ac9s AcJc AcJd AcJh AcJs AcKc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTs Ad5c Ad5h Ad5s Ad6c Ad6h Ad6s Ad7c Ad7h Ad7s Ad8c Ad8d Ad8h Ad8s Ad9c Ad9h Ad9s AdAc AdJc AdJd AdJh AdJs AdKc AdKd AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTs Ah5c Ah5d Ah5s Ah6c Ah6d Ah6s Ah7c Ah7d Ah7s Ah8c Ah8d Ah8h Ah8s Ah9c Ah9d Ah9s AhAc AhAd AhJc AhJd AhJh AhJs AhKc AhKd AhKh AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTs As5c As5d As5h As6c As6d As6h As7c As7d As7h As8c As8d As8h As8s As9c As9d As9h AsAc AsAd AsAh AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTc AsTd AsTs Jc8c JcTd JcTs Jd8d JdJc JdTc JdTs Jh8h JhJc JhJd JhTc JhTd JhTs Js8s JsJc JsJd JsJh JsTc JsTd Kc3c Kc4c Kc6c Kc9h KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc KcTd KcTs Kd3d Kd4d Kd6d Kd9h KdJc KdJh KdJs KdKc KdQc KdQd KdQh KdQs KdTc KdTd KdTs Kh3h Kh6h Kh9c Kh9d Kh9s KhJc KhJd KhJs KhKc KhKd KhQc KhQd KhQh KhQs KhTc KhTd KhTs Ks3s Ks4s Ks6s Ks9h KsJc KsJd KsJh KsKc KsKd KsKh KsQc KsQd KsQh KsQs KsTc KsTd KsTs Qc6c Qc7c QcJc QcJd QcJh QcJs QcTd QcTs Qd6d Qd7d QdJc QdJd QdJh QdJs QdQc QdTc QdTs Qh5h Qh6h Qh7h QhJc QhJd QhJh QhJs QhQc QhQd QhTc QhTd QhTs Qs6s Qs7s QsJc QsJd QsJh QsJs QsQc QsQd QsQh QsTc QsTd TdTc TsTc TsTd'),
      buckets: [
        {
          actions: [
            'bet_10pct'
          ],
          combos: expand('4d4c 4s4c 4s4d 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6d6c 6h6c 6h6d 6s6c 6s6d 6s6h 7d7c 7h7c 7h7d 7s7c 7s7d 7s7h 8d8c 8h8c 8h8d 8s8c 8s8d 8s8h 9d9c 9h9c 9h9d 9s9c 9s9d 9s9h Ac5d Ac5h Ac5s Ac6d Ac6h Ac6s Ac7d Ac7h Ac7s Ac8c Ac8d Ac8h Ac8s Ac9d Ac9h Ac9s AcJc AcJd AcJh AcJs AcKc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTs Ad5c Ad5h Ad5s Ad6c Ad6h Ad6s Ad7c Ad7h Ad7s Ad8c Ad8d Ad8h Ad8s Ad9c Ad9h Ad9s AdAc AdJc AdJd AdJh AdJs AdKc AdKd AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTs Ah5c Ah5d Ah5s Ah7c Ah7d Ah7s Ah8c Ah8d Ah8h Ah8s Ah9c Ah9d Ah9s AhAc AhAd AhJc AhJd AhJh AhJs AhKc AhKd AhKh AhKs AhQh As5c As5d As5h As6c As6d As6h As7c As7d As7h As8c As8d As8h As8s As9c As9d As9h AsAc AsAd AsAh AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTc AsTd AsTs Jc8c JcTd JcTs Jd8d JdJc JdTc JdTs Jh8h JhTc JhTd JhTs Js8s JsJc JsJd JsTc JsTd Kc4c Kc6c KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTd KcTs Kd4d Kd6d KdJc KdJh KdJs KdKc KdQc KdQd KdQh KdQs KdTc KdTs Kh3h Kh6h Kh9c Kh9d Kh9s KhJc KhJd KhJs KhKc KhKd KhQc KhQd KhQh KhQs KhTc KhTd KhTs Ks4s Ks6s KsJc KsJd KsJh KsKc KsKd KsKh KsQc KsQd KsQh KsQs KsTc KsTd Qc6c Qc7c QcJc QcJd QcJh QcJs QcTd QcTs Qd6d Qd7d QdJc QdJd QdJh QdJs QdQc QdTc QdTs Qh5h Qh6h Qh7h QhJc QhJd QhJh QhJs QhQc QhQd QhTc QhTd QhTs Qs6s Qs7s QsJc QsJd QsJh QsJs QsQc QsQd QsQh QsTc QsTd TdTc TsTc TsTd')
        },
        {
          actions: [
            'bet_25pct'
          ],
          combos: expand('4d4c 4s4c 4s4d 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6h6c 6h6d 6s6h 8h8c 8h8d 8s8h 9d9c 9h9c 9h9d 9s9c 9s9d 9s9h Ac5d Ac5h Ac5s Ac6d Ac6s Ac7d Ac7h Ac7s Ac8c Ac8d Ac8h Ac8s Ac9d Ac9h Ac9s AcJc AcJd AcJh AcJs AcKc AcKd AcKh AcKs AcQc AcTc AcTd AcTs Ad5c Ad5h Ad5s Ad6c Ad6s Ad7c Ad7h Ad7s Ad8c Ad8d Ad8h Ad8s Ad9c Ad9h Ad9s AdAc AdJc AdJd AdJh AdJs AdKc AdKd AdKh AdKs AdQd AdTc AdTd AdTs Ah5c Ah5d Ah5s Ah6c Ah6d Ah6s Ah7c Ah7d Ah7s Ah8c Ah8d Ah8s Ah9c Ah9d Ah9s AhAc AhAd AhJc AhJd AhJh AhJs AhKc AhKd AhKh AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTs As5c As5d As5h As6c As6d As7c As7d As7h As8c As8d As8h As8s As9c As9d As9h AsAc AsAd AsAh AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsKs AsQs AsTc AsTd AsTs Jc8c Jd8d JdJc JhJc JhJd JhTc JhTd JhTs Js8s JsJc JsJd JsJh Kc3c Kc4c Kc6c Kc9h KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc KcTd KcTs Kd3d Kd4d Kd6d Kd9h KdJc KdJh KdJs KdKc KdQc KdQd KdQh KdQs KdTc KdTd KdTs Kh6h KhJc KhJd KhJs KhKc KhKd KhQc KhQd KhQs KhTc KhTd KhTs Ks3s Ks4s Ks6s Ks9h KsJc KsJd KsJh KsKc KsKd KsKh KsQc KsQd KsQh KsQs KsTc KsTd KsTs Qc6c Qc7c QcJc QcJd QcJh QcJs QcTd QcTs Qd6d Qd7d QdJc QdJd QdJh QdJs QdQc QdTc QdTs Qh6h QhJc QhJd QhJs QhQc QhQd QhTc QhTd QhTs Qs6s Qs7s QsJc QsJd QsJh QsJs QsQc QsQd QsQh QsTc QsTd TdTc TsTc TsTd')
        },
        {
          actions: [
            'check'
          ],
          combos: expand('8d8c 8s8c 8s8d 9d9c 9h9c 9h9d 9s9c 9s9d 9s9h Ac7d Ac7s Ac8d Ac8h Ac8s Ac9d Ac9h Ac9s AcJc AcKc AcKd AcKh AcKs AcQc Ad7c Ad7s Ad8c Ad8h Ad8s Ad9c Ad9h Ad9s AdAc AdJd AdKc AdKd AdKh AdKs AdQd Ah8c Ah8d Ah8s Ah9c Ah9d Ah9s AhJh AhKh AhQh As7c As7d As8c As8d As8h As9c As9d As9h AsAc AsAd AsJs AsKc AsKd AsKh AsKs AsQs KcQc KdKc KdQd KsKc KsKd KsQs Qc6c Qc7c Qd6d Qd7d Qh6h QhQc QhQd Qs6s Qs7s QsQh TdTc TsTc TsTd')
        }
      ]
    }
  ]
};

export default pack;
