// Generated by scripts/import-ct-curriculum.ts. Do not edit by hand.
import type { RangePack } from '../types';

const expand = (value: string): string[] => value.split(' ');

const pack: RangePack = {
  slug: 'facing-a-3-bet-co-btn-vs-3-bet-jam-baseline',
  title: 'Facing a 3-bet: CO vs BTN - vs 3-bet jam (25/20/14bb)',
  description: 'Preflop practice after facing a 3-bet, kept separate from imported-hand grading.',
  scenario: 'FACING_3BET',
  street: 'preflop',
  tier: 'advanced',
  methodology: 'gto_cev',
  source: {
    kind: 'brand_neutralized_snapshot_config',
    capturedAt: '2026-07-18',
    path: 'research/ct-trainer-2026-07-18/',
    sha256: 'f493ef03af32a50bf9f9287b4e0851855b2a8c937f45fdd05592663f05a2df0a'
  },
  cells: [
    {
      position: 'CO',
      stackBb: 14,
      villainPosition: 'BTN',
      heroStackSize: 12,
      actionLine: 'preflop: CO raises 2bb',
      buckets: [
        {
          actions: [
            'call'
          ],
          combos: expand('8d8c 8h8c 8h8d 8s8c 8s8d 8s8h 9d9c 9h9c 9h9d 9s9c 9s9d 9s9h Ac7c Ac8c AcJc AcKd AcKh AcKs AcQc AcTc Ad7d Ad8d AdJd AdKc AdKh AdKs AdQd AdTd Ah7h Ah8h AhJh AhKc AhKd AhKs AhQh AhTh As7s As8s AsJs AsKc AsKd AsKh AsQs AsTs JdJc JhJc JhJd JsJc JsJd JsJh KcJc KcQc KdJd KdKc KdQd KhJh KhKc KhKd KhQh KsJs KsKc KsKd KsKh KsQs QdQc QhQc QhQd QsQc QsQd QsQh TdTc ThTc ThTd TsTc TsTd TsTh')
        },
        {
          actions: [
            'fold'
          ],
          combos: expand('Ac4d Ac4h Ac4s Ac6d Ac6h Ac6s Ad4c Ad4h Ad4s Ad6c Ad6h Ad6s Ah4c Ah4d Ah4s Ah6c Ah6d Ah6s As4c As4d As4h As6c As6d As6h Jc7c Jc8c Jc9d Jc9h Jc9s Jd7d Jd8d Jd9c Jd9h Jd9s Jh7h Jh8h Jh9c Jh9d Jh9s Js7s Js8s Js9c Js9d Js9h Kc5c Kc7c Kc8c Kc9d Kc9h Kc9s KcTd KcTh KcTs Kd5d Kd7d Kd8d Kd9c Kd9h Kd9s KdTc KdTh KdTs Kh5h Kh7h Kh8h Kh9c Kh9d Kh9s KhTc KhTd KhTs Ks5s Ks7s Ks8s Ks9c Ks9d Ks9h KsTc KsTd KsTh Qc7c Qc8c Qc9d Qc9h Qc9s QcTd QcTh QcTs Qd7d Qd8d Qd9c Qd9h Qd9s QdTc QdTh QdTs Qh7h Qh8h Qh9c Qh9d Qh9s QhTc QhTd QhTs Qs7s Qs8s Qs9c Qs9d Qs9h QsTc QsTd QsTh Tc8c Td8d Th8h Ts8s')
        }
      ]
    },
    {
      position: 'CO',
      stackBb: 20,
      villainPosition: 'BTN',
      heroStackSize: 18,
      actionLine: 'preflop: CO raises 2bb',
      buckets: [
        {
          actions: [
            'call'
          ],
          combos: expand('4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6d6c 6h6c 6h6d 6s6c 6s6d 6s6h 7d7c 7h7c 7h7d 7s7c 7s7d 7s7h 8d8c 8h8c 8h8d 8s8c 8s8d 8s8h 9d9c 9h9c 9h9d 9s9c 9s9d 9s9h Ac8c Ac9c AcJc AcJd AcJh AcJs AcKc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad8d Ad9d AdAc AdJc AdJd AdJh AdJs AdKc AdKd AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah8h Ah9h AhAc AhAd AhJc AhJd AhJh AhJs AhKc AhKd AhKh AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs As8s As9s AsAc AsAd AsAh AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs JdJc JhJc JhJd JsJc JsJd JsJh KcJc KcQc KcQd KcQh KcQs KdJd KdKc KdQc KdQd KdQh KdQs KhJh KhKc KhKd KhQc KhQd KhQh KhQs KsJs KsKc KsKd KsKh KsQc KsQd KsQh KsQs QdQc QhQc QhQd QsQc QsQd QsQh TdTc ThTc ThTd TsTc TsTd TsTh')
        },
        {
          actions: [
            'fold'
          ],
          combos: expand('4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 6c5c 6d5d 6h5h 6s5s 7c5c 7c6c 7d5d 7d6d 7h5h 7h6h 7s5s 7s6s 8c6c 8c7c 8d6d 8d7d 8h6h 8h7h 8s6s 8s7s 9c7c 9c8c 9d7d 9d8d 9h7h 9h8h 9s7s 9s8s Ac2c Ac3c Ac4c Ac5c Ac5d Ac5h Ac5s Ac6c Ac6d Ac6h Ac6s Ac7c Ac7d Ac7h Ac7s Ac8d Ac8h Ac8s Ac9d Ac9h Ac9s Ad2d Ad3d Ad4d Ad5c Ad5d Ad5h Ad5s Ad6c Ad6d Ad6h Ad6s Ad7c Ad7d Ad7h Ad7s Ad8c Ad8h Ad8s Ad9c Ad9h Ad9s Ah2h Ah3h Ah4h Ah5c Ah5d Ah5h Ah5s Ah6c Ah6d Ah6h Ah6s Ah7c Ah7d Ah7h Ah7s Ah8c Ah8d Ah8s Ah9c Ah9d Ah9s As2s As3s As4s As5c As5d As5h As5s As6c As6d As6h As6s As7c As7d As7h As7s As8c As8d As8h As9c As9d As9h Jc6c Jc7c Jc8c Jc9c Jc9d Jc9h Jc9s JcTc JcTd JcTh JcTs Jd6d Jd7d Jd8d Jd9c Jd9d Jd9h Jd9s JdTc JdTd JdTh JdTs Jh6h Jh7h Jh8h Jh9c Jh9d Jh9h Jh9s JhTc JhTd JhTh JhTs Js6s Js7s Js8s Js9c Js9d Js9h Js9s JsTc JsTd JsTh JsTs Kc4c Kc5c Kc6c Kc7c Kc8c Kc9c Kc9d Kc9h Kc9s KcJd KcJh KcJs KcTc KcTd KcTh KcTs Kd4d Kd5d Kd6d Kd7d Kd8d Kd9c Kd9d Kd9h Kd9s KdJc KdJh KdJs KdTc KdTd KdTh KdTs Kh4h Kh5h Kh6h Kh7h Kh8h Kh9c Kh9d Kh9h Kh9s KhJc KhJd KhJs KhTc KhTd KhTh KhTs Ks4s Ks5s Ks6s Ks7s Ks8s Ks9c Ks9d Ks9h Ks9s KsJc KsJd KsJh KsTc KsTd KsTh KsTs Qc5c Qc6c Qc7c Qc8c Qc9c Qc9d Qc9h Qc9s QcJc QcJd QcJh QcJs QcTc QcTd QcTh QcTs Qd5d Qd6d Qd7d Qd8d Qd9c Qd9d Qd9h Qd9s QdJc QdJd QdJh QdJs QdTc QdTd QdTh QdTs Qh5h Qh6h Qh7h Qh8h Qh9c Qh9d Qh9h Qh9s QhJc QhJd QhJh QhJs QhTc QhTd QhTh QhTs Qs5s Qs6s Qs7s Qs8s Qs9c Qs9d Qs9h Qs9s QsJc QsJd QsJh QsJs QsTc QsTd QsTh QsTs Tc7c Tc8c Tc9c Tc9d Tc9h Tc9s Td7d Td8d Td9c Td9d Td9h Td9s Th7h Th8h Th9c Th9d Th9h Th9s Ts7s Ts8s Ts9c Ts9d Ts9h Ts9s')
        }
      ]
    },
    {
      position: 'CO',
      stackBb: 25,
      villainPosition: 'BTN',
      heroStackSize: 22.9,
      actionLine: 'preflop: CO raises 2.1bb',
      buckets: [
        {
          actions: [
            'call'
          ],
          combos: expand('5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6d6c 6h6c 6h6d 6s6c 6s6d 6s6h 7d7c 7h7c 7h7d 7s7c 7s7d 7s7h 8d8c 8h8c 8h8d 8s8c 8s8d 8s8h 9d9c 9h9c 9h9d 9s9c 9s9d 9s9h Ac9c AcJc AcJd AcJh AcJs AcKc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad9d AdAc AdJc AdJd AdJh AdJs AdKc AdKd AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah9h AhAc AhAd AhJc AhJd AhJh AhJs AhKc AhKd AhKh AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs As9s AsAc AsAd AsAh AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs JdJc JhJc JhJd JsJc JsJd JsJh KcJc KcQc KcQd KcQh KcQs KdJd KdKc KdQc KdQd KdQh KdQs KhJh KhKc KhKd KhQc KhQd KhQh KhQs KsJs KsKc KsKd KsKh KsQc KsQd KsQh KsQs QdQc QhQc QhQd QsQc QsQd QsQh TdTc ThTc ThTd TsTc TsTd TsTh')
        },
        {
          actions: [
            'fold'
          ],
          combos: expand('4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5c4c 5d4d 5h4h 5s4s 6c5c 6d5d 6h5h 6s5s 7c5c 7c6c 7d5d 7d6d 7h5h 7h6h 7s5s 7s6s 8c6c 8c7c 8d6d 8d7d 8h6h 8h7h 8s6s 8s7s 9c6c 9c7c 9c8c 9d6d 9d7d 9d8d 9h6h 9h7h 9h8h 9s6s 9s7s 9s8s Ac2c Ac3c Ac4c Ac5c Ac5d Ac5h Ac5s Ac6c Ac6d Ac6h Ac6s Ac7c Ac7d Ac7h Ac7s Ac8c Ac8d Ac8h Ac8s Ac9d Ac9h Ac9s AcTd AcTh AcTs Ad2d Ad3d Ad4d Ad5c Ad5d Ad5h Ad5s Ad6c Ad6d Ad6h Ad6s Ad7c Ad7d Ad7h Ad7s Ad8c Ad8d Ad8h Ad8s Ad9c Ad9h Ad9s AdTc AdTh AdTs Ah2h Ah3h Ah4h Ah5c Ah5d Ah5h Ah5s Ah6c Ah6d Ah6h Ah6s Ah7c Ah7d Ah7h Ah7s Ah8c Ah8d Ah8h Ah8s Ah9c Ah9d Ah9s AhTc AhTd AhTs As2s As3s As4s As5c As5d As5h As5s As6c As6d As6h As6s As7c As7d As7h As7s As8c As8d As8h As8s As9c As9d As9h AsTc AsTd AsTh Jc6c Jc7c Jc8c Jc9c Jc9d Jc9h Jc9s JcTc JcTd JcTh JcTs Jd6d Jd7d Jd8d Jd9c Jd9d Jd9h Jd9s JdTc JdTd JdTh JdTs Jh6h Jh7h Jh8h Jh9c Jh9d Jh9h Jh9s JhTc JhTd JhTh JhTs Js6s Js7s Js8s Js9c Js9d Js9h Js9s JsTc JsTd JsTh JsTs Kc3c Kc4c Kc5c Kc6c Kc7c Kc8c Kc9c Kc9d Kc9h Kc9s KcJd KcJh KcJs KcQd KcQh KcQs KcTc KcTd KcTh KcTs Kd3d Kd4d Kd5d Kd6d Kd7d Kd8d Kd9c Kd9d Kd9h Kd9s KdJc KdJh KdJs KdQc KdQh KdQs KdTc KdTd KdTh KdTs Kh3h Kh4h Kh5h Kh6h Kh7h Kh8h Kh9c Kh9d Kh9h Kh9s KhJc KhJd KhJs KhQc KhQd KhQs KhTc KhTd KhTh KhTs Ks3s Ks4s Ks5s Ks6s Ks7s Ks8s Ks9c Ks9d Ks9h Ks9s KsJc KsJd KsJh KsQc KsQd KsQh KsTc KsTd KsTh KsTs Qc4c Qc5c Qc6c Qc7c Qc8c Qc9c Qc9d Qc9h Qc9s QcJc QcJd QcJh QcJs QcTc QcTd QcTh QcTs Qd4d Qd5d Qd6d Qd7d Qd8d Qd9c Qd9d Qd9h Qd9s QdJc QdJd QdJh QdJs QdTc QdTd QdTh QdTs Qh4h Qh5h Qh6h Qh7h Qh8h Qh9c Qh9d Qh9h Qh9s QhJc QhJd QhJh QhJs QhTc QhTd QhTh QhTs Qs4s Qs5s Qs6s Qs7s Qs8s Qs9c Qs9d Qs9h Qs9s QsJc QsJd QsJh QsJs QsTc QsTd QsTh QsTs Tc7c Tc8c Tc9c Tc9d Tc9h Tc9s Td7d Td8d Td9c Td9d Td9h Td9s Th7h Th8h Th9c Th9d Th9h Th9s Ts7s Ts8s Ts9c Ts9d Ts9h Ts9s')
        }
      ]
    }
  ]
};

export default pack;
