// Generated by scripts/import-ct-curriculum.ts. Do not edit by hand.
import type { RangePack } from '../types';

const expand = (value: string): string[] => value.split(' ');

const pack: RangePack = {
  slug: 'facing-an-open-sb-utg-vs-open-baseline',
  title: 'Facing an open: SB vs UTG - vs open (100/50/25/15bb)',
  description: 'Preflop response practice when another player opens first.',
  scenario: 'FACING_RAISE',
  street: 'preflop',
  tier: 'foundational',
  methodology: 'gto_cev',
  source: {
    kind: 'brand_neutralized_snapshot_config',
    capturedAt: '2026-07-18',
    path: 'research/ct-trainer-2026-07-18/',
    sha256: '246c91191d987405cd173dd083905bb0b54c68938606e485c2477f09c99f18e8'
  },
  cells: [
    {
      position: 'SB',
      stackBb: 15,
      villainPosition: 'UTG',
      villainStackSize: 13,
      actionLine: 'preflop: UTG raises 2bb',
      buckets: [
        {
          actions: [
            'all_in'
          ],
          combos: expand('3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6d6c 6h6c 6h6d 6s6c 6s6d 6s6h 7d7c 7h7c 7h7d 7s7c 7s7d 7s7h 8d8c 8h8c 8h8d 8s8c 8s8d 8s8h 9d9c 9h9c 9h9d 9s9c 9s9d 9s9h Ac8c AcJc AcJd AcJh AcJs AcKc AcKd AcKh AcKs AcQc AcQd AcQh AcQs Ad8d AdAc AdJc AdJd AdJh AdJs AdKc AdKd AdKh AdKs AdQc AdQd AdQh AdQs Ah8h AhAc AhAd AhJc AhJd AhJh AhJs AhKc AhKd AhKh AhKs AhQc AhQd AhQh AhQs As8s AsAc AsAd AsAh AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsQs JcTc JdJc JdTd JhJc JhJd JhTh JsJc JsJd JsJh JsTs KcJc KcQc KcTc KdJd KdKc KdQd KdTd KhJh KhKc KhKd KhQh KhTh KsJs KsKc KsKd KsKh KsQs KsTs QcJc QcTc QdJd QdQc QdTd QhJh QhQc QhQd QhTh QsJs QsQc QsQd QsQh QsTs TdTc ThTc ThTd TsTc TsTd TsTh')
        },
        {
          actions: [
            'call'
          ],
          combos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5c4c 5d4d 5d5c 5h4h 5h5c 5h5d 5s4s 5s5c 5s5d 5s5h 6c5c 6d5d 6d6c 6h5h 6h6c 6h6d 6s5s 6s6c 6s6d 6s6h 7c6c 7d6d 7h6h 7s6s 8c7c 8d7d 8h7h 8s7s 9c7c 9c8c 9d7d 9d8d 9h7h 9h8h 9s7s 9s8s Ac2c Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcTc AcTd AcTh AcTs Ad2d Ad3d Ad4d Ad5d Ad6d Ad7d Ad8d Ad9d AdTc AdTd AdTh AdTs Ah2h Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhTc AhTd AhTh AhTs As2s As3s As4s As5s As6s As7s As8s As9s AsTc AsTd AsTh AsTs Jc8c Jc9c Jd8d Jd9d Jh8h Jh9h Js8s Js9s Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQh KcQs Kd8d Kd9d KdJc KdJd KdJh KdJs KdQc KdQd KdQh KdQs Kh8h Kh9h KhJc KhJd KhJh KhJs KhQc KhQd KhQh KhQs Ks8s Ks9s KsJc KsJd KsJh KsJs KsQc KsQd KsQh KsQs Qc8c Qc9c QcJc QcJd QcJh QcJs Qd8d Qd9d QdJc QdJd QdJh QdJs Qh8h Qh9h QhJc QhJd QhJh QhJs Qs8s Qs9s QsJc QsJd QsJh QsJs Tc8c Tc9c Td8d Td9d Th8h Th9h Ts8s Ts9s')
        },
        {
          actions: [
            'fold'
          ],
          combos: expand('3c2c 3d2d 3h2h 3s2s 4c3c 4d3d 4h3h 4s3s 5c3c 5c4c 5d3d 5d4d 5h3h 5h4h 5s3s 5s4s 6c3c 6c4c 6d3d 6d4d 6h3h 6h4h 6s3s 6s4s 7c4c 7c5c 7d4d 7d5d 7h4h 7h5h 7s4s 7s5s 8c5c 8c6c 8d5d 8d6d 8h5h 8h6h 8s5s 8s6s 9c6c 9c7c 9d6d 9d7d 9h6h 9h7h 9s6s 9s7s Ac8d Ac8h Ac8s Ac9d Ac9h Ac9s Ad8c Ad8h Ad8s Ad9c Ad9h Ad9s Ah8c Ah8d Ah8s Ah9c Ah9d Ah9s As8c As8d As8h As9c As9d As9h Jc6c Jc7c Jc8c Jc9d Jc9h Jc9s JcTd JcTh JcTs Jd6d Jd7d Jd8d Jd9c Jd9h Jd9s JdTc JdTh JdTs Jh6h Jh7h Jh8h Jh9c Jh9d Jh9s JhTc JhTd JhTs Js6s Js7s Js8s Js9c Js9d Js9h JsTc JsTd JsTh Kc2c Kc3c Kc4c Kc5c Kc6c Kc7c Kc9d Kc9h Kc9s KcTd KcTh KcTs Kd2d Kd3d Kd4d Kd5d Kd6d Kd7d Kd9c Kd9h Kd9s KdTc KdTh KdTs Kh2h Kh3h Kh4h Kh5h Kh6h Kh7h Kh9c Kh9d Kh9s KhTc KhTd KhTs Ks2s Ks3s Ks4s Ks5s Ks6s Ks7s Ks9c Ks9d Ks9h KsTc KsTd KsTh Qc6c Qc7c Qc8c Qc9d Qc9h Qc9s QcJd QcJh QcJs QcTd QcTh QcTs Qd6d Qd7d Qd8d Qd9c Qd9h Qd9s QdJc QdJh QdJs QdTc QdTh QdTs Qh6h Qh7h Qh8h Qh9c Qh9d Qh9s QhJc QhJd QhJs QhTc QhTd QhTs Qs6s Qs7s Qs8s Qs9c Qs9d Qs9h QsJc QsJd QsJh QsTc QsTd QsTh Tc6c Tc7c Tc9d Tc9h Tc9s Td6d Td7d Td9c Td9h Td9s Th6h Th7h Th9c Th9d Th9s Ts6s Ts7s Ts9c Ts9d Ts9h')
        }
      ]
    },
    {
      position: 'SB',
      stackBb: 25,
      villainPosition: 'UTG',
      villainStackSize: 23,
      actionLine: 'preflop: UTG raises 2bb',
      buckets: [
        {
          actions: [
            'all_in'
          ],
          combos: expand('9d9c 9h9c 9h9d 9s9c 9s9d 9s9h Ac3c Ac4c AcKd AcKh AcKs AcQd AcQh AcQs Ad3d Ad4d AdKc AdKh AdKs AdQc AdQh AdQs Ah3h Ah4h AhKc AhKd AhKs AhQc AhQd AhQs As3s As4s AsKc AsKd AsKh AsQc AsQd AsQh JdJc JhJc JhJd JsJc JsJd JsJh KcJc KcTc KdJd KdTd KhJh KhTh KsJs KsTs QcJc QdJd QhJh QsJs TdTc ThTc ThTd TsTc TsTd TsTh')
        },
        {
          actions: [
            'call'
          ],
          combos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5c4c 5d4d 5d5c 5h4h 5h5c 5h5d 5s4s 5s5c 5s5d 5s5h 6c5c 6d5d 6d6c 6h5h 6h6c 6h6d 6s5s 6s6c 6s6d 6s6h 7c6c 7d6d 7d7c 7h6h 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8c6c 8c7c 8d6d 8d7d 8d8c 8h6h 8h7h 8h8c 8h8d 8s6s 8s7s 8s8c 8s8d 8s8h 9c7c 9c8c 9d7d 9d8d 9h7h 9h8h 9s7s 9s8s Ac2c Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcTc AcTd AcTh AcTs Ad2d Ad3d Ad4d Ad5d Ad6d Ad7d Ad8d Ad9d AdJc AdJd AdJh AdJs AdTc AdTd AdTh AdTs Ah2h Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhJc AhJd AhJh AhJs AhTc AhTd AhTh AhTs As2s As3s As4s As5s As6s As7s As8s As9s AsJc AsJd AsJh AsJs AsTc AsTd AsTh AsTs Jc8c Jc9c JcTc Jd8d Jd9d JdTd Jh8h Jh9h JhTh Js8s Js9s JsTs Kc6c Kc7c Kc8c Kc9c KcJd KcJh KcJs KcQc KcQd KcQh KcQs Kd6d Kd7d Kd8d Kd9d KdJc KdJh KdJs KdQc KdQd KdQh KdQs Kh6h Kh7h Kh8h Kh9h KhJc KhJd KhJs KhQc KhQd KhQh KhQs Ks6s Ks7s Ks8s Ks9s KsJc KsJd KsJh KsQc KsQd KsQh KsQs Qc8c Qc9c QcJc QcJd QcJh QcJs QcTc Qd8d Qd9d QdJc QdJd QdJh QdJs QdTd Qh8h Qh9h QhJc QhJd QhJh QhJs QhTh Qs8s Qs9s QsJc QsJd QsJh QsJs QsTs Tc8c Tc9c Td8d Td9d Th8h Th9h Ts8s Ts9s')
        },
        {
          actions: [
            'fold'
          ],
          combos: expand('3c2c 3d2d 3h2h 3s2s 4c3c 4d3d 4h3h 4s3s 5c3c 5d3d 5h3h 5s3s 6c3c 6c4c 6d3d 6d4d 6h3h 6h4h 6s3s 6s4s 7c4c 7c5c 7d4d 7d5d 7h4h 7h5h 7s4s 7s5s 8c5c 8c6c 8d5d 8d6d 8h5h 8h6h 8s5s 8s6s 9c6c 9d6d 9h6h 9s6s Ac8d Ac8h Ac8s Ac9d Ac9h Ac9s Ad8c Ad8h Ad8s Ad9c Ad9h Ad9s Ah8c Ah8d Ah8s Ah9c Ah9d Ah9s As8c As8d As8h As9c As9d As9h Jc6c Jc7c Jc9d Jc9h Jc9s JcTd JcTh JcTs Jd6d Jd7d Jd9c Jd9h Jd9s JdTc JdTh JdTs Jh6h Jh7h Jh9c Jh9d Jh9s JhTc JhTd JhTs Js6s Js7s Js9c Js9d Js9h JsTc JsTd JsTh Kc2c Kc3c Kc4c Kc5c Kc6c Kc9d Kc9h Kc9s KcTd KcTh KcTs Kd2d Kd3d Kd4d Kd5d Kd6d Kd9c Kd9h Kd9s KdTc KdTh KdTs Kh2h Kh3h Kh4h Kh5h Kh6h Kh9c Kh9d Kh9s KhTc KhTd KhTs Ks2s Ks3s Ks4s Ks5s Ks6s Ks9c Ks9d Ks9h KsTc KsTd KsTh Qc6c Qc7c Qc9d Qc9h Qc9s QcJd QcJh QcJs QcTd QcTh QcTs Qd6d Qd7d Qd9c Qd9h Qd9s QdJc QdJh QdJs QdTc QdTh QdTs Qh6h Qh7h Qh9c Qh9d Qh9s QhJc QhJd QhJs QhTc QhTd QhTs Qs6s Qs7s Qs9c Qs9d Qs9h QsJc QsJd QsJh QsTc QsTd QsTh Tc6c Tc7c Tc9d Tc9h Tc9s Td6d Td7d Td9c Td9h Td9s Th6h Th7h Th9c Th9d Th9s Ts6s Ts7s Ts9c Ts9d Ts9h')
        },
        {
          actions: [
            'raise_6'
          ],
          combos: expand('8c7c 8d7d 8d8c 8h7h 8h8c 8h8d 8s7s 8s8c 8s8d 8s8h 9d9c 9h9c 9h9d 9s9c 9s9d 9s9h Ac2c Ac4c Ac6c Ac7c Ac9c Ac9d Ac9h Ac9s AcJd AcJh AcJs AcKc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad2d Ad4d Ad6d Ad7d Ad9c Ad9d Ad9h Ad9s AdAc AdJc AdJh AdJs AdKc AdKd AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah2h Ah4h Ah6h Ah7h Ah9c Ah9d Ah9h Ah9s AhAc AhAd AhJc AhJd AhJs AhKc AhKd AhKh AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs As2s As4s As6s As7s As9c As9d As9h As9s AsAc AsAd AsAh AsJc AsJd AsJh AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs JcTc JdJc JdTd JhJc JhJd JhTh JsJc JsJd JsJh JsTs Kc6c Kc7c Kc8c Kc9c KcJd KcJh KcJs KcQd KcQh KcQs KcTd KcTh KcTs Kd6d Kd7d Kd8d Kd9d KdJc KdJh KdJs KdKc KdQc KdQh KdQs KdTc KdTh KdTs Kh6h Kh7h Kh8h Kh9h KhJc KhJd KhJs KhKc KhKd KhQc KhQd KhQs KhTc KhTd KhTs Ks6s Ks7s Ks8s Ks9s KsJc KsJd KsJh KsKc KsKd KsKh KsQc KsQd KsQh KsTc KsTd KsTh Qc9c QcJd QcJh QcJs Qd9d QdJc QdJh QdJs QdQc Qh9h QhJc QhJd QhJs QhQc QhQd Qs9s QsJc QsJd QsJh QsQc QsQd QsQh TdTc ThTc ThTd TsTc TsTd TsTh')
        }
      ]
    },
    {
      position: 'SB',
      stackBb: 50,
      villainPosition: 'UTG',
      villainStackSize: 48,
      actionLine: 'preflop: UTG raises 2bb',
      buckets: [
        {
          actions: [
            'call'
          ],
          combos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5c3c 5c4c 5d3d 5d4d 5d5c 5h3h 5h4h 5h5c 5h5d 5s3s 5s4s 5s5c 5s5d 5s5h 6c4c 6c5c 6d4d 6d5d 6d6c 6h4h 6h5h 6h6c 6h6d 6s4s 6s5s 6s6c 6s6d 6s6h 7c5c 7c6c 7d5d 7d6d 7d7c 7h5h 7h6h 7h7c 7h7d 7s5s 7s6s 7s7c 7s7d 7s7h 8c6c 8c7c 8d6d 8d7d 8d8c 8h6h 8h7h 8h8c 8h8d 8s6s 8s7s 8s8c 8s8d 8s8h 9c7c 9c8c 9d7d 9d8d 9d9c 9h7h 9h8h 9h9c 9h9d 9s7s 9s8s 9s9c 9s9d 9s9h Ac2c Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTd AcTh AcTs Ad2d Ad3d Ad4d Ad5d Ad6d Ad7d Ad8d Ad9d AdJc AdJd AdJh AdJs AdKc AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTh AdTs Ah2h Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhJc AhJd AhJh AhJs AhKc AhKd AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTs As2s As3s As4s As5s As6s As7s As8s As9s AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsQc AsQd AsQh AsQs AsTc AsTd AsTh Jc8c Jc9c JcTc JcTd JcTh JcTs Jd8d Jd9d JdJc JdTc JdTd JdTh JdTs Jh8h Jh9h JhJc JhJd JhTc JhTd JhTh JhTs Js8s Js9s JsJc JsJd JsJh JsTc JsTd JsTh JsTs Kc5c Kc6c Kc7c Kc8c Kc9c KcJd KcJh KcJs KcQd KcQh KcQs KcTc Kd5d Kd6d Kd7d Kd8d Kd9d KdJc KdJh KdJs KdQc KdQh KdQs KdTd Kh5h Kh6h Kh7h Kh8h Kh9h KhJc KhJd KhJs KhQc KhQd KhQs KhTh Ks5s Ks6s Ks7s Ks8s Ks9s KsJc KsJd KsJh KsQc KsQd KsQh KsTs Qc8c Qc9c QcJd QcJh QcJs QcTc Qd8d Qd9d QdJc QdJh QdJs QdTd Qh8h Qh9h QhJc QhJd QhJs QhTh Qs8s Qs9s QsJc QsJd QsJh QsTs Tc7c Tc8c Tc9c Td7d Td8d Td9d TdTc Th7h Th8h Th9h ThTc ThTd Ts7s Ts8s Ts9s TsTc TsTd TsTh')
        },
        {
          actions: [
            'fold'
          ],
          combos: expand('3c2c 3d2d 3h2h 3s2s 4c3c 4d3d 4h3h 4s3s 5c3c 5d3d 5h3h 5s3s 6c3c 6c4c 6d3d 6d4d 6h3h 6h4h 6s3s 6s4s 7c4c 7d4d 7h4h 7s4s 8c5c 8d5d 8h5h 8s5s 9c6c 9d6d 9h6h 9s6s Ac8d Ac8h Ac8s Ac9d Ac9h Ac9s AcTd AcTh AcTs Ad8c Ad8h Ad8s Ad9c Ad9h Ad9s AdTc AdTh AdTs Ah8c Ah8d Ah8s Ah9c Ah9d Ah9s AhTc AhTd AhTs As8c As8d As8h As9c As9d As9h AsTc AsTd AsTh Jc6c Jc7c Jc9d Jc9h Jc9s JcTd JcTh JcTs Jd6d Jd7d Jd9c Jd9h Jd9s JdTc JdTh JdTs Jh6h Jh7h Jh9c Jh9d Jh9s JhTc JhTd JhTs Js6s Js7s Js9c Js9d Js9h JsTc JsTd JsTh Kc2c Kc3c Kc4c Kc9d Kc9h Kc9s KcJd KcJh KcJs KcTd KcTh KcTs Kd2d Kd3d Kd4d Kd9c Kd9h Kd9s KdJc KdJh KdJs KdTc KdTh KdTs Kh2h Kh3h Kh4h Kh9c Kh9d Kh9s KhJc KhJd KhJs KhTc KhTd KhTs Ks2s Ks3s Ks4s Ks9c Ks9d Ks9h KsJc KsJd KsJh KsTc KsTd KsTh Qc6c Qc7c Qc8c Qc9d Qc9h Qc9s QcJd QcJh QcJs QcTd QcTh QcTs Qd6d Qd7d Qd8d Qd9c Qd9h Qd9s QdJc QdJh QdJs QdTc QdTh QdTs Qh6h Qh7h Qh8h Qh9c Qh9d Qh9s QhJc QhJd QhJs QhTc QhTd QhTs Qs6s Qs7s Qs8s Qs9c Qs9d Qs9h QsJc QsJd QsJh QsTc QsTd QsTh Tc6c Tc9d Tc9h Tc9s Td6d Td9c Td9h Td9s Th6h Th9c Th9d Th9s Ts6s Ts9c Ts9d Ts9h')
        },
        {
          actions: [
            'raise_7_5'
          ],
          combos: expand('5c4c 5d4d 5h4h 5s4s 6c5c 6d5d 6h5h 6s5s 7c6c 7d6d 7h6h 7s6s 8c7c 8d7d 8h7h 8s7s 9c8c 9d8d 9d9c 9h8h 9h9c 9h9d 9s8s 9s9c 9s9d 9s9h Ac4c Ac5c Ac8c Ac9c AcJc AcKc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc Ad4d Ad5d Ad8d Ad9d AdAc AdJd AdKc AdKd AdKh AdKs AdQc AdQd AdQh AdQs AdTd Ah4h Ah5h Ah8h Ah9h AhAc AhAd AhJh AhKc AhKd AhKh AhKs AhQc AhQd AhQh AhQs AhTh As4s As5s As8s As9s AsAc AsAd AsAh AsJs AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTs Jc9c JcTc Jd9d JdJc JdTd Jh9h JhJc JhJd JhTh Js9s JsJc JsJd JsJh JsTs KcJc KcQc KcTc KdJd KdKc KdQd KdTd KhJh KhKc KhKd KhQh KhTh KsJs KsKc KsKd KsKh KsQs KsTs QcJc QcTc QdJd QdQc QdTd QhJh QhQc QhQd QhTh QsJs QsQc QsQd QsQh QsTs Tc9c Td9d TdTc Th9h ThTc ThTd Ts9s TsTc TsTd TsTh')
        }
      ]
    },
    {
      position: 'SB',
      stackBb: 100,
      villainPosition: 'UTG',
      villainStackSize: 98,
      actionLine: 'preflop: UTG raises 2bb',
      buckets: [
        {
          actions: [
            'call'
          ],
          combos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5c3c 5c4c 5d3d 5d4d 5d5c 5h3h 5h4h 5h5c 5h5d 5s3s 5s4s 5s5c 5s5d 5s5h 6c4c 6c5c 6d4d 6d5d 6d6c 6h4h 6h5h 6h6c 6h6d 6s4s 6s5s 6s6c 6s6d 6s6h 7c5c 7c6c 7d5d 7d6d 7d7c 7h5h 7h6h 7h7c 7h7d 7s5s 7s6s 7s7c 7s7d 7s7h 8c6c 8c7c 8d6d 8d7d 8d8c 8h6h 8h7h 8h8c 8h8d 8s6s 8s7s 8s8c 8s8d 8s8h 9c7c 9c8c 9d7d 9d8d 9d9c 9h7h 9h8h 9h9c 9h9d 9s7s 9s8s 9s9c 9s9d 9s9h Ac2c Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad2d Ad3d Ad4d Ad5d Ad6d Ad7d Ad8d Ad9d AdJc AdJd AdJh AdJs AdKc AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah2h Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhJc AhJd AhJh AhJs AhKc AhKd AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs As2s As3s As4s As5s As6s As7s As8s As9s AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc8c Jc9c JcTc JcTd JcTh JcTs Jd8d Jd9d JdJc JdTc JdTd JdTh JdTs Jh8h Jh9h JhJc JhJd JhTc JhTd JhTh JhTs Js8s Js9s JsJc JsJd JsJh JsTc JsTd JsTh JsTs Kc4c Kc5c Kc6c Kc7c Kc8c Kc9c KcJc KcJd KcJh KcJs KcQd KcQh KcQs KcTc KcTd KcTh KcTs Kd4d Kd5d Kd6d Kd7d Kd8d Kd9d KdJc KdJd KdJh KdJs KdQc KdQh KdQs KdTc KdTd KdTh KdTs Kh4h Kh5h Kh6h Kh7h Kh8h Kh9h KhJc KhJd KhJh KhJs KhQc KhQd KhQs KhTc KhTd KhTh KhTs Ks4s Ks5s Ks6s Ks7s Ks8s Ks9s KsJc KsJd KsJh KsJs KsQc KsQd KsQh KsTc KsTd KsTh KsTs Qc8c Qc9c QcJc QcJd QcJh QcJs QcTc Qd8d Qd9d QdJc QdJd QdJh QdJs QdQc QdTd Qh8h Qh9h QhJc QhJd QhJh QhJs QhQc QhQd QhTh Qs8s Qs9s QsJc QsJd QsJh QsJs QsQc QsQd QsQh QsTs Tc7c Tc8c Tc9c Td7d Td8d Td9d TdTc Th7h Th8h Th9h ThTc ThTd Ts7s Ts8s Ts9s TsTc TsTd TsTh')
        },
        {
          actions: [
            'fold'
          ],
          combos: expand('3c2c 3d2d 3h2h 3s2s 4c3c 4d3d 4h3h 4s3s 5c3c 5d3d 5h3h 5s3s 6c3c 6c4c 6d3d 6d4d 6h3h 6h4h 6s3s 6s4s 7c4c 7d4d 7h4h 7s4s 8c5c 8d5d 8h5h 8s5s 9c6c 9d6d 9h6h 9s6s Ac8d Ac8h Ac8s Ac9d Ac9h Ac9s AcTd AcTh AcTs Ad8c Ad8h Ad8s Ad9c Ad9h Ad9s AdTc AdTh AdTs Ah8c Ah8d Ah8s Ah9c Ah9d Ah9s AhTc AhTd AhTs As8c As8d As8h As9c As9d As9h AsTc AsTd AsTh Jc6c Jc7c Jc9d Jc9h Jc9s JcTd JcTh JcTs Jd6d Jd7d Jd9c Jd9h Jd9s JdTc JdTh JdTs Jh6h Jh7h Jh9c Jh9d Jh9s JhTc JhTd JhTs Js6s Js7s Js9c Js9d Js9h JsTc JsTd JsTh Kc2c Kc3c Kc9d Kc9h Kc9s KcJd KcJh KcJs KcTd KcTh KcTs Kd2d Kd3d Kd9c Kd9h Kd9s KdJc KdJh KdJs KdTc KdTh KdTs Kh2h Kh3h Kh9c Kh9d Kh9s KhJc KhJd KhJs KhTc KhTd KhTs Ks2s Ks3s Ks9c Ks9d Ks9h KsJc KsJd KsJh KsTc KsTd KsTh Qc6c Qc7c Qc8c Qc9d Qc9h Qc9s QcJd QcJh QcJs QcTd QcTh QcTs Qd6d Qd7d Qd8d Qd9c Qd9h Qd9s QdJc QdJh QdJs QdTc QdTh QdTs Qh6h Qh7h Qh8h Qh9c Qh9d Qh9s QhJc QhJd QhJs QhTc QhTd QhTs Qs6s Qs7s Qs8s Qs9c Qs9d Qs9h QsJc QsJd QsJh QsTc QsTd QsTh Tc6c Tc7c Tc9d Tc9h Tc9s Td6d Td7d Td9c Td9h Td9s Th6h Th7h Th9c Th9d Th9s Ts6s Ts7s Ts9c Ts9d Ts9h')
        },
        {
          actions: [
            'raise_10'
          ],
          combos: expand('5c4c 5d4d 5h4h 5s4s 6c5c 6d5d 6h5h 6s5s 7c6c 7d6d 7h6h 7s6s 8c7c 8d7d 8h7h 8s7s Ac3c Ac4c Ac5c AcJc AcKc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc Ad3d Ad4d Ad5d AdAc AdJd AdKc AdKd AdKh AdKs AdQc AdQd AdQh AdQs AdTd Ah3h Ah4h Ah5h AhAc AhAd AhJh AhKc AhKd AhKh AhKs AhQc AhQd AhQh AhQs AhTh As3s As4s As5s AsAc AsAd AsAh AsJs AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTs Jc9c JcTc Jd9d JdJc JdTd Jh9h JhJc JhJd JhTh Js9s JsJc JsJd JsJh JsTs KcJc KcQc KcTc KdJd KdKc KdQd KdTd KhJh KhKc KhKd KhQh KhTh KsJs KsKc KsKd KsKh KsQs KsTs Qc9c QcJc QcTc Qd9d QdJd QdQc QdTd Qh9h QhJh QhQc QhQd QhTh Qs9s QsJs QsQc QsQd QsQh QsTs Tc8c Tc9c Td8d Td9d TdTc Th8h Th9h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh')
        }
      ]
    }
  ]
};

export default pack;
