// Generated by scripts/import-ct-curriculum.ts. Do not edit by hand.
import type { RangePack } from '../types';

const expand = (value: string): string[] => value.split(' ');

const pack: RangePack = {
  slug: 'facing-an-open-utgplus1-utg-vs-open-baseline',
  title: 'Facing an open: UTG+1 vs UTG - vs open (100/50/25/15bb)',
  description: 'Preflop response practice when another player opens first.',
  scenario: 'FACING_RAISE',
  street: 'preflop',
  tier: 'foundational',
  methodology: 'gto_cev',
  source: {
    kind: 'brand_neutralized_snapshot_config',
    capturedAt: '2026-07-18',
    path: 'research/ct-trainer-2026-07-18/',
    sha256: 'e8fdaadbdc3ebdcfd935dc4bddc43f287a84ea42dddca016a473f82527be5292'
  },
  cells: [
    {
      position: 'UTG+1',
      stackBb: 15,
      villainPosition: 'UTG',
      villainStackSize: 13,
      actionLine: 'preflop: UTG raises 2bb',
      buckets: [
        {
          actions: [
            'all_in'
          ],
          combos: expand('5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 7d7c 7h7c 7h7d 7s7c 7s7d 7s7h 8d8c 8h8c 8h8d 8s8c 8s8d 8s8h 9d9c 9h9c 9h9d 9s9c 9s9d 9s9h AcJc AcKc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AdAc AdJd AdKc AdKd AdKh AdKs AdQc AdQd AdQh AdQs AdTd AhAc AhAd AhJh AhKc AhKd AhKh AhKs AhQc AhQd AhQh AhQs AhTh AsAc AsAd AsAh AsJs AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTs JdJc JhJc JhJd JsJc JsJd JsJh KcJc KcQc KcTc KdJd KdKc KdQd KdTd KhJh KhKc KhKd KhQh KhTh KsJs KsKc KsKd KsKh KsQs KsTs QcJc QdJd QdQc QhJh QhQc QhQd QsJs QsQc QsQd QsQh TdTc ThTc ThTd TsTc TsTd TsTh')
        },
        {
          actions: [
            'call'
          ],
          combos: expand('7d7c 7h7c 7h7d 7s7c 7s7d 7s7h 8d8c 8h8c 8h8d 8s8c 8s8d 8s8h Ac5c Ac9c AcJd AcJh AcJs Ad5d Ad9d AdAc AdJc AdJh AdJs Ah5h Ah9h AhAc AhAd AhJc AhJd AhJs As5s As9s AsAc AsAd AsAh AsJc AsJd AsJh JcTc JdTd JhTh JsTs KcQd KcQh KcQs KcTc KdQc KdQh KdQs KdTd KhQc KhQd KhQs KhTh KsQc KsQd KsQh KsTs QcTc QdTd QhTh QsTs')
        },
        {
          actions: [
            'fold'
          ],
          combos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4c3c 4d3d 4d4c 4h3h 4h4c 4h4d 4s3s 4s4c 4s4d 4s4h 5c4c 5d4d 5d5c 5h4h 5h5c 5h5d 5s4s 5s5c 5s5d 5s5h 6c5c 6d5d 6d6c 6h5h 6h6c 6h6d 6s5s 6s6c 6s6d 6s6h 7c6c 7d6d 7d7c 7h6h 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8c6c 8c7c 8d6d 8d7d 8h6h 8h7h 8s6s 8s7s 9c7c 9c8c 9d7d 9d8d 9h7h 9h8h 9s7s 9s8s Ac2c Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJd AcJh AcJs AcTd AcTh AcTs Ad2d Ad3d Ad4d Ad5d Ad6d Ad7d Ad8d Ad9d AdJc AdJh AdJs AdTc AdTh AdTs Ah2h Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhJc AhJd AhJs AhTc AhTd AhTs As2s As3s As4s As5s As6s As7s As8s As9s AsJc AsJd AsJh AsTc AsTd AsTh Jc8c Jc9c JcTc Jd8d Jd9d JdTd Jh8h Jh9h JhTh Js8s Js9s JsTs Kc7c Kc8c Kc9c KcJd KcJh KcJs KcQd KcQh KcQs KcTc KcTd KcTh KcTs Kd7d Kd8d Kd9d KdJc KdJh KdJs KdQc KdQh KdQs KdTc KdTd KdTh KdTs Kh7h Kh8h Kh9h KhJc KhJd KhJs KhQc KhQd KhQs KhTc KhTd KhTh KhTs Ks7s Ks8s Ks9s KsJc KsJd KsJh KsQc KsQd KsQh KsTc KsTd KsTh KsTs Qc8c Qc9c QcJd QcJh QcJs QcTc Qd8d Qd9d QdJc QdJh QdJs QdTd Qh8h Qh9h QhJc QhJd QhJs QhTh Qs8s Qs9s QsJc QsJd QsJh QsTs Tc7c Tc8c Tc9c Td7d Td8d Td9d Th7h Th8h Th9h Ts7s Ts8s Ts9s')
        },
        {
          actions: [
            'raise_5'
          ],
          combos: expand('Ac9c Ad9d AdAc Ah9h AhAc AhAd As9s AsAc AsAd AsAh KcTc KdTd KhTh KsTs')
        }
      ]
    },
    {
      position: 'UTG+1',
      stackBb: 25,
      villainPosition: 'UTG',
      villainStackSize: 23,
      actionLine: 'preflop: UTG raises 2bb',
      buckets: [
        {
          actions: [
            'all_in'
          ],
          combos: expand('AcKd AcKh AcKs AdKc AdKh AdKs AhKc AhKd AhKs AsKc AsKd AsKh JdJc JhJc JhJd JsJc JsJd JsJh KcQc KdQd KhQh KsQs TdTc ThTc ThTd TsTc TsTd TsTh')
        },
        {
          actions: [
            'call'
          ],
          combos: expand('6d6c 6h6c 6h6d 6s6c 6s6d 6s6h 7d7c 7h7c 7h7d 7s7c 7s7d 7s7h 8d8c 8h8c 8h8d 8s8c 8s8d 8s8h 9d9c 9h9c 9h9d 9s9c 9s9d 9s9h Ac5c AcJc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc Ad5d AdJd AdKc AdKh AdKs AdQc AdQd AdQh AdQs AdTd Ah5h AhJh AhKc AhKd AhKs AhQc AhQd AhQh AhQs AhTh As5s AsJs AsKc AsKd AsKh AsQc AsQd AsQh AsQs AsTs JcTc JdJc JdTd JhJc JhJd JhTh JsJc JsJd JsJh JsTs KcJc KcQc KcTc KdJd KdKc KdQd KdTd KhJh KhKc KhKd KhQh KhTh KsJs KsKc KsKd KsKh KsQs KsTs QcJc QcTc QdJd QdTd QhJh QhTh QsJs QsTs Tc9c Td9d TdTc Th9h ThTc ThTd Ts9s TsTc TsTd TsTh')
        },
        {
          actions: [
            'fold'
          ],
          combos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4c3c 4d3d 4d4c 4h3h 4h4c 4h4d 4s3s 4s4c 4s4d 4s4h 5c4c 5d4d 5d5c 5h4h 5h5c 5h5d 5s4s 5s5c 5s5d 5s5h 6c5c 6d5d 6d6c 6h5h 6h6c 6h6d 6s5s 6s6c 6s6d 6s6h 7c6c 7d6d 7d7c 7h6h 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8c6c 8c7c 8d6d 8d7d 8h6h 8h7h 8s6s 8s7s 9c7c 9c8c 9d7d 9d8d 9h7h 9h8h 9s7s 9s8s Ac2c Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c AcJd AcJh AcJs AcTd AcTh AcTs Ad2d Ad3d Ad4d Ad5d Ad6d Ad7d Ad8d AdJc AdJh AdJs AdTc AdTh AdTs Ah2h Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h AhJc AhJd AhJs AhTc AhTd AhTs As2s As3s As4s As5s As6s As7s As8s AsJc AsJd AsJh AsTc AsTd AsTh Jc8c Jc9c JcTc Jd8d Jd9d JdTd Jh8h Jh9h JhTh Js8s Js9s JsTs Kc7c Kc8c Kc9c KcJd KcJh KcJs KcQd KcQh KcQs KcTd KcTh KcTs Kd7d Kd8d Kd9d KdJc KdJh KdJs KdQc KdQh KdQs KdTc KdTh KdTs Kh7h Kh8h Kh9h KhJc KhJd KhJs KhQc KhQd KhQs KhTc KhTd KhTs Ks7s Ks8s Ks9s KsJc KsJd KsJh KsQc KsQd KsQh KsTc KsTd KsTh Qc8c Qc9c QcJc QcJd QcJh QcJs QcTc Qd8d Qd9d QdJc QdJd QdJh QdJs QdTd Qh8h Qh9h QhJc QhJd QhJh QhJs QhTh Qs8s Qs9s QsJc QsJd QsJh QsJs QsTs Tc7c Tc8c Tc9c Td7d Td8d Td9d Th7h Th8h Th9h Ts7s Ts8s Ts9s')
        },
        {
          actions: [
            'raise_5'
          ],
          combos: expand('8d8c 8h8c 8h8d 8s8c 8s8d 8s8h 9d9c 9h9c 9h9d 9s9c 9s9d 9s9h Ac9c AcJd AcJh AcJs AcKc AcKd AcKh AcKs AcQd AcQh AcQs AcTc Ad9d AdAc AdJc AdJh AdJs AdKc AdKd AdKh AdKs AdQc AdQh AdQs AdTd Ah9h AhAc AhAd AhJc AhJd AhJs AhKc AhKd AhKh AhKs AhQc AhQd AhQs AhTh As9s AsAc AsAd AsAh AsJc AsJd AsJh AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsTs JcTc JdJc JdTd JhJc JhJd JhTh JsJc JsJd JsJh JsTs KcJc KcQd KcQh KcQs KcTc KdJd KdKc KdQc KdQh KdQs KdTd KhJh KhKc KhKd KhQc KhQd KhQs KhTh KsJs KsKc KsKd KsKh KsQc KsQd KsQh KsTs QcJc QdJd QdQc QhJh QhQc QhQd QsJs QsQc QsQd QsQh TdTc ThTc ThTd TsTc TsTd TsTh')
        }
      ]
    },
    {
      position: 'UTG+1',
      stackBb: 50,
      villainPosition: 'UTG',
      villainStackSize: 48,
      actionLine: 'preflop: UTG raises 2bb',
      buckets: [
        {
          actions: [
            'call'
          ],
          combos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5c4c 5d4d 5d5c 5h4h 5h5c 5h5d 5s4s 5s5c 5s5d 5s5h 6c5c 6d5d 6d6c 6h5h 6h6c 6h6d 6s5s 6s6c 6s6d 6s6h 7d7c 7h7c 7h7d 7s7c 7s7d 7s7h 8d8c 8h8c 8h8d 8s8c 8s8d 8s8h 9d9c 9h9c 9h9d 9s9c 9s9d 9s9h Ac4c Ac5c Ac8c Ac9c AcJc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc Ad4d Ad5d Ad8d Ad9d AdJd AdKc AdKh AdKs AdQc AdQd AdQh AdQs AdTd Ah4h Ah5h Ah8h Ah9h AhJh AhKc AhKd AhKs AhQc AhQd AhQh AhQs AhTh As4s As5s As8s As9s AsJs AsKc AsKd AsKh AsQc AsQd AsQh AsQs AsTs JcTc JdJc JdTd JhJc JhJd JhTh JsJc JsJd JsJh JsTs Kc9c KcJc KcQc KcTc Kd9d KdJd KdQd KdTd Kh9h KhJh KhQh KhTh Ks9s KsJs KsQs KsTs QcJc QcTc QdJd QdQc QdTd QhJh QhQc QhQd QhTh QsJs QsQc QsQd QsQh QsTs Tc9c Td9d TdTc Th9h ThTc ThTd Ts9s TsTc TsTd TsTh')
        },
        {
          actions: [
            'fold'
          ],
          combos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4c3c 4d3d 4d4c 4h3h 4h4c 4h4d 4s3s 4s4c 4s4d 4s4h 5c4c 5d4d 5d5c 5h4h 5h5c 5h5d 5s4s 5s5c 5s5d 5s5h 6c5c 6d5d 6h5h 6s5s 7c6c 7d6d 7h6h 7s6s 8c6c 8c7c 8d6d 8d7d 8h6h 8h7h 8s6s 8s7s 9c7c 9c8c 9d7d 9d8d 9h7h 9h8h 9s7s 9s8s Ac2c Ac3c Ac6c Ac7c Ac8c AcJd AcJh AcJs AcTd AcTh AcTs Ad2d Ad3d Ad6d Ad7d Ad8d AdJc AdJh AdJs AdTc AdTh AdTs Ah2h Ah3h Ah6h Ah7h Ah8h AhJc AhJd AhJs AhTc AhTd AhTs As2s As3s As6s As7s As8s AsJc AsJd AsJh AsTc AsTd AsTh Jc8c Jc9c Jd8d Jd9d Jh8h Jh9h Js8s Js9s Kc7c Kc8c Kc9c KcJd KcJh KcJs KcQd KcQh KcQs KcTd KcTh KcTs Kd7d Kd8d Kd9d KdJc KdJh KdJs KdQc KdQh KdQs KdTc KdTh KdTs Kh7h Kh8h Kh9h KhJc KhJd KhJs KhQc KhQd KhQs KhTc KhTd KhTs Ks7s Ks8s Ks9s KsJc KsJd KsJh KsQc KsQd KsQh KsTc KsTd KsTh Qc8c Qc9c QcJd QcJh QcJs Qd8d Qd9d QdJc QdJh QdJs Qh8h Qh9h QhJc QhJd QhJs Qs8s Qs9s QsJc QsJd QsJh Tc7c Tc8c Tc9c Td7d Td8d Td9d Th7h Th8h Th9h Ts7s Ts8s Ts9s')
        },
        {
          actions: [
            'raise_6'
          ],
          combos: expand('6c5c 6d5d 6d6c 6h5h 6h6c 6h6d 6s5s 6s6c 6s6d 6s6h 7c6c 7d6d 7d7c 7h6h 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8c7c 8d7d 8d8c 8h7h 8h8c 8h8d 8s7s 8s8c 8s8d 8s8h 9d9c 9h9c 9h9d 9s9c 9s9d 9s9h Ac4c Ac5c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcKc AcKd AcKh AcKs AcQd AcQh AcQs AcTc Ad4d Ad5d Ad7d Ad8d Ad9d AdAc AdJc AdJd AdJh AdJs AdKc AdKd AdKh AdKs AdQc AdQh AdQs AdTd Ah4h Ah5h Ah7h Ah8h Ah9h AhAc AhAd AhJc AhJd AhJh AhJs AhKc AhKd AhKh AhKs AhQc AhQd AhQs AhTh As4s As5s As7s As8s As9s AsAc AsAd AsAh AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsTs JcTc JdJc JdTd JhJc JhJd JhTh JsJc JsJd JsJh JsTs Kc9c KcJc KcQd KcQh KcQs KcTc Kd9d KdJd KdKc KdQc KdQh KdQs KdTd Kh9h KhJh KhKc KhKd KhQc KhQd KhQs KhTh Ks9s KsJs KsKc KsKd KsKh KsQc KsQd KsQh KsTs QcJc QcTc QdJd QdQc QdTd QhJh QhQc QhQd QhTh QsJs QsQc QsQd QsQh QsTs Tc9c Td9d TdTc Th9h ThTc ThTd Ts9s TsTc TsTd TsTh')
        }
      ]
    },
    {
      position: 'UTG+1',
      stackBb: 100,
      villainPosition: 'UTG',
      villainStackSize: 98,
      actionLine: 'preflop: UTG raises 2bb',
      buckets: [
        {
          actions: [
            'call'
          ],
          combos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5c4c 5d4d 5d5c 5h4h 5h5c 5h5d 5s4s 5s5c 5s5d 5s5h 6c5c 6d5d 6d6c 6h5h 6h6c 6h6d 6s5s 6s6c 6s6d 6s6h 7c6c 7d6d 7d7c 7h6h 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8d8c 8h8c 8h8d 8s8c 8s8d 8s8h 9d9c 9h9c 9h9d 9s9c 9s9d 9s9h Ac4c Ac5c Ac7c Ac8c Ac9c AcJc AcKc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc Ad4d Ad5d Ad7d Ad8d Ad9d AdJd AdKc AdKd AdKh AdKs AdQc AdQd AdQh AdQs AdTd Ah4h Ah5h Ah7h Ah8h Ah9h AhJh AhKc AhKd AhKh AhKs AhQc AhQd AhQh AhQs AhTh As4s As5s As7s As8s As9s AsJs AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTs JcTc JdJc JdTd JhJc JhJd JhTh JsJc JsJd JsJh JsTs Kc9c KcJc KcQc KcTc Kd9d KdJd KdKc KdQd KdTd Kh9h KhJh KhKc KhKd KhQh KhTh Ks9s KsJs KsKc KsKd KsKh KsQs KsTs QcJc QcTc QdJd QdQc QdTd QhJh QhQc QhQd QhTh QsJs QsQc QsQd QsQh QsTs Tc9c Td9d TdTc Th9h ThTc ThTd Ts9s TsTc TsTd TsTh')
        },
        {
          actions: [
            'fold'
          ],
          combos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4c3c 4d3d 4d4c 4h3h 4h4c 4h4d 4s3s 4s4c 4s4d 4s4h 5c4c 5d4d 5d5c 5h4h 5h5c 5h5d 5s4s 5s5c 5s5d 5s5h 7c6c 7d6d 7h6h 7s6s 8c6c 8c7c 8d6d 8d7d 8h6h 8h7h 8s6s 8s7s 9c7c 9c8c 9d7d 9d8d 9h7h 9h8h 9s7s 9s8s Ac2c Ac3c Ac6c Ac7c AcJd AcJh AcJs AcTd AcTh AcTs Ad2d Ad3d Ad6d Ad7d AdJc AdJh AdJs AdTc AdTh AdTs Ah2h Ah3h Ah6h Ah7h AhJc AhJd AhJs AhTc AhTd AhTs As2s As3s As6s As7s AsJc AsJd AsJh AsTc AsTd AsTh Jc8c Jc9c Jd8d Jd9d Jh8h Jh9h Js8s Js9s Kc7c Kc8c Kc9c KcJd KcJh KcJs KcQd KcQh KcQs KcTd KcTh KcTs Kd7d Kd8d Kd9d KdJc KdJh KdJs KdQc KdQh KdQs KdTc KdTh KdTs Kh7h Kh8h Kh9h KhJc KhJd KhJs KhQc KhQd KhQs KhTc KhTd KhTs Ks7s Ks8s Ks9s KsJc KsJd KsJh KsQc KsQd KsQh KsTc KsTd KsTh Qc8c Qc9c QcJd QcJh QcJs Qd8d Qd9d QdJc QdJh QdJs Qh8h Qh9h QhJc QhJd QhJs Qs8s Qs9s QsJc QsJd QsJh Tc7c Tc8c Td7d Td8d Th7h Th8h Ts7s Ts8s')
        },
        {
          actions: [
            'raise_7'
          ],
          combos: expand('5c4c 5d4d 5h4h 5s4s 6c5c 6d5d 6d6c 6h5h 6h6c 6h6d 6s5s 6s6c 6s6d 6s6h 7c6c 7d6d 7d7c 7h6h 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8c7c 8d7d 8d8c 8h7h 8h8c 8h8d 8s7s 8s8c 8s8d 8s8h 9d9c 9h9c 9h9d 9s9c 9s9d 9s9h Ac3c Ac4c Ac5c Ac7c Ac8c Ac9c AcJc AcKc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc Ad3d Ad4d Ad5d Ad7d Ad8d Ad9d AdAc AdJd AdKc AdKd AdKh AdKs AdQc AdQd AdQh AdQs AdTd Ah3h Ah4h Ah5h Ah7h Ah8h Ah9h AhAc AhAd AhJh AhKc AhKd AhKh AhKs AhQc AhQd AhQh AhQs AhTh As3s As4s As5s As7s As8s As9s AsAc AsAd AsAh AsJs AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTs JcTc JdJc JdTd JhJc JhJd JhTh JsJc JsJd JsJh JsTs Kc9c KcJc KcQc KcQd KcQh KcQs KcTc Kd9d KdJd KdKc KdQc KdQd KdQh KdQs KdTd Kh9h KhJh KhKc KhKd KhQc KhQd KhQh KhQs KhTh Ks9s KsJs KsKc KsKd KsKh KsQc KsQd KsQh KsQs KsTs QcJc QcTc QdJd QdQc QdTd QhJh QhQc QhQd QhTh QsJs QsQc QsQd QsQh QsTs Tc9c Td9d TdTc Th9h ThTc ThTd Ts9s TsTc TsTd TsTh')
        }
      ]
    }
  ]
};

export default pack;
