// Generated by scripts/import-ct-curriculum.ts. Do not edit by hand.
import type { RangePack } from '../types';

const expand = (value: string): string[] => value.split(' ');

const pack: RangePack = {
  slug: 'facing-a-3-bet-hj-bb-vs-3-bet-jam-baseline',
  title: 'Facing a 3-bet: HJ vs BB - vs 3-bet jam (25/20/14bb)',
  description: 'Preflop practice after facing a 3-bet, kept separate from imported-hand grading.',
  scenario: 'FACING_3BET',
  street: 'preflop',
  tier: 'advanced',
  methodology: 'gto_cev',
  source: {
    kind: 'brand_neutralized_snapshot_config',
    capturedAt: '2026-07-18',
    path: 'research/ct-trainer-2026-07-18/',
    sha256: 'd90f4ed547ab9570741e4bbd95ad2eefea0965d51fc2fb066151dc611dab18bd'
  },
  cells: [
    {
      position: 'HJ',
      stackBb: 14,
      villainPosition: 'BB',
      heroStackSize: 12,
      actionLine: 'preflop: HJ raises 2bb',
      buckets: [
        {
          actions: [
            'call'
          ],
          combos: expand('5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 7d7c 7h7c 7h7d 7s7c 7s7d 7s7h 8d8c 8h8c 8h8d 8s8c 8s8d 8s8h 9d9c 9h9c 9h9d 9s9c 9s9d 9s9h Ac7c Ac8c Ac9c Ac9d Ac9h Ac9s AcJc AcKc AcKd AcKh AcKs AcQc AcTc Ad7d Ad8d Ad9c Ad9d Ad9h Ad9s AdAc AdJd AdKc AdKd AdKh AdKs AdQd AdTd Ah7h Ah8h Ah9c Ah9d Ah9h Ah9s AhAc AhAd AhJh AhKc AhKd AhKh AhKs AhQh AhTh As7s As8s As9c As9d As9h As9s AsAc AsAd AsAh AsJs AsKc AsKd AsKh AsKs AsQs AsTs JdJc JhJc JhJd JsJc JsJd JsJh KcQc KdKc KdQd KhKc KhKd KhQh KsKc KsKd KsKh KsQs QdQc QhQc QhQd QsQc QsQd QsQh TdTc ThTc ThTd TsTc TsTd TsTh')
        },
        {
          actions: [
            'fold'
          ],
          combos: expand('9c8c 9d8d 9h8h 9s8s Ac2c Ac5d Ac5h Ac5s Ac6c Ac7d Ac7h Ac7s Ac8d Ac8h Ac8s Ad2d Ad5c Ad5h Ad5s Ad6d Ad7c Ad7h Ad7s Ad8c Ad8h Ad8s Ah2h Ah5c Ah5d Ah5s Ah6h Ah7c Ah7d Ah7s Ah8c Ah8d Ah8s As2s As5c As5d As5h As6s As7c As7d As7h As8c As8d As8h Jc8c JcTd JcTh JcTs Jd8d JdTc JdTh JdTs Jh8h JhTc JhTd JhTs Js8s JsTc JsTd JsTh Kc7c Kc8c Kc9c KcJd KcJh KcJs KcTd KcTh KcTs Kd7d Kd8d Kd9d KdJc KdJh KdJs KdTc KdTh KdTs Kh7h Kh8h Kh9h KhJc KhJd KhJs KhTc KhTd KhTs Ks7s Ks8s Ks9s KsJc KsJd KsJh KsTc KsTd KsTh Qc8c Qc9c QcJd QcJh QcJs QcTd QcTh QcTs Qd8d Qd9d QdJc QdJh QdJs QdTc QdTh QdTs Qh8h Qh9h QhJc QhJd QhJs QhTc QhTd QhTs Qs8s Qs9s QsJc QsJd QsJh QsTc QsTd QsTh Tc8c Td8d Th8h Ts8s')
        }
      ]
    },
    {
      position: 'HJ',
      stackBb: 20,
      villainPosition: 'BB',
      heroStackSize: 18,
      actionLine: 'preflop: HJ raises 2bb',
      buckets: [
        {
          actions: [
            'call'
          ],
          combos: expand('5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6d6c 6h6c 6h6d 6s6c 6s6d 6s6h 7d7c 7h7c 7h7d 7s7c 7s7d 7s7h 8d8c 8h8c 8h8d 8s8c 8s8d 8s8h 9d9c 9h9c 9h9d 9s9c 9s9d 9s9h Ac9c AcJc AcJd AcJh AcJs AcKc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad9d AdAc AdJc AdJd AdJh AdJs AdKc AdKd AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah9h AhAc AhAd AhJc AhJd AhJh AhJs AhKc AhKd AhKh AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs As9s AsAc AsAd AsAh AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs JdJc JhJc JhJd JsJc JsJd JsJh KcJc KcQc KcTc KdJd KdKc KdQd KdTd KhJh KhKc KhKd KhQh KhTh KsJs KsKc KsKd KsKh KsQs KsTs QcTc QdQc QdTd QhQc QhQd QhTh QsQc QsQd QsQh QsTs TdTc ThTc ThTd TsTc TsTd TsTh')
        },
        {
          actions: [
            'fold'
          ],
          combos: expand('4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 7c6c 7d6d 7h6h 7s6s 8c6c 8c7c 8d6d 8d7d 8h6h 8h7h 8s6s 8s7s 9c7c 9c8c 9d7d 9d8d 9h7h 9h8h 9s7s 9s8s Ac2c Ac3c Ac4c Ac5c Ac6c Ac7c Ac7d Ac7h Ac7s Ac8c Ac8d Ac8h Ac8s Ac9d Ac9h Ac9s AcTd AcTh AcTs Ad2d Ad3d Ad4d Ad5d Ad6d Ad7c Ad7d Ad7h Ad7s Ad8c Ad8d Ad8h Ad8s Ad9c Ad9h Ad9s AdTc AdTh AdTs Ah2h Ah3h Ah4h Ah5h Ah6h Ah7c Ah7d Ah7h Ah7s Ah8c Ah8d Ah8h Ah8s Ah9c Ah9d Ah9s AhTc AhTd AhTs As2s As3s As4s As5s As6s As7c As7d As7h As7s As8c As8d As8h As8s As9c As9d As9h AsTc AsTd AsTh Jc7c Jc8c Jc9c JcTc JcTd JcTh JcTs Jd7d Jd8d Jd9d JdTc JdTd JdTh JdTs Jh7h Jh8h Jh9h JhTc JhTd JhTh JhTs Js7s Js8s Js9s JsTc JsTd JsTh JsTs Kc5c Kc6c Kc7c Kc8c Kc9c KcJd KcJh KcJs KcQd KcQh KcQs KcTd KcTh KcTs Kd5d Kd6d Kd7d Kd8d Kd9d KdJc KdJh KdJs KdQc KdQh KdQs KdTc KdTh KdTs Kh5h Kh6h Kh7h Kh8h Kh9h KhJc KhJd KhJs KhQc KhQd KhQs KhTc KhTd KhTs Ks5s Ks6s Ks7s Ks8s Ks9s KsJc KsJd KsJh KsQc KsQd KsQh KsTc KsTd KsTh Qc6c Qc7c Qc8c Qc9c QcJc QcJd QcJh QcJs QcTc QcTd QcTh QcTs Qd6d Qd7d Qd8d Qd9d QdJc QdJd QdJh QdJs QdTc QdTd QdTh QdTs Qh6h Qh7h Qh8h Qh9h QhJc QhJd QhJh QhJs QhTc QhTd QhTh QhTs Qs6s Qs7s Qs8s Qs9s QsJc QsJd QsJh QsJs QsTc QsTd QsTh QsTs Tc7c Tc8c Tc9c Td7d Td8d Td9d Th7h Th8h Th9h Ts7s Ts8s Ts9s')
        }
      ]
    },
    {
      position: 'HJ',
      stackBb: 25,
      villainPosition: 'BB',
      heroStackSize: 22.9,
      actionLine: 'preflop: HJ raises 2.1bb',
      buckets: [
        {
          actions: [
            'call'
          ],
          combos: expand('5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6d6c 6h6c 6h6d 6s6c 6s6d 6s6h 7d7c 7h7c 7h7d 7s7c 7s7d 7s7h 8d8c 8h8c 8h8d 8s8c 8s8d 8s8h 9d9c 9h9c 9h9d 9s9c 9s9d 9s9h Ac9c AcJc AcJd AcJh AcJs AcKc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc Ad9d AdAc AdJc AdJd AdJh AdJs AdKc AdKd AdKh AdKs AdQc AdQd AdQh AdQs AdTd Ah9h AhAc AhAd AhJc AhJd AhJh AhJs AhKc AhKd AhKh AhKs AhQc AhQd AhQh AhQs AhTh As9s AsAc AsAd AsAh AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTs JcTc JdJc JdTd JhJc JhJd JhTh JsJc JsJd JsJh JsTs KcJc KcQc KcTc KdJd KdKc KdQd KdTd KhJh KhKc KhKd KhQh KhTh KsJs KsKc KsKd KsKh KsQs KsTs QcJc QdJd QdQc QhJh QhQc QhQd QsJs QsQc QsQd QsQh TdTc ThTc ThTd TsTc TsTd TsTh')
        },
        {
          actions: [
            'fold'
          ],
          combos: expand('4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6c5c 6d5d 6h5h 6s5s 7c6c 7d6d 7h6h 7s6s 8c6c 8c7c 8d6d 8d7d 8h6h 8h7h 8s6s 8s7s 9c7c 9c8c 9d7d 9d8d 9h7h 9h8h 9s7s 9s8s Ac2c Ac3c Ac4c Ac5c Ac6c Ac7c Ac7d Ac7h Ac7s Ac8c Ac8d Ac8h Ac8s Ac9d Ac9h Ac9s AcTd AcTh AcTs Ad2d Ad3d Ad4d Ad5d Ad6d Ad7c Ad7d Ad7h Ad7s Ad8c Ad8d Ad8h Ad8s Ad9c Ad9h Ad9s AdTc AdTh AdTs Ah2h Ah3h Ah4h Ah5h Ah6h Ah7c Ah7d Ah7h Ah7s Ah8c Ah8d Ah8h Ah8s Ah9c Ah9d Ah9s AhTc AhTd AhTs As2s As3s As4s As5s As6s As7c As7d As7h As7s As8c As8d As8h As8s As9c As9d As9h AsTc AsTd AsTh Jc7c Jc8c Jc9c JcTc JcTd JcTh JcTs Jd7d Jd8d Jd9d JdTc JdTd JdTh JdTs Jh7h Jh8h Jh9h JhTc JhTd JhTh JhTs Js7s Js8s Js9s JsTc JsTd JsTh JsTs Kc4c Kc5c Kc6c Kc7c Kc8c Kc9c Kc9d Kc9h Kc9s KcJd KcJh KcJs KcQd KcQh KcQs KcTc KcTd KcTh KcTs Kd4d Kd5d Kd6d Kd7d Kd8d Kd9c Kd9d Kd9h Kd9s KdJc KdJh KdJs KdQc KdQh KdQs KdTc KdTd KdTh KdTs Kh4h Kh5h Kh6h Kh7h Kh8h Kh9c Kh9d Kh9h Kh9s KhJc KhJd KhJs KhQc KhQd KhQs KhTc KhTd KhTh KhTs Ks4s Ks5s Ks6s Ks7s Ks8s Ks9c Ks9d Ks9h Ks9s KsJc KsJd KsJh KsQc KsQd KsQh KsTc KsTd KsTh KsTs Qc6c Qc7c Qc8c Qc9c QcJc QcJd QcJh QcJs QcTc QcTd QcTh QcTs Qd6d Qd7d Qd8d Qd9d QdJc QdJd QdJh QdJs QdTc QdTd QdTh QdTs Qh6h Qh7h Qh8h Qh9h QhJc QhJd QhJh QhJs QhTc QhTd QhTh QhTs Qs6s Qs7s Qs8s Qs9s QsJc QsJd QsJh QsJs QsTc QsTd QsTh QsTs Tc7c Tc8c Tc9c Td7d Td8d Td9d Th7h Th8h Th9h Ts7s Ts8s Ts9s')
        }
      ]
    }
  ]
};

export default pack;
