// Generated by scripts/import-ct-curriculum.ts. Do not edit by hand.
import type { RangePack } from '../types';

const expand = (value: string): string[] => value.split(' ');

const pack: RangePack = {
  slug: 'in-position-postflop-response-btn-utg-flop-baseline',
  title: 'In-position postflop response: BTN vs UTG - Flop (100bb)',
  description: 'Board-aware in-position response practice after the preflop raiser acts.',
  scenario: 'IP_POSTFLOP',
  street: 'flop',
  tier: 'advanced',
  methodology: 'gto_cev',
  source: {
    kind: 'brand_neutralized_snapshot_config',
    capturedAt: '2026-07-18',
    path: 'research/ct-trainer-2026-07-18/',
    sha256: '789b9694997976d78652013489fd71ab633b248c76d9fa439d31d27b9a680e1f'
  },
  cells: [
    {
      position: 'BTN',
      stackBb: 100,
      villainPosition: 'UTG',
      board: [
        '8h',
        '6d',
        '2h'
      ],
      heroStackSize: 97.7,
      villainStackSize: 95.9,
      actionLine: 'preflop: UTG raises 2.3bb, BTN calls 2.3bb; flop: UTG bets 1.8bb',
      dealCombos: expand('2d2c 2s2c 2s2d 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4c3c 4d3d 4d4c 4h3h 4h4c 4h4d 4s3s 4s4c 4s4d 4s4h 5c3c 5c4c 5d3d 5d4d 5d5c 5h3h 5h4h 5h5c 5h5d 5s3s 5s4s 5s5c 5s5d 5s5h 6c4c 6c5c 6h4h 6h5h 6h6c 6s4s 6s5s 6s6c 6s6h 7c5c 7c6c 7d5d 7d7c 7h5h 7h6h 7h7c 7h7d 7s5s 7s6s 7s7c 7s7d 7s7h 8c6c 8c7c 8d7d 8d8c 8s6s 8s7s 8s8c 8s8d 9c7c 9c8c 9d7d 9d8d 9d9c 9h7h 9h9c 9h9d 9s7s 9s8s 9s9c 9s9d 9s9h Ac2c Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad2d Ad3d Ad4d Ad5d Ad7d Ad8d Ad9d AdJc AdJd AdJh AdJs AdKc AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah3h Ah4h Ah5h Ah6h Ah7h Ah9h AhJc AhJd AhJh AhJs AhKc AhKd AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs As2s As3s As4s As5s As6s As7s As8s As9s AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc8c Jc9c JcTc JcTd JcTh JcTs Jd8d Jd9d JdJc JdTc JdTd JdTh JdTs Jh9h JhJc JhJd JhTc JhTd JhTh JhTs Js8s Js9s JsJc JsJd JsJh JsTc JsTd JsTh JsTs Kc5c Kc6c Kc7c Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc KcTd KcTh KcTs Kd5d Kd7d Kd8d Kd9d KdJc KdJd KdJh KdJs KdQc KdQd KdQh KdQs KdTc KdTd KdTh KdTs Kh5h Kh6h Kh7h Kh9h KhJc KhJd KhJh KhJs KhKc KhKd KhQc KhQd KhQh KhQs KhTc KhTd KhTh KhTs Ks5s Ks6s Ks7s Ks8s Ks9s KsJc KsJd KsJh KsJs KsKc KsKh KsQc KsQd KsQh KsQs KsTc KsTd KsTh KsTs Qc8c Qc9c QcJc QcJd QcJh QcJs QcTc QcTd QcTh QcTs Qd8d Qd9d QdJc QdJd QdJh QdJs QdQc QdTc QdTd QdTh QdTs Qh9h QhJc QhJd QhJh QhJs QhQc QhQd QhTc QhTd QhTh QhTs Qs8s Qs9s QsJc QsJd QsJh QsJs QsQc QsQd QsQh QsTc QsTd QsTh QsTs Tc7c Tc8c Tc9c Td7d Td8d Td9d TdTc Th7h Th9h ThTc ThTd Ts7s Ts8s Ts9s TsTc TsTd TsTh'),
      buckets: [
        {
          actions: [
            'call'
          ],
          combos: expand('2d2c 2s2c 2s2d 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4c3c 4d3d 4d4c 4h4c 4h4d 4s3s 4s4c 4s4d 4s4h 5c3c 5c4c 5d3d 5d4d 5d5c 5h4h 5h5c 5h5d 5s3s 5s4s 5s5c 5s5d 5s5h 6c4c 6c5c 6h4h 6h5h 6h6c 6s4s 6s5s 6s6c 6s6h 7c5c 7c6c 7d7c 7h5h 7h6h 7h7c 7h7d 7s5s 7s6s 7s7c 7s7d 7s7h 8c6c 8c7c 8d8c 8s6s 8s7s 8s8d 9c7c 9c8c 9d7d 9d8d 9d9c 9h7h 9h9c 9h9d 9s7s 9s8s 9s9c 9s9d 9s9h Ac2c Ac6c Ac8c Ac9c AcJc AcJd AcJh AcJs AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad2d Ad3d Ad4d Ad5d Ad7d Ad8d Ad9d AdJc AdJd AdJh AdJs AdKc AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah3h Ah4h Ah5h Ah6h Ah7h Ah9h AhJc AhJd AhJh AhJs AhKc AhKd AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs As2s As6s As8s As9s AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc8c Jc9c JcTh Jd8d Jd9d JdJc JdTh Jh9h JhJc JhJd JhTc JhTd JhTh JhTs Js8s Js9s JsJc JsJd JsJh JsTh Kc6c Kc8c Kc9c KcJh KcQc KcQh KcQs KcTh Kd5d Kd7d Kd8d Kd9d KdJd KdJh KdQd KdQh KdTd KdTh Kh5h Kh7h Kh9h KhJc KhJd KhJh KhJs KhKc KhKd KhQc KhQd KhQh KhQs KhTh Ks6s Ks8s Ks9s KsJh KsKh KsQc KsQh KsQs KsTh Qc8c Qc9c QcJh QcTh Qd8d Qd9d QdJd QdJh QdQc QdTd QdTh Qh9h QhJc QhJd QhJs QhQc QhQd QhTc QhTd QhTh QhTs Qs8s Qs9s QsJh QsQd QsQh QsTh Tc7c Tc8c Tc9c Td7d Td8d Td9d TdTc Th9h ThTc ThTd Ts7s Ts8s Ts9s TsTc TsTd TsTh')
        },
        {
          actions: [
            'fold'
          ],
          combos: expand('Ac3c Ac4c Ac5c Ac7c AcTc AcTd AcTs AdTc AdTs As3s As4s As5s As7s AsTc AsTd AsTs Jc9c JcTc JcTd JcTs JdTc JdTs Js9s JsTc JsTd JsTs Kc5c Kc7c Kc9c KcJc KcJd KcJs KcQd KcTc KcTd KcTs KdJc KdJs KdQc KdQs KdTc KdTs Ks5s Ks7s Ks9s KsJc KsJd KsJs KsQd KsTc KsTd KsTs Qc9c QcJc QcJd QcJs QcTc QcTd QcTs QdJc QdJs QdTc QdTs Qs9s QsJc QsJd QsJs QsTc QsTd QsTs')
        },
        {
          actions: [
            'raise_33%'
          ],
          combos: expand('2d2c 2s2c 2s2d 3h3c 3s3c 3s3h 4d4c 4h3h 4h4c 4s4c 4s4d 4s4h 5c3c 5c4c 5d4d 5d5c 5h3h 5h5c 5h5d 5s3s 5s4s 5s5c 5s5d 5s5h 6c4c 6h4h 6h5h 6h6c 6s4s 6s6c 6s6h 7c5c 7d5d 7d7c 7h6h 7h7c 7h7d 7s5s 7s7c 7s7d 7s7h 8c6c 8c7c 8d7d 8d8c 8s6s 8s7s 8s8c 8s8d 9d7d 9d8d 9h7h 9h9c 9h9d 9s9h Ac2c Ac6c Ac7c Ac8c AcJh AcKh AcKs AcQh AcTh Ad4d Ad8d AdJh AdKc AdKh AdKs AdQc AdQh AdQs AdTh Ah3h Ah4h Ah5h Ah6h Ah7h Ah9h AhJc AhJd AhJs AhKc AhKs AhQc AhQs AhTc AhTd AhTs As2s As6s As7s As8s AsJh AsKc AsKh AsQh AsTh Jc8c Jc9c JcTh Jd8d Jd9d JdTd JhJc JhTc JhTd JhTs Js8s Js9s JsJc JsJh JsTh Kc6c Kc7c Kc8c KcJh KcQc KcQh KcQs KcTh Kd5d Kd7d Kd9d Kh5h Kh6h Kh9h KhJc KhJd KhJh KhJs KhQd KhQh KhTc KhTd KhTh KhTs Ks6s Ks7s Ks8s KsJh KsKc KsQc KsQh KsQs KsTh Qc9c QcTh Qd8d Qd9d QdJd QdTd QhJh QhQc QhTc QhTd QhTs Qs9s QsQc QsQh QsTh Tc8c Tc9c Td8d Th7h Th9h ThTc Ts8s Ts9s TsTc TsTh')
        }
      ]
    },
    {
      position: 'BTN',
      stackBb: 100,
      villainPosition: 'UTG',
      board: [
        '8s',
        '3s',
        '2s'
      ],
      heroStackSize: 97.7,
      villainStackSize: 95.9,
      actionLine: 'preflop: UTG raises 2.3bb, BTN calls 2.3bb; flop: UTG bets 1.8bb',
      dealCombos: expand('2d2c 2h2c 2h2d 3d3c 3h3c 3h3d 4c3c 4d3d 4d4c 4h3h 4h4c 4h4d 4s4c 4s4d 4s4h 5c3c 5c4c 5d3d 5d4d 5d5c 5h3h 5h4h 5h5c 5h5d 5s4s 5s5c 5s5d 5s5h 6c4c 6c5c 6d4d 6d5d 6d6c 6h4h 6h5h 6h6c 6h6d 6s4s 6s5s 6s6c 6s6d 6s6h 7c5c 7c6c 7d5d 7d6d 7d7c 7h5h 7h6h 7h7c 7h7d 7s5s 7s6s 7s7c 7s7d 7s7h 8c6c 8c7c 8d6d 8d7d 8d8c 8h6h 8h7h 8h8c 8h8d 9c7c 9c8c 9d7d 9d8d 9d9c 9h7h 9h8h 9h9c 9h9d 9s7s 9s9c 9s9d 9s9h Ac2c Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad2d Ad3d Ad4d Ad5d Ad6d Ad7d Ad8d Ad9d AdJc AdJd AdJh AdJs AdKc AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah2h Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhJc AhJd AhJh AhJs AhKc AhKd AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs As4s As5s As6s As7s As9s AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc8c Jc9c JcTc JcTd JcTh JcTs Jd8d Jd9d JdJc JdTc JdTd JdTh JdTs Jh8h Jh9h JhJc JhJd JhTc JhTd JhTh JhTs Js9s JsJc JsJd JsJh JsTc JsTd JsTh JsTs Kc5c Kc6c Kc7c Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc KcTd KcTh KcTs Kd5d Kd6d Kd7d Kd8d Kd9d KdJc KdJd KdJh KdJs KdKc KdQc KdQd KdQh KdQs KdTc KdTd KdTh KdTs Kh5h Kh6h Kh7h Kh8h Kh9h KhJc KhJd KhJh KhJs KhKc KhKd KhQc KhQd KhQh KhQs KhTc KhTd KhTh KhTs Ks5s Ks6s Ks7s Ks9s KsJc KsJd KsJh KsJs KsKc KsKd KsKh KsQc KsQd KsQh KsQs KsTc KsTd KsTh KsTs Qc8c Qc9c QcJc QcJd QcJh QcJs QcTc QcTd QcTh QcTs Qd8d Qd9d QdJc QdJd QdJh QdJs QdQc QdTc QdTd QdTh QdTs Qh8h Qh9h QhJc QhJd QhJh QhJs QhQc QhQd QhTc QhTd QhTh QhTs Qs9s QsJc QsJd QsJh QsJs QsQc QsQd QsQh QsTc QsTd QsTh QsTs Tc7c Tc8c Tc9c Td7d Td8d Td9d TdTc Th7h Th8h Th9h ThTc ThTd Ts7s Ts9s TsTc TsTd TsTh'),
      buckets: [
        {
          actions: [
            'call'
          ],
          combos: expand('2d2c 2h2c 2h2d 3d3c 3h3c 3h3d 4c3c 4d3d 4d4c 4h3h 4h4c 4h4d 4s4c 4s4d 4s4h 5c3c 5c4c 5d3d 5d4d 5d5c 5h3h 5h4h 5h5c 5h5d 5s4s 5s5c 5s5d 5s5h 6c4c 6c5c 6d4d 6d5d 6d6c 6h4h 6h5h 6h6c 6h6d 6s4s 6s5s 6s6c 6s6d 6s6h 7c6c 7d6d 7d7c 7h6h 7h7c 7h7d 7s5s 7s6s 7s7c 7s7d 7s7h 8c6c 8c7c 8d6d 8d7d 8d8c 8h6h 8h7h 8h8c 8h8d 9c7c 9c8c 9d7d 9d8d 9d9c 9h7h 9h8h 9h9c 9h9d 9s7s 9s9c 9s9d 9s9h Ac2c Ac3c Ac4c Ac5c Ac8c AcJc AcJd AcJh AcJs AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad2d Ad3d Ad4d Ad5d Ad8d AdJc AdJd AdJh AdJs AdKc AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah2h Ah3h Ah4h Ah5h Ah8h AhJc AhJd AhJh AhJs AhKc AhKd AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs As4s As5s As6s As7s As9s AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc8c Jc9c JcTc JcTd JcTh JcTs Jd8d Jd9d JdJc JdTc JdTd JdTh JdTs Jh8h Jh9h JhJc JhJd JhTc JhTd JhTh JhTs Js9s JsJc JsJd JsJh JsTc JsTd JsTh JsTs Kc5c Kc8c KcJc KcJs KcQc KcQd KcQh KcQs KcTc KcTs Kd5d Kd8d KdJd KdJs KdKc KdQc KdQd KdQh KdQs KdTd KdTs Kh5h Kh8h KhJh KhJs KhKc KhKd KhQc KhQd KhQh KhQs KhTh KhTs Ks5s Ks6s Ks7s Ks9s KsJc KsJd KsJh KsJs KsKc KsKd KsKh KsQc KsQd KsQh KsQs KsTc KsTd KsTh KsTs Qc8c QcJc QcJs QcTs Qd8d QdJd QdJs QdQc QdTs Qh8h QhJh QhJs QhQc QhQd QhTs Qs9s QsJc QsJd QsJh QsJs QsQc QsQd QsQh QsTc QsTd QsTh QsTs Tc8c Tc9c Td8d Td9d TdTc Th8h Th9h ThTc ThTd Ts7s Ts9s TsTc TsTd TsTh')
        },
        {
          actions: [
            'fold'
          ],
          combos: expand('7c5c 7c6c 7d5d 7d6d 7h5h 7h6h 9c7c 9d7d 9h7h Ac6c Ac7c Ac9c AcTc AcTd AcTh Ad6d Ad7d Ad9d AdTc AdTd AdTh Ah6h Ah7h Ah9h AhTc AhTd AhTh Jc9c JcTc JcTd JcTh Jd9d JdTc JdTd JdTh Jh9h JhTc JhTd JhTh Kc5c Kc6c Kc7c Kc9c KcJc KcJd KcJh KcQc KcTc KcTd KcTh Kd5d Kd6d Kd7d Kd9d KdJc KdJd KdJh KdQd KdTc KdTd KdTh Kh5h Kh6h Kh7h Kh9h KhJc KhJd KhJh KhQh KhTc KhTd KhTh Qc9c QcJc QcJd QcJh QcTc QcTd QcTh Qd9d QdJc QdJd QdJh QdTc QdTd QdTh Qh9h QhJc QhJd QhJh QhTc QhTd QhTh Tc7c Td7d Th7h')
        },
        {
          actions: [
            'raise_33%'
          ],
          combos: expand('2d2c 2h2c 2h2d 3d3c 3h3c 3h3d 4c3c 4d3d 4d4c 4h3h 4h4c 4h4d 5c3c 5c4c 5d3d 5d4d 5d5c 5h3h 5h4h 5h5c 5h5d 6c4c 6c5c 6d4d 6d5d 6h4h 6h5h 7c6c 7d6d 7d7c 7h6h 7h7c 7h7d 7s6s 8c6c 8c7c 8d6d 8d7d 8d8c 8h6h 8h7h 8h8c 8h8d 9c7c 9d7d 9h7h 9s9c 9s9d 9s9h Ac3c Ac4c Ac5c Ac8c AcJs AcTs Ad3d Ad4d Ad5d Ad8d AdJs AdTs Ah3h Ah4h Ah5h Ah8h AhJs AhTs As4s As7s As9s AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs JcTc JcTs JdTd JdTs JhTh JhTs Js9s JsJc JsJd JsJh JsTs KcJc KcJs KcQs KdJd KdJs KdQs KhJh KhJs KhQs Ks5s Ks6s Ks7s KsJc KsJd KsJh KsQc KsQd KsQh KsTc KsTd KsTh KsTs QcTc QdTd QhTh QsQc QsQd QsQh QsTs Tc8c Tc9c Td8d Td9d Th8h Th9h Ts9s TsTc TsTd TsTh')
        }
      ]
    },
    {
      position: 'BTN',
      stackBb: 100,
      villainPosition: 'UTG',
      board: [
        '9h',
        '5h',
        '5d'
      ],
      heroStackSize: 97.7,
      villainStackSize: 94.9,
      actionLine: 'preflop: UTG raises 2.3bb, BTN calls 2.3bb; flop: UTG bets 1.8bb',
      dealCombos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4c3c 4d3d 4d4c 4h3h 4h4c 4h4d 4s3s 4s4c 4s4d 4s4h 5c3c 5c4c 5s3s 5s4s 5s5c 6c4c 6c5c 6d4d 6d6c 6h4h 6h6c 6h6d 6s4s 6s5s 6s6c 6s6d 6s6h 7c5c 7c6c 7d6d 7d7c 7h6h 7h7c 7h7d 7s5s 7s6s 7s7c 7s7d 7s7h 8c6c 8c7c 8d6d 8d7d 8d8c 8h6h 8h7h 8h8c 8h8d 8s6s 8s7s 8s8c 8s8d 8s8h 9c7c 9c8c 9d7d 9d8d 9d9c 9s7s 9s8s 9s9c 9s9d Ac2c Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad2d Ad3d Ad4d Ad6d Ad7d Ad8d Ad9d AdJc AdJd AdJh AdJs AdKc AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah2h Ah3h Ah4h Ah6h Ah7h Ah8h AhJc AhJd AhJh AhJs AhKc AhKd AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs As2s As3s As4s As5s As6s As7s As8s As9s AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc8c Jc9c JcTc JcTd JcTh JcTs Jd8d Jd9d JdJc JdTc JdTd JdTh JdTs Jh8h JhJc JhJd JhTc JhTd JhTh JhTs Js8s Js9s JsJc JsJd JsJh JsTc JsTd JsTh JsTs Kc5c Kc6c Kc7c Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc KcTd KcTh KcTs Kd6d Kd7d Kd8d Kd9d KdJc KdJd KdJh KdJs KdKc KdQc KdQd KdQh KdQs KdTc KdTd KdTh KdTs Kh6h Kh7h Kh8h KhJc KhJd KhJh KhJs KhKc KhKd KhQc KhQd KhQh KhQs KhTc KhTd KhTh KhTs Ks5s Ks6s Ks7s Ks8s Ks9s KsJc KsJd KsJh KsJs KsKc KsKd KsKh KsQc KsQd KsQh KsQs KsTc KsTd KsTh KsTs Qc8c Qc9c QcJc QcJd QcJh QcJs QcTc QcTd QcTh QcTs Qd8d Qd9d QdJc QdJd QdJh QdJs QdQc QdTc QdTd QdTh QdTs Qh8h QhJc QhJd QhJh QhJs QhQc QhQd QhTc QhTd QhTh QhTs Qs8s Qs9s QsJc QsJd QsJh QsJs QsQc QsQd QsQh QsTc QsTd QsTh QsTs Tc7c Tc8c Tc9c Td7d Td8d Td9d TdTc Th7h Th8h ThTc ThTd Ts7s Ts8s Ts9s TsTc TsTd TsTh'),
      buckets: [
        {
          actions: [
            'call'
          ],
          combos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4d4c 4h3h 4h4c 4h4d 4s4c 4s4d 4s4h 5s5c 6c5c 6d4d 6d6c 6h4h 6h6c 6h6d 6s5s 6s6c 6s6d 6s6h 7c5c 7c6c 7d6d 7d7c 7h6h 7h7c 7h7d 7s5s 7s6s 7s7c 7s7d 7s7h 8c6c 8c7c 8d7d 8d8c 8h6h 8h7h 8h8c 8h8d 8s6s 8s7s 8s8c 8s8d 8s8h 9c7c 9c8c 9d7d 9d8d 9d9c 9s7s 9s8s 9s9c 9s9d Ac8c Ac9c AcJc AcJd AcJh AcJs AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad2d Ad3d Ad4d Ad6d Ad7d Ad8d Ad9d AdJc AdJd AdJh AdJs AdKc AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah2h Ah3h Ah6h Ah8h AhJc AhJd AhJh AhJs AhKc AhKd AhKs AhQc AhQd AhQh AhQs AhTd AhTh As8s As9s AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc9c JcTc JcTd JcTs Jd8d Jd9d JdJc JdTc JdTd JdTh JdTs Jh8h JhJc JhJd JhTc JhTd JhTh JhTs Js9s JsJd JsJh JsTc JsTd JsTs Kc5c Kc9c KcJc KcJd KcJs KcQc KcQd KcQs KcTc KcTs Kd6d Kd7d Kd8d Kd9d KdJc KdJd KdJh KdJs KdKc KdQc KdQd KdQh KdQs KdTc KdTd KdTh KdTs Kh6h Kh7h KhJc KhJd KhJh KhJs KhKc KhKd KhQc KhQd KhQh KhQs KhTd KhTh Ks5s Ks9s KsJc KsJd KsJs KsKd KsKh KsQc KsQd KsQs KsTc KsTs Qc9c QcJc QcJh QcTh Qd8d Qd9d QdJd QdJh QdQc QdTd QdTh Qh8h QhJc QhJd QhJs QhQc QhQd QhTc QhTd QhTh QhTs Qs9s QsJh QsJs QsQc QsQd QsQh QsTh Tc9c Td7d Td8d Td9d TdTc Th7h Th8h ThTc ThTd Ts9s TsTd TsTh')
        },
        {
          actions: [
            'fold'
          ],
          combos: expand('4c3c 4d3d 4s3s 6c4c 6d4d 6s4s Ac2c Ac3c Ac4c Ac6c Ac7c As2s As3s As4s As6s As7s Jc8c JcTc JcTd JcTs JdTc JdTs Js8s JsTc JsTd JsTs Kc6c Kc7c Kc8c KcJc KcJd KcJs KcTc KcTd KcTs KdJc KdJs KdTc KdTs Ks6s Ks7s Ks8s KsJc KsJd KsJs KsTc KsTd KsTs Qc8c QcJc QcJd QcJs QcTc QcTd QcTs QdJc QdJs QdTc QdTs Qs8s QsJc QsJd QsJs QsTc QsTd QsTs Tc7c Tc8c Ts7s Ts8s')
        },
        {
          actions: [
            'raise_83%'
          ],
          combos: expand('2h2d 5c3c 5c4c 5s3s 5s4s 5s5c 6c5c 6s5s 7c6c 7d6d 7s6s 8c6c 8c7c 8d6d 8d7d 8h6h 8h7h 8s6s 8s7s 8s8c 9c7c 9d7d 9d8d 9d9c 9s7s 9s9c 9s9d Ac5c Ac8c Ac9c AcJh AcTh Ad7d Ad8d Ah2h Ah3h Ah4h Ah6h Ah7h Ah8h AhJc AhJd AhJs AhQc AhQs AhTc AhTd AhTs As5s As8s As9s AsJh AsTh JcTh JdTd JhJc JhTc JhTh JhTs JsJc JsJh JsTh Kc5c KcJh KcQc KcQh KcTh Kd8d KdJd KdQd KdTd Kh6h Kh7h Kh8h KhJc KhJh KhJs KhQc KhQs KhTc KhTd KhTh KhTs Ks5s KsJh KsKc KsQh KsQs KsTh QcJh QcTh Qd8d QdJd QdTd Qh8h QhJh QhQc QhTh QsJh QsQc QsQh QsTh ThTc TsTc TsTh')
        }
      ]
    },
    {
      position: 'BTN',
      stackBb: 100,
      villainPosition: 'UTG',
      board: [
        'Ac',
        'Kc',
        '3d'
      ],
      heroStackSize: 97.7,
      villainStackSize: 90.4,
      actionLine: 'preflop: UTG raises 2.3bb, BTN calls 2.3bb; flop: UTG bets 7.3bb',
      dealCombos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3h3c 3s3c 3s3h 4c3c 4d4c 4h3h 4h4c 4h4d 4s3s 4s4c 4s4d 4s4h 5c3c 5c4c 5d4d 5d5c 5h3h 5h4h 5h5c 5h5d 5s3s 5s4s 5s5c 5s5d 5s5h 6c4c 6c5c 6d4d 6d5d 6d6c 6h4h 6h5h 6h6c 6h6d 6s4s 6s5s 6s6c 6s6d 6s6h 7c5c 7c6c 7d5d 7d6d 7d7c 7h5h 7h6h 7h7c 7h7d 7s5s 7s6s 7s7c 7s7d 7s7h 8c6c 8c7c 8d6d 8d7d 8d8c 8h6h 8h7h 8h8c 8h8d 8s6s 8s7s 8s8c 8s8d 8s8h 9c7c 9c8c 9d7d 9d8d 9d9c 9h7h 9h8h 9h9c 9h9d 9s7s 9s8s 9s9c 9s9d 9s9h Ad2d Ad4d Ad5d Ad6d Ad7d Ad8d Ad9d AdJc AdJd AdJh AdJs AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah2h Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhJc AhJd AhJh AhJs AhKd AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs As2s As3s As4s As5s As6s As7s As8s As9s AsJc AsJd AsJh AsJs AsKd AsKh AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc8c Jc9c JcTc JcTd JcTh JcTs Jd8d Jd9d JdJc JdTc JdTd JdTh JdTs Jh8h Jh9h JhJc JhJd JhTc JhTd JhTh JhTs Js8s Js9s JsJc JsJd JsJh JsTc JsTd JsTh JsTs Kd5d Kd6d Kd7d Kd8d Kd9d KdJc KdJd KdJh KdJs KdQc KdQd KdQh KdQs KdTc KdTd KdTh KdTs Kh5h Kh6h Kh7h Kh8h Kh9h KhJc KhJd KhJh KhJs KhKd KhQc KhQd KhQh KhQs KhTc KhTd KhTh KhTs Ks5s Ks6s Ks7s Ks8s Ks9s KsJc KsJd KsJh KsJs KsKd KsKh KsQc KsQd KsQh KsQs KsTc KsTd KsTh KsTs Qc8c Qc9c QcJc QcJd QcJh QcJs QcTc QcTd QcTh QcTs Qd8d Qd9d QdJc QdJd QdJh QdJs QdQc QdTc QdTd QdTh QdTs Qh8h Qh9h QhJc QhJd QhJh QhJs QhQc QhQd QhTc QhTd QhTh QhTs Qs8s Qs9s QsJc QsJd QsJh QsJs QsQc QsQd QsQh QsTc QsTd QsTh QsTs Tc7c Tc8c Tc9c Td7d Td8d Td9d TdTc Th7h Th8h Th9h ThTc ThTd Ts7s Ts8s Ts9s TsTc TsTd TsTh'),
      buckets: [
        {
          actions: [
            'call'
          ],
          combos: expand('3h3c 3s3c 3s3h 4h3h 4s3s 5c3c 5c4c 5d4d 5h4h 5s4s 6c4c 6c5c 7c5c 7c6c 8c6c 8c7c 8d8c 9c7c 9c8c 9d9c 9h9c 9s9c Ad2d Ad4d Ad5d Ad6d Ad7d Ad8d Ad9d AdJc AdJd AdJh AdJs AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah2h Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhJc AhJd AhJh AhJs AhKd AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs As2s As3s As4s As5s As6s As7s As8s As9s AsJc AsJd AsJh AsJs AsKd AsKh AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc8c Jc9c JcTc JcTd JcTh JcTs JdJc JdTc JhTc JsTc Kd5d Kd6d Kd7d Kd8d Kd9d KdJc KdJd KdQc KdQd KdTc KdTd Kh5h Kh7h Kh8h Kh9h KhJc KhKd KhQc KhTc Ks5s Ks7s Ks8s Ks9s KsJc KsKd KsKh KsQc KsTc Qc8c Qc9c QcJc QcJd QcJh QcJs QcTc QcTd QcTh QcTs QdJc QdJd QdQc QdTc QdTd QhJc QhJh QhJs QhQc QhTc QhTh QsJc QsJh QsJs QsQc QsTc QsTs Tc7c Tc8c Tc9c')
        },
        {
          actions: [
            'fold'
          ],
          combos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 4d4c 4h3h 4h4c 4h4d 4s3s 4s4c 4s4d 4s4h 5d5c 5h3h 5h5c 5h5d 5s3s 5s5c 5s5d 5s5h 6d4d 6d5d 6d6c 6h4h 6h5h 6h6c 6h6d 6s4s 6s5s 6s6c 6s6d 6s6h 7d5d 7d6d 7d7c 7h5h 7h6h 7h7c 7h7d 7s5s 7s6s 7s7c 7s7d 7s7h 8d6d 8d7d 8d8c 8h6h 8h7h 8h8c 8h8d 8s6s 8s7s 8s8c 8s8d 8s8h 9d7d 9d8d 9h7h 9h8h 9h9c 9h9d 9s7s 9s8s 9s9c 9s9d 9s9h AdTh AdTs Ah6h Ah7h AhTd As6s As7s AsTd Jd8d Jd9d JdTd JdTh JdTs Jh8h Jh9h JhJc JhJd JhTd JhTh JhTs Js8s Js9s JsJc JsJd JsJh JsTd JsTh JsTs KdJd KdJh KdJs KdQd KdQh KdQs KdTh KdTs Kh6h Kh7h Kh8h Kh9h KhJd KhJh KhJs KhQd KhQh KhQs KhTd KhTh KhTs Ks6s Ks7s Ks8s Ks9s KsJd KsJh KsJs KsQd KsQh KsQs KsTd KsTh KsTs Qd8d Qd9d QdJh QdJs QdTh QdTs Qh8h Qh9h QhJd QhJs QhQd QhTd QhTh QhTs Qs8s Qs9s QsJd QsJh QsQd QsQh QsTd QsTh QsTs Td7d Td8d Td9d TdTc Th7h Th8h Th9h ThTc ThTd Ts7s Ts8s Ts9s TsTc TsTd TsTh')
        },
        {
          actions: [
            'raise_33%'
          ],
          combos: expand('3h3c 3s3c 3s3h 4c3c 5c3c 9c7c 9c8c AdJh AdJs AdKh AdKs AdQd AdTh AdTs Ah2h Ah6h Ah8h Ah9h AhJd AhKs AhQc AhQh AhQs As2s As6s As8s As9s AsJd AsKh AsQc AsQh AsQs Jc9c JcTc JdTd Kh6h Kh7h Kh9h KhJc KhTc Ks6s Ks7s Ks9s KsJc KsTc Qc8c Qc9c QdJc QdJd QdQc QdTd QhJc QsJc Tc7c')
        }
      ]
    },
    {
      position: 'BTN',
      stackBb: 100,
      villainPosition: 'UTG',
      board: [
        'Ad',
        'Jh',
        'Th'
      ],
      heroStackSize: 97.7,
      villainStackSize: 95.9,
      actionLine: 'preflop: UTG raises 2.3bb, BTN calls 2.3bb; flop: UTG bets 1.8bb',
      dealCombos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4c3c 4d3d 4d4c 4h3h 4h4c 4h4d 4s3s 4s4c 4s4d 4s4h 5c3c 5c4c 5d3d 5d4d 5d5c 5h3h 5h4h 5h5c 5h5d 5s3s 5s4s 5s5c 5s5d 5s5h 6c4c 6c5c 6d4d 6d5d 6d6c 6h4h 6h5h 6h6c 6h6d 6s4s 6s5s 6s6c 6s6d 6s6h 7c5c 7c6c 7d5d 7d6d 7d7c 7h5h 7h6h 7h7c 7h7d 7s5s 7s6s 7s7c 7s7d 7s7h 8c6c 8c7c 8d6d 8d7d 8d8c 8h6h 8h7h 8h8c 8h8d 8s6s 8s7s 8s8c 8s8d 8s8h 9c7c 9c8c 9d7d 9d8d 9d9c 9h7h 9h8h 9h9c 9h9d 9s7s 9s8s 9s9c 9s9d 9s9h Ac2c Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJs AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTs Ah2h Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhJc AhJd AhJs AhKc AhKd AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTs As2s As3s As4s As5s As6s As7s As8s As9s AsJc AsJd AsJs AsKc AsKd AsKh AsQc AsQd AsQh AsQs AsTc AsTd AsTs Jc8c Jc9c JcTc JcTd JcTs Jd8d Jd9d JdJc JdTc JdTd JdTs Js8s Js9s JsJc JsJd JsTc JsTd JsTs Kc5c Kc6c Kc7c Kc8c Kc9c KcJc KcJd KcJs KcQc KcQd KcQh KcQs KcTc KcTd KcTs Kd5d Kd6d Kd7d Kd8d Kd9d KdJc KdJd KdJs KdKc KdQc KdQd KdQh KdQs KdTc KdTd KdTs Kh5h Kh6h Kh7h Kh8h Kh9h KhJc KhJd KhJs KhKc KhKd KhQc KhQd KhQh KhQs KhTc KhTd KhTs Ks5s Ks6s Ks7s Ks8s Ks9s KsJc KsJd KsJs KsKc KsKd KsKh KsQc KsQd KsQh KsQs KsTc KsTd KsTs Qc8c Qc9c QcJc QcJd QcJs QcTc QcTd QcTs Qd8d Qd9d QdJc QdJd QdJs QdQc QdTc QdTd QdTs Qh8h Qh9h QhJc QhJd QhJs QhQc QhQd QhTc QhTd QhTs Qs8s Qs9s QsJc QsJd QsJs QsQc QsQd QsQh QsTc QsTd QsTs Tc7c Tc8c Tc9c Td7d Td8d Td9d TdTc Ts7s Ts8s Ts9s TsTc TsTd'),
      buckets: [
        {
          actions: [
            'call'
          ],
          combos: expand('2h2d 3h3c 3h3d 3s3h 4h3h 4h4d 5h3h 5h4h 5h5d 6h4h 6h5h 6h6c 6h6d 6s6h 7h5h 7h6h 7h7d 8c7c 8d7d 8h6h 8h7h 8h8c 8h8d 8s7s 8s8h 9c7c 9c8c 9d7d 9d8d 9h7h 9h8h 9h9c 9h9d 9s7s 9s8s 9s9h Ac2c Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJs AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTs Ah2h Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhJc AhJd AhJs AhKc AhKd AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTs As2s As3s As4s As5s As6s As7s As8s As9s AsJc AsJd AsJs AsKc AsKd AsKh AsQc AsQd AsQh AsQs AsTc AsTd AsTs Jc8c Jc9c JcTc JcTd JcTs Jd8d Jd9d JdJc JdTc JdTd JdTs Js8s Js9s JsJc JsJd JsTc JsTd JsTs Kc5c Kc6c Kc7c Kc8c Kc9c KcJc KcJd KcJs KcQc KcQd KcQh KcQs KcTc KcTd KcTs Kd5d Kd6d Kd7d Kd8d Kd9d KdJc KdJd KdJs KdKc KdQc KdQd KdQs KdTc KdTd KdTs Kh5h Kh6h Kh7h Kh8h Kh9h KhJc KhJd KhJs KhKc KhKd KhQc KhQd KhQh KhQs KhTc KhTd KhTs Ks5s Ks6s Ks7s Ks8s Ks9s KsJc KsJd KsJs KsKc KsKd KsKh KsQc KsQd KsQh KsQs KsTc KsTd KsTs Qc8c Qc9c QcJc QcJd QcJs QcTc QcTd QcTs Qd8d Qd9d QdJc QdJd QdJs QdQc QdTc QdTd QdTs Qh9h QhJc QhJd QhJs QhQc QhQd QhTc QhTd QhTs Qs8s Qs9s QsJc QsJd QsJs QsQc QsQd QsQh QsTc QsTd QsTs Tc7c Tc8c Tc9c Td7d Td8d Td9d TdTc Ts7s Ts8s Ts9s TsTc TsTd')
        },
        {
          actions: [
            'fold'
          ],
          combos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3s3c 3s3d 3s3h 4c3c 4d3d 4d4c 4h4c 4s3s 4s4c 4s4d 4s4h 5c3c 5c4c 5d3d 5d4d 5d5c 5h5c 5s3s 5s4s 5s5c 5s5d 5s5h 6c4c 6c5c 6d4d 6d5d 6d6c 6h6c 6s4s 6s5s 6s6c 6s6d 6s6h 7c5c 7c6c 7d5d 7d6d 7d7c 7h7c 7h7d 7s5s 7s6s 7s7c 7s7d 7s7h 8c6c 8d6d 8d8c 8s6s 8s8c 8s8d 9c7c 9d9c 9s7s 9s9c 9s9d')
        },
        {
          actions: [
            'raise_33%'
          ],
          combos: expand('3h3c 3h3d 3s3h 4h3h 4h4d 5d3d 5d4d 6h5h 8c7c 8d6d 8d7d 8h6h 8h8d 8s7s 9d7d 9d8d 9h7h Ac3c Ac4c Ac7c AcJs AcKh AcQd Ah5h Ah7h Ah9h AhJc AhJs AhQh AhTc AhTs As3s As4s As7s AsJc AsKh AsQd JcTd JdJc JdTd JsJd JsTd Kc6c Kc7c Kc8c Kc9c KcQd KcQh Kd8d Kd9d KdJd KdQc KdQd KdQh KdQs Kh5h Kh6h Kh7h Kh8h KhJd KhQd KhQh KhTc KhTd KhTs Ks6s Ks7s Ks8s Ks9s KsQd KsQh Qc8c Qc9c QcJd QcTc QcTd QcTs Qd9d QdQc Qh8h Qh9h Qs8s Qs9s QsJd QsQc QsQd QsTc QsTd QsTs TsTc')
        }
      ]
    },
    {
      position: 'BTN',
      stackBb: 100,
      villainPosition: 'UTG',
      board: [
        'Ah',
        '9d',
        '3c'
      ],
      heroStackSize: 97.7,
      villainStackSize: 95.9,
      actionLine: 'preflop: UTG raises 2.3bb, BTN calls 2.3bb; flop: UTG bets 1.8bb',
      dealCombos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3h3d 3s3d 3s3h 4d3d 4d4c 4h3h 4h4c 4h4d 4s3s 4s4c 4s4d 4s4h 5c4c 5d3d 5d4d 5d5c 5h3h 5h4h 5h5c 5h5d 5s3s 5s4s 5s5c 5s5d 5s5h 6c4c 6c5c 6d4d 6d5d 6d6c 6h4h 6h5h 6h6c 6h6d 6s4s 6s5s 6s6c 6s6d 6s6h 7c5c 7c6c 7d5d 7d6d 7d7c 7h5h 7h6h 7h7c 7h7d 7s5s 7s6s 7s7c 7s7d 7s7h 8c6c 8c7c 8d6d 8d7d 8d8c 8h6h 8h7h 8h8c 8h8d 8s6s 8s7s 8s8c 8s8d 8s8h 9c7c 9c8c 9h7h 9h8h 9h9c 9s7s 9s8s 9s9c 9s9h Ac2c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad2d Ad3d Ad4d Ad5d Ad6d Ad7d Ad8d AdJc AdJd AdJh AdJs AdKc AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs As2s As3s As4s As5s As6s As7s As8s As9s AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc8c Jc9c JcTc JcTd JcTh JcTs Jd8d JdJc JdTc JdTd JdTh JdTs Jh8h Jh9h JhJc JhJd JhTc JhTd JhTh JhTs Js8s Js9s JsJc JsJd JsJh JsTc JsTd JsTh JsTs Kc5c Kc6c Kc7c Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc KcTd KcTh KcTs Kd5d Kd6d Kd7d Kd8d KdJc KdJd KdJh KdJs KdKc KdQc KdQd KdQh KdQs KdTc KdTd KdTh KdTs Kh5h Kh6h Kh7h Kh8h Kh9h KhJc KhJd KhJh KhJs KhKc KhKd KhQc KhQd KhQh KhQs KhTc KhTd KhTh KhTs Ks5s Ks6s Ks7s Ks8s Ks9s KsJc KsJd KsJh KsJs KsKc KsKd KsKh KsQc KsQd KsQh KsQs KsTc KsTd KsTh KsTs Qc8c Qc9c QcJc QcJd QcJh QcJs QcTc QcTd QcTh QcTs Qd8d QdJc QdJd QdJh QdJs QdQc QdTc QdTd QdTh QdTs Qh8h Qh9h QhJc QhJd QhJh QhJs QhQc QhQd QhTc QhTd QhTh QhTs Qs8s Qs9s QsJc QsJd QsJh QsJs QsQc QsQd QsQh QsTc QsTd QsTh QsTs Tc7c Tc8c Tc9c Td7d Td8d TdTc Th7h Th8h Th9h ThTc ThTd Ts7s Ts8s Ts9s TsTc TsTd TsTh'),
      buckets: [
        {
          actions: [
            'call'
          ],
          combos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s4s 5s5c 5s5d 5s5h 6c4c 6d4d 6d5d 6d6c 6h4h 6h5h 6h6c 6h6d 6s6c 6s6d 6s6h 7c6c 7d5d 7d6d 7d7c 7h5h 7h6h 7h7c 7h7d 7s7c 7s7d 7s7h 8c7c 8d7d 8d8c 8h6h 8h7h 8h8c 8h8d 8s8c 8s8d 8s8h 9c7c 9c8c 9h7h 9h8h 9h9c 9s7s 9s8s 9s9c 9s9h Ac2c Ac4c Ac5c Ac6c Ac7c Ac8c AcJc AcJd AcJh AcJs AcKd AcKh AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad2d Ad3d Ad4d Ad5d Ad6d Ad7d Ad8d AdJc AdJd AdJh AdJs AdKc AdKh AdQc AdQh AdQs AdTc AdTd AdTh AdTs As2s As4s As5s As6s As7s As8s As9s AsJc AsJd AsJh AsKc AsKd AsKh AsQc AsQd AsQh AsTc AsTd AsTh AsTs Jc9c JcTc JcTs Jd8d JdJc JdTd JdTh JdTs Jh8h Jh9h JhJc JhJd JhTs Js9s JsJc JsJd JsJh JsTc JsTd JsTh JsTs Kc9c KcJc KcQc KdJd KdKc KdQd KdTd Kh9h KhJh KhKc KhKd KhQh Ks9s KsKc KsKd KsKh KsQd KsQs Qc9c QcJc QcJs QcTc QdJd QdJs QdQc QdTd Qh9h QhJh QhJs QhQc QhQd QhTh Qs9s QsJs QsQc QsQd QsQh Tc8c Tc9c Td7d Td8d TdTc Th7h Th8h Th9h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh')
        },
        {
          actions: [
            'fold'
          ],
          combos: expand('6c4c 6d4d 6s4s 6s5s 7s5s 7s6s 8c6c 8d6d 8h6h 8s6s 8s7s Jc8c JcTd JcTh JcTs JdTc JdTh JhTc JhTd JhTs Js8s Kc5c Kc6c Kc7c Kc8c KcJd KcJh KcJs KcQd KcQh KcQs KcTc KcTd KcTh KcTs Kd5d Kd6d Kd7d Kd8d KdJc KdJh KdJs KdQc KdQh KdQs KdTc KdTd KdTh KdTs Kh5h Kh6h Kh7h Kh8h KhJc KhJd KhJs KhQc KhQd KhQs KhTc KhTd KhTh KhTs Ks5s Ks6s Ks7s Ks8s KsJc KsJd KsJh KsJs KsQc KsQd KsQh KsTc KsTd KsTh KsTs Qc8c QcJd QcJh QcTd QcTh QcTs Qd8d QdJc QdJh QdTc QdTh QdTs Qh8h QhJc QhJd QhTc QhTd QhTs Qs8s QsJc QsJd QsJh QsTc QsTd QsTh QsTs Tc7c Ts7s Ts8s')
        },
        {
          actions: [
            'raise_83%'
          ],
          combos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3h3d 3s3d 3s3h 4d3d 4h3h 4s3s 4s4c 4s4d 4s4h 5c4c 5d3d 5d4d 5h3h 5h4h 5s3s 5s5c 5s5d 5s5h 6c4c 6c5c 6d4d 6d5d 6h4h 6h5h 7c5c 7d5d 7d6d 7h6h 8d7d 8h7h 9c7c 9c8c 9h7h 9h8h 9h9c 9s9c 9s9h Ac9c AcJc AcJs AcKd AcKh AcKs AcQc AcQs AcTc Ad3d AdJd AdKc AdKh AdKs AdQd AdQs As3s As9s AsJs AsKc AsKd AsKh AsQc AsQd AsQh AsQs AsTs JcTc JdTd Jh9h JhTh KhJh Qc9c QcJc QdJd QdTd Qh9h QhJh Tc8c Tc9c Td8d Th8h Th9h')
        }
      ]
    },
    {
      position: 'BTN',
      stackBb: 100,
      villainPosition: 'UTG',
      board: [
        'As',
        'Ac',
        '7s'
      ],
      heroStackSize: 97.7,
      villainStackSize: 95.9,
      actionLine: 'preflop: UTG raises 2.3bb, BTN calls 2.3bb; flop: UTG bets 1.8bb',
      dealCombos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4c3c 4d3d 4d4c 4h3h 4h4c 4h4d 4s3s 4s4c 4s4d 4s4h 5c3c 5c4c 5d3d 5d4d 5d5c 5h3h 5h4h 5h5c 5h5d 5s3s 5s4s 5s5c 5s5d 5s5h 6c4c 6c5c 6d4d 6d5d 6d6c 6h4h 6h5h 6h6c 6h6d 6s4s 6s5s 6s6c 6s6d 6s6h 7c5c 7c6c 7d5d 7d6d 7d7c 7h5h 7h6h 7h7c 7h7d 8c6c 8c7c 8d6d 8d7d 8d8c 8h6h 8h7h 8h8c 8h8d 8s6s 8s8c 8s8d 8s8h 9c7c 9c8c 9d7d 9d8d 9d9c 9h7h 9h8h 9h9c 9h9d 9s8s 9s9c 9s9d 9s9h Ad2d Ad3d Ad4d Ad5d Ad6d Ad7d Ad8d Ad9d AdJc AdJd AdJh AdJs AdKc AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah2h Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhJc AhJd AhJh AhJs AhKc AhKd AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs Jc8c Jc9c JcTc JcTd JcTh JcTs Jd8d Jd9d JdJc JdTc JdTd JdTh JdTs Jh8h Jh9h JhJc JhJd JhTc JhTd JhTh JhTs Js8s Js9s JsJc JsJd JsJh JsTc JsTd JsTh JsTs Kc5c Kc6c Kc7c Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc KcTd KcTh KcTs Kd5d Kd6d Kd7d Kd8d Kd9d KdJc KdJd KdJh KdJs KdKc KdQc KdQd KdQh KdQs KdTc KdTd KdTh KdTs Kh5h Kh6h Kh7h Kh8h Kh9h KhJc KhJd KhJh KhJs KhKc KhKd KhQc KhQd KhQh KhQs KhTc KhTd KhTh KhTs Ks5s Ks6s Ks8s Ks9s KsJc KsJd KsJh KsJs KsKc KsKd KsKh KsQc KsQd KsQh KsQs KsTc KsTd KsTh KsTs Qc8c Qc9c QcJc QcJd QcJh QcJs QcTc QcTd QcTh QcTs Qd8d Qd9d QdJc QdJd QdJh QdJs QdQc QdTc QdTd QdTh QdTs Qh8h Qh9h QhJc QhJd QhJh QhJs QhQc QhQd QhTc QhTd QhTh QhTs Qs8s Qs9s QsJc QsJd QsJh QsJs QsQc QsQd QsQh QsTc QsTd QsTh QsTs Tc7c Tc8c Tc9c Td7d Td8d Td9d TdTc Th7h Th8h Th9h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh'),
      buckets: [
        {
          actions: [
            'call'
          ],
          combos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s3s 5s4s 5s5c 5s5d 5s5h 6d6c 6h6c 6h6d 6s4s 6s5s 6s6c 6s6d 6s6h 7c5c 7c6c 7d5d 7d6d 7d7c 7h5h 7h6h 7h7c 7h7d 8c7c 8d7d 8d8c 8h7h 8h8c 8h8d 8s6s 8s8c 8s8d 8s8h 9c7c 9c8c 9d7d 9d9c 9h7h 9h9c 9h9d 9s8s 9s9c 9s9d 9s9h Ad2d Ad3d Ad4d Ad5d Ad6d Ad7d Ad8d Ad9d AdJc AdJd AdJh AdJs AdKc AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah2h Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhJc AhJd AhJh AhJs AhKc AhKd AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs JcTc JcTs JdJc JdTs JhJc JhJd JhTs Js8s Js9s JsJc JsJd JsJh JsTc JsTd JsTh JsTs Kc7c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc KcTs Kd7d KdJd KdJs KdKc KdQc KdQd KdQh KdQs KdTs Kh7h KhJh KhJs KhKc KhKd KhQc KhQd KhQh KhQs KhTs Ks5s Ks6s Ks8s Ks9s KsJc KsJd KsJh KsJs KsKc KsKd KsKh KsQd KsQh KsQs KsTc KsTd KsTh KsTs QcJc QcJs QcTc QcTs QdJs QdQc QdTs QhJs QhQc QhQd QhTs Qs8s QsJc QsJd QsJh QsJs QsQc QsQd QsQh QsTc QsTd QsTh QsTs Tc7c Tc9c Td7d TdTc Th7h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh')
        },
        {
          actions: [
            'fold'
          ],
          combos: expand('4c3c 4d3d 4h3h 5c3c 5c4c 5d3d 5d4d 5h3h 5h4h 6c4c 6c5c 6d4d 6d5d 6h4h 6h5h 8c6c 8d6d 8h6h 9d8d 9h8h Jc8c Jc9c JcTd JcTh Jd8d Jd9d JdTc JdTd JdTh Jh8h Jh9h JhTc JhTd JhTh Kc5c Kc6c Kc8c KcJd KcJh KcTd KcTh Kd5d Kd6d Kd8d Kd9d KdJc KdJh KdTc KdTd KdTh Kh5h Kh6h Kh8h Kh9h KhJc KhJd KhTc KhTd KhTh Qc8c Qc9c QcJd QcJh QcTd QcTh Qd8d Qd9d QdJc QdJd QdJh QdTc QdTd QdTh Qh8h Qh9h QhJc QhJd QhJh QhTc QhTd QhTh Tc8c Tc9c Td8d Td9d Th8h Th9h')
        },
        {
          actions: [
            'raise_33%'
          ],
          combos: expand('2d2c 2h2c 2s2c 2s2d 2s2h 3s3c 3s3d 3s3h 4d4c 4h4c 4h4d 4s3s 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6h6d 6s4s 7c6c 7d5d 7d6d 7d7c 7h5h 7h6h 7h7c 7h7d 8c6c 8c7c 8h8d 8s6s 9s8s 9s9d 9s9h Ad4d Ad5d Ad6d Ad7d Ad8d Ad9d AdJd AdJh AdKh AdKs AdQd AdQh AdQs AdTd AdTh AdTs Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhJd AhJh AhKd AhKs AhQd AhQh AhQs AhTd AhTh AhTs JcTc JcTs JdTs JhTs Js8s JsJc JsTc JsTs Kc7c KcJs KcQs KdJs KdQs KdTs KhJs KhQs KhTs Ks5s Ks6s Ks9s KsJs KsQc KsQs QcJs QdJs QdTs QhJs QhTs Qs8s Qs9s QsJs QsQc Tc7c Ts8s Ts9s TsTd TsTh')
        }
      ]
    },
    {
      position: 'BTN',
      stackBb: 100,
      villainPosition: 'UTG',
      board: [
        'Jd',
        '6d',
        '2c'
      ],
      heroStackSize: 97.7,
      villainStackSize: 94.9,
      actionLine: 'preflop: UTG raises 2.3bb, BTN calls 2.3bb; flop: UTG bets 2.8bb',
      dealCombos: expand('2h2d 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4c3c 4d3d 4d4c 4h3h 4h4c 4h4d 4s3s 4s4c 4s4d 4s4h 5c3c 5c4c 5d3d 5d4d 5d5c 5h3h 5h4h 5h5c 5h5d 5s3s 5s4s 5s5c 5s5d 5s5h 6c4c 6c5c 6h4h 6h5h 6h6c 6s4s 6s5s 6s6c 6s6h 7c5c 7c6c 7d5d 7d7c 7h5h 7h6h 7h7c 7h7d 7s5s 7s6s 7s7c 7s7d 7s7h 8c6c 8c7c 8d7d 8d8c 8h6h 8h7h 8h8c 8h8d 8s6s 8s7s 8s8c 8s8d 8s8h 9c7c 9c8c 9d7d 9d8d 9d9c 9h7h 9h8h 9h9c 9h9d 9s7s 9s8s 9s9c 9s9d 9s9h Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJh AcJs AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad2d Ad3d Ad4d Ad5d Ad7d Ad8d Ad9d AdJc AdJh AdJs AdKc AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah2h Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhJc AhJh AhJs AhKc AhKd AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs As2s As3s As4s As5s As6s As7s As8s As9s AsJc AsJh AsJs AsKc AsKd AsKh AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc8c Jc9c JcTc JcTd JcTh JcTs Jh8h Jh9h JhJc JhTc JhTd JhTh JhTs Js8s Js9s JsJc JsJh JsTc JsTd JsTh JsTs Kc5c Kc6c Kc7c Kc8c Kc9c KcJc KcJh KcJs KcQc KcQd KcQh KcQs KcTc KcTd KcTh KcTs Kd5d Kd7d Kd8d Kd9d KdJc KdJh KdJs KdKc KdQc KdQd KdQh KdQs KdTc KdTd KdTh KdTs Kh5h Kh6h Kh7h Kh8h Kh9h KhJc KhJh KhJs KhKd KhQc KhQd KhQh KhQs KhTc KhTd KhTh KhTs Ks5s Ks6s Ks7s Ks8s Ks9s KsJc KsJh KsJs KsKd KsKh KsQc KsQd KsQh KsQs KsTc KsTd KsTh KsTs Qc8c Qc9c QcJc QcJh QcJs QcTc QcTd QcTh QcTs Qd8d Qd9d QdJc QdJh QdJs QdQc QdTc QdTd QdTh QdTs Qh8h Qh9h QhJc QhJh QhJs QhQc QhQd QhTc QhTd QhTh QhTs Qs8s Qs9s QsJc QsJh QsJs QsQc QsQd QsQh QsTc QsTd QsTh QsTs Tc7c Tc8c Tc9c Td7d Td8d Td9d TdTc Th7h Th8h Th9h ThTc ThTd Ts7s Ts8s Ts9s TsTc TsTd TsTh'),
      buckets: [
        {
          actions: [
            'call'
          ],
          combos: expand('2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4c3c 4d4c 4h3h 4h4c 4h4d 4s3s 4s4c 4s4d 4s4h 5c3c 5c4c 5d3d 5d4d 5d5c 5h3h 5h4h 5h5c 5h5d 5s3s 5s4s 5s5c 5s5d 5s5h 6c4c 6c5c 6h4h 6h5h 6h6c 6s4s 6s5s 6s6c 6s6h 7c6c 7d5d 7d7c 7h6h 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8c6c 8d7d 8d8c 8h6h 8h8c 8h8d 8s6s 8s8c 8s8d 8s8h 9c8c 9d7d 9d8d 9d9c 9h9c 9h9d 9s9c 9s9d 9s9h Ac3c Ac4c Ac5c Ac6c Ac8c Ac9c AcJc AcJh AcJs AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd Ad2d Ad3d Ad4d Ad5d Ad7d Ad8d Ad9d AdJc AdJh AdJs AdKc AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah2h Ah6h AhJc AhJh AhJs AhKc AhKd AhKs AhQc AhQd AhQh AhQs AhTd As2s As6s AsJc AsJh AsJs AsKc AsKd AsKh AsQc AsQd AsQh AsQs AsTd Jc8c Jc9c JcTc JcTd JcTh JcTs Jh8h Jh9h JhJc JhTc JhTd JhTh JhTs Js8s Js9s JsJc JsJh JsTc JsTd JsTh JsTs Kc6c KcJc KcJh KcJs KcQc KcQd KcTc KcTd Kd5d Kd7d Kd8d Kd9d KdJc KdJh KdJs KdKc KdQc KdQd KdQh KdQs KdTc KdTd KdTh KdTs Kh6h KhJc KhJh KhJs KhKd KhQc KhQd KhQh KhQs KhTd Ks6s KsJc KsJh KsJs KsKd KsQc KsQd KsQh KsQs KsTd Qc9c QcJc QcJh QcJs QcTc QcTd Qd8d Qd9d QdJc QdJh QdJs QdQc QdTc QdTd QdTh QdTs QhJc QhJh QhJs QhQc QhQd QhTd QsJc QsJh QsJs QsQc QsQd QsQh QsTd Tc9c Td7d Td8d Td9d TdTc ThTc ThTd TsTc TsTd TsTh')
        },
        {
          actions: [
            'fold'
          ],
          combos: expand('3h3c 3s3c 3s3h 4h4c 4s4c 4s4h 7c5c 7h5h 7s5s 8c7c 8h7h 8s7s 9c7c 9c8c 9h7h 9h8h 9s7s 9s8s Ac3c Ac7c Ac8c AcQh AcQs AcTh AcTs Ah3h Ah4h Ah5h Ah7h Ah8h Ah9h AhTc AhTh AhTs As3s As4s As5s As7s As8s As9s AsTc AsTh AsTs Kc5c Kc7c Kc8c Kc9c KcQh KcQs KcTh KcTs Kh5h Kh7h Kh8h Kh9h KhQc KhTc KhTh KhTs Ks5s Ks7s Ks8s Ks9s KsQc KsTc KsTh KsTs Qc8c Qc9c QcTh QcTs Qh8h Qh9h QhTc QhTh QhTs Qs8s Qs9s QsTc QsTh QsTs Tc7c Tc8c Th7h Th8h Th9h Ts7s Ts8s Ts9s')
        },
        {
          actions: [
            'raise_55%'
          ],
          combos: expand('2h2d 2s2d 2s2h 3h3d 3s3d 3s3h 4c3c 4d3d 4h4d 4s4d 5c3c 5d3d 5h3h 5h4h 5s3s 5s4s 6c4c 6c5c 6h5h 6h6c 6s5s 6s6c 6s6h 7h6h 7s6s 8c6c 8c7c 9d7d 9d8d AcJc Ad3d Ad4d Ad5d Ad7d Ad8d Ad9d AdKh AdKs AdQc AdQh AdQs AdTh AdTs Ah2h AhJc AhJs AhTd As2s AsJc AsJh AsTd Jh8h Jh9h JhTs Js8s Js9s JsTh KcQc KcQd KcTc Kd5d Kd7d Kd8d Kd9d KdQc KdQd KdQh KdQs KdTd KdTh KdTs KhQd KhTd KsKh KsQd KsTd Qc9c Qd9d QdTd QdTh QdTs QhQd QsQd QsQh')
        }
      ]
    },
    {
      position: 'BTN',
      stackBb: 100,
      villainPosition: 'UTG',
      board: [
        'Js',
        '8s',
        '8d'
      ],
      heroStackSize: 97.7,
      villainStackSize: 94.9,
      actionLine: 'preflop: UTG raises 2.3bb, BTN calls 2.3bb; flop: UTG bets 1.8bb',
      dealCombos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4c3c 4d3d 4d4c 4h3h 4h4c 4h4d 4s3s 4s4c 4s4d 4s4h 5c3c 5c4c 5d3d 5d4d 5d5c 5h3h 5h4h 5h5c 5h5d 5s3s 5s4s 5s5c 5s5d 5s5h 6c4c 6c5c 6d4d 6d5d 6d6c 6h4h 6h5h 6h6c 6h6d 6s4s 6s5s 6s6c 6s6d 6s6h 7c5c 7c6c 7d5d 7d6d 7d7c 7h5h 7h6h 7h7c 7h7d 7s5s 7s6s 7s7c 7s7d 7s7h 8c6c 8c7c 8h6h 8h7h 8h8c 9c7c 9c8c 9d7d 9d9c 9h7h 9h8h 9h9c 9h9d 9s7s 9s9c 9s9d 9s9h Ac2c Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad2d Ad3d Ad4d Ad5d Ad6d Ad7d Ad9d AdJc AdJd AdJh AdKc AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah2h Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhJc AhJd AhJh AhKc AhKd AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs As2s As3s As4s As5s As6s As7s As9s AsJc AsJd AsJh AsKc AsKd AsKh AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc8c Jc9c JcTc JcTd JcTh JcTs Jd9d JdJc JdTc JdTd JdTh JdTs Jh8h Jh9h JhJc JhJd JhTc JhTd JhTh JhTs Kc5c Kc6c Kc7c Kc8c Kc9c KcJc KcJd KcJh KcQc KcQd KcQh KcQs KcTc KcTd KcTh KcTs Kd5d Kd6d Kd7d Kd9d KdJc KdJd KdJh KdKc KdQc KdQd KdQh KdQs KdTc KdTd KdTh KdTs Kh5h Kh6h Kh7h Kh8h Kh9h KhJc KhJd KhJh KhKc KhKd KhQc KhQd KhQh KhQs KhTc KhTd KhTh KhTs Ks5s Ks6s Ks7s Ks9s KsJc KsJd KsJh KsKd KsQc KsQd KsQh KsQs KsTc KsTd KsTh KsTs Qc8c Qc9c QcJc QcJd QcJh QcTc QcTd QcTh QcTs Qd9d QdJc QdJd QdJh QdQc QdTc QdTd QdTh QdTs Qh8h Qh9h QhJc QhJd QhJh QhQc QhQd QhTc QhTd QhTh QhTs Qs9s QsJc QsJd QsJh QsQc QsQd QsQh QsTc QsTd QsTh QsTs Tc7c Tc8c Tc9c Td7d Td9d TdTc Th7h Th8h Th9h ThTc ThTd Ts7s Ts9s TsTc TsTd TsTh'),
      buckets: [
        {
          actions: [
            'call'
          ],
          combos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4d4c 4h4c 4h4d 4s3s 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s3s 5s4s 5s5c 5s5d 5s5h 6d6c 6h6c 6h6d 6s4s 6s5s 6s6c 6s6d 6s6h 7d7c 7h7c 7h7d 7s5s 7s6s 7s7c 7s7d 7s7h 8c6c 8c7c 8h6h 8h7h 8h8c 9c7c 9c8c 9d7d 9d9c 9h7h 9h8h 9h9c 9h9d 9s7s 9s9c 9s9d 9s9h Ac9c AcJc AcJd AcJh AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh Ad3d Ad4d Ad5d Ad6d Ad7d Ad9d AdJc AdJh AdKc AdKh AdKs AdQc AdQd AdQh AdQs AdTd AdTs Ah9h AhJc AhJd AhJh AhKc AhKd AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh As2s As3s As4s As5s As6s As7s As9s AsJc AsJd AsJh AsKc AsKd AsKh AsQc AsQd AsQh AsTd AsTs Jc8c Jc9c JcTc JcTd JcTh JcTs Jd9d JdJc JdTc JdTd JdTh JdTs Jh8h Jh9h JhJc JhJd JhTc JhTd JhTh JhTs Kc8c KcJc KcJd KcJh KcQc KcQd KcQh Kd9d KdJc KdJd KdJh KdKc KdQc KdQd KdQh KdQs KdTd KdTs Kh8h KhJc KhJd KhJh KhKc KhKd KhQc KhQd KhQh Ks6s Ks7s Ks9s KsJc KsJd KsJh KsKd KsQc KsQd KsQh KsQs KsTd KsTs Qc9c QcJc QcJd QcJh QcTc QcTd QcTh Qd9d QdJc QdJd QdJh QdQc QdTc QdTd QdTh Qh9h QhJc QhJd QhJh QhQc QhQd QhTc QhTd QhTh Qs9s QsJc QsJd QsJh QsQc QsQd QsQh QsTc QsTd QsTh QsTs Tc7c Tc8c Tc9c Td7d Td9d TdTc Th7h Th8h Th9h ThTc ThTd Ts7s Ts9s TsTc TsTd TsTh')
        },
        {
          actions: [
            'fold'
          ],
          combos: expand('4c3c 4d3d 4h3h 5c3c 5c4c 5d3d 5d4d 5h3h 5h4h 6c4c 6c5c 6d4d 6d5d 6h4h 6h5h 7c5c 7c6c 7d5d 7d6d 7h5h 7h6h Ac2c Ac3c Ac4c Ac5c Ac6c Ac7c Ac9c Ad2d Ad3d Ad4d AdTc AdTh Ah2h Ah3h Ah4h Ah5h Ah6h Ah7h Ah9h Kc5c Kc6c Kc7c Kc9c KcQd KcQh KcTc KcTd KcTh Kd5d Kd6d Kd7d KdQc KdQh KdTc KdTh Kh5h Kh6h Kh7h Kh9h KhQc KhQd KhTc KhTd KhTh')
        },
        {
          actions: [
            'raise_55%'
          ],
          combos: expand('2d2c 2h2c 2h2d 2s2d 3h3c 3s3c 3s3d 3s3h 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s4s 6h6c 6s5s 6s6c 6s6h 7h7c 7s7c 7s7h 8c6c 8c7c 8h6h 8h7h 8h8c 9c7c 9c8c 9d7d 9h7h 9h8h 9s7s Ac8c Ac9c AcJc AcJd AcJh AcQh AcQs AcTh AcTs Ad7d Ad9d AdJc AdJd AdJh Ah8h Ah9h AhJc AhJd AhJh AhQc AhQs AhTc AhTs As2s As4s As5s As7s As9s AsJc AsJh AsKc AsKh AsQd AsQs AsTc AsTd AsTh AsTs Jc9c JcTc JcTd JcTh Jd9d JdJc JdTc JdTd JdTh Jh9h JhJc JhJd JhTc JhTd JhTh Kc8c KcJh KcQc KcQd KcQs KcTs KdJd KdQd KdTd Kh8h KhJc KhQd KhQh KhQs KhTs Ks5s Ks6s Ks7s Ks9s KsQc KsQd KsQh KsQs KsTc KsTd KsTh KsTs Qc8c QcTc QcTh QcTs Qd9d QdQc QdTc QdTd QdTh QdTs Qh8h QhQc QhQd QhTc QhTh QhTs Qs9s QsQc QsQd QsQh QsTc QsTh QsTs Tc8c Tc9c Td7d Td9d Th8h Th9h Ts7s Ts9s')
        }
      ]
    },
    {
      position: 'BTN',
      stackBb: 100,
      villainPosition: 'UTG',
      board: [
        'Kc',
        '6c',
        '3s'
      ],
      heroStackSize: 97.7,
      villainStackSize: 95.9,
      actionLine: 'preflop: UTG raises 2.3bb, BTN calls 2.3bb; flop: UTG bets 1.8bb',
      dealCombos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 4c3c 4d3d 4d4c 4h3h 4h4c 4h4d 4s4c 4s4d 4s4h 5c3c 5c4c 5d3d 5d4d 5d5c 5h3h 5h4h 5h5c 5h5d 5s4s 5s5c 5s5d 5s5h 6d4d 6d5d 6h4h 6h5h 6h6d 6s4s 6s5s 6s6d 6s6h 7c5c 7d5d 7d6d 7d7c 7h5h 7h6h 7h7c 7h7d 7s5s 7s6s 7s7c 7s7d 7s7h 8c7c 8d6d 8d7d 8d8c 8h6h 8h7h 8h8c 8h8d 8s6s 8s7s 8s8c 8s8d 8s8h 9c7c 9c8c 9d7d 9d8d 9d9c 9h7h 9h8h 9h9c 9h9d 9s7s 9s8s 9s9c 9s9d 9s9h Ac2c Ac3c Ac4c Ac5c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad2d Ad3d Ad4d Ad5d Ad6d Ad7d Ad8d Ad9d AdJc AdJd AdJh AdJs AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah2h Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhJc AhJd AhJh AhJs AhKd AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs As2s As4s As5s As6s As7s As8s As9s AsJc AsJd AsJh AsJs AsKd AsKh AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc8c Jc9c JcTc JcTd JcTh JcTs Jd8d Jd9d JdJc JdTc JdTd JdTh JdTs Jh8h Jh9h JhJc JhJd JhTc JhTd JhTh JhTs Js8s Js9s JsJc JsJd JsJh JsTc JsTd JsTh JsTs Kd5d Kd6d Kd7d Kd8d Kd9d KdJc KdJd KdJh KdJs KdQc KdQd KdQh KdQs KdTc KdTd KdTh KdTs Kh5h Kh6h Kh7h Kh8h Kh9h KhJc KhJd KhJh KhJs KhKd KhQc KhQd KhQh KhQs KhTc KhTd KhTh KhTs Ks5s Ks6s Ks7s Ks8s Ks9s KsJc KsJd KsJh KsJs KsKd KsKh KsQc KsQd KsQh KsQs KsTc KsTd KsTh KsTs Qc8c Qc9c QcJc QcJd QcJh QcJs QcTc QcTd QcTh QcTs Qd8d Qd9d QdJc QdJd QdJh QdJs QdQc QdTc QdTd QdTh QdTs Qh8h Qh9h QhJc QhJd QhJh QhJs QhQc QhQd QhTc QhTd QhTh QhTs Qs8s Qs9s QsJc QsJd QsJh QsJs QsQc QsQd QsQh QsTc QsTd QsTh QsTs Tc7c Tc8c Tc9c Td7d Td8d Td9d TdTc Th7h Th8h Th9h ThTc ThTd Ts7s Ts8s Ts9s TsTc TsTd TsTh'),
      buckets: [
        {
          actions: [
            'call'
          ],
          combos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3h3d 4d3d 4d4c 4h3h 4h4c 4h4d 4s4c 4s4d 4s4h 5c3c 5c4c 5d3d 5d4d 5d5c 5h3h 5h4h 5h5c 5h5d 5s4s 5s5c 5s5d 5s5h 6d4d 6d5d 6h4h 6h5h 6h6d 6s6d 6s6h 7c5c 7d5d 7d6d 7d7c 7h5h 7h6h 7h7c 7h7d 7s5s 7s6s 7s7c 7s7d 7s7h 8c7c 8d6d 8d8c 8h6h 8h8c 8h8d 8s6s 8s7s 8s8c 8s8d 8s8h 9c7c 9c8c 9d9c 9h9c 9h9d 9s7s 9s8s 9s9c 9s9d 9s9h Ac2c Ac3c Ac4c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad3d Ad4d Ad6d AdJc AdJd AdJh AdJs AdKh AdKs AdQc AdQd AdQh AdQs AdTd AdTh Ah3h Ah4h Ah6h AhJc AhJd AhJh AhJs AhKd AhKs AhQc AhQd AhQh AhQs AhTd AhTh As2s As4s As5s As6s As7s As8s As9s AsJc AsJd AsJh AsJs AsKd AsKh AsQc AsQd AsQh AsQs AsTc AsTs Jc8c Jc9c JcTc JcTd JcTh JcTs JdJc JdTc JhJc JhJd JhTc JsJc JsJd JsJh JsTc JsTs Kd5d Kd6d Kd7d Kd8d Kd9d KdJc KdJd KdJh KdJs KdQc KdQd KdQh KdQs KdTc KdTd KdTh KdTs Kh5h Kh6h Kh7h Kh8h Kh9h KhJc KhJd KhJh KhJs KhKd KhQc KhQd KhQh KhQs KhTc KhTd KhTh KhTs Ks5s Ks6s Ks7s Ks8s Ks9s KsJc KsJd KsJh KsJs KsKd KsKh KsQc KsQd KsQh KsQs KsTc KsTd KsTh KsTs Qc8c Qc9c QcJc QcJd QcJh QcJs QcTc QcTs QdJc QdQc QdTc QhJc QhQc QhQd QhTc QsJc QsJs QsQc QsQd QsQh QsTc QsTs Tc8c Tc9c TdTc ThTc ThTd Ts9s TsTc TsTd TsTh')
        },
        {
          actions: [
            'fold'
          ],
          combos: expand('8d7d 8h7h 9d7d 9d8d 9h7h 9h8h Ad2d Ad4d Ad5d Ad7d Ad8d Ad9d AdTd AdTh AdTs Ah2h Ah4h Ah5h Ah7h Ah8h Ah9h AhTd AhTh AhTs AsJd AsJh AsTd AsTh Jd8d Jd9d JdTd JdTh JdTs Jh8h Jh9h JhTd JhTh JhTs Js8s Js9s JsTd JsTh Qd8d Qd9d QdJd QdJh QdJs QdTd QdTh QdTs Qh8h Qh9h QhJd QhJh QhJs QhTd QhTh QhTs Qs8s Qs9s QsJd QsJh QsTd QsTh Td7d Td8d Td9d Th7h Th8h Th9h Ts7s Ts8s')
        },
        {
          actions: [
            'raise_83%'
          ],
          combos: expand('2d2c 2h2c 2s2c 3d3c 3h3c 3h3d 4c3c 4d4c 4h4c 4s4c 5c3c 5c4c 5d3d 5h3h 5s4s 6d4d 6d5d 6h4h 6h5h 6h6d 6s4s 6s5s 6s6d 6s6h 7d6d 7h6h 7s5s 7s6s 8s6s 8s7s 9c7c 9c8c Ac4c Ac5c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcQd AcQh AcQs AcTc Ad3d Ad4d AdJc AdKh AdQc AdTc Ah3h Ah4h AhJc AhKd AhQc AhTc As2s As4s AsJc AsKd AsKh AsTc Jc8c Jc9c JcTd JcTh Kd6d KdQd KdQh Kh6h KhQd KhQh Ks5s Ks6s KsJd KsJh KsQs Qc9c QcTd QcTh Tc7c Tc8c Tc9c')
        }
      ]
    },
    {
      position: 'BTN',
      stackBb: 100,
      villainPosition: 'UTG',
      board: [
        'Kd',
        'Th',
        '7h'
      ],
      heroStackSize: 97.7,
      villainStackSize: 94.9,
      actionLine: 'preflop: UTG raises 2.3bb, BTN calls 2.3bb; flop: UTG bets 2.8bb',
      dealCombos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4c3c 4d3d 4d4c 4h3h 4h4c 4h4d 4s3s 4s4c 4s4d 4s4h 5c3c 5c4c 5d3d 5d4d 5d5c 5h3h 5h4h 5h5c 5h5d 5s3s 5s4s 5s5c 5s5d 5s5h 6c4c 6c5c 6d4d 6d5d 6d6c 6h4h 6h5h 6h6c 6h6d 6s4s 6s5s 6s6c 6s6d 6s6h 7c5c 7c6c 7d5d 7d6d 7d7c 7s5s 7s6s 7s7c 7s7d 8c6c 8c7c 8d6d 8d7d 8d8c 8h6h 8h8c 8h8d 8s6s 8s7s 8s8c 8s8d 8s8h 9c7c 9c8c 9d7d 9d8d 9d9c 9h8h 9h9c 9h9d 9s7s 9s8s 9s9c 9s9d 9s9h Ac2c Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTs Ad2d Ad3d Ad4d Ad5d Ad6d Ad7d Ad8d Ad9d AdJc AdJd AdJh AdJs AdKc AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTs Ah2h Ah3h Ah4h Ah5h Ah6h Ah8h Ah9h AhJc AhJd AhJh AhJs AhKc AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTs As2s As3s As4s As5s As6s As7s As8s As9s AsJc AsJd AsJh AsJs AsKc AsKh AsQc AsQd AsQh AsQs AsTc AsTd AsTs Jc8c Jc9c JcTc JcTd JcTs Jd8d Jd9d JdJc JdTc JdTd JdTs Jh8h Jh9h JhJc JhJd JhTc JhTd JhTs Js8s Js9s JsJc JsJd JsJh JsTc JsTd JsTs Kc5c Kc6c Kc7c Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc KcTd KcTs Kh5h Kh6h Kh8h Kh9h KhJc KhJd KhJh KhJs KhKc KhQc KhQd KhQh KhQs KhTc KhTd KhTs Ks5s Ks6s Ks7s Ks8s Ks9s KsJc KsJd KsJh KsJs KsKc KsKh KsQc KsQd KsQh KsQs KsTc KsTd KsTs Qc8c Qc9c QcJc QcJd QcJh QcJs QcTc QcTd QcTs Qd8d Qd9d QdJc QdJd QdJh QdJs QdQc QdTc QdTd QdTs Qh8h Qh9h QhJc QhJd QhJh QhJs QhQc QhQd QhTc QhTd QhTs Qs8s Qs9s QsJc QsJd QsJh QsJs QsQc QsQd QsQh QsTc QsTd QsTs Tc7c Tc8c Tc9c Td7d Td8d Td9d TdTc Ts7s Ts8s Ts9s TsTc TsTd'),
      buckets: [
        {
          actions: [
            'call'
          ],
          combos: expand('2h2c 2h2d 2s2h 3h3c 3h3d 3s3h 4h3h 4h4c 4h4d 4s4h 5h3h 5h4h 5h5d 6h4h 6h5h 6h6c 6h6d 6s6h 7c5c 7c6c 7d5d 7d6d 7d7c 7s5s 7s6s 7s7c 7s7d 8c6c 8c7c 8d6d 8d7d 8h6h 8h8c 8h8d 8s6s 8s7s 8s8h 9c7c 9c8c 9d7d 9d8d 9h8h 9h9c 9h9d 9s7s 9s8s 9s9h Ac7c AcJc AcJd AcJh AcJs AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTs Ad7d AdJc AdJd AdJh AdJs AdKc AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTs Ah2h Ah3h Ah4h Ah5h Ah6h Ah8h Ah9h AhJc AhJd AhJh AhJs AhKc AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTs As7s AsJc AsJd AsJh AsJs AsKc AsKh AsQc AsQd AsQh AsQs AsTc AsTd AsTs Jc8c Jc9c JcTc JcTd JcTs Jd8d Jd9d JdJc JdTc JdTd JdTs Jh8h Jh9h JhJc JhJd JhTc JhTs Js8s Js9s JsJc JsJd JsJh JsTc JsTd JsTs Kc5c Kc6c Kc7c Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc KcTd KcTs Kh5h Kh6h Kh8h Kh9h KhJc KhJd KhJh KhJs KhKc KhQc KhQd KhQh KhQs KhTc KhTd KhTs Ks5s Ks6s Ks7s Ks8s Ks9s KsJc KsJd KsJh KsJs KsKh KsQc KsQd KsQh KsQs KsTc KsTd KsTs QcJc QcJd QcJh QcJs QcTc QcTd QcTs Qd9d QdJc QdJd QdJh QdJs QdQc QdTc QdTd QdTs Qh8h Qh9h QhJc QhJd QhJs QhQc QhQd QhTc QhTd QhTs QsJc QsJd QsJh QsJs QsQc QsQd QsQh QsTc QsTd QsTs Tc7c Tc8c Tc9c Td8d Td9d Ts7s Ts8s Ts9s TsTc')
        },
        {
          actions: [
            'fold'
          ],
          combos: expand('2d2c 2h2c 2s2c 2s2d 2s2h 3d3c 3h3c 3s3c 3s3d 3s3h 4c3c 4d3d 4d4c 4h4c 4s3s 4s4c 4s4d 4s4h 5c3c 5c4c 5d3d 5d4d 5d5c 5h5c 5s3s 5s4s 5s5c 5s5d 5s5h 6c4c 6c5c 6d4d 6d5d 6d6c 6h6c 6h6d 6s4s 6s5s 6s6c 6s6d 6s6h 8d8c 8s8c 8s8d 9d9c 9s9c 9s9d Ac2c Ac3c Ac4c Ac5c Ac6c Ac8c Ac9c Ad2d Ad3d Ad4d Ad5d Ad6d Ad8d Ad9d As2s As3s As4s As5s As6s As8s As9s Qc8c Qc9c Qd8d Qs8s Qs9s')
        },
        {
          actions: [
            'raise_83%'
          ],
          combos: expand('3h3d 6h6d 7c6c 7d5d 7d6d 7d7c 7s6s 7s7c 7s7d 8c6c 8c7c 8d6d 8s6s 8s7s 9c7c 9d7d 9h8h 9s7s AcJh AcQh AdJh AdKc AdKs AdQh Ah6h Ah8h Ah9h AhJc AhJd AhJs AhQc AhQs AsJh AsQh Jd8d Jh9h JhTc JhTd JhTs KcTc KcTd KcTs Kh5h Kh8h KhJc KhJh KhJs KhQh KhTd KsKc KsTc KsTd KsTs Qc9c Qd9d Qh8h QhJd QhJh QhTd Qs9s Tc7c Tc8c Tc9c Td7d TdTc Ts7s Ts8s Ts9s TsTc TsTd')
        }
      ]
    },
    {
      position: 'BTN',
      stackBb: 100,
      villainPosition: 'UTG',
      board: [
        'Kh',
        'Jd',
        '4d'
      ],
      heroStackSize: 97.7,
      villainStackSize: 92.9,
      actionLine: 'preflop: UTG raises 2.3bb, BTN calls 2.3bb; flop: UTG bets 4.8bb',
      dealCombos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4c3c 4h3h 4h4c 4s3s 4s4c 4s4h 5c3c 5c4c 5d3d 5d5c 5h3h 5h4h 5h5c 5h5d 5s3s 5s4s 5s5c 5s5d 5s5h 6c4c 6c5c 6d5d 6d6c 6h4h 6h5h 6h6c 6h6d 6s4s 6s5s 6s6c 6s6d 6s6h 7c5c 7c6c 7d5d 7d6d 7d7c 7h5h 7h6h 7h7c 7h7d 7s5s 7s6s 7s7c 7s7d 7s7h 8c6c 8c7c 8d6d 8d7d 8d8c 8h6h 8h7h 8h8c 8h8d 8s6s 8s7s 8s8c 8s8d 8s8h 9c7c 9c8c 9d7d 9d8d 9d9c 9h7h 9h8h 9h9c 9h9d 9s7s 9s8s 9s9c 9s9d 9s9h Ac2c Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJh AcJs AcKd AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad2d Ad3d Ad5d Ad6d Ad7d Ad8d Ad9d AdJc AdJh AdJs AdKc AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah2h Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhJc AhJh AhJs AhKc AhKd AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs As2s As3s As4s As5s As6s As7s As8s As9s AsJc AsJh AsJs AsKc AsKd AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc8c Jc9c JcTc JcTd JcTh JcTs Jh8h Jh9h JhJc JhTc JhTd JhTh JhTs Js8s Js9s JsJc JsJh JsTc JsTd JsTh JsTs Kc5c Kc6c Kc7c Kc8c Kc9c KcJc KcJh KcJs KcQc KcQd KcQh KcQs KcTc KcTd KcTh KcTs Kd5d Kd6d Kd7d Kd8d Kd9d KdJc KdJh KdJs KdKc KdQc KdQd KdQh KdQs KdTc KdTd KdTh KdTs Ks5s Ks6s Ks7s Ks8s Ks9s KsJc KsJh KsJs KsKc KsKd KsQc KsQd KsQh KsQs KsTc KsTd KsTh KsTs Qc8c Qc9c QcJc QcJh QcJs QcTc QcTd QcTh QcTs Qd8d Qd9d QdJc QdJh QdJs QdQc QdTc QdTd QdTh QdTs Qh8h Qh9h QhJc QhJh QhJs QhQc QhQd QhTc QhTd QhTh QhTs Qs8s Qs9s QsJc QsJh QsJs QsQc QsQd QsQh QsTc QsTd QsTh QsTs Tc7c Tc8c Tc9c Td7d Td8d Td9d TdTc Th7h Th8h Th9h ThTc ThTd Ts7s Ts8s Ts9s TsTc TsTd TsTh'),
      buckets: [
        {
          actions: [
            'call'
          ],
          combos: expand('4c3c 4h3h 4h4c 4s3s 4s4c 4s4h 5c4c 5d3d 5h4h 5s4s 6c4c 6d5d 6d6c 6h4h 6h6d 6s4s 6s6d 7d5d 7d6d 7d7c 7h7d 7s7d 8d6d 8d7d 8d8c 8h8d 8s8d 9d7d 9d8d 9d9c 9h9d 9s9d AcJc AcJh AcJs AcKd AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad2d Ad3d Ad5d Ad6d Ad7d Ad8d Ad9d AdJc AdJh AdJs AdKc AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah4h AhJc AhJh AhJs AhKc AhKd AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs AsJc AsJh AsJs AsKc AsKd AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc8c Jc9c JcTc JcTd JcTh JcTs Jh8h Jh9h JhJc JhTc JhTd JhTh JhTs Js8s Js9s JsJc JsJh JsTc JsTd JsTh JsTs Kc5c Kc6c Kc7c Kc8c Kc9c KcJc KcJh KcJs KcQc KcQd KcQh KcQs KcTc KcTd KcTh KcTs Kd5d Kd6d Kd7d Kd8d Kd9d KdJc KdJh KdJs KdKc KdQc KdQd KdQh KdQs KdTc KdTd KdTh KdTs Ks5s Ks6s Ks7s Ks8s Ks9s KsJc KsJh KsJs KsKc KsKd KsQc KsQd KsQh KsQs KsTc KsTd KsTh KsTs QcJc QcJh QcJs QcTc QcTd QcTh QcTs Qd8d Qd9d QdJc QdJh QdJs QdQc QdTc QdTh QdTs Qh9h QhJc QhJh QhJs QhQc QhQd QhTc QhTd QhTh QhTs QsJc QsJh QsJs QsQc QsQd QsQh QsTc QsTd QsTh QsTs Td7d Td8d Td9d TdTc Th9h ThTd TsTd')
        },
        {
          actions: [
            'fold'
          ],
          combos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 5c3c 5d5c 5h3h 5h5c 5h5d 5s3s 5s5c 5s5d 5s5h 6c5c 6d6c 6h5h 6h6c 6h6d 6s5s 6s6c 6s6d 6s6h 7c5c 7c6c 7d7c 7h5h 7h6h 7h7c 7s5s 7s6s 7s7c 7s7d 7s7h 8c6c 8c7c 8h6h 8h7h 8h8c 8s6s 8s7s 8s8c 8s8h 9c7c 9c8c 9d9c 9h7h 9h8h 9h9c 9h9d 9s7s 9s8s 9s9c 9s9d 9s9h Ac2c Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcTc AcTh AcTs Ah2h Ah3h Ah5h Ah6h Ah7h Ah8h Ah9h AhTc AhTs As2s As3s As4s As5s As6s As7s As8s As9s AsTc AsTh AsTs Jc9c JcTc JcTh JcTs Js9s JsTc JsTh JsTs Qc8c Qc9c QcJc QcJs Qh8h Qh9h QhJc QhJs QhQc Qs8s Qs9s QsJc QsJs QsQc QsQh Tc7c Tc8c Tc9c TdTc Th7h Th8h ThTc ThTd Ts7s Ts8s Ts9s TsTc TsTd TsTh')
        },
        {
          actions: [
            'raise_55%'
          ],
          combos: expand('4c3c 4h3h 4h4c 4s3s 4s4c 4s4h 5c4c 5s4s 6c4c 6h4h 6s4s 9d7d 9d8d Ac4c AcKs AcQc AcQd AcQh Ad6d Ad7d Ad8d AdQh AdTc AdTh AdTs AhJc AhJs AhQc AhQd AhQs As4s AsKc AsQd AsQh AsQs Jc8c Jc9c JcTd Jh8h JhJc JhTd Js8s Js9s JsJc JsJh JsTd Kc6c KcJc KcJh KcJs KcQc KcQd Kd5d Kd9d KdJc KdJs KdQd KdTd Ks6s KsJc KsJh KsJs KsQd KsQs Qd8d Qd9d QdJh QdTd QhTd Td7d Td8d Th9h')
        }
      ]
    },
    {
      position: 'BTN',
      stackBb: 100,
      villainPosition: 'UTG',
      board: [
        'Qd',
        'Qc',
        'Js'
      ],
      heroStackSize: 97.7,
      villainStackSize: 94.9,
      actionLine: 'preflop: UTG raises 2.3bb, BTN calls 2.3bb; flop: UTG bets 1.8bb',
      dealCombos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4c3c 4d3d 4d4c 4h3h 4h4c 4h4d 4s3s 4s4c 4s4d 4s4h 5c3c 5c4c 5d3d 5d4d 5d5c 5h3h 5h4h 5h5c 5h5d 5s3s 5s4s 5s5c 5s5d 5s5h 6c4c 6c5c 6d4d 6d5d 6d6c 6h4h 6h5h 6h6c 6h6d 6s4s 6s5s 6s6c 6s6d 6s6h 7c5c 7c6c 7d5d 7d6d 7d7c 7h5h 7h6h 7h7c 7h7d 7s5s 7s6s 7s7c 7s7d 7s7h 8c6c 8c7c 8d6d 8d7d 8d8c 8h6h 8h7h 8h8c 8h8d 8s6s 8s7s 8s8c 8s8d 8s8h 9c7c 9c8c 9d7d 9d8d 9d9c 9h7h 9h8h 9h9c 9h9d 9s7s 9s8s 9s9c 9s9d 9s9h Ac2c Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcKd AcKh AcKs AcQh AcQs AcTc AcTd AcTh AcTs Ad2d Ad3d Ad4d Ad5d Ad6d Ad7d Ad8d Ad9d AdJc AdJd AdJh AdKc AdKh AdKs AdQh AdQs AdTc AdTd AdTh AdTs Ah2h Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhJc AhJd AhJh AhKc AhKd AhKs AhQh AhQs AhTc AhTd AhTh AhTs As2s As3s As4s As5s As6s As7s As8s As9s AsJc AsJd AsJh AsKc AsKd AsKh AsQh AsQs AsTc AsTd AsTh AsTs Jc8c Jc9c JcTc JcTd JcTh JcTs Jd8d Jd9d JdJc JdTc JdTd JdTh JdTs Jh8h Jh9h JhJc JhJd JhTc JhTd JhTh JhTs Kc5c Kc6c Kc7c Kc8c Kc9c KcJc KcJd KcJh KcQh KcQs KcTc KcTd KcTh KcTs Kd5d Kd6d Kd7d Kd8d Kd9d KdJc KdJd KdJh KdKc KdQh KdQs KdTc KdTd KdTh KdTs Kh5h Kh6h Kh7h Kh8h Kh9h KhJc KhJd KhJh KhKc KhKd KhQh KhQs KhTc KhTd KhTh KhTs Ks5s Ks6s Ks7s Ks8s Ks9s KsJc KsJd KsJh KsKc KsKd KsKh KsQh KsQs KsTc KsTd KsTh KsTs Qh8h Qh9h QhJc QhJd QhJh QhTc QhTd QhTh QhTs Qs8s Qs9s QsJc QsJd QsJh QsQh QsTc QsTd QsTh QsTs Tc7c Tc8c Tc9c Td7d Td8d Td9d TdTc Th7h Th8h Th9h ThTc ThTd Ts7s Ts8s Ts9s TsTc TsTd TsTh'),
      buckets: [
        {
          actions: [
            'call'
          ],
          combos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6d6c 6h6c 6h6d 6s6c 6s6d 6s6h 7d7c 7h7c 7h7d 7s7c 7s7d 7s7h 8d8c 8h8c 8h8d 8s8c 8s8d 8s8h 9c8c 9d8d 9d9c 9h8h 9h9c 9h9d 9s8s 9s9c 9s9d 9s9h Ac3c Ac6c Ac7c Ac8c Ac9c AcJd AcJh AcKd AcKh AcKs AcQh AcQs AcTd AcTh AcTs Ad3d Ad6d Ad7d Ad8d Ad9d AdJc AdJh AdKc AdKh AdKs AdQh AdQs AdTc AdTh AdTs Ah8h Ah9h AhJc AhJd AhJh AhQh AhQs AhTc AhTd AhTh AhTs As3s As6s As7s As8s As9s AsJc AsJd AsJh AsKc AsKd AsKh AsQh AsTc AsTd AsTh Jc8c Jc9c JcTc JcTd JcTh JcTs Jd8d Jd9d JdTc JdTd JdTh JdTs Jh8h Jh9h JhTc JhTd JhTh JhTs Kc6c Kc7c Kc8c Kc9c KcJc KcJd KcJh KcQh KcQs KcTc KcTd KcTh KcTs Kd6d Kd7d Kd8d Kd9d KdJc KdJd KdJh KdKc KdQh KdQs KdTc KdTd KdTh KdTs Kh9h KhJc KhJd KhKc KhKd KhQh KhQs Ks5s Ks6s Ks7s Ks8s Ks9s KsJc KsJd KsJh KsKc KsKd KsKh KsQh KsQs KsTc KsTd KsTh KsTs Qh9h QhJc QhJd QhJh QhTc QhTd QhTh QhTs Qs9s QsJc QsJd QsQh QsTc QsTd QsTh QsTs Tc8c Tc9c Td8d Td9d TdTc Th8h Th9h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh')
        },
        {
          actions: [
            'fold'
          ],
          combos: expand('4c3c 4d3d 4h3h 4s3s 5c3c 5c4c 5d3d 5d4d 5h3h 5h4h 5s3s 5s4s 6c4c 6c5c 6d4d 6d5d 6h4h 6h5h 6s4s 6s5s 7c5c 7c6c 7d5d 7d6d 7h5h 7h6h 7s5s 7s6s 8c6c 8c7c 8d6d 8d7d 8h6h 8h7h 8s6s 8s7s 9c7c 9d7d 9h7h 9s7s Ac2c Ac3c Ac4c Ac5c Ac6c Ad2d Ad3d Ad4d Ad5d Ad6d Ah2h Ah3h Ah4h Ah5h Ah6h Ah7h As2s As3s As4s As5s As6s Kc5c Kc6c Kc8c Kd5d Kd6d Kd8d Kh5h Kh6h Kh7h Kh8h Ks5s Tc7c Td7d Th7h Ts7s')
        },
        {
          actions: [
            'raise_33%'
          ],
          combos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6h6c 6h6d 6s6h 7h7c 7h7d 7s7h 8h8c 8h8d 8s8h 9c8c 9d8d 9d9c 9h9c 9h9d 9s8s 9s9c 9s9d 9s9h Ac6c Ac7c Ac8c Ac9c AcJc AcJh AcKh AcQh AcQs AcTc AcTd AcTh AcTs Ad6d Ad7d Ad8d Ad9d AdJd AdJh AdKh AdQh AdQs AdTc AdTd AdTh AdTs AhJc AhJd AhJh AhKc AhKd AhKs AhQh AhQs AhTc AhTd AhTs As6s As7s As8s As9s AsJh AsKh AsQh AsQs AsTc AsTd AsTh AsTs Jc8c Jc9c JcTc JcTd JcTh JcTs Jd8d Jd9d JdJc JdTc JdTd JdTh JdTs Jh9h JhJc JhJd JhTc JhTd JhTh JhTs Kc6c Kc7c Kc8c Kc9c KcJc KcQh KcQs KcTc Kd6d Kd7d Kd8d Kd9d KdJd KdQh KdQs KdTd Kh9h KhJc KhJd KhJh KhQs KhTc KhTd KhTh KhTs Ks6s Ks7s Ks8s Ks9s KsQh KsTs Qh8h Qh9h Qs8s Qs9s QsJc QsJd QsJh QsQh QsTc QsTd QsTh QsTs Tc8c Tc9c Td8d Td9d ThTc ThTd Ts8s Ts9s TsTh')
        }
      ]
    },
    {
      position: 'BTN',
      stackBb: 100,
      villainPosition: 'UTG',
      board: [
        'Qh',
        '8h',
        '3h'
      ],
      heroStackSize: 97.7,
      villainStackSize: 95.9,
      actionLine: 'preflop: UTG raises 2.3bb, BTN calls 2.3bb; flop: UTG bets 1.8bb',
      dealCombos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3s3c 3s3d 4c3c 4d3d 4d4c 4h4c 4h4d 4s3s 4s4c 4s4d 4s4h 5c3c 5c4c 5d3d 5d4d 5d5c 5h4h 5h5c 5h5d 5s3s 5s4s 5s5c 5s5d 5s5h 6c4c 6c5c 6d4d 6d5d 6d6c 6h4h 6h5h 6h6c 6h6d 6s4s 6s5s 6s6c 6s6d 6s6h 7c5c 7c6c 7d5d 7d6d 7d7c 7h5h 7h6h 7h7c 7h7d 7s5s 7s6s 7s7c 7s7d 7s7h 8c6c 8c7c 8d6d 8d7d 8d8c 8s6s 8s7s 8s8c 8s8d 9c7c 9c8c 9d7d 9d8d 9d9c 9h7h 9h9c 9h9d 9s7s 9s8s 9s9c 9s9d 9s9h Ac2c Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcKd AcKh AcKs AcQc AcQd AcQs AcTc AcTd AcTh AcTs Ad2d Ad3d Ad4d Ad5d Ad6d Ad7d Ad8d Ad9d AdJc AdJd AdJh AdJs AdKc AdKh AdKs AdQc AdQd AdQs AdTc AdTd AdTh AdTs Ah2h Ah4h Ah5h Ah6h Ah7h Ah9h AhJc AhJd AhJh AhJs AhKc AhKd AhKs AhQc AhQd AhQs AhTc AhTd AhTh AhTs As2s As3s As4s As5s As6s As7s As8s As9s AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsQc AsQd AsQs AsTc AsTd AsTh AsTs Jc8c Jc9c JcTc JcTd JcTh JcTs Jd8d Jd9d JdJc JdTc JdTd JdTh JdTs Jh9h JhJc JhJd JhTc JhTd JhTh JhTs Js8s Js9s JsJc JsJd JsJh JsTc JsTd JsTh JsTs Kc5c Kc6c Kc7c Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQs KcTc KcTd KcTh KcTs Kd5d Kd6d Kd7d Kd8d Kd9d KdJc KdJd KdJh KdJs KdQc KdQd KdQs KdTc KdTd KdTh KdTs Kh5h Kh6h Kh7h Kh9h KhJc KhJd KhJh KhJs KhQc KhQd KhQs KhTc KhTd KhTh KhTs Ks5s Ks6s Ks7s Ks8s Ks9s KsJc KsJd KsJh KsJs KsQc KsQd KsQs KsTc KsTd KsTh KsTs Qc8c Qc9c QcJc QcJd QcJh QcJs QcTc QcTd QcTh QcTs Qd8d Qd9d QdJc QdJd QdJh QdJs QdQc QdTc QdTd QdTh QdTs Qs8s Qs9s QsJc QsJd QsJh QsJs QsQc QsQd QsTc QsTd QsTh QsTs Tc7c Tc8c Tc9c Td7d Td8d Td9d TdTc Th7h Th9h ThTc ThTd Ts7s Ts8s Ts9s TsTc TsTd TsTh'),
      buckets: [
        {
          actions: [
            'call'
          ],
          combos: expand('2h2c 2h2d 2s2h 3d3c 3s3c 3s3d 4c3c 4d3d 4h4c 4h4d 4s3s 4s4h 5h4h 5h5c 5h5d 5s5h 6h4h 6h5h 6h6c 6h6d 6s6h 7h5h 7h6h 7h7c 7h7d 7s7h 8c6c 8c7c 8d6d 8d7d 8d8c 8s6s 8s7s 8s8c 8s8d 9c8c 9d8d 9d9c 9h7h 9h9c 9h9d 9s8s 9s9c 9s9d 9s9h Ac8c AcJh AcKh AcQc AcQd AcQs AcTh Ad8d AdJh AdKh AdQc AdQd AdQs AdTh Ah2h Ah5h Ah6h Ah7h Ah9h AhJc AhJd AhJh AhJs AhKc AhKd AhKs AhQc AhQd AhQs AhTh As8s AsJh AsKh AsQc AsQd AsQs AsTh Jc8c JcTh Jd8d JdJc JdTh Jh9h JhJc JhJd JhTc JhTd JhTh JhTs Js8s JsJc JsJd JsJh JsTh Kc8c KcJh KcQc KcQd KcQs KcTh Kd8d KdJh KdQc KdQd KdQs KdTh Kh5h Kh6h Kh7h Kh9h KhJc KhJd KhJh KhJs KhQc KhQd KhQs KhTc KhTd KhTs Ks8s KsJh KsQc KsQd KsQs KsTh Qc8c Qc9c QcJc QcJd QcJh QcJs QcTc QcTd QcTh QcTs Qd8d Qd9d QdJc QdJd QdJh QdJs QdQc QdTc QdTd QdTh QdTs Qs8s Qs9s QsJc QsJd QsJh QsJs QsQc QsQd QsTc QsTd QsTh QsTs Tc8c Td8d TdTc Th7h Th9h ThTc ThTd Ts8s TsTc TsTd TsTh')
        },
        {
          actions: [
            'fold'
          ],
          combos: expand('2d2c 2s2c 2s2d 4d4c 4s4c 4s4d 5c3c 5c4c 5d3d 5d4d 5d5c 5s3s 5s4s 5s5c 5s5d 6c4c 6c5c 6d4d 6d5d 6d6c 6s4s 6s5s 6s6c 6s6d 7c5c 7c6c 7d5d 7d6d 7d7c 7s5s 7s6s 7s7c 7s7d 9c7c 9d7d 9d9c 9s7s 9s9c 9s9d Ac2c Ac3c Ac4c Ac5c Ac6c Ac7c Ac9c AcJc AcJd AcJs AcKd AcKs AcTc AcTd AcTs Ad2d Ad3d Ad4d Ad5d Ad6d Ad7d Ad9d AdJc AdJd AdJs AdKc AdKs AdTc AdTd AdTs As2s As3s As4s As5s As6s As7s As9s AsJc AsJd AsJs AsKc AsKd AsTc AsTd AsTs Jc9c JcTc JcTd JcTs Jd9d JdTc JdTd JdTs Js9s JsTc JsTd JsTs Kc5c Kc6c Kc7c Kc9c KcJc KcJd KcJs KcTc KcTd KcTs Kd5d Kd6d Kd7d Kd9d KdJc KdJd KdJs KdTc KdTd KdTs Ks5s Ks6s Ks7s Ks9s KsJc KsJd KsJs KsTc KsTd KsTs Tc7c Tc9c Td7d Td9d Ts7s Ts9s')
        },
        {
          actions: [
            'raise_55%'
          ],
          combos: expand('3d3c 3s3c 3s3d 5c3c 5d3d 5s3s 6h5h 8c6c 8c7c 8d6d 8d7d 8d8c 8s6s 8s7s 8s8c 8s8d 9h7h Ah2h Ah4h Ah5h Ah6h Ah7h Ah9h AhTc AhTd AhTh AhTs JcTh JdTh JhTc JhTd JhTh JhTs JsTh KcJh KcTh KdJh KdTh KhJh KhTc KhTd KhTh KhTs KsJh KsTh Qc8c Qd8d Qs8s Th7h')
        }
      ]
    },
    {
      position: 'BTN',
      stackBb: 100,
      villainPosition: 'UTG',
      board: [
        'Tc',
        '7d',
        '6s'
      ],
      heroStackSize: 97.7,
      villainStackSize: 95.9,
      actionLine: 'preflop: UTG raises 2.3bb, BTN calls 2.3bb; flop: UTG bets 1.8bb',
      dealCombos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4c3c 4d3d 4d4c 4h3h 4h4c 4h4d 4s3s 4s4c 4s4d 4s4h 5c3c 5c4c 5d3d 5d4d 5d5c 5h3h 5h4h 5h5c 5h5d 5s3s 5s4s 5s5c 5s5d 5s5h 6c4c 6c5c 6d4d 6d5d 6d6c 6h4h 6h5h 6h6c 6h6d 7c5c 7c6c 7h5h 7h6h 7h7c 7s5s 7s7c 7s7h 8c6c 8c7c 8d6d 8d8c 8h6h 8h7h 8h8c 8h8d 8s7s 8s8c 8s8d 8s8h 9c7c 9c8c 9d8d 9d9c 9h7h 9h8h 9h9c 9h9d 9s7s 9s8s 9s9c 9s9d 9s9h Ac2c Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTd AcTh AcTs Ad2d Ad3d Ad4d Ad5d Ad6d Ad8d Ad9d AdJc AdJd AdJh AdJs AdKc AdKh AdKs AdQc AdQd AdQh AdQs AdTd AdTh AdTs Ah2h Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhJc AhJd AhJh AhJs AhKc AhKd AhKs AhQc AhQd AhQh AhQs AhTd AhTh AhTs As2s As3s As4s As5s As7s As8s As9s AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsQc AsQd AsQh AsQs AsTd AsTh AsTs Jc8c Jc9c JcTd JcTh JcTs Jd8d Jd9d JdJc JdTd JdTh JdTs Jh8h Jh9h JhJc JhJd JhTd JhTh JhTs Js8s Js9s JsJc JsJd JsJh JsTd JsTh JsTs Kc5c Kc6c Kc7c Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTd KcTh KcTs Kd5d Kd6d Kd8d Kd9d KdJc KdJd KdJh KdJs KdKc KdQc KdQd KdQh KdQs KdTd KdTh KdTs Kh5h Kh6h Kh7h Kh8h Kh9h KhJc KhJd KhJh KhJs KhKc KhKd KhQc KhQd KhQh KhQs KhTd KhTh KhTs Ks5s Ks7s Ks8s Ks9s KsJc KsJd KsJh KsJs KsKc KsKd KsKh KsQc KsQd KsQh KsQs KsTd KsTh KsTs Qc8c Qc9c QcJc QcJd QcJh QcJs QcTd QcTh QcTs Qd8d Qd9d QdJc QdJd QdJh QdJs QdQc QdTd QdTh QdTs Qh8h Qh9h QhJc QhJd QhJh QhJs QhQc QhQd QhTd QhTh QhTs Qs8s Qs9s QsJc QsJd QsJh QsJs QsQc QsQd QsQh QsTd QsTh QsTs Td8d Td9d Th7h Th8h Th9h ThTd Ts7s Ts8s Ts9s TsTd TsTh'),
      buckets: [
        {
          actions: [
            'call'
          ],
          combos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4c3c 4d3d 4d4c 4h3h 4h4c 4h4d 4s3s 4s4c 4s4d 4s4h 5c3c 5c4c 5d3d 5d4d 5d5c 5h3h 5h4h 5h5c 5h5d 5s3s 5s4s 5s5c 5s5d 5s5h 6c4c 6c5c 6d4d 6d5d 6d6c 6h4h 6h5h 6h6c 6h6d 7c5c 7h5h 7h6h 7h7c 7s5s 7s7c 7s7h 8c6c 8c7c 8d6d 8d8c 8h6h 8h7h 8h8c 8h8d 8s7s 8s8c 8s8d 8s8h 9c7c 9c8c 9d8d 9d9c 9h7h 9h8h 9h9c 9h9d 9s7s 9s8s 9s9c 9s9d 9s9h Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTd AcTh AcTs Ad4d Ad5d Ad6d Ad8d Ad9d AdJc AdJd AdJh AdJs AdKc AdKh AdKs AdQc AdQd AdQh AdQs AdTd AdTh AdTs Ah6h Ah7h Ah8h Ah9h AhJc AhJd AhJh AhJs AhKc AhKd AhKs AhQc AhQd AhQh AhQs AhTd AhTs As4s As5s As7s As8s As9s AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsQc AsQd AsQh AsQs AsTd AsTh AsTs Jc8c Jc9c JcTd JcTh JcTs Jd8d Jd9d JdJc JdTd JdTh JdTs Jh8h Jh9h JhJc JhJd JhTd JhTh JhTs Js8s Js9s JsJc JsJd JsJh JsTd JsTh JsTs Kc6c Kc7c Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTd KcTh KcTs Kd6d Kd8d Kd9d KdJc KdJd KdJh KdJs KdKc KdQc KdQd KdQh KdQs KdTd KdTh KdTs Kh6h Kh7h Kh8h Kh9h KhJc KhJd KhJh KhJs KhKc KhKd KhQc KhQd KhQh KhQs KhTd KhTh KhTs Ks7s Ks8s Ks9s KsJc KsJd KsJh KsJs KsKc KsKd KsKh KsQc KsQd KsQh KsQs KsTd KsTh KsTs Qc9c QcJc QcJd QcJh QcJs QcTd QcTh QcTs Qd8d Qd9d QdJc QdJd QdJh QdJs QdQc QdTd QdTh QdTs Qh8h Qh9h QhJc QhJd QhJh QhJs QhQc QhQd QhTd QhTh QhTs Qs8s Qs9s QsJc QsJd QsJh QsJs QsQc QsQd QsQh QsTd QsTh QsTs Td8d Td9d Th7h Th8h Th9h ThTd Ts7s Ts8s Ts9s TsTd TsTh')
        },
        {
          actions: [
            'fold'
          ],
          combos: expand('Ac2c Ac3c Ac4c Ad2d Ad3d Ad4d Ah2h Ah3h Ah4h Ah5h As2s As3s As4s Kc5c Kd5d Kh5h Ks5s')
        },
        {
          actions: [
            'raise_83%'
          ],
          combos: expand('4c3c 4s3s 5c3c 5c4c 5d3d 5d4d 5s3s 5s4s 6d4d 6d6c 7c6c 7h6h 7h7c 7s7c 7s7h 9c8c 9d8d 9h8h 9s8s Ac4c Ac8c Ac9c AcJc AcJh Ad8d AdJd AdJh AdQd AdTh Ah8h Ah9h AhQh AhTh As4s AsJh AsJs AsQh AsQs Jc8c Jc9c Jd8d JdTd JhJc JhJd JhTh Js8s Js9s JsJh JsTs Kc8c Kc9c KcJc KcQc Kd9d KdJd KdQd Kh8h Kh9h KhJh KhTh Ks9s KsJs KsQs Qc8c Qc9c QcJc Qd8d Qd9d QdJd Qh9h QhJh Qs8s Qs9s QsJs Td8d Td9d Th8h ThTd Ts7s Ts8s Ts9s TsTh')
        }
      ]
    }
  ]
};

export default pack;
