// Generated by scripts/import-ct-curriculum.ts. Do not edit by hand.
import type { RangePack } from '../types';

const expand = (value: string): string[] => value.split(' ');

const pack: RangePack = {
  slug: 'in-position-postflop-response-btn-utgplus1-flop-baseline',
  title: 'In-position postflop response: BTN vs UTG+1 - Flop (40bb)',
  description: 'Board-aware in-position response practice after the preflop raiser acts.',
  scenario: 'IP_POSTFLOP',
  street: 'flop',
  tier: 'advanced',
  methodology: 'gto_cev',
  source: {
    kind: 'brand_neutralized_snapshot_config',
    capturedAt: '2026-07-18',
    path: 'research/ct-trainer-2026-07-18/',
    sha256: '03e1dbb631a9a96d4450b63c996736674c4e0af3c2ccc8cd393066180bd1b0ec'
  },
  cells: [
    {
      position: 'BTN',
      stackBb: 40,
      villainPosition: 'UTG+1',
      board: [
        '6h',
        '4d',
        '2c'
      ],
      heroStackSize: 37.7,
      villainStackSize: 37.7,
      actionLine: 'preflop: UTG+1 raises 2.3bb, BTN calls 2.3bb; flop: UTG+1 checks, BTN checks; turn: UTG+1 checks',
      dealCombos: expand('2h2d 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4h4c 4s4c 4s4h 5c4c 5d5c 5h4h 5h5c 5h5d 5s4s 5s5c 5s5d 5s5h 6c5c 6d5d 6d6c 6s5s 6s6c 6s6d 7c6c 7d6d 7d7c 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8c7c 8d7d 8d8c 8h7h 8h8c 8h8d 8s7s 8s8c 8s8d 8s8h 9c7c 9c8c 9d7d 9d8d 9d9c 9h7h 9h8h 9h9c 9h9d 9s7s 9s8s 9s9c 9s9d 9s9h Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad2d Ad3d Ad5d Ad6d Ad7d Ad8d Ad9d AdJc AdJd AdJh AdJs AdKc AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah2h Ah3h Ah4h Ah5h Ah7h Ah8h Ah9h AhJc AhJd AhJh AhJs AhKc AhKd AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs As2s As3s As4s As5s As6s As7s As8s As9s AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc8c Jc9c JcTc Jd8d Jd9d JdJc JdTd Jh8h Jh9h JhJc JhJd JhTh Js8s Js9s JsJc JsJd JsJh JsTs Kc6c Kc7c Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc Kd6d Kd7d Kd8d Kd9d KdJc KdJd KdJh KdJs KdQc KdQd KdQh KdQs KdTd Kh7h Kh8h Kh9h KhJc KhJd KhJh KhJs KhQc KhQd KhQh KhQs KhTh Ks6s Ks7s Ks8s Ks9s KsJc KsJd KsJh KsJs KsQc KsQd KsQh KsQs KsTs Qc8c Qc9c QcJc QcJd QcJh QcJs QcTc Qd8d Qd9d QdJc QdJd QdJh QdJs QdQc QdTd Qh8h Qh9h QhJc QhJd QhJh QhJs QhQc QhQd QhTh Qs8s Qs9s QsJc QsJd QsJh QsJs QsQc QsQd QsQh QsTs Tc8c Tc9c Td8d Td9d TdTc Th8h Th9h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh'),
      buckets: [
        {
          actions: [
            'bet_20pct'
          ],
          combos: expand('2h2d 2s2d 2s2h 3h3c 3h3d 3s3c 3s3d 3s3h 4h4c 4s4c 4s4h 5c4c 5d5c 5h4h 5h5d 5s4s 5s5c 5s5d 6d5d 6d6c 6s5s 6s6c 6s6d 7c6c 7d6d 7d7c 7h7c 7h7d 7s7c 7s7d 7s7h 8c7c 8d7d 8h7h 9d9c 9h9c 9h9d 9s7s Ac3c AcJc AcQc AcQd AcQh Ad3d AdJd AdQc AdQd AdQh Ah3h AhJh AhQc AhQd AhQh As3s As7s AsJs AsQs Jc9c JcTc Jd9d JdTd Jh9h JhTh Kc6c Kc7c Kc8c KcQc Kd6d Kd7d Kd8d KdQd Kh7h Kh8h KhQh Ks6s Ks7s Ks8s KsQs QdQc QhQc QhQd Tc9c Td9d Th9h')
        },
        {
          actions: [
            'bet_33pct'
          ],
          combos: expand('2h2d 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4h4c 4s4c 4s4h 5c4c 5d5c 5h4h 5h5c 5h5d 5s4s 5s5c 5s5d 5s5h 6c5c 6d5d 6d6c 6s5s 6s6c 6s6d 7c6c 7d6d 7d7c 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8c7c 8d7d 8d8c 8h7h 8h8c 8h8d 8s7s 8s8c 8s8d 8s8h 9c7c 9c8c 9d7d 9d8d 9d9c 9h7h 9h8h 9h9c 9h9d 9s7s 9s8s 9s9c 9s9d 9s9h Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTd AcTh AcTs Ad2d Ad3d Ad5d Ad6d Ad7d Ad8d Ad9d AdJc AdJd AdJh AdJs AdKc AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTh AdTs Ah2h Ah3h Ah4h Ah5h Ah7h Ah8h Ah9h AhJc AhJd AhJh AhJs AhKc AhKd AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTs As2s As3s As4s As5s As6s As7s As8s As9s AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsQc AsQd AsQh AsQs AsTc AsTd AsTh Jc8c Jc9c JcTc Jd8d Jd9d JdJc JdTd Jh8h Jh9h JhJc JhJd JhTh Js8s Js9s JsJc JsJd JsJh JsTs Kc6c Kc7c Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQh KcTc Kd6d Kd7d Kd8d Kd9d KdJc KdJd KdJh KdJs KdQc KdQd KdQh KdTd Kh7h Kh8h Kh9h KhJc KhJd KhJh KhJs KhQc KhQd KhQh KhTh Ks6s Ks7s Ks8s Ks9s KsJc KsJd KsJh KsJs KsQc KsQd KsQh KsQs KsTs Qc8c Qc9c QcJc QcJd QcJh QcJs QcTc Qd8d Qd9d QdJc QdJd QdJh QdJs QdQc QdTd Qh8h Qh9h QhJc QhJd QhJh QhJs QhQc QhQd QhTh Qs8s Qs9s QsJc QsJd QsJh QsJs QsQc QsQd QsQh QsTs Tc8c Tc9c Td8d Td9d TdTc Th8h Th9h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh')
        },
        {
          actions: [
            'bet_55pct'
          ],
          combos: expand('2h2d 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4h4c 4s4c 4s4h 5d5c 5h4h 5h5c 5h5d 5s5c 5s5d 5s5h 6c5c 6d5d 6d6c 6s5s 6s6c 6s6d 7d7c 7s7c 7s7d 7s7h 8c7c 8d7d 8d8c 8h7h 8h8c 8h8d 8s7s 8s8c 8s8d 8s8h 9c7c 9c8c 9d7d 9d8d 9d9c 9h7h 9h8h 9h9c 9h9d 9s7s 9s8s 9s9c 9s9d 9s9h Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcQc AcQs AcTd AcTh Ad2d Ad3d Ad5d Ad6d Ad7d Ad8d Ad9d AdQd AdTc AdTh Ah2h Ah3h Ah4h Ah5h Ah7h Ah8h Ah9h AhQh AhTc AhTd As3s As4s As5s As6s As7s As8s As9s AsQs AsTc AsTd AsTh Jc8c Jc9c JcTc Jd8d Jd9d JdJc JdTd Jh8h Jh9h JhJc JhJd JhTh Js8s Js9s JsJc JsJd JsJh JsTs Kc6c Kc7c Kc8c KcJc KcJd KcJh KcJs KcQd KcQh KcTc Kd6d Kd7d Kd8d KdJc KdJd KdJh KdJs KdQc KdQh KdTd Kh7h Kh8h KhJc KhJd KhJh KhJs KhQc KhQd KhTh Ks6s Ks7s Ks8s KsQs KsTs Qc8c Qc9c QcJc QcJd QcJh QcJs QcTc Qd8d Qd9d QdJc QdJd QdJh QdJs QdQc QdTd Qh8h Qh9h QhJc QhJd QhJh QhJs QhTh Qs8s Qs9s QsJc QsJd QsJh QsJs QsQc QsQd QsQh QsTs Tc8c Tc9c Td8d Td9d TdTc Th8h Th9h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh')
        },
        {
          actions: [
            'check'
          ],
          combos: expand('2h2d 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4h4c 4s4c 4s4h 5c4c 5d5c 5h4h 5h5c 5h5d 5s4s 5s5c 5s5d 5s5h 6d6c 6s6c 6s6d 7c6c 7d6d 7d7c 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8c7c 8d7d 8d8c 8h7h 8h8c 8h8d 8s7s 8s8c 8s8d 8s8h 9c7c 9c8c 9d7d 9d8d 9d9c 9h7h 9h8h 9h9c 9h9d 9s7s 9s8s Ac3c Ac4c Ac5c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad2d Ad3d Ad5d Ad7d Ad8d Ad9d AdJc AdJd AdJh AdJs AdKc AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah2h Ah3h Ah4h Ah5h Ah7h Ah8h Ah9h AhJc AhJd AhJh AhJs AhKc AhKd AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs As2s As3s As4s As5s As7s As8s As9s AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc8c Jc9c JcTc Jd8d Jd9d JdJc JdTd Jh8h Jh9h JhJc JhJd JhTh Js8s Js9s JsTs Kc6c Kc7c Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc Kd6d Kd7d Kd8d Kd9d KdJc KdJd KdJh KdJs KdQc KdQd KdQh KdQs KdTd Kh7h Kh8h Kh9h KhJc KhJd KhJh KhJs KhQc KhQd KhQh KhQs KhTh Ks6s Ks7s Ks8s Ks9s KsJc KsJd KsJh KsJs KsQc KsQd KsQh KsQs KsTs Qc8c Qc9c QcJc QcJs QcTc Qd8d Qd9d QdJd QdJs QdQc QdTd Qh8h Qh9h QhJh QhJs QhQc QhQd QhTh Qs8s Qs9s QsJc QsJd QsJh QsJs QsTs Tc8c Tc9c Td8d Td9d TdTc Th8h Th9h ThTc ThTd Ts8s Ts9s')
        }
      ]
    },
    {
      position: 'BTN',
      stackBb: 40,
      villainPosition: 'UTG+1',
      board: [
        '6h',
        '5s',
        '3s'
      ],
      heroStackSize: 37.7,
      villainStackSize: 37.7,
      actionLine: 'preflop: UTG+1 raises 2.3bb, BTN calls 2.3bb; flop: UTG+1 checks, BTN checks; turn: UTG+1 checks',
      dealCombos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5c4c 5d4d 5d5c 5h4h 5h5c 5h5d 6c5c 6d5d 6d6c 6s6c 6s6d 7c6c 7d6d 7d7c 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8c7c 8d7d 8d8c 8h7h 8h8c 8h8d 8s7s 8s8c 8s8d 8s8h 9c7c 9c8c 9d7d 9d8d 9d9c 9h7h 9h8h 9h9c 9h9d 9s7s 9s8s 9s9c 9s9d 9s9h Ac2c Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad2d Ad3d Ad4d Ad5d Ad6d Ad7d Ad8d Ad9d AdJc AdJd AdJh AdJs AdKc AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah2h Ah3h Ah4h Ah5h Ah7h Ah8h Ah9h AhJc AhJd AhJh AhJs AhKc AhKd AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs As2s As4s As6s As7s As8s As9s AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc8c Jc9c JcTc Jd8d Jd9d JdJc JdTd Jh8h Jh9h JhJc JhJd JhTh Js8s Js9s JsJc JsJd JsJh JsTs Kc6c Kc7c Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc Kd6d Kd7d Kd8d Kd9d KdJc KdJd KdJh KdJs KdQc KdQd KdQh KdQs KdTd Kh7h Kh8h Kh9h KhJc KhJd KhJh KhJs KhQc KhQd KhQh KhQs KhTh Ks6s Ks7s Ks8s Ks9s KsJc KsJd KsJh KsJs KsQc KsQd KsQh KsQs KsTs Qc8c Qc9c QcJc QcJd QcJh QcJs QcTc Qd8d Qd9d QdJc QdJd QdJh QdJs QdQc QdTd Qh8h Qh9h QhJc QhJd QhJh QhJs QhQc QhQd QhTh Qs8s Qs9s QsJc QsJd QsJh QsJs QsQc QsQd QsQh QsTs Tc8c Tc9c Td8d Td9d TdTc Th8h Th9h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh'),
      buckets: [
        {
          actions: [
            'bet_20pct'
          ],
          combos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5c4c 5d4d 5d5c 5h4h 5h5c 5h5d 6c5c 6d5d 6d6c 6s6c 6s6d 7c6c 7d6d 7d7c 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8c7c 8d7d 8d8c 8h7h 8h8c 8h8d 8s7s 8s8c 8s8d 8s8h 9c7c 9c8c 9d7d 9d8d 9d9c 9h7h 9h8h 9h9c 9h9d 9s7s 9s8s 9s9c 9s9d 9s9h Ac2c Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTh AcTs Ad2d Ad3d Ad4d Ad5d Ad6d Ad7d Ad8d Ad9d AdJc AdJd AdJh AdJs AdKc AdKh AdKs AdQc AdQd AdQh AdQs AdTd AdTh AdTs Ah2h Ah3h Ah4h Ah5h Ah7h Ah8h Ah9h AhJc AhJd AhJs AhKc AhKd AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTs As2s As4s As6s As7s As8s As9s AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc8c Jc9c JcTc Jd8d Jd9d JdJc JdTd Jh8h Jh9h JhJc JhJd JhTh Js8s Js9s JsJc JsJd JsJh JsTs Kc6c Kc7c Kc8c Kc9c KcJc KcJd KcJh KcJs KcQh KcQs KcTc Kd6d Kd7d Kd8d Kd9d KdJc KdJd KdJh KdJs KdQh KdQs KdTd Kh7h Kh8h Kh9h KhJc KhJd KhJh KhJs KhQc KhQd KhQs KhTh Ks6s Ks7s Ks8s Ks9s KsJc KsJd KsJh KsJs KsQc KsQd KsQh KsQs KsTs Qc8c Qc9c QcJc QcJd QcJh QcJs QcTc Qd8d Qd9d QdJc QdJd QdJh QdJs QdQc QdTd Qh8h Qh9h QhJc QhJd QhJh QhJs QhQc QhQd QhTh Qs8s Qs9s QsJc QsJd QsJh QsJs QsQc QsQd QsQh QsTs Tc8c Tc9c Td8d Td9d TdTc Th8h Th9h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh')
        },
        {
          actions: [
            'bet_33pct'
          ],
          combos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5c4c 5d4d 5d5c 5h4h 5h5c 5h5d 6c5c 6d5d 6d6c 6s6c 6s6d 7c6c 7d6d 7d7c 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8c7c 8d7d 8d8c 8h7h 8h8c 8h8d 8s7s 8s8c 8s8d 8s8h 9c7c 9c8c 9d7d 9d8d 9d9c 9h7h 9h8h 9h9c 9h9d 9s7s 9s8s 9s9c 9s9d 9s9h Ac2c Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJs AcKs AcQc AcQd AcQh AcQs AcTh AcTs Ad2d Ad3d Ad4d Ad5d Ad6d Ad7d Ad8d Ad9d AdJs AdKs AdQc AdQd AdQh AdQs AdTh AdTs Ah2h Ah3h Ah4h Ah5h Ah7h Ah8h Ah9h AhKc AhKd AhQc AhQd AhTc AhTd AhTs As2s As4s As6s As7s As8s As9s AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc8c Jc9c JcTc Jd8d Jd9d JdJc JdTd Jh8h Jh9h JhJc JhJd JhTh Js8s Js9s JsJc JsJd JsJh JsTs Kc6c Kc7c Kc8c Kc9c KcJc KcJd KcJh KcJs KcQh KcQs KcTc Kd6d Kd7d Kd8d Kd9d KdJc KdJd KdJh KdJs KdQh KdQs KdTd Kh7h Kh8h Kh9h KhJc KhJd KhJs KhQc KhQd KhQs KhTh Ks6s Ks7s Ks8s Ks9s KsJc KsJd KsJh KsJs KsQc KsQd KsQh KsQs KsTs Qc8c Qc9c QcJc QcJd QcJh QcJs QcTc Qd8d Qd9d QdJc QdJd QdJh QdJs QdQc QdTd Qh8h Qh9h QhJc QhJd QhJh QhJs QhQc QhQd QhTh Qs8s Qs9s QsJc QsJd QsJh QsJs QsQc QsQd QsQh QsTs Tc8c Tc9c Td8d Td9d TdTc Th8h Th9h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh')
        },
        {
          actions: [
            'bet_55pct'
          ],
          combos: expand('7s6s As2s')
        },
        {
          actions: [
            'check'
          ],
          combos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3h3c 3h3d 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5c4c 5d4d 5h4h 6d6c 7c6c 7d6d 7d7c 7h7c 7h7d 7s7c 7s7d 7s7h 8c7c 8d7d 8d8c 8h7h 8h8c 8h8d 8s7s 8s8c 8s8d 8s8h 9c7c 9c8c 9d7d 9d8d 9d9c 9h7h 9h8h 9h9c 9h9d 9s7s 9s8s 9s9c 9s9d 9s9h Ac2c Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad2d Ad3d Ad4d Ad5d Ad6d Ad7d Ad8d Ad9d AdJc AdJd AdJh AdJs AdKc AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah2h Ah3h Ah4h Ah5h Ah7h Ah8h Ah9h AhJc AhJd AhJh AhJs AhKc AhKd AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs As2s As6s As8s As9s AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc8c Jc9c JcTc Jd8d Jd9d JdJc JdTd Jh8h Jh9h JhJc JhJd JhTh Js8s Js9s JsJc JsJd JsJh JsTs Kc6c Kc7c Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc Kd6d Kd7d Kd8d Kd9d KdJc KdJd KdJh KdJs KdQc KdQd KdQh KdQs KdTd Kh7h Kh8h Kh9h KhJc KhJd KhJh KhJs KhQc KhQd KhQh KhQs KhTh Ks6s Ks8s Ks9s KsJc KsJd KsJh KsJs KsQc KsQd KsQh KsQs KsTs Qc8c Qc9c QcJc QcJd QcJs QcTc Qd8d Qd9d QdJc QdJd QdJs QdTd Qh8h Qh9h QhJh QhQc QhQd QhTh Qs8s Qs9s QsJc QsJd QsJh QsJs QsQh QsTs Tc8c Tc9c Td8d Td9d TdTc Th8h Th9h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh')
        }
      ]
    },
    {
      position: 'BTN',
      stackBb: 40,
      villainPosition: 'UTG+1',
      board: [
        '8d',
        '6h',
        '5h'
      ],
      heroStackSize: 37.7,
      villainStackSize: 37.7,
      actionLine: 'preflop: UTG+1 raises 2.3bb, BTN calls 2.3bb; flop: UTG+1 checks, BTN checks; turn: UTG+1 checks',
      dealCombos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5c4c 5d4d 5d5c 5s4s 5s5c 5s5d 6c5c 6d5d 6d6c 6s5s 6s6c 6s6d 7c6c 7d6d 7d7c 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8c7c 8h7h 8h8c 8s7s 8s8c 8s8h 9c7c 9c8c 9d7d 9d9c 9h7h 9h8h 9h9c 9h9d 9s7s 9s8s 9s9c 9s9d 9s9h Ac2c Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad2d Ad3d Ad4d Ad5d Ad6d Ad7d Ad9d AdJc AdJd AdJh AdJs AdKc AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah2h Ah3h Ah4h Ah7h Ah8h Ah9h AhJc AhJd AhJh AhJs AhKc AhKd AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs As2s As3s As4s As5s As6s As7s As8s As9s AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc8c Jc9c JcTc Jd9d JdJc JdTd Jh8h Jh9h JhJc JhJd JhTh Js8s Js9s JsJc JsJd JsJh JsTs Kc6c Kc7c Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc Kd6d Kd7d Kd9d KdJc KdJd KdJh KdJs KdQc KdQd KdQh KdQs KdTd Kh7h Kh8h Kh9h KhJc KhJd KhJh KhJs KhQc KhQd KhQh KhQs KhTh Ks6s Ks7s Ks8s Ks9s KsJc KsJd KsJh KsJs KsQc KsQd KsQh KsQs KsTs Qc8c Qc9c QcJc QcJd QcJh QcJs QcTc Qd9d QdJc QdJd QdJh QdJs QdQc QdTd Qh8h Qh9h QhJc QhJd QhJh QhJs QhQc QhQd QhTh Qs8s Qs9s QsJc QsJd QsJh QsJs QsQc QsQd QsQh QsTs Tc8c Tc9c Td9d TdTc Th8h Th9h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh'),
      buckets: [
        {
          actions: [
            'bet_20pct'
          ],
          combos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3s3c 3s3d 3s3h 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5c4c 5d4d 5d5c 5s4s 5s5c 5s5d 6c5c 6d5d 6d6c 6s5s 6s6c 6s6d 7c6c 7d6d 7d7c 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8c7c 8h7h 8h8c 8s7s 8s8c 8s8h 9c7c 9c8c 9d7d 9d9c 9h7h 9h8h 9h9c 9h9d 9s7s 9s8s 9s9c 9s9d 9s9h Ac2c Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcKh AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad2d Ad3d Ad4d Ad5d Ad6d Ad7d Ad9d AdJc AdJh AdJs AdKh AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah2h Ah3h Ah4h Ah7h Ah8h Ah9h AhJc AhJd AhJh AhJs AhKc AhKd AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs As2s As3s As4s As5s As6s As7s As8s As9s AsJd AsJh AsJs AsKh AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc8c Jc9c JcTc Jd9d JdJc JdTd Jh8h Jh9h JhJc JhJd JhTh Js8s Js9s JsJc JsJd JsJh JsTs Kc6c Kc7c Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc Kd6d Kd7d Kd9d KdJc KdJd KdJh KdJs KdQc KdQd KdQh KdQs KdTd Kh7h Kh8h Kh9h KhJc KhJd KhJh KhJs KhQc KhQd KhQh KhQs KhTh Ks6s Ks7s Ks8s Ks9s KsJc KsJd KsJh KsJs KsQc KsQd KsQh KsQs KsTs Qc8c Qc9c QcJc QcJd QcJh QcJs QcTc Qd9d QdJc QdJd QdJh QdJs QdQc QdTd Qh8h Qh9h QhJc QhJd QhJh QhJs QhQc QhQd QhTh Qs8s Qs9s QsJc QsJd QsJh QsJs QsQc QsQd QsQh QsTs Tc8c Tc9c Td9d TdTc Th8h Th9h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh')
        },
        {
          actions: [
            'bet_33pct'
          ],
          combos: expand('2d2c 2h2c 2s2c 2s2d 2s2h 3h3c 3h3d 3s3c 3s3h 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5c4c 5d4d 5d5c 5s4s 5s5c 5s5d 6c5c 6d5d 6d6c 6s5s 6s6c 6s6d 7c6c 7d6d 7d7c 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8c7c 8h7h 8h8c 8s7s 8s8c 8s8h 9c7c 9c8c 9d7d 9d9c 9h7h 9h8h 9h9c 9h9d 9s7s 9s8s 9s9c 9s9d 9s9h Ac2c Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJd AcJh AcKh AcQc AcQd AcQh AcTc AcTd AcTh Ad2d Ad3d Ad4d Ad5d Ad6d Ad7d Ad9d AdJc AdJh AdJs AdKh AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah2h Ah3h Ah4h Ah7h Ah8h Ah9h AhJc AhJd AhJh AhJs AhKc AhKd AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs As2s As3s As4s As5s As6s As7s As8s As9s AsJd AsJh AsKh AsQd AsQh AsQs AsTd AsTh AsTs Jc9c JcTc Jd9d JdJc JdTd Jh8h Jh9h JhJc JhJd JhTh Js9s JsJc JsJd JsJh JsTs Kc6c Kc7c Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc Kd6d Kd7d Kd9d KdJc KdJd KdJh KdJs KdQc KdQd KdQh KdQs KdTd Kh7h Kh8h Kh9h KhJc KhJd KhJh KhJs KhQc KhQd KhQh KhQs KhTh Ks6s Ks7s Ks8s Ks9s KsJc KsJd KsJh KsJs KsQc KsQd KsQh KsQs KsTs Qc8c Qc9c QcJc QcJd QcJh QcJs QcTc Qd9d QdJc QdJd QdJh QdJs QdQc QdTd Qh8h Qh9h QhJc QhJd QhJh QhJs QhQc QhQd QhTh Qs8s Qs9s QsJc QsJd QsJh QsJs QsQc QsQd QsQh QsTs Tc8c Tc9c Td9d TdTc Th8h Th9h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh')
        },
        {
          actions: [
            'check'
          ],
          combos: expand('2d2c 2h2c 2h2d 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5c4c 5d4d 5d5c 5s4s 5s5d 6c5c 6d5d 6d6c 6s5s 6s6d 7c6c 7d6d 7d7c 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8c7c 8h8c 8s7s 8s8c 8s8h 9c7c 9c8c 9d7d 9d9c 9h7h 9h8h 9h9c 9h9d 9s7s 9s8s 9s9d 9s9h Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad2d Ad3d Ad4d Ad5d Ad6d Ad7d Ad9d AdJc AdJd AdJh AdJs AdKc AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah2h Ah3h Ah4h Ah8h Ah9h AhJc AhJd AhJh AhJs AhKc AhKd AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs As3s As4s As5s As6s As7s As8s As9s AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc8c Jc9c JcTc Jd9d JdJc JdTd Jh8h Jh9h JhJc JhJd JhTh Js8s Js9s JsJc JsJd JsJh JsTs Kc6c Kc7c Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc Kd6d Kd7d Kd9d KdJc KdJd KdJh KdJs KdQc KdQd KdQh KdQs KdTd Kh7h Kh8h Kh9h KhJc KhJd KhJh KhJs KhQc KhQd KhQh KhQs KhTh Ks6s Ks7s Ks8s Ks9s KsJc KsJd KsJh KsJs KsQc KsQd KsQh KsQs KsTs Qc8c Qc9c QcJc QcJh QcJs QcTc Qd9d QdJd QdJh QdQc QdTd Qh8h Qh9h QhJc QhJd QhJh QhJs QhQc QhQd QhTh Qs8s Qs9s QsJc QsJh QsJs QsQc QsQd QsQh QsTs Tc8c Tc9c Td9d TdTc Th8h Th9h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh')
        }
      ]
    },
    {
      position: 'BTN',
      stackBb: 40,
      villainPosition: 'UTG+1',
      board: [
        'Ah',
        '6d',
        '2c'
      ],
      heroStackSize: 37.7,
      villainStackSize: 37.7,
      actionLine: 'preflop: UTG+1 raises 2.3bb, BTN calls 2.3bb; flop: UTG+1 checks, BTN checks; turn: UTG+1 checks',
      dealCombos: expand('2h2d 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5c4c 5d4d 5d5c 5h4h 5h5c 5h5d 5s4s 5s5c 5s5d 5s5h 6c5c 6h5h 6h6c 6s5s 6s6c 6s6h 7c6c 7d7c 7h6h 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8c7c 8d7d 8d8c 8h7h 8h8c 8h8d 8s7s 8s8c 8s8d 8s8h 9c7c 9c8c 9d7d 9d8d 9d9c 9h7h 9h8h 9h9c 9h9d 9s7s 9s8s 9s9c 9s9d 9s9h Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad2d Ad3d Ad4d Ad5d Ad7d Ad8d Ad9d AdJc AdJd AdJh AdJs AdKc AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs As2s As3s As4s As5s As6s As7s As8s As9s AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc8c Jc9c JcTc Jd8d Jd9d JdJc JdTd Jh8h Jh9h JhJc JhJd JhTh Js8s Js9s JsJc JsJd JsJh JsTs Kc6c Kc7c Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc Kd7d Kd8d Kd9d KdJc KdJd KdJh KdJs KdQc KdQd KdQh KdQs KdTd Kh6h Kh7h Kh8h Kh9h KhJc KhJd KhJh KhJs KhQc KhQd KhQh KhQs KhTh Ks6s Ks7s Ks8s Ks9s KsJc KsJd KsJh KsJs KsQc KsQd KsQh KsQs KsTs Qc8c Qc9c QcJc QcJd QcJh QcJs QcTc Qd8d Qd9d QdJc QdJd QdJh QdJs QdQc QdTd Qh8h Qh9h QhJc QhJd QhJh QhJs QhQc QhQd QhTh Qs8s Qs9s QsJc QsJd QsJh QsJs QsQc QsQd QsQh QsTs Tc8c Tc9c Td8d Td9d TdTc Th8h Th9h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh'),
      buckets: [
        {
          actions: [
            'bet_20pct'
          ],
          combos: expand('2h2d 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5c4c 5d4d 5d5c 5h4h 5h5c 5h5d 5s4s 5s5c 5s5d 5s5h 6c5c 6h5h 6h6c 6s5s 6s6c 6s6h 7c6c 7d7c 7h6h 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8c7c 8d7d 8d8c 8h7h 8h8c 8h8d 8s7s 8s8c 8s8d 8s8h 9c7c 9c8c 9d7d 9d8d 9d9c 9h7h 9h8h 9h9c 9h9d 9s7s 9s8s 9s9c 9s9d 9s9h Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad2d Ad3d Ad4d Ad5d Ad7d Ad8d Ad9d AdJc AdJd AdJh AdJs AdKc AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs As2s As3s As4s As5s As6s As7s As8s As9s AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc8c Jc9c JcTc Jd8d Jd9d JdJc JdTd Jh8h Jh9h JhJc JhTh Js8s Js9s JsJc JsJd JsJh JsTs Kc6c Kc7c Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQh KcTc Kd7d Kd8d Kd9d KdJc KdJd KdJh KdQc KdQd KdQh KdTd Kh6h Kh7h Kh8h Kh9h KhJc KhJd KhJh KhJs KhQc KhQd KhQh KhTh Ks6s Ks7s Ks8s Ks9s KsJc KsJd KsJh KsQc KsQd KsQh KsQs KsTs Qc8c Qc9c QcJc QcJd QcJh QcJs QcTc Qd8d Qd9d QdJc QdJd QdJh QdJs QdQc QdTd Qh8h Qh9h QhJc QhJd QhJh QhJs QhQc QhQd QhTh Qs8s Qs9s QsJc QsJd QsJh QsJs QsQc QsQd QsQh QsTs Tc8c Tc9c Td8d Td9d TdTc Th8h Th9h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh')
        },
        {
          actions: [
            'bet_33pct'
          ],
          combos: expand('2h2d 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5c4c 5d4d 5d5c 5h4h 5h5c 5h5d 5s4s 5s5c 5s5d 5s5h 6c5c 6h5h 6h6c 6s5s 6s6c 6s6h 7c6c 7d7c 7h6h 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8c7c 8d7d 8d8c 8h7h 8h8c 8h8d 8s7s 8s8c 8s8d 8s8h 9c7c 9c8c 9d7d 9d8d 9d9c 9h7h 9h8h 9h9c 9h9d 9s7s 9s8s 9s9c 9s9d 9s9h Ac3c Ac4c Ac5c Ac6c Ac8c AcJc AcJd AcJh AcJs AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad2d Ad3d Ad4d Ad5d Ad8d AdJc AdJd AdJh AdJs AdKc AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs As2s As3s As4s As5s As6s As7s As8s As9s AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc8c Jc9c JcTc Jd8d Jd9d JdTd Jh8h Jh9h JhTh Js8s JsTs Kc6c Kc7c Kc8c Kc9c KcJc KcJd KcJh KcTc Kd7d Kd8d Kd9d KdJc KdJd KdJh KdTd Kh6h Kh7h Kh8h Kh9h KhJc KhJd KhJh KhJs KhTh Ks6s Ks7s Ks8s KsJd KsJh KsTs Qc8c Qc9c QcJc QcJd QcJh QcJs QcTc Qd8d Qd9d QdJc QdJd QdJh QdJs QdTd Qh8h Qh9h QhJc QhJd QhJh QhJs QhTh Qs8s Qs9s QsJc QsJd QsJh QsJs QsTs Tc8c Tc9c Td8d Td9d TdTc Th8h Th9h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh')
        },
        {
          actions: [
            'bet_55pct'
          ],
          combos: expand('2h2d 2s2d 2s2h 6s6c 8s7s 9s7s 9s8s AcQs AdQs AsJs AsQs JcTc JdTd JhTh Kc7c Kd7d Kh7h QcTc QdTd')
        },
        {
          actions: [
            'check'
          ],
          combos: expand('3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5c4c 5d4d 5d5c 5h5c 5h5d 5s4s 5s5c 5s5d 5s5h 6c5c 6h5h 6s5s 6s6c 6s6h 7c6c 7d7c 7h6h 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8c7c 8d7d 8d8c 8h7h 8h8c 8h8d 8s7s 8s8c 8s8d 8s8h 9c7c 9c8c 9d7d 9d8d 9d9c 9h7h 9h8h 9h9c 9h9d 9s7s 9s8s 9s9c 9s9d 9s9h Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad2d Ad3d Ad4d Ad5d Ad7d Ad8d Ad9d AdJc AdJd AdJh AdJs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs As2s As3s As4s As5s As6s As7s As8s As9s AsJc AsJd AsJh AsJs AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc8c Jc9c JcTc Jd8d Jd9d JdJc JdTd Jh8h Jh9h JhJc JhJd JhTh Js8s Js9s JsJc JsJd JsJh JsTs Kc6c Kc7c Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc Kd7d Kd8d Kd9d KdJc KdJd KdJh KdJs KdQc KdQd KdQh KdQs KdTd Kh6h Kh7h Kh8h Kh9h KhJc KhJd KhJh KhJs KhQc KhQd KhQh KhQs KhTh Ks6s Ks7s Ks8s Ks9s KsJc KsJd KsJh KsJs KsQc KsQd KsQh KsQs KsTs Qc8c Qc9c QcJc QcJd QcJh QcJs QcTc Qd8d Qd9d QdJc QdJd QdJh QdJs QdQc QdTd Qh8h Qh9h QhJc QhJd QhJh QhJs QhQc QhQd QhTh Qs8s Qs9s QsJc QsJd QsJh QsJs QsQc QsQd QsQh QsTs Tc8c Tc9c Td8d Td9d TdTc Th8h Th9h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh')
        }
      ]
    },
    {
      position: 'BTN',
      stackBb: 40,
      villainPosition: 'UTG+1',
      board: [
        'Ah',
        'Kd',
        'Jc'
      ],
      heroStackSize: 37.7,
      villainStackSize: 37.7,
      actionLine: 'preflop: UTG+1 raises 2.3bb, BTN calls 2.3bb; flop: UTG+1 checks, BTN checks; turn: UTG+1 checks',
      dealCombos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5c4c 5d4d 5d5c 5h4h 5h5c 5h5d 5s4s 5s5c 5s5d 5s5h 6c5c 6d5d 6d6c 6h5h 6h6c 6h6d 6s5s 6s6c 6s6d 6s6h 7c6c 7d6d 7d7c 7h6h 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8c7c 8d7d 8d8c 8h7h 8h8c 8h8d 8s7s 8s8c 8s8d 8s8h 9c7c 9c8c 9d7d 9d8d 9d9c 9h7h 9h8h 9h9c 9h9d 9s7s 9s8s 9s9c 9s9d 9s9h Ac2c Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJd AcJh AcJs AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad2d Ad3d Ad4d Ad5d Ad6d Ad7d Ad8d Ad9d AdJd AdJh AdJs AdKc AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs As2s As3s As4s As5s As6s As7s As8s As9s AsJd AsJh AsJs AsKc AsKh AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jd8d Jd9d JdTd Jh8h Jh9h JhJd JhTh Js8s Js9s JsJd JsJh JsTs Kc6c Kc7c Kc8c Kc9c KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc Kh6h Kh7h Kh8h Kh9h KhJd KhJh KhJs KhQc KhQd KhQh KhQs KhTh Ks6s Ks7s Ks8s Ks9s KsJd KsJh KsJs KsQc KsQd KsQh KsQs KsTs Qc8c Qc9c QcJd QcJh QcJs QcTc Qd8d Qd9d QdJd QdJh QdJs QdQc QdTd Qh8h Qh9h QhJd QhJh QhJs QhQc QhQd QhTh Qs8s Qs9s QsJd QsJh QsJs QsQc QsQd QsQh QsTs Tc8c Tc9c Td8d Td9d TdTc Th8h Th9h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh'),
      buckets: [
        {
          actions: [
            'bet_33pct'
          ],
          combos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5c4c 5d4d 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6c5c 6d5d 6d6c 6h6c 6h6d 6s6c 6s6d 6s6h 7c6c 8c7c 8d7d Ac4c Ac6c Ac7c Ac8c AcJd AcJh AcJs AcKh AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad4d Ad6d Ad7d Ad8d AdJd AdJh AdJs AdKc AdKh AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs As4s As8s As9s AsJd AsJh AsJs AsKh AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc KhJd KhJh KhJs KhQc KhQd KhQh KhQs KhTh KsJd KsJh KsJs KsQd KsQs KsTs Qc8c Qc9c QcTc Qd8d Qd9d QdTd Qh8h Qh9h QhTh Qs8s QsTs Tc8c Tc9c Td8d Td9d Th8h Th9h Ts8s Ts9s')
        },
        {
          actions: [
            'bet_55pct'
          ],
          combos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5c4c 5d4d 5d5c 5h4h 5h5c 5h5d 5s5c 5s5d 5s5h 6c5c 6d5d 6d6c 6h5h 6h6c 6h6d 6s6d 6s6h 7c6c 7d6d 7h6h 8c7c 8d7d 8h7h Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c AcJd AcJh AcJs AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad3d Ad4d Ad5d Ad8d AdJd AdJh AdJs AdKc AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs AsJd AsJh AsJs AsKc AsKh AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs JsTs KcJd KcJh KcJs KcQc KcQd KcTc KhJd KhJh KhJs KhQd KhQh KhQs KhTh KsJd KsJh KsJs KsQc KsQd KsQh KsQs Qc8c Qc9c QcTc Qd8d Qd9d QdTd Qh8h Qh9h QhTh Qs8s Qs9s QsTs Tc8c Tc9c Td8d Td9d Th8h Th9h Ts8s Ts9s')
        },
        {
          actions: [
            'bet_83pct'
          ],
          combos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5c4c 5d4d 5d5c 5h4h 5h5c 5h5d 5s5d 5s5h 6c5c 6d5d 6h5h 6h6d 6s6d 7d6d AcJd AcJh AcJs AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs AdJd AdJh AdJs AdKc AdKh AdKs AdQc AdQd AdQh AdQs AdTd AdTh AdTs AsJd AsJh AsJs AsKc AsKh AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs KcJd KcJh KcJs KhJd KhJh KhJs KsJd KsJh KsJs Qc8c Qc9c QcTc Qd8d Qd9d QdTd Qh8h Qh9h QhTh Qs8s Qs9s QsTs Tc8c Tc9c Td8d Td9d Th8h Th9h Ts8s')
        },
        {
          actions: [
            'check'
          ],
          combos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5c4c 5d4d 5d5c 5h4h 5h5c 5h5d 5s4s 5s5c 5s5d 5s5h 6c5c 6d5d 6d6c 6h5h 6h6c 6h6d 6s5s 6s6c 6s6d 6s6h 7c6c 7d6d 7d7c 7h6h 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8c7c 8d7d 8d8c 8h7h 8h8c 8h8d 8s7s 8s8c 8s8d 8s8h 9c7c 9c8c 9d7d 9d8d 9d9c 9h7h 9h8h 9h9c 9h9d 9s7s 9s8s 9s9c 9s9d 9s9h Ac2c Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJd AcJh AcJs AcKh AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad2d Ad3d Ad4d Ad5d Ad6d Ad7d Ad8d Ad9d AdJd AdJh AdJs AdKh AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs As2s As3s As4s As5s As6s As7s As8s As9s AsJd AsJh AsJs AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jd8d Jd9d JdTd Jh8h Jh9h JhJd JhTh Js8s Js9s JsJd JsJh JsTs Kc6c Kc7c Kc8c Kc9c KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc Kh6h Kh7h Kh8h Kh9h KhJd KhJh KhJs KhQc KhQd KhQh KhQs KhTh Ks6s Ks7s Ks8s Ks9s KsJd KsJh KsJs KsQc KsQd KsQh KsQs KsTs Qc8c Qc9c QcJd QcJh QcJs QcTc Qd8d Qd9d QdJd QdJh QdJs QdQc QdTd Qh8h Qh9h QhJd QhJh QhJs QhQc QhQd QhTh Qs8s Qs9s QsJd QsJh QsJs QsQc QsQd QsQh QsTs Tc8c Tc9c Td8d Td9d TdTc Th8h Th9h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh')
        }
      ]
    }
  ]
};

export default pack;
