// Generated by scripts/import-ct-curriculum.ts. Do not edit by hand.
import type { RangePack } from '../types';

const expand = (value: string): string[] => value.split(' ');

const pack: RangePack = {
  slug: 'in-position-postflop-response-btn-co-flop-baseline',
  title: 'In-position postflop response: BTN vs CO - Flop (40bb) - Variant 1',
  description: 'Board-aware in-position response practice after the preflop raiser acts.',
  scenario: 'IP_POSTFLOP',
  street: 'flop',
  tier: 'advanced',
  methodology: 'gto_cev',
  source: {
    kind: 'brand_neutralized_snapshot_config',
    capturedAt: '2026-07-18',
    path: 'research/ct-trainer-2026-07-18/',
    sha256: '7b75912451630a4c383574431fa42a31887c1e7e23dcbffd6d67749796147c02'
  },
  cells: [
    {
      position: 'BTN',
      stackBb: 40,
      villainPosition: 'CO',
      board: [
        '6h',
        '4d',
        '2c'
      ],
      heroStackSize: 37.7,
      villainStackSize: 37.7,
      actionLine: 'preflop: CO raises 2.3bb, BTN calls 2.3bb; flop: CO checks, BTN checks; turn: CO checks',
      dealCombos: expand('2h2d 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4h4c 4s4c 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6c5c 6d5d 6d6c 6s5s 6s6c 6s6d 7c6c 7d6d 7d7c 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8c6c 8c7c 8d6d 8d7d 8d8c 8h7h 8h8c 8h8d 8s6s 8s7s 8s8c 8s8d 8s8h 9c7c 9c8c 9d7d 9d8d 9d9c 9h7h 9h8h 9h9c 9h9d 9s7s 9s8s 9s9c 9s9d 9s9h Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c Ac9d Ac9h Ac9s AcJc AcJd AcJh AcJs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad2d Ad3d Ad5d Ad6d Ad7d Ad8d Ad9c Ad9d Ad9h Ad9s AdJc AdJd AdJh AdJs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah2h Ah3h Ah4h Ah5h Ah7h Ah8h Ah9c Ah9d Ah9h Ah9s AhJc AhJd AhJh AhJs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs As4s As5s As6s As7s As8s As9c As9d As9h As9s AsJc AsJd AsJh AsJs AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc8c Jc9c JcTc JcTd JcTh JcTs Jd8d Jd9d JdJc JdTc JdTd JdTh JdTs Jh8h Jh9h JhJc JhJd JhTc JhTd JhTh JhTs Js8s Js9s JsJc JsJd JsJh JsTc JsTd JsTh JsTs Kc4c Kc5c Kc6c Kc7c Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc KcTd KcTh KcTs Kd5d Kd6d Kd7d Kd8d Kd9d KdJc KdJd KdJh KdJs KdQc KdQd KdQh KdQs KdTc KdTd KdTh KdTs Kh4h Kh5h Kh7h Kh8h Kh9h KhJc KhJd KhJh KhJs KhQc KhQd KhQh KhQs KhTc KhTd KhTh KhTs Ks4s Ks5s Ks6s Ks7s Ks8s Ks9s KsJc KsJd KsJh KsJs KsQc KsQd KsQh KsQs KsTc KsTd KsTh KsTs Qc8c Qc9c QcJc QcJd QcJh QcJs QcTc QcTd QcTh QcTs Qd8d Qd9d QdJc QdJd QdJh QdJs QdTc QdTd QdTh QdTs Qh8h Qh9h QhJc QhJd QhJh QhJs QhTc QhTd QhTh QhTs Qs8s Qs9s QsJc QsJd QsJh QsJs QsTc QsTd QsTh QsTs Tc7c Tc8c Tc9c Td7d Td8d Td9d Th7h Th8h Th9h Ts7s Ts8s Ts9s'),
      buckets: [
        {
          actions: [
            'bet_33pct'
          ],
          combos: expand('2h2d 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4h4c 4s4c 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6c5c 6d5d 6d6c 6s5s 6s6c 6s6d 7c6c 7d6d 7d7c 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8c6c 8c7c 8d6d 8d7d 8d8c 8h7h 8h8c 8h8d 8s6s 8s7s 8s8c 8s8d 8s8h 9c7c 9c8c 9d7d 9d8d 9d9c 9h7h 9h8h 9h9c 9h9d 9s7s 9s8s 9s9c 9s9d 9s9h Ac3c Ac4c Ac5c Ac7c Ac8c Ac9c Ac9d Ac9h AcJc AcJd AcJh AcJs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad2d Ad3d Ad5d Ad7d Ad8d Ad9c Ad9d Ad9h AdJc AdJd AdJh AdJs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah2h Ah3h Ah4h Ah5h Ah7h Ah8h Ah9c Ah9d Ah9h AhJc AhJd AhJh AhJs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs As4s As5s As7s As8s As9s AsJc AsJd AsJh AsJs AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc8c Jc9c JcTc JcTd JcTh JcTs Jd8d Jd9d JdJc JdTc JdTd JdTh JdTs Jh8h Jh9h JhJc JhJd JhTc JhTd JhTh JhTs Js8s Js9s JsJc JsJd JsJh JsTc JsTd JsTh JsTs Kc4c Kc5c Kc6c Kc7c Kc8c Kc9c KcJc KcJd KcJh KcQc KcQd KcQh KcTc KcTd KcTh KcTs Kd5d Kd6d Kd7d Kd8d Kd9d KdJc KdJd KdJh KdQc KdQd KdQh KdTc KdTd KdTh KdTs Kh4h Kh5h Kh7h Kh8h Kh9h KhJc KhJd KhJh KhQc KhQd KhQh KhTc KhTd KhTh KhTs Ks4s Ks5s Ks6s Ks7s Ks8s Ks9s KsJs KsQc KsQd KsQs KsTc KsTd KsTh Qc8c Qc9c QcJc QcJd QcJh QcJs QcTc QcTd QcTh QcTs Qd8d Qd9d QdJc QdJd QdJh QdJs QdTc QdTd QdTh QdTs Qh8h Qh9h QhJc QhJd QhJh QhJs QhTc QhTd QhTh QhTs Qs8s Qs9s QsJc QsJd QsJh QsJs QsTc QsTd QsTh QsTs Tc8c Tc9c Td8d Td9d Th8h Th9h Ts8s Ts9s')
        },
        {
          actions: [
            'bet_55pct'
          ],
          combos: expand('2h2d 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4h4c 4s4c 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6c5c 6d5d 6d6c 6s5s 6s6c 6s6d 7c6c 7d6d 7d7c 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8c6c 8c7c 8d6d 8d7d 8d8c 8h7h 8h8c 8h8d 8s6s 8s7s 8s8c 8s8d 8s8h 9c7c 9c8c 9d7d 9d8d 9d9c 9h7h 9h8h 9h9c 9h9d 9s7s 9s8s 9s9c 9s9d 9s9h Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c AcJc AcJd AcJh AcJs AcQc AcQd AcQh AcQs AcTc AcTs Ad2d Ad3d Ad5d Ad6d Ad7d Ad8d AdJc AdJd AdJh AdJs AdQc AdQd AdQh AdQs AdTd Ah2h Ah3h Ah4h Ah5h Ah7h Ah8h AhJc AhJh AhJs AhQc AhQd AhQh AhQs AhTh As4s As5s As6s As7s As8s AsJc AsJd AsJh AsJs AsQc AsQd AsQh AsQs Jc8c Jc9c JcTc JcTd JcTh JcTs Jd8d Jd9d JdJc JdTc JdTd JdTh JdTs Jh8h Jh9h JhJc JhJd JhTc JhTd JhTh JhTs Js8s Js9s JsJc JsJd JsJh JsTc JsTd JsTh JsTs Kc5c Kc6c Kc7c Kc8c Kc9c KcJd KcJh KcJs KcQc KcTc KcTd KcTh KcTs Kd5d Kd6d Kd7d Kd8d Kd9d KdJc KdJh KdJs KdQd KdTc KdTd KdTh KdTs Kh5h Kh7h Kh8h Kh9h KhJc KhJd KhJh KhQh KhTc KhTd KhTh KhTs Ks5s Ks6s Ks7s Ks8s Ks9s KsJc KsJd KsJs KsQc KsQs KsTc KsTd KsTh Qc8c Qc9c QcJc QcJd QcJh QcJs QcTc QcTd QcTh QcTs Qd8d Qd9d QdJc QdJd QdJh QdJs QdTc QdTd QdTh QdTs Qh8h Qh9h QhJc QhJd QhJh QhJs QhTc QhTd QhTh QhTs Qs8s Qs9s QsJc QsJd QsJh QsJs QsTc QsTd QsTh QsTs Tc8c Tc9c Td8d Td9d Th8h Th9h Ts8s Ts9s')
        },
        {
          actions: [
            'bet_83pct'
          ],
          combos: expand('6c5c 6d5d 6s5s 7d7c 7h7c 7h7d 7s7c 7s7d 7s7h 8d8c 8h8c 8h8d 8s8c 8s8d 8s8h 9c8c 9s9c 9s9d 9s9h Ac5c Ac6c Ac7c Ad5d Ad6d Ad7d Ah4h Ah5h AhQh As4s As6s As8s Jc8c Jd8d Jh8h Js8s Kc6c Kc8c KcTd KcTh KcTs Kd6d Kd8d KdTc KdTh KdTs Kh8h KhTc KhTd Ks6s Ks8s QcJc QdJd Tc8c Tc9c Td8d Td9d Th9h Ts9s')
        },
        {
          actions: [
            'check'
          ],
          combos: expand('2h2d 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4h4c 4s4c 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6d6c 6s6c 6s6d 7c6c 7d6d 7h7c 7h7d 7s6s 8c6c 8c7c 8d6d 8d7d 8h7h 8s6s 8s7s 9c7c 9c8c 9d7d 9d8d 9d9c 9h7h 9h8h 9h9c 9h9d 9s7s 9s8s Ac3c Ac4c Ac5c Ac7c Ac8c Ac9c Ac9d Ac9h Ac9s AcJc AcJd AcJh AcJs AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad2d Ad3d Ad5d Ad7d Ad8d Ad9c Ad9d Ad9h Ad9s AdJc AdJd AdJh AdJs AdQc AdQh AdQs AdTc AdTd AdTh AdTs Ah2h Ah3h Ah4h Ah5h Ah7h Ah8h Ah9c Ah9d Ah9h Ah9s AhJc AhJd AhJh AhJs AhQc AhQd AhQs AhTc AhTd AhTh AhTs As4s As5s As7s As8s As9c As9d As9h As9s AsJc AsJd AsJh AsJs AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc8c Jc9c JcTc JcTd JcTh JcTs Jd8d Jd9d JdJc JdTc JdTd JdTh JdTs Jh8h Jh9h JhJc JhJd JhTc JhTd JhTh JhTs Js8s Js9s JsTc JsTd JsTh JsTs Kc4c Kc5c Kc7c Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc KcTd KcTh KcTs Kd5d Kd7d Kd8d Kd9d KdJc KdJd KdJh KdJs KdQc KdQd KdQh KdQs KdTc KdTd KdTh KdTs Kh4h Kh5h Kh7h Kh8h Kh9h KhJc KhJd KhJh KhJs KhQc KhQd KhQh KhQs KhTc KhTd KhTh KhTs Ks4s Ks5s Ks7s Ks9s KsJc KsJd KsJh KsJs KsQc KsQd KsQh KsQs KsTc KsTd KsTh KsTs Qc8c Qc9c QcJc QcJd QcJh QcJs QcTc QcTd QcTh QcTs Qd8d Qd9d QdJc QdJd QdJh QdJs QdTc QdTd QdTh QdTs Qh8h Qh9h QhJc QhJd QhJh QhJs QhTc QhTd QhTh QhTs Qs8s Qs9s QsJc QsJd QsJh QsJs QsTc QsTd QsTh QsTs Tc7c Tc8c Tc9c Td7d Td8d Td9d Th7h Th8h Th9h Ts7s Ts8s Ts9s')
        }
      ]
    },
    {
      position: 'BTN',
      stackBb: 40,
      villainPosition: 'CO',
      board: [
        '8d',
        '6h',
        '5h'
      ],
      heroStackSize: 37.7,
      villainStackSize: 37.7,
      actionLine: 'preflop: CO raises 2.3bb, BTN calls 2.3bb; flop: CO checks, BTN checks; turn: CO checks',
      dealCombos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5s5c 5s5d 6c5c 6d5d 6d6c 6s5s 6s6c 6s6d 7c6c 7d6d 7d7c 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8c6c 8c7c 8h7h 8h8c 8s6s 8s7s 8s8c 8s8h 9c7c 9c8c 9d7d 9d9c 9h7h 9h8h 9h9c 9h9d 9s7s 9s8s 9s9c 9s9d 9s9h Ac2c Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c Ac9d Ac9h Ac9s AcJc AcJd AcJh AcJs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad2d Ad3d Ad4d Ad5d Ad6d Ad7d Ad9c Ad9d Ad9h Ad9s AdJc AdJd AdJh AdJs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah2h Ah3h Ah4h Ah7h Ah8h Ah9c Ah9d Ah9h Ah9s AhJc AhJd AhJh AhJs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs As2s As3s As4s As5s As6s As7s As8s As9c As9d As9h As9s AsJc AsJd AsJh AsJs AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc8c Jc9c JcTc JcTd JcTh JcTs Jd9d JdJc JdTc JdTd JdTh JdTs Jh8h Jh9h JhJc JhJd JhTc JhTd JhTh JhTs Js8s Js9s JsJc JsJd JsJh JsTc JsTd JsTh JsTs Kc4c Kc5c Kc6c Kc7c Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc KcTd KcTh KcTs Kd4d Kd5d Kd6d Kd7d Kd9d KdJc KdJd KdJh KdJs KdQc KdQd KdQh KdQs KdTc KdTd KdTh KdTs Kh4h Kh7h Kh8h Kh9h KhJc KhJd KhJh KhJs KhQc KhQd KhQh KhQs KhTc KhTd KhTh KhTs Ks4s Ks5s Ks6s Ks7s Ks8s Ks9s KsJc KsJd KsJh KsJs KsQc KsQd KsQh KsQs KsTc KsTd KsTh KsTs Qc8c Qc9c QcJc QcJd QcJh QcJs QcTc QcTd QcTh QcTs Qd9d QdJc QdJd QdJh QdJs QdTc QdTd QdTh QdTs Qh8h Qh9h QhJc QhJd QhJh QhJs QhTc QhTd QhTh QhTs Qs8s Qs9s QsJc QsJd QsJh QsJs QsTc QsTd QsTh QsTs Tc7c Tc8c Tc9c Td7d Td9d Th7h Th8h Th9h Ts7s Ts8s Ts9s'),
      buckets: [
        {
          actions: [
            'bet_20pct'
          ],
          combos: expand('2s2c 3s3c 6s6c 8s8c 9h7h Kh9h')
        },
        {
          actions: [
            'bet_33pct'
          ],
          combos: expand('2d2c 2h2c 2s2c 2s2d 2s2h 3d3c 3h3c 3s3c 3s3d 3s3h 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5s5c 5s5d 6c5c 6d5d 6d6c 6s5s 6s6c 6s6d 7c6c 7d6d 7d7c 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8c6c 8c7c 8h7h 8h8c 8s6s 8s7s 8s8c 8s8h 9c7c 9c8c 9d7d 9d9c 9h7h 9h8h 9h9c 9h9d 9s7s 9s8s 9s9c 9s9d 9s9h Ac2c Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c Ac9d Ac9h Ac9s AcJc AcJd AcJh AcJs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad2d Ad3d Ad4d Ad5d Ad6d Ad7d Ad9c Ad9d Ad9h Ad9s AdJc AdJd AdJh AdJs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah2h Ah3h Ah4h Ah7h Ah8h Ah9c Ah9d Ah9h Ah9s AhJc AhJd AhJh AhJs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs As2s As3s As4s As5s As6s As7s As8s As9c As9d As9h As9s AsJc AsJd AsJh AsJs AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc8c Jc9c JcTc JcTd JcTh JcTs Jd9d JdJc JdTc JdTd JdTh JdTs Jh8h Jh9h JhJc JhJd JhTc JhTd JhTh JhTs Js8s Js9s JsJc JsJd JsJh JsTc JsTd JsTh JsTs Kc4c Kc6c Kc7c Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc KcTd KcTh KcTs Kd4d Kd5d Kd6d Kd7d Kd9d KdJc KdJd KdJh KdJs KdQc KdQh KdQs KdTc KdTd KdTh KdTs Kh4h Kh7h Kh8h Kh9h KhJc KhJd KhJh KhJs KhQc KhQd KhQh KhQs KhTc KhTd KhTh KhTs Ks4s Ks6s Ks7s Ks8s Ks9s KsJc KsJd KsJh KsJs KsQc KsQd KsQh KsQs KsTc KsTd KsTh KsTs Qc8c Qc9c QcJc QcJd QcJh QcJs QcTc QcTd QcTh QcTs Qd9d QdJc QdJd QdJh QdJs QdTc QdTd QdTh QdTs Qh8h Qh9h QhJc QhJd QhJh QhJs QhTc QhTd QhTh QhTs Qs8s Qs9s QsJc QsJd QsJh QsJs QsTc QsTd QsTh QsTs Tc7c Tc8c Tc9c Td7d Td9d Th7h Th8h Th9h Ts7s Ts8s Ts9s')
        },
        {
          actions: [
            'bet_55pct'
          ],
          combos: expand('2s2c 4h4c 4s4h 5d5c 5s5c 5s5d 6c5c 6d5d 6d6c 6s5s 6s6c 6s6d 7d6d 7d7c 7h7c 7h7d 7s7c 7s7d 7s7h 8c6c 8c7c 8h7h 8h8c 8s6s 8s7s 8s8h 9c7c 9d7d 9d9c 9h8h 9h9c 9h9d 9s7s 9s9c 9s9d 9s9h Ac2c Ac3c Ac4c Ac6c Ac7c Ac8c Ac9c Ac9h Ac9s AcJd AcQh AcTc Ad2d Ad3d Ad6d Ad7d Ad9d AdJc AdJd AdJs AdQd AdTc AdTh AdTs Ah4h Ah7h Ah8h Ah9c Ah9h Ah9s AhJc AhJd AhJh AhJs AhQc AhQh AhQs AhTc AhTd AhTh AhTs As2s As3s As4s As6s As7s As8s As9c As9h As9s AsJd AsQh AsTs Jc9c JcTc JcTd JcTh JcTs Jd9d JdJc JdTc JdTd JdTh JdTs Jh8h Jh9h JhJc JhJd JhTc JhTd JhTh JhTs Js9s JsJc JsJd JsJh JsTc JsTd JsTh JsTs Kc4c Kc7c Kc8c Kc9c KcJd KcJh KcQh KcTc KcTd KcTh KcTs Kd4d Kd7d Kd9d KdJc KdJh KdJs KdQh KdTc KdTh KdTs Kh4h Kh7h Kh8h Kh9h KhJc KhJd KhJh KhJs KhQd KhQh KhTc KhTd KhTh KhTs Ks4s Ks7s Ks8s Ks9s KsJd KsJh KsQh KsTc KsTd KsTh KsTs Qc9c QcJc QcJd QcJh QcJs QcTc QcTd QcTh QcTs Qd9d QdJc QdJh QdJs QdTc QdTd QdTh QdTs Qh8h Qh9h QhJc QhJd QhJh QhJs QhTc QhTd QhTh QhTs Qs9s QsJc QsJd QsJh QsJs QsTc QsTd QsTh QsTs Th8h')
        },
        {
          actions: [
            'check'
          ],
          combos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5s5c 5s5d 6c5c 6d5d 6d6c 6s5s 6s6c 6s6d 7c6c 7d6d 7d7c 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8h8c 8s8c 8s8h 9c8c 9h7h 9h8h 9s8s Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c Ac9d Ac9h Ac9s AcJc AcJd AcJh AcJs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad2d Ad3d Ad4d Ad5d Ad6d Ad7d Ad9c Ad9d Ad9h Ad9s AdJc AdJd AdJh AdJs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah2h Ah3h Ah4h Ah7h Ah8h Ah9c Ah9d Ah9s AhJc AhJd AhJh AhJs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs As4s As5s As6s As7s As8s As9c As9d As9h As9s AsJc AsJd AsJh AsJs AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc8c Jc9c JcTc JcTd JcTh JcTs Jd9d JdJc JdTc JdTd JdTh JdTs Jh8h Jh9h JhTc JhTd JhTh JhTs Js8s Js9s JsJd JsTc JsTd JsTh JsTs Kc4c Kc5c Kc6c Kc7c Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc KcTd KcTh KcTs Kd4d Kd5d Kd6d Kd7d Kd9d KdJc KdJd KdJh KdJs KdQc KdQd KdQh KdQs KdTc KdTd KdTh KdTs Kh4h Kh7h Kh8h Kh9h KhJc KhJd KhJh KhJs KhQc KhQd KhQh KhQs KhTc KhTd KhTh KhTs Ks4s Ks5s Ks6s Ks7s Ks8s Ks9s KsJc KsJd KsJh KsJs KsQc KsQd KsQh KsQs KsTc KsTd KsTh KsTs Qc8c Qc9c QcJc QcJd QcJh QcJs QcTc QcTd QcTh QcTs Qd9d QdJc QdJd QdJh QdJs QdTc QdTd QdTh QdTs Qh9h QhJc QhJd QhJh QhJs QhTc QhTd QhTh QhTs Qs8s Qs9s QsJc QsJd QsJh QsJs QsTc QsTd QsTh QsTs Tc7c Tc8c Tc9c Td7d Td9d Th7h Th8h Th9h Ts7s Ts8s Ts9s')
        }
      ]
    },
    {
      position: 'BTN',
      stackBb: 40,
      villainPosition: 'CO',
      board: [
        'Ah',
        '6d',
        '2c'
      ],
      heroStackSize: 37.7,
      villainStackSize: 37.7,
      actionLine: 'preflop: CO raises 2.3bb, BTN calls 2.3bb; flop: CO checks, BTN checks; turn: CO checks',
      dealCombos: expand('2h2d 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6c5c 6h5h 6h6c 6s5s 6s6c 6s6h 7c6c 7d7c 7h6h 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8c6c 8c7c 8d7d 8d8c 8h6h 8h7h 8h8c 8h8d 8s6s 8s7s 8s8c 8s8d 8s8h 9c7c 9c8c 9d7d 9d8d 9d9c 9h7h 9h8h 9h9c 9h9d 9s7s 9s8s 9s9c 9s9d 9s9h Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c Ac9d Ac9h Ac9s AcJc AcJd AcJh AcJs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad2d Ad3d Ad4d Ad5d Ad7d Ad8d Ad9c Ad9d Ad9h Ad9s AdJc AdJd AdJh AdJs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs As2s As3s As4s As5s As6s As7s As8s As9c As9d As9h As9s AsJc AsJd AsJh AsJs AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc8c Jc9c JcTc JcTd JcTh JcTs Jd8d Jd9d JdJc JdTc JdTd JdTh JdTs Jh8h Jh9h JhJc JhJd JhTc JhTd JhTh JhTs Js8s Js9s JsJc JsJd JsJh JsTc JsTd JsTh JsTs Kc4c Kc5c Kc6c Kc7c Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc KcTd KcTh KcTs Kd4d Kd5d Kd7d Kd8d Kd9d KdJc KdJd KdJh KdJs KdQc KdQd KdQh KdQs KdTc KdTd KdTh KdTs Kh4h Kh5h Kh6h Kh7h Kh8h Kh9h KhJc KhJd KhJh KhJs KhQc KhQd KhQh KhQs KhTc KhTd KhTh KhTs Ks4s Ks5s Ks6s Ks7s Ks8s Ks9s KsJc KsJd KsJh KsJs KsQc KsQd KsQh KsQs KsTc KsTd KsTh KsTs Qc8c Qc9c QcJc QcJd QcJh QcJs QcTc QcTd QcTh QcTs Qd8d Qd9d QdJc QdJd QdJh QdJs QdTc QdTd QdTh QdTs Qh8h Qh9h QhJc QhJd QhJh QhJs QhTc QhTd QhTh QhTs Qs8s Qs9s QsJc QsJd QsJh QsJs QsTc QsTd QsTh QsTs Tc7c Tc8c Tc9c Td7d Td8d Td9d Th7h Th8h Th9h Ts7s Ts8s Ts9s'),
      buckets: [
        {
          actions: [
            'bet_20pct'
          ],
          combos: expand('2h2d 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6c5c 6h5h 6h6c 6s5s 6s6c 6s6h 7c6c 7d7c 7h6h 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8c6c 8c7c 8d7d 8d8c 8h6h 8h7h 8h8c 8h8d 8s6s 8s7s 8s8c 8s8d 8s8h 9c7c 9c8c 9d7d 9d8d 9d9c 9h7h 9h8h 9h9c 9h9d 9s7s 9s8s 9s9c 9s9d 9s9h Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c Ac9d Ac9h Ac9s AcJc AcJd AcJh AcJs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad2d Ad3d Ad4d Ad5d Ad7d Ad8d Ad9c Ad9d Ad9h Ad9s AdJc AdJd AdJh AdJs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs As2s As3s As4s As5s As6s As7s As8s As9c As9d As9h As9s AsJc AsJd AsJh AsJs AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc8c Jc9c JcTc JcTd JcTh JcTs Jd8d Jd9d JdTc JdTd JdTh JdTs Jh8h Jh9h JhTc JhTd JhTh JhTs Js8s Js9s JsTc JsTd JsTh JsTs Kc4c Kc5c Kc6c Kc7c Kc8c KcJc KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc KcTd KcTh KcTs Kd4d Kd5d Kd7d Kd8d KdJc KdJd KdJh KdJs KdQc KdQd KdQh KdQs KdTc KdTd KdTh KdTs Kh4h Kh5h Kh6h Kh7h Kh8h KhJc KhJd KhJh KhJs KhQc KhQd KhQh KhQs KhTc KhTd KhTh KhTs Ks4s Ks5s Ks6s Ks7s Ks8s KsJc KsJd KsJh KsJs KsQc KsQd KsQh KsQs Qc8c Qc9c QcJc QcJd QcJh QcJs QcTc QcTd QcTh QcTs Qd8d Qd9d QdJc QdJd QdJh QdJs QdTc QdTd QdTh QdTs Qh8h Qh9h QhJc QhJd QhJh QhJs QhTc QhTd QhTh QhTs Qs8s Qs9s QsJc QsJd QsJh QsJs QsTc QsTd QsTh QsTs Tc7c Tc8c Tc9c Td7d Td8d Td9d Th7h Th8h Th9h Ts7s Ts8s Ts9s')
        },
        {
          actions: [
            'bet_33pct'
          ],
          combos: expand('2h2d 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6c5c 6h5h 6h6c 6s5s 6s6c 6s6h 7c6c 7d7c 7h6h 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8c6c 8c7c 8d7d 8d8c 8h6h 8h7h 8h8c 8h8d 8s6s 8s7s 8s8c 8s8d 8s8h 9c7c 9c8c 9d7d 9d8d 9d9c 9h7h 9h8h 9h9c 9h9d 9s7s 9s8s 9s9c 9s9d 9s9h Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c Ac9d Ac9h Ac9s AcJc AcJd AcJh AcJs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad2d Ad4d Ad5d Ad7d Ad8d Ad9c Ad9d Ad9h Ad9s AdJc AdJd AdJh AdJs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs As2s As4s As5s As6s As7s As8s As9c As9d As9h As9s AsJc AsJd AsJh AsJs AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc8c Jc9c JcTc JcTd JcTh JcTs Jd8d Jd9d JdTc JdTd JdTh JdTs Jh8h Jh9h JhTc JhTd JhTh JhTs Js8s Js9s JsTc JsTd JsTh JsTs Kc4c Kc5c Kc6c Kc7c Kc8c KcQc KcTd KcTh Kd4d Kd5d Kd7d Kd8d KdJd KdQc KdQd KdQh KdTc KdTh Kh4h Kh5h Kh6h Kh7h Kh8h KhQh KhTc Ks4s Ks5s Ks6s Ks7s Ks8s KsQs Qc8c Qc9c QcJc QcJd QcJh QcJs QcTc QcTd QcTh QcTs Qd8d Qd9d QdJc QdJd QdJh QdJs QdTc QdTd QdTh QdTs Qh8h Qh9h QhJc QhJd QhJh QhJs QhTc QhTd QhTh QhTs Qs8s QsJc QsJd QsJh QsJs QsTc QsTd QsTh QsTs Tc7c Tc8c Tc9c Td7d Td8d Td9d Th7h Th8h Th9h Ts8s Ts9s')
        },
        {
          actions: [
            'bet_55pct'
          ],
          combos: expand('2s2d')
        },
        {
          actions: [
            'check'
          ],
          combos: expand('3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6c5c 6h5h 6s5s 7c6c 7d7c 7h6h 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8c6c 8c7c 8d7d 8d8c 8h6h 8h7h 8h8c 8h8d 8s6s 8s7s 8s8c 8s8d 8s8h 9c7c 9c8c 9d7d 9d8d 9d9c 9h7h 9h8h 9h9c 9h9d 9s7s 9s8s 9s9c 9s9d 9s9h Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c Ac9d Ac9h Ac9s AcJc AcJd AcJh AcJs AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad2d Ad3d Ad4d Ad5d Ad7d Ad8d Ad9c Ad9d Ad9h Ad9s AdJc AdJd AdJh AdJs AdQc AdQh AdQs AdTc AdTd AdTh AdTs As2s As3s As4s As5s As6s As7s As8s As9c As9d As9h As9s AsJc AsJd AsJh AsJs AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc8c Jc9c JcTc JcTd JcTh JcTs Jd8d Jd9d JdJc JdTc JdTd JdTh JdTs Jh8h Jh9h JhJc JhJd JhTc JhTd JhTh JhTs Js8s Js9s JsJc JsJd JsJh JsTc JsTd JsTh JsTs Kc4c Kc5c Kc6c Kc7c Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc KcTd KcTh KcTs Kd4d Kd5d Kd7d Kd8d Kd9d KdJc KdJd KdJh KdJs KdQc KdQd KdQh KdQs KdTc KdTd KdTh KdTs Kh4h Kh5h Kh6h Kh7h Kh8h Kh9h KhJc KhJd KhJh KhJs KhQc KhQd KhQh KhQs KhTc KhTd KhTh KhTs Ks4s Ks5s Ks6s Ks7s Ks8s Ks9s KsJc KsJd KsJh KsJs KsQc KsQd KsQh KsQs KsTc KsTd KsTh KsTs Qc8c Qc9c QcJc QcJd QcJh QcJs QcTc QcTd QcTh QcTs Qd8d Qd9d QdJc QdJd QdJh QdJs QdTc QdTd QdTh QdTs Qh8h Qh9h QhJc QhJd QhJh QhJs QhTc QhTd QhTh QhTs Qs8s Qs9s QsJc QsJd QsJh QsJs QsTc QsTd QsTh QsTs Tc7c Tc8c Tc9c Td7d Td8d Td9d Th7h Th8h Th9h Ts7s Ts8s Ts9s')
        }
      ]
    },
    {
      position: 'BTN',
      stackBb: 40,
      villainPosition: 'CO',
      board: [
        'Ah',
        'Kd',
        'Jc'
      ],
      heroStackSize: 37.7,
      villainStackSize: 37.7,
      actionLine: 'preflop: CO raises 2.3bb, BTN calls 2.3bb; flop: CO checks, BTN checks; turn: CO checks',
      dealCombos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6c5c 6d5d 6d6c 6h5h 6h6c 6h6d 6s5s 6s6c 6s6d 6s6h 7c6c 7d6d 7d7c 7h6h 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8c6c 8c7c 8d6d 8d7d 8d8c 8h6h 8h7h 8h8c 8h8d 8s6s 8s7s 8s8c 8s8d 8s8h 9c7c 9c8c 9d7d 9d8d 9d9c 9h7h 9h8h 9h9c 9h9d 9s7s 9s8s 9s9c 9s9d 9s9h Ac2c Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c Ac9d Ac9h Ac9s AcJd AcJh AcJs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad2d Ad3d Ad4d Ad5d Ad6d Ad7d Ad8d Ad9c Ad9d Ad9h Ad9s AdJd AdJh AdJs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs As2s As3s As4s As5s As6s As7s As8s As9c As9d As9h As9s AsJd AsJh AsJs AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jd8d Jd9d JdTc JdTd JdTh JdTs Jh8h Jh9h JhJd JhTc JhTd JhTh JhTs Js8s Js9s JsJd JsJh JsTc JsTd JsTh JsTs Kc4c Kc5c Kc6c Kc7c Kc8c Kc9c KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc KcTd KcTh KcTs Kh4h Kh5h Kh6h Kh7h Kh8h Kh9h KhJd KhJh KhJs KhQc KhQd KhQh KhQs KhTc KhTd KhTh KhTs Ks4s Ks5s Ks6s Ks7s Ks8s Ks9s KsJd KsJh KsJs KsQc KsQd KsQh KsQs KsTc KsTd KsTh KsTs Qc8c Qc9c QcJd QcJh QcJs QcTc QcTd QcTh QcTs Qd8d Qd9d QdJd QdJh QdJs QdTc QdTd QdTh QdTs Qh8h Qh9h QhJd QhJh QhJs QhTc QhTd QhTh QhTs Qs8s Qs9s QsJd QsJh QsJs QsTc QsTd QsTh QsTs Tc7c Tc8c Tc9c Td7d Td8d Td9d Th7h Th8h Th9h Ts7s Ts8s Ts9s'),
      buckets: [
        {
          actions: [
            'bet_33pct'
          ],
          combos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5d 5s5c 5s5d 5s5h 6d6c 6h6c 6h6d 6s6c 6s6d 6s6h 7d6d 7h6h 8d6d 8d7d 8h6h 8s7s Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c Ac9d AcJd AcJh AcJs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad4d Ad5d Ad7d Ad8d Ad9c Ad9d Ad9h AdJd AdJh AdJs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs As4s As5s As6s As7s As8s As9s AsJd AsJh AsJs AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs KcJd KcJh KcJs KcQc KcQd KcQs KcTc KcTd KcTs KhJd KhJh KhJs KhQc KhQd KhQh KhQs KhTh KhTs KsJd KsJh KsJs KsQc KsQd KsQs KsTc KsTd KsTs Qc8c Qc9c QcTd QcTh QcTs Qd8d Qd9d QdTc QdTd QdTh QdTs Qh8h Qh9h QhTc QhTd QhTh QhTs Qs9s QsTc QsTd QsTh QsTs Tc8c Tc9c Td8d Td9d Th8h Th9h Ts8s Ts9s')
        },
        {
          actions: [
            'bet_55pct'
          ],
          combos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6c5c 6d5d 6d6c 6h5h 6h6c 6h6d 6s6c 6s6d 6s6h 7c6c 7d6d 7d7c 7h6h 7h7c 7h7d 8c6c 8c7c 8d6d 8d7d 8h6h 8h7h Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c Ac9s AcJd AcJh AcJs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad4d Ad5d Ad6d Ad7d Ad8d Ad9d Ad9s AdJd AdJh AdJs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs As4s As5s As6s As7s As8s As9s AsJd AsJh AsJs AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs JdTc JdTd JdTh JdTs JhTc JhTd JhTh JhTs JsTc JsTd JsTh JsTs KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc KcTd KcTs KhJd KhJh KhJs KhQc KhQd KhQh KhQs KhTc KhTd KhTh KhTs KsJd KsJh KsJs KsQc KsQd KsQh KsQs KsTc KsTd KsTh KsTs Qc8c Qc9c QcJd QcJh QcJs QcTc QcTd QcTh QcTs Qd8d Qd9d QdJd QdJh QdJs QdTc QdTd QdTh QdTs Qh8h Qh9h QhJd QhJh QhJs QhTc QhTd QhTh QhTs Qs8s Qs9s QsJd QsJh QsJs QsTc QsTd QsTh QsTs Tc7c Tc8c Tc9c Td7d Td8d Td9d Th7h Th8h Th9h Ts7s Ts8s Ts9s')
        },
        {
          actions: [
            'bet_83pct'
          ],
          combos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4d4c 4h4c 4h4d 4s4c 4s4d 6c5c 6d5d 6h5h 6s5s 7c6c 7d6d 7h6h 8c6c 8c7c 8d6d 8d7d 8h6h 8h7h Ac4c Ac6c AcJd AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad4d AdJh AdJs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs As4s As5s AsJd AsJs AsQc AsQd AsQh AsQs AsTd AsTh AsTs KcJd KcJh KcJs KcQs KhJd KhJh KhJs KhQs KsJd KsJh KsJs KsQs Qc8c Qc9c QcTc QcTd QcTh QcTs Qd8d Qd9d QdTc QdTh QdTs Qh8h Qh9h QhTc QhTd QhTs Qs8s Qs9s QsTc QsTd QsTh QsTs Tc7c Tc8c Tc9c Td7d Td8d Td9d Th7h Th8h Th9h Ts7s Ts8s Ts9s')
        },
        {
          actions: [
            'check'
          ],
          combos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6c5c 6d5d 6d6c 6h5h 6h6c 6h6d 6s5s 6s6c 6s6d 6s6h 7c6c 7d6d 7d7c 7h6h 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8c6c 8c7c 8d6d 8d7d 8d8c 8h6h 8h7h 8h8c 8h8d 8s6s 8s7s 8s8c 8s8d 8s8h 9c7c 9c8c 9d7d 9d8d 9d9c 9h7h 9h8h 9h9c 9h9d 9s7s 9s8s 9s9c 9s9d 9s9h Ac2c Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c Ac9d Ac9h Ac9s AcJd AcJh AcJs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad2d Ad3d Ad4d Ad5d Ad6d Ad7d Ad8d Ad9c Ad9d Ad9h Ad9s AdJd AdJh AdJs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs As2s As3s As4s As5s As6s As7s As8s As9c As9d As9h As9s AsJd AsJh AsJs AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jd8d Jd9d JdTc JdTd JdTh JdTs Jh8h Jh9h JhJd JhTc JhTd JhTh JhTs Js8s Js9s JsJd JsJh JsTc JsTd JsTh JsTs Kc4c Kc5c Kc6c Kc7c Kc8c Kc9c KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc KcTd KcTh KcTs Kh4h Kh5h Kh6h Kh7h Kh8h Kh9h KhJd KhJh KhJs KhQc KhQd KhQh KhQs KhTc KhTd KhTh KhTs Ks4s Ks5s Ks6s Ks7s Ks8s Ks9s KsJd KsJh KsJs KsQc KsQd KsQh KsQs KsTc KsTd KsTh KsTs Qc8c Qc9c QcJd QcJh QcJs QcTc Qd8d Qd9d QdJd QdJh QdJs QdTd Qh8h Qh9h QhJd QhJh QhJs QhTh Qs9s QsJd QsJh QsJs QsTs Tc7c Tc8c Tc9c Td7d Td8d Td9d Th7h Th8h Th9h Ts8s Ts9s')
        }
      ]
    },
    {
      position: 'BTN',
      stackBb: 40,
      villainPosition: 'CO',
      board: [
        'As',
        'Ks',
        '4h'
      ],
      heroStackSize: 37.7,
      villainStackSize: 37.7,
      actionLine: 'preflop: CO raises 2.3bb, BTN calls 2.3bb; flop: CO checks, BTN checks; turn: CO checks',
      dealCombos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4d4c 4s4c 4s4d 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6c5c 6d5d 6d6c 6h5h 6h6c 6h6d 6s5s 6s6c 6s6d 6s6h 7c6c 7d6d 7d7c 7h6h 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8c6c 8c7c 8d6d 8d7d 8d8c 8h6h 8h7h 8h8c 8h8d 8s6s 8s7s 8s8c 8s8d 8s8h 9c7c 9c8c 9d7d 9d8d 9d9c 9h7h 9h8h 9h9c 9h9d 9s7s 9s8s 9s9c 9s9d 9s9h Ac2c Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c Ac9d Ac9h Ac9s AcJc AcJd AcJh AcJs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad2d Ad3d Ad4d Ad5d Ad6d Ad7d Ad8d Ad9c Ad9d Ad9h Ad9s AdJc AdJd AdJh AdJs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah2h Ah3h Ah5h Ah6h Ah7h Ah8h Ah9c Ah9d Ah9h Ah9s AhJc AhJd AhJh AhJs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs Jc8c Jc9c JcTc JcTd JcTh JcTs Jd8d Jd9d JdJc JdTc JdTd JdTh JdTs Jh8h Jh9h JhJc JhJd JhTc JhTd JhTh JhTs Js8s Js9s JsJc JsJd JsJh JsTc JsTd JsTh JsTs Kc4c Kc5c Kc6c Kc7c Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc KcTd KcTh KcTs Kd4d Kd5d Kd6d Kd7d Kd8d Kd9d KdJc KdJd KdJh KdJs KdQc KdQd KdQh KdQs KdTc KdTd KdTh KdTs Kh5h Kh6h Kh7h Kh8h Kh9h KhJc KhJd KhJh KhJs KhQc KhQd KhQh KhQs KhTc KhTd KhTh KhTs Qc8c Qc9c QcJc QcJd QcJh QcJs QcTc QcTd QcTh QcTs Qd8d Qd9d QdJc QdJd QdJh QdJs QdTc QdTd QdTh QdTs Qh8h Qh9h QhJc QhJd QhJh QhJs QhTc QhTd QhTh QhTs Qs8s Qs9s QsJc QsJd QsJh QsJs QsTc QsTd QsTh QsTs Tc7c Tc8c Tc9c Td7d Td8d Td9d Th7h Th8h Th9h Ts7s Ts8s Ts9s'),
      buckets: [
        {
          actions: [
            'bet_55pct'
          ],
          combos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4d4c 4s4c 4s4d 5s5c 5s5d 5s5h 6c5c 6d5d 6h5h 6s5s 6s6c 6s6d 7c6c 7d6d 7h6h 7s6s 8c6c 8c7c 8d6d 8d7d 8h6h 8h7h 8s6s 8s7s 9h7h 9h8h 9s7s 9s8s Ac4c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcQc AcQd AcQs AcTc AcTd AcTh AcTs Ad4d Ad6d Ad7d Ad8d Ad9d AdJc AdJd AdJh AdJs AdQc AdQd AdQs AdTc AdTd AdTh AdTs Ah6h Ah7h Ah8h Ah9h AhJc AhJd AhJh AhJs AhQh AhQs AhTc AhTd AhTh AhTs JcTc JcTs JdTd JdTs Jh8h JhTh Js8s Js9s JsTc JsTd JsTs KcJh KcQc KcQd KcQh KcTs KdJh KdQc KdQd KdQh KdTs KhQc KhQd KhQh KhTs QcJc QcJd QcJh QcJs QcTs QdJc QdJd QdJh QdJs QdTs QhJh QhTh Qs9s QsJc QsJd QsJh QsJs QsTc QsTd QsTh QsTs Th8h Th9h Ts7s Ts8s Ts9s')
        },
        {
          actions: [
            'bet_83pct'
          ],
          combos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4d4c 4s4c 4s4d 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6c5c 6d5d 6h5h 6s5s 6s6c 6s6d 6s6h 7c6c 7d6d 7h6h 7s6s 8c6c 8c7c 8d6d 8d7d 8h6h 8h7h 8s6s 8s7s 9c7c 9c8c 9d7d 9d8d 9h7h 9h8h 9s7s 9s8s Ac4c Ac9c Ac9d AcJc AcJd AcJh AcJs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad4d Ad9c Ad9d AdJc AdJd AdJh AdJs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah9h AhJc AhJd AhJh AhJs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs JcTc JcTd JcTh JcTs JdTc JdTd JdTh JdTs Jh8h JhTc JhTd JhTh JhTs Js8s Js9s JsTc JsTd JsTh JsTs Kc4c KcQh KcTs Kd4d KdQh KdTs KhQc KhQd KhTs QcJc QcJh QcJs QcTh QcTs QdJd QdJh QdJs QdTh QdTs QhJc QhJd QhJh QhJs QhTc QhTd QhTh QhTs Qs8s Qs9s QsJc QsJd QsJh QsJs QsTc QsTd QsTh QsTs Th7h Th8h Th9h Ts7s Ts8s Ts9s')
        },
        {
          actions: [
            'check'
          ],
          combos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6c5c 6d5d 6d6c 6h5h 6h6c 6h6d 6s5s 6s6c 6s6d 6s6h 7c6c 7d6d 7d7c 7h6h 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8c6c 8c7c 8d6d 8d7d 8d8c 8h6h 8h7h 8h8c 8h8d 8s6s 8s7s 8s8c 8s8d 8s8h 9c7c 9c8c 9d7d 9d8d 9d9c 9h7h 9h8h 9h9c 9h9d 9s7s 9s8s 9s9c 9s9d 9s9h Ac2c Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c Ac9d Ac9h Ac9s AcJc AcJd AcJh AcJs AcQs AcTc AcTd AcTh AcTs Ad2d Ad3d Ad4d Ad5d Ad6d Ad7d Ad8d Ad9c Ad9d Ad9h Ad9s AdJc AdJd AdJh AdJs AdQs AdTc AdTd AdTh AdTs Ah2h Ah3h Ah5h Ah6h Ah7h Ah8h Ah9c Ah9d Ah9h Ah9s AhJh AhJs AhQs AhTc AhTd AhTh AhTs Jc8c Jc9c JcTc JcTd JcTh JcTs Jd8d Jd9d JdJc JdTc JdTd JdTh JdTs Jh8h Jh9h JhJc JhJd JhTc JhTd JhTh JhTs Js8s Js9s JsJc JsJd JsJh JsTc JsTd JsTh JsTs Kc5c Kc6c Kc7c Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc KcTd KcTh KcTs Kd5d Kd6d Kd7d Kd8d Kd9d KdJc KdJd KdJh KdJs KdQc KdQd KdQh KdQs KdTc KdTd KdTh KdTs Kh5h Kh6h Kh7h Kh8h Kh9h KhJc KhJd KhJh KhJs KhQc KhQd KhQh KhQs KhTc KhTd KhTh KhTs Qc8c Qc9c QcJc QcJd QcJh QcJs QcTc QcTd QcTh QcTs Qd8d Qd9d QdJc QdJd QdJh QdJs QdTc QdTd QdTh QdTs Qh8h Qh9h QhJc QhJd QhJh QhJs QhTc QhTd QhTh QhTs Qs8s Qs9s QsJc QsJd QsJh QsJs QsTc QsTd QsTh QsTs Tc7c Tc8c Tc9c Td7d Td8d Td9d Th7h Th8h Th9h Ts7s Ts8s Ts9s')
        }
      ]
    }
  ]
};

export default pack;
