// Generated by scripts/import-ct-curriculum.ts. Do not edit by hand.
import type { RangePack } from '../types';

const expand = (value: string): string[] => value.split(' ');

const pack: RangePack = {
  slug: 'out-of-position-c-bet-co-btn-river-baseline-2',
  title: 'Out-of-position c-bet: CO vs BTN - River (30bb)',
  description: 'Board-aware continuation-bet and barrel practice out of position.',
  scenario: 'CBET_OOP',
  street: 'river',
  tier: 'advanced',
  methodology: 'gto_cev',
  source: {
    kind: 'brand_neutralized_snapshot_config',
    capturedAt: '2026-07-18',
    path: 'research/ct-trainer-2026-07-18/',
    sha256: '1989294bab18e492a2e94e224f4f59d6a2a170294abd54d2e5bb65a2e5c75e51'
  },
  cells: [
    {
      position: 'CO',
      stackBb: 30,
      villainPosition: 'BTN',
      board: [
        '6d',
        '4h',
        '3c',
        '9d',
        'Td'
      ],
      heroStackSize: 20.4,
      villainStackSize: 20.4,
      actionLine: 'preflop: CO raises 2.1bb, BTN calls 2.1bb; flop: CO bets 2.7bb, BTN calls 2.7bb; turn: CO bets 4.8bb, BTN calls 4.8bb',
      dealCombos: expand('3h3d 3s3d 3s3h 4d4c 4s4c 4s4d 5d5c 5h5c 5h5d 5s5d 6s5s 6s6c 6s6h 7c5c 7c6c 7d7c 7h5h 7h6h 7h7d 7s5s 7s6s 7s7c 7s7d 7s7h 8c7c 8d8c 8h7h 8h8c 8h8d 8s6s 8s8c 8s8d 8s8h 9c6c 9c7c 9c8c 9h6h 9h7h 9h8h 9h9c 9s8s Ac4c Ac5s Ac6c Ac6h Ac6s Ac7c Ac7d Ac7s Ac8d Ac9h Ac9s Ad4d Ad5s Ad6c Ad6h Ad6s Ad7d Ad7s Ad8s Ad9c Ad9h Ad9s AdKc AdKh AdQs Ah3h Ah5s Ah6c Ah6h Ah6s Ah7d Ah7h Ah7s Ah8d Ah9c Ah9s As3s As4s As5d As6c As6h As7c As7d As7h As7s As9c As9h AsKd Jc6c Jc7c Jc9c Jd7d Jd8d JdJc Jh6h Jh7h Jh9h JhJc JhJd Js7s JsJc JsJd JsJh Kc2c Kc4c Kc5c Kc6c Kc7c Kc8d Kc9c Kc9h KcJd KcJs KcQd Kd2d Kd4d Kd5d Kd7d Kd8s Kd9c Kd9h KdJs KdQc KdQh Kh2h Kh5h Kh6h Kh7h Kh8d Kh9c Kh9h KhJd KhJs KhQd KhTh Ks2s Ks4s Ks6s Ks7s Ks9s KsKc KsKd KsKh Qc5c Qc6c Qc7c Qc9c QcJc QcTc Qd5d Qd7d Qd8d QdJd QdQc Qh5h Qh6h Qh7h Qh9h QhJh QhQc QhQd QhTh Qs5s Qs6s Qs9s QsJs QsQc QsQd QsQh Tc7c Tc8c Tc9c Th7h Th8h Th9h ThTc Ts6s Ts7s Ts8s Ts9s TsTc TsTh'),
      buckets: [
        {
          actions: [
            'bet_10pct'
          ],
          combos: expand('7c5c 7d7c 7h5h 7h7d 7s7d 8c7c 8d8c 8h7h 8h8d 8s8c 8s8h 9c6c 9c7c 9c8c 9h6h 9h7h 9h8h 9h9c 9s8s Ac5s Ac6c Ac6h Ac8d Ac9h Ad6c Ad6h Ad6s Ah5s Ah6c Ah6h Ah9c As5d As7s AsKd Jc7c Jc9c Jd7d JdJc Jh7h Jh9h JhJd Kc9c Kc9h Kd2d Kd9c Kd9h KdJs Kh9c Kh9h Ks2s Ks9s Qc5c Qc9c Qd7d QdQc Qh5h Qh9h QhQd Qs5s Qs9s QsQc QsQd Tc9c Th9h Ts6s Ts9s')
        },
        {
          actions: [
            'bet_40pct'
          ],
          combos: expand('3h3d 3s3d 4d4c 4s4c 4s4d 7c5c 7h5h 7s5s 8c7c 8h7h Ac7d Ac8d Ac9s Ad4d Ad5s Ad7d Ad7s Ad8s Ad9c Ad9h Ad9s Ah7d Ah8d Ah9s As5d As7d As9c As9h Jc7c Jd7d Jd8d JdJc Jh7h JhJc JhJd JsJc JsJd JsJh Kc8d KcJd KcQd Kd2d Kd4d Kd7d Kd8s KdJs KdQc KdQh Kh8d KhJd KhQd KhTh Ks2s Ks9s KsKc KsKd KsKh Qc7c QcTc Qd7d Qd8d QdJd QdQc Qh7h QhQc QhQd QhTh Qs5s QsQc QsQd QsQh Tc7c Tc8c Th7h Th8h ThTc Ts6s Ts7s Ts8s TsTc TsTh')
        },
        {
          actions: [
            'check'
          ],
          combos: expand('3h3d 3s3d 3s3h 4s4c 5d5c 5h5c 5h5d 5s5d 6s5s 6s6c 6s6h 7c5c 7c6c 7d7c 7h5h 7h6h 7h7d 7s5s 7s6s 7s7c 7s7d 7s7h 8d8c 8h8c 8h8d 8s6s 8s8c 8s8d 8s8h 9c6c 9h6h Ac4c Ac6c Ac6h Ac6s Ac7c Ac7s Ac9h Ad6c Ad6h Ad6s AdKc AdKh AdQs Ah3h Ah6c Ah6h Ah6s Ah7h Ah7s Ah8d Ah9c As3s As4s As6c As6h As7c As7h As7s As9c As9h AsKd Jc6c Jc7c Jd7d JdJc Jh6h Jh7h JhJd Js7s Kc2c Kc4c Kc5c Kc6c Kc7c Kc9h KcJs Kd2d Kd5d Kh2h Kh5h Kh6h Kh7h Kh9c KhJs Ks2s Ks4s Ks6s Ks7s Qc5c Qc6c Qc7c QcJc Qd5d Qd7d Qd8d Qh5h Qh6h Qh7h QhJh Qs5s Qs6s QsJs Ts6s Ts8s Ts9s')
        }
      ]
    },
    {
      position: 'CO',
      stackBb: 30,
      villainPosition: 'BTN',
      board: [
        '6d',
        '4h',
        '3c',
        'Ks',
        'Ts'
      ],
      heroStackSize: 22.2,
      villainStackSize: 22.2,
      actionLine: 'preflop: CO raises 2.1bb, BTN calls 2.1bb; flop: CO bets 2.7bb, BTN calls 2.7bb; turn: CO bets 3bb, BTN calls 3bb',
      dealCombos: expand('3h3d 3s3d 3s3h 4s4c 4s4d 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6s5s 6s6c 6s6h 7c5c 7c6c 7d5d 7d7c 7h5h 7h6h 7h7c 7h7d 7s5s 7s6s 7s7c 7s7d 7s7h 8c7c 8d7d 8d8c 8h7h 8h8d 8s6s 8s8c 8s8d 8s8h 9h9c 9s9c 9s9d 9s9h Ac4c Ac5s Ac6c Ac6h Ac6s Ac7s Ac8s Ac9s AcJc AcKc AcKd AcKh AcQc AcQd AcQs Ad3d Ad4d Ad5s Ad6c Ad6h Ad6s Ad7s Ad8s AdKc AdKd AdKh AdQc AdQd AdQh AdQs Ah3h Ah5s Ah6c Ah6h Ah6s Ah7s Ah8s Ah9d Ah9s AhJh AhKc AhKd AhKh AhQc AhQd AhQs As3s As4s As5c As5d As5h As5s As6c As6h As6s As7c As7h As7s AsAd AsKc AsKd AsKh AsQh Jc6c Jc7c Jc9c Jd7d Jd9d Jh6h Jh7h Jh9h Js6s Js7s JsJc JsJd Kc2c Kc4c Kc5c Kc6c Kc7c Kc8d Kc8h Kc8s Kc9c Kc9d Kc9h KcJs KcQd KcQh KcTc Kd2d Kd4d Kd5d Kd7d Kd8c Kd8h Kd8s Kd9c Kd9d Kd9h KdJs KdQc KdQh KdTd Kh2h Kh5h Kh6h Kh7h Kh8c Kh8d Kh8s Kh9c Kh9d Kh9h KhJs KhQc KhQd KhTh Qc5c Qc6c Qc7c Qc9c QcJc Qd5d Qd7d Qd9d QdJd QdQc Qh5h Qh6h Qh7h Qh9h QhJh QhQc QhQd Qs5s Qs6s Qs9s QsJs QsQc QsQd QsQh Tc6c Tc7c Td7d Td9d TdTc Th7h ThTc ThTd'),
      buckets: [
        {
          actions: [
            'bet_10pct'
          ],
          combos: expand('3s3d 3s3h 4s4c 4s4d 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6s5s 6s6c 6s6h 7c5c 7c6c 7d5d 7d7c 7h5h 7h6h 7h7c 7h7d 7s5s 7s6s 7s7c 7s7d 7s7h 8s6s 8s8c 8s8d 8s8h 9h9c 9s9c 9s9d 9s9h Ac5s Ac6c Ac6h Ac6s Ad5s Ad6c Ad6h Ad6s AdKc AdKd AdKh Ah5s Ah6c Ah6h Ah6s AhJh As5s As6c As6h As6s AsKc AsKh Jc6c Jh6h Js6s KcJs KhJs Qc6c QcJc QdJd Qh6h QhJh Qs5s Qs6s QsJs Tc6c TdTc ThTc ThTd')
        },
        {
          actions: [
            'bet_40pct'
          ],
          combos: expand('5h5c 7c5c 7d5d 7h5h 7s5s 8c7c 8d7d 8d8c 8h7h 8h8d 8s8c 8s8d 8s8h 9h9c 9s9c 9s9d 9s9h Ac8s AcKd Ad5s Ad8s AdKd AdKh Ah8s AhKd AhKh As4s As5c As5d As5h AsKc AsKd AsKh Jc9c Jd9d Jh9h Js6s Js7s JsJc JsJd Kc2c Kc4c Kc5c Kc6c Kc7c Kc8d Kc8h Kc8s Kc9c Kc9d Kc9h KcJs KcQd KcQh KcTc Kd2d Kd4d Kd5d Kd7d Kd8c Kd8h Kd8s Kd9c Kd9d Kd9h KdJs KdQc KdQh KdTd Kh2h Kh5h Kh6h Kh7h Kh8c Kh8d Kh8s Kh9c Kh9d Kh9h KhJs KhQc KhQd KhTh Qc5c Qc6c Qc9c QcJc Qd5d Qd9d QdJd QdQc Qh5h Qh6h Qh9h QhJh QhQc QhQd Qs5s Qs6s Qs9s QsJs QsQc QsQd QsQh Tc7c Td7d Td9d Th7h')
        },
        {
          actions: [
            'check'
          ],
          combos: expand('3h3d 3s3d 3s3h 5d5c 5h5c 5h5d 6s6c 6s6h 7d7c 7h7c 7h7d 7s7d Ac4c Ac6c Ac6h Ac6s Ac7s Ac8s Ac9s AcJc AcKc AcKd AcKh AcQc AcQd AcQs Ad3d Ad4d Ad6c Ad6h Ad7s Ad8s AdKc AdKd AdKh AdQc AdQd AdQh AdQs Ah3h Ah6c Ah6h Ah7s Ah8s Ah9d Ah9s AhJh AhKc AhKd AhKh AhQc AhQd AhQs As3s As4s As6c As6h As7c As7h As7s AsAd AsKc AsKh AsQh Jc7c Jc9c Jd7d Jd9d Jh7h Jh9h Js6s Js7s KcJs KdJs KhJs Qc5c Qc7c Qc9c QcJc Qd5d Qd7d Qd9d Qh5h Qh7h Qh9h QhJh Qs5s')
        }
      ]
    },
    {
      position: 'CO',
      stackBb: 30,
      villainPosition: 'BTN',
      board: [
        '9h',
        '6d',
        '2h',
        '7c',
        'As'
      ],
      heroStackSize: 20.4,
      villainStackSize: 20.4,
      actionLine: 'preflop: CO raises 2.1bb, BTN calls 2.1bb; flop: CO bets 2.7bb, BTN calls 2.7bb; turn: CO bets 4.8bb, BTN calls 4.8bb',
      dealCombos: expand('4d4c 4s4c 4s4d 6h5h 6h6c 6s6c 6s6h 7d5d 7h6h 7h7d 7s5s 7s7h 8d7d 8d8c 8h8c 8h8d 8s7s 8s8d 8s8h 9c6c 9c8c 9d7d 9d8d 9s7s 9s8s 9s9c Ac3c Ac6c Ac6h Ac6s Ac7h Ac8h Ac9c Ac9d Ac9s AcJc AcJd AcKc AcKd AcKs AcTc AcTs Ad5d Ad5h Ad6s Ad7h Ad9c Ad9d Ad9s AdKc AdKs AdTc AdTh AdTs Ah4h Ah5h Ah6c Ah6h Ah6s Ah7d Ah7h Ah7s Ah9c Ah9s AhJc AhJs AhKc AhKs AhQc AhQs Jc9c Jc9s JcTh Jd8d JdJc JdTd JdTh Jh7h JhJc JhJd JhTc JhTd JhTh JhTs Js9c Js9s JsJc JsJd JsJh JsTh Kc2c Kc8h Kc9c Kc9d Kc9s KcQd KcTh Kd7d Kd8d Kd8h Kd9c Kd9d Kd9s KdKc KdQd KdTh Kh3h Kh4h Kh5h Kh8c Kh8d Kh8h Kh8s Kh9c Kh9s KhKc KhTc KhTd KhTs Ks2s Ks6s Ks8h Ks9c Ks9d Ks9s KsKc KsKd KsKh KsQd KsTh Qc9c Qc9d Qc9s QcTh Qd8d Qd9d QdQc QdTd QdTh Qh4h Qh5h Qh6h Qh7h Qh9c Qh9s QhJh QhQd QhTc QhTd QhTh QhTs Qs9c Qs9d Qs9s QsQd QsTh Tc8c Tc9c Tc9s Td7d Td8d TdTc Th6h Th7h Th8h Th9c Th9s ThTc ThTd Ts8s Ts9c Ts9s TsTc TsTd TsTh'),
      buckets: [
        {
          actions: [
            'all_in'
          ],
          combos: expand('6h6c 6s6c 6s6h 7h6h 7s7h 9c6c 9d7d 9s7s AcJc AcJd AdTh AhJc AhQc JcTh JdTd JhTc JhTs Kc8h Kd8h Kh8s Ks8h Qd8d QdTd Tc8c Td8d Th8h Ts8s')
        },
        {
          actions: [
            'bet_10pct'
          ],
          combos: expand('4d4c 4s4c 4s4d 6h5h Ac3c Ac6c Ac6h Ac6s Ac7h Ac8h Ac9c Ac9d Ac9s AcKc AcKd AcKs AcTc AcTs Ad5d Ad6s Ad9c Ad9d Ad9s AdKc AdKs AdTc AdTh AdTs Ah4h Ah5h Ah6c Ah6s Ah7d Ah7s Ah9c AhJc AhJs AhKc AhKs AhQc AhQs Jc9c Jc9s JdJc JdTd JhJc JhTc JhTs Js9c Js9s JsJc JsJd JsJh Kc2c Kc8h Kc9c Kc9d Kc9s KcQd Kd8d Kd9c Kd9d Kd9s KdKc KdQd Kh8s Kh9c Kh9s KhKc KhTc KhTs Ks2s Ks8h Ks9d Ks9s KsKc KsKd KsKh KsQd Qc9c Qc9d Qc9s QcTh Qd8d Qd9d QdQc Qh5h QhTc QhTs Qs9c Qs9d Qs9s QsQd Tc9c Tc9s TdTc ThTc Ts9c Ts9s TsTc TsTd TsTh')
        },
        {
          actions: [
            'check'
          ],
          combos: expand('4s4c 6h5h 6s6c 6s6h 7d5d 7h6h 7h7d 7s5s 7s7h 8d7d 8d8c 8h8c 8h8d 8s7s 8s8d 8s8h 9c6c 9c8c 9d7d 9d8d 9s8s 9s9c Ac6h Ac7h Ac9s AcTc AcTs Ad5d Ad5h Ad7h Ad9c Ad9s AdTc AdTs Ah5h Ah6h Ah6s Ah7h Ah9c Ah9s Jc9c Jc9s JcTh Jd8d JdTd JdTh Jh7h JhJc JhJd JhTc JhTd JhTh JhTs Js9c JsJh JsTh Kc9c Kc9d Kc9s KcTh Kd7d Kd8d Kd8h Kd9c KdQd KdTh Kh3h Kh4h Kh5h Kh8c Kh8d Kh8h Kh8s Kh9c KhTc KhTd KhTs Ks6s Ks9c Ks9d Ks9s KsTh QcTh Qd8d QdTh Qh4h Qh5h Qh6h Qh7h Qh9c Qh9s QhJh QhQd QhTc QhTd QhTh QhTs Qs9c Qs9d QsTh Tc9c Tc9s Td7d Th6h Th7h Th9c Th9s ThTc ThTd Ts8s Ts9c Ts9s TsTh')
        }
      ]
    },
    {
      position: 'CO',
      stackBb: 30,
      villainPosition: 'BTN',
      board: [
        '9h',
        '6d',
        '2h',
        '7c',
        'Qs'
      ],
      heroStackSize: 20.4,
      villainStackSize: 20.4,
      actionLine: 'preflop: CO raises 2.1bb, BTN calls 2.1bb; flop: CO bets 2.7bb, BTN calls 2.7bb; turn: CO bets 4.8bb, BTN calls 4.8bb',
      dealCombos: expand('4d4c 4s4c 4s4d 6h5h 6h6c 6s6c 6s6h 7d5d 7h6h 7h7d 7s5s 7s6s 7s7h 8d7d 8d8c 8h8c 8h8d 8s7s 8s8d 8s8h 9c6c 9c8c 9d7d 9d8d 9s7s 9s8s 9s9c Ac3c Ac6c Ac6h Ac6s Ac7h Ac8h Ac9c Ac9d Ac9s AcJc AcJd AcKc AcKd AcKs AcTc AcTs Ad5d Ad5h Ad6h Ad6s Ad7h Ad9c Ad9d Ad9s AdKc AdKs AdTc AdTh AdTs Ah4h Ah5h Ah6c Ah6h Ah6s Ah7d Ah7h Ah7s Ah9c Ah9s AhJc AhJs AhKc AhKs AhQc As3s As6c As6h As6s As7h As8h As9c As9d As9s AsJd AsJs AsKc AsKd AsKs AsTc AsTs Jc9c Jc9s JcTh Jd8d JdJc JdTd JdTh Jh7h JhJc JhJd JhTc JhTd JhTh JhTs Js9c Js9s JsJc JsJd JsJh JsTh Kc2c Kc8h Kc9c Kc9d Kc9s KcQd KcTh Kd7d Kd8d Kd8h Kd9c Kd9d Kd9s KdKc KdQd KdTh Kh3h Kh4h Kh5h Kh8c Kh8d Kh8h Kh8s Kh9c Kh9s KhKc KhTc KhTd KhTs Ks2s Ks6s Ks8h Ks9c Ks9d Ks9s KsKc KsKd KsKh KsTh Qc9c Qc9d Qc9s QcTh Qd8d Qd9d QdQc QdTd QdTh Qh4h Qh5h Qh6h Qh7h Qh9c Qh9s QhJh QhQd QhTc QhTd QhTh QhTs Tc8c Tc9c Tc9s Td7d Td8d TdTc Th6h Th7h Th8h Th9c Th9s ThTc ThTd Ts8s Ts9c Ts9s TsTc TsTd TsTh'),
      buckets: [
        {
          actions: [
            'bet_10pct'
          ],
          combos: expand('8d7d 8d8c 8h8c 8s8d 8s8h 9c6c 9c8c 9d7d 9d8d 9s7s 9s8s 9s9c Ac6c Ac7h Ac9c Ac9s AcKc AcKs AdTc AdTs Ah7d Ah7s As7h As9c As9s AsTs JhTc JhTd JhTs Kd7d Kh4h Kh5h KsKc Qc9d Qc9s Qd9d Qh9s Td7d Th9c Th9s')
        },
        {
          actions: [
            'bet_40pct'
          ],
          combos: expand('7s5s 9s9c Ac3c Ac9c Ac9s AcTc AcTs Ad5d Ad5h Ad7h Ad9c Ad9d Ad9s AdTc AdTs Ah4h Ah5h Ah6c Ah6h Ah6s Ah7h Ah9c Ah9s AhQc As3s As9c AsTc AsTs Jc9c Jc9s JcTh Jd8d JdJc JdTd JhJc JhJd JhTc JhTs Js9c Js9s JsJc JsJd JsJh JsTh Kc8h Kc9c Kc9d Kc9s KcQd KcTh Kd8d Kd8h Kd9c Kd9d Kd9s KdKc KdQd Kh3h Kh4h Kh8c Kh8s Kh9c Kh9s KhKc KhTc KhTs Ks8h Ks9c Ks9d Ks9s KsKc KsKd KsKh KsTh Qc9c Qc9d Qc9s QcTh Qd8d Qd9d QdQc QdTd QdTh Qh4h Qh5h Qh6h Qh7h Qh9c Qh9s QhJh QhQd QhTc QhTd QhTh QhTs Tc8c Tc9c Tc9s Td8d TdTc Th8h Th9c Th9s ThTc ThTd Ts8s Ts9c Ts9s TsTc TsTd TsTh')
        },
        {
          actions: [
            'check'
          ],
          combos: expand('4d4c 4s4c 4s4d 6h5h 6h6c 6s6c 6s6h 7d5d 7h6h 7h7d 7s5s 7s6s 7s7h 8d7d 8h8c 8h8d 8s7s 8s8h 9c6c 9d7d 9s7s Ac6c Ac6h Ac6s Ac7h Ac8h Ac9c Ac9d Ac9s AcJc AcJd AcKc AcKd AcKs Ad6h Ad6s Ad7h AdKc AdKs AdTc AdTh AdTs Ah6c Ah6h Ah6s Ah7s AhJc AhJs AhKc AhKs As6c As6h As6s As7h As8h As9c As9d As9s AsJd AsJs AsKc AsKd AsKs JcTh JdTh Jh7h JhTd JhTh JsTh Kc2c KcTh Kd7d KdTh Kh8d Kh8h KhTc KhTd KhTs Ks2s Ks6s KsKc KsTh Qc9d Qh5h Qh7h Td7d Th6h Th7h')
        }
      ]
    },
    {
      position: 'CO',
      stackBb: 30,
      villainPosition: 'BTN',
      board: [
        'Ah',
        '9d',
        '3c',
        'Tc',
        '2s'
      ],
      heroStackSize: 18.7,
      villainStackSize: 18.7,
      actionLine: 'preflop: CO raises 2.1bb, BTN calls 2.1bb; flop: CO bets 1.7bb, BTN calls 1.7bb; turn: CO bets 7.5bb, BTN calls 7.5bb',
      dealCombos: expand('3h3d 3s3d 3s3h 4h4d 4s4d 4s4h 5h4h 5h5c 5s4s 5s5c 5s5h 6c5c 7c5c 7c6c 7d6d 7h6h 7s6s 8c6c 8d7d 8h6h 8h7h 8s7s Ac6c Ac9c Ac9h Ac9s AcJc AcJd AcJh AcJs AcKc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTd AcTs Ad3d Ad8c Ad9c Ad9h AdJc AdJd AdJh AdJs AdKc AdKd AdKh AdKs AdQc AdQd AdQh AdQs AdTd AdTh AdTs As7c As8c As9c As9h As9s AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTd AsTh Jc7c Jc8c Jd7d Jd8d Jh7h Jh8h Js8s Kc2c Kc4c Kc5c Kc6c Kc8c KcJs KdJs Ks3s KsJs Qc4c Qc5c Qc8c QcJc QcJd QcJh QcJs Qd8d QdJc QdJd QdJh QdJs Qh8h QhJc QhJd QhJh QhJs QsJc QsJd QsJh QsJs Td7d Td9s Th9h Th9s Ts9c Ts9h Ts9s'),
      buckets: [
        {
          actions: [
            'all_in'
          ],
          combos: expand('3h3d 3s3d 3s3h 5h4h 5s4s 6c5c 7c5c 7c6c 7d6d 7h6h 7s6s 8c6c 8d7d 8h6h 8h7h 8s7s Ac9c Ac9h Ac9s AcJc AcJd AcJs AcKc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTd AcTs Ad3d Ad9c Ad9h AdJc AdJd AdJh AdJs AdKc AdKd AdKh AdKs AdQc AdQd AdQh AdQs AdTd AdTh AdTs As9s AsJd AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTd AsTh Jd7d Jd8d Jh8h Qc4c QdJd QsJd QsJs Td9s Th9h Th9s Ts9c Ts9h Ts9s')
        },
        {
          actions: [
            'bet_40pct'
          ],
          combos: expand('7c6c Ac6c AcJc AcJd AcJh AcJs Ad8c AdJh AdJs As7c As8c AsJc AsJd AsJh AsJs AsQh AsQs Jc8c Jh8h QdJd QhJd QsJd QsJs')
        },
        {
          actions: [
            'check'
          ],
          combos: expand('4h4d 4s4d 4s4h 5h5c 5s5c 5s5h 8c6c 8h7h Ac9c Ac9h AcKs AcTs Ad9c Ad9h AdKs AdTs As9c As9h AsKd AsKh AsKs AsTd AsTh Jc7c Jc8c Jh7h Jh8h Js8s Kc2c Kc4c Kc5c Kc6c Kc8c KcJs KdJs Ks3s KsJs Qc4c Qc5c Qc8c QcJc QcJd QcJh QcJs Qd8d QdJc QdJd QdJh QdJs Qh8h QhJc QhJd QhJh QhJs QsJc QsJd QsJh QsJs Td7d')
        }
      ]
    },
    {
      position: 'CO',
      stackBb: 30,
      villainPosition: 'BTN',
      board: [
        'Ah',
        '9d',
        '3c',
        'Tc',
        'Qc'
      ],
      heroStackSize: 18.7,
      villainStackSize: 18.7,
      actionLine: 'preflop: CO raises 2.1bb, BTN calls 2.1bb; flop: CO bets 1.7bb, BTN calls 1.7bb; turn: CO bets 7.5bb, BTN calls 7.5bb',
      dealCombos: expand('3h3d 3s3d 3s3h 4h4d 4s4d 4s4h 5h5c 5s4s 5s5c 5s5h 6c5c 7c5c 7c6c 7d6d 7h6h 7s6s 8c6c 8d7d 8h6h 8h7h 8s7s Ac6c Ac9c Ac9h Ac9s AcJc AcJd AcJh AcJs AcKc AcKd AcKh AcKs AcQd AcQh AcQs AcTd AcTh AcTs Ad3d Ad8c Ad9c Ad9h AdJc AdJd AdJh AdJs AdKc AdKd AdKh AdKs AdQd AdQh AdQs AdTd AdTh AdTs As7c As8c As9c As9h As9s AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsKs AsQd AsQh AsQs AsTd AsTh Jc7c Jc8c Jd7d Jd8d Jh7h Jh8h Js8s Kc2c Kc4c Kc5c Kc6c Kc8c KdJs Ks3s KsJs Qd8d QdJc QdJd QdJh QdJs Qh8h QhJc QhJd QhJh QhJs QsJc QsJd QsJh QsJs Td7d Td9s Th9h Th9s Ts9c Ts9h Ts9s'),
      buckets: [
        {
          actions: [
            'all_in'
          ],
          combos: expand('3h3d 3s3d 3s3h 4h4d 4s4d 4s4h 5h5c 5s5c 6c5c 7c5c 7c6c 7h6h 8c6c 8d7d 8h6h 8h7h AcTs AdTh AdTs AsTh Jc7c Jc8c Jd7d Jd8d Jh8h Js8s Kc2c Kc4c Kc5c Kc6c Kc8c KdJs Ks3s KsJs QsJc Ts9c')
        },
        {
          actions: [
            'bet_40pct'
          ],
          combos: expand('4h4d 4s4d 4s4h 5s4s 5s5h 7d6d 7h6h 7s6s 8d7d Ac6c Ac9c Ac9h Ac9s AcJc AcKc AcKs AcQd AcQs AcTd AcTh AcTs Ad9c Ad9h AdTd As9s AsTd AsTh Jc7c Jc8c Jd8d Jh8h Ks3s KsJs QsJc QsJh QsJs Ts9c')
        },
        {
          actions: [
            'check'
          ],
          combos: expand('7d6d 7s6s 8d7d 8s7s AcJc AcJd AcJh AcJs AcKc AcKd AcKh AcKs AcQd AcQh AcQs Ad3d Ad8c Ad9c AdJc AdJd AdJh AdJs AdKc AdKd AdKh AdKs AdQd AdQh AdQs AdTs As7c As8c As9c As9h As9s AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsKs AsQd AsQh AsQs AsTd Jh7h Qd8d QdJc QdJd QdJh QdJs Qh8h QhJc QhJd QhJh QhJs QsJc QsJd QsJh QsJs Td7d Td9s Th9h Th9s Ts9h Ts9s')
        }
      ]
    },
    {
      position: 'CO',
      stackBb: 30,
      villainPosition: 'BTN',
      board: [
        'Kh',
        '9d',
        '8d',
        'Ad',
        '2c'
      ],
      heroStackSize: 19.5,
      villainStackSize: 19.5,
      actionLine: 'preflop: CO raises 2.1bb, BTN calls 2.1bb; flop: CO bets 4.5bb, BTN calls 4.5bb; turn: CO bets 3.9bb, BTN calls 3.9bb',
      dealCombos: expand('5c4c 5d4d 5h4h 5s4s 6c5c 6d5d 6h5h 6s5s 7c6c 7h6h 7s6s 8c7c 8s7s 9c6c 9c7c 9s6s 9s7s Ac9c Ac9s AcJd AcKc AcKd AcKs AcQs Ah6h Ah7h Ah9c Ah9s AhAc AhJd AhJh AhKc AhKd AhKs AhTh As9c As9s AsAh AsJd AsKc AsKd AsKs AsQc JcTd Jd6d JdJc JdTc JdTh JdTs JhJd JhTd JhTh JsJd JsTd Kc7c Kc8c Kc8s Kc9h Kc9s KcJd KcJh KcJs KcQc KcQh KcQs KcTc KcTd KcTh KcTs Kd8c Kd8h Kd8s Kd9h KdJc KdJh KdJs KdQc KdQh KdQs KdTc KdTd KdTh KdTs Ks7s Ks8c Ks8s Ks9c Ks9h KsJc KsJd KsJh KsQc KsQh KsQs KsTc KsTd KsTh KsTs QcJc QcJs QcTd Qd4d Qd5d Qd7d QdTc QdTh QdTs Qh9c Qh9s QhTd QsJc QsJs QsTd Tc7c Th7h Ts7s'),
      buckets: [
        {
          actions: [
            'all_in'
          ],
          combos: expand('5c4c 5d4d 5h4h 5s4s 6d5d 6h5h 7h6h Ac9c Ac9s Ah6h Ah7h Ah9c Ah9s AhTh As9c As9s Jd6d Kc8c Kc8s Kd8h Kd9h Ks8c Ks8s Qd4d Qd5d Qd7d QdTc QdTh QdTs')
        },
        {
          actions: [
            'bet_40pct'
          ],
          combos: expand('6c5c 6h5h 6s5s 7c6c 7h6h 7s6s AcJd AcKc AcKd AcKs AcQs Ah6h Ah7h Ah9c Ah9s AhAc AhJd AhJh AhKc AhKd AhKs AhTh AsAh AsJd AsKc AsKd AsKs AsQc Jd6d JdTc JdTh JdTs JhTd JhTh Kc8c KcJd KcJh KcJs KcQc KcQh KcQs Kd8c Kd8s KdJc KdJh KdJs KdQc KdQh KdQs KdTd Ks8s KsJc KsJd KsJh KsQc KsQh KsQs Qd4d Qd5d Qd7d QdTc QdTs QhTd Tc7c Th7h Ts7s')
        },
        {
          actions: [
            'check'
          ],
          combos: expand('8c7c 8s7s 9c6c 9c7c 9s6s 9s7s AcKc AcKs AsKc AsKs JcTd JdJc JhJd JhTd JhTh JsJd JsTd Kc7c Kc8c Kc8s Kc9h Kc9s KcJs KcQc KcQs KcTc KcTd KcTh KcTs Kd8h Kd9h KdTc KdTh KdTs Ks7s Ks8c Ks8s Ks9c Ks9h KsJc KsQc KsQs KsTc KsTd KsTh KsTs QcJc QcJs QcTd Qd4d Qd7d QdTc QdTh QdTs Qh9c Qh9s QsJc QsJs QsTd')
        }
      ]
    },
    {
      position: 'CO',
      stackBb: 30,
      villainPosition: 'BTN',
      board: [
        'Kh',
        '9d',
        '8d',
        'Ad',
        'Jh'
      ],
      heroStackSize: 19.5,
      villainStackSize: 19.5,
      actionLine: 'preflop: CO raises 2.1bb, BTN calls 2.1bb; flop: CO bets 4.5bb, BTN calls 4.5bb; turn: CO bets 3.9bb, BTN calls 3.9bb',
      dealCombos: expand('5c4c 5d4d 5h4h 5s4s 6c5c 6d5d 6h5h 6s5s 7c6c 7h6h 7s6s 8c7c 8s7s 9c6c 9c7c 9s6s 9s7s Ac9c Ac9s AcJd AcKc AcKd AcKs AcQs Ah6h Ah7h Ah9c Ah9s AhAc AhJd AhKc AhKd AhKs AhTh As9c As9s AsAh AsJd AsKc AsKd AsKs AsQc JcTd Jd6d Jd7d JdJc JdTc JdTh JdTs JsJd JsTd Kc7c Kc8c Kc8s Kc9h Kc9s KcJc KcJd KcJs KcQc KcQh KcQs KcTc KcTd KcTh KcTs Kd8c Kd8h Kd8s Kd9h KdJc KdJs KdQc KdQh KdQs KdTc KdTd KdTh KdTs Ks7s Ks8c Ks8s Ks9c Ks9h KsJc KsJd KsJs KsQc KsQh KsQs KsTc KsTd KsTh KsTs QcJc QcJs QcTd Qd4d Qd5d Qd7d QdTc QdTh QdTs Qh9c Qh9s QhTd QsJc QsJs QsTd Tc7c Th7h Ts7s'),
      buckets: [
        {
          actions: [
            'all_in'
          ],
          combos: expand('5c4c 5d4d 5h4h 5s4s 6c5c 6d5d 6h5h 6s5s 7h6h 8c7c 8s7s 9c6c 9s6s Ac9c Ac9s AcJd AcKc AcKd AcKs AcQs Ah7h Ah9c Ah9s AhAc As9c As9s AsAh AsJd AsKc AsKd AsKs AsQc Jd6d Jd7d JdJc JdTc JdTs JsJd KdTd QcJs QcTd Qd4d Qd5d Qd7d QdTc QdTs Qh9c Qh9s QhTd QsJc QsTd Tc7c Th7h Ts7s')
        },
        {
          actions: [
            'bet_10pct'
          ],
          combos: expand('7c6c 7s6s AcKc AcKs Ah7h AhAc AhJd AhKc AhKd AhKs AhTh AsAh AsKc AsKs JdTc JdTs Kc8c Kc8s Kc9h Kc9s KcJc KcJs KcQc KcQs Kd8c Kd8h Kd8s Kd9h KdQh KdTc KdTs Ks8c Ks8s Ks9c Ks9h KsJc KsJs KsQc KsQs Qd4d Qd7d')
        },
        {
          actions: [
            'check'
          ],
          combos: expand('7c6c 7s6s 9c7c 9s7s AcKd Ah6h Ah7h AhJd AhKd AhTh AsKd JcTd JdJc JdTc JdTh JdTs JsJd JsTd Kc7c Kc9h KcJd KcJs KcQc KcQh KcQs KcTc KcTd KcTh KcTs KdJc KdJs KdQc KdQh KdQs KdTc KdTd KdTh KdTs Ks7s Ks9h KsJc KsJd KsQc KsQh KsQs KsTc KsTd KsTh KsTs QcJc QcJs Qd4d Qd5d Qd7d QdTc QdTh QdTs QsJc QsJs')
        }
      ]
    },
    {
      position: 'CO',
      stackBb: 30,
      villainPosition: 'BTN',
      board: [
        'Qh',
        'Qd',
        '8h',
        '7h',
        '6s'
      ],
      heroStackSize: 20.4,
      villainStackSize: 20.4,
      actionLine: 'preflop: CO raises 2.1bb, BTN calls 2.1bb; flop: CO bets 2.7bb, BTN calls 2.7bb; turn: CO bets 4.8bb, BTN calls 4.8bb',
      dealCombos: expand('3d3c 3s3c 3s3d 4s4c 7d6d 9d6d 9h9c 9h9d 9s9h Ac8c Ac8d Ac8s AcQc AcQs Ad7c Ad7d Ad7s Ah3h Ah4h Ah5c Ah5d Ah5h Ah5s Ah6c Ah6d Ah6h Ah8c Ah8d Ah8s Ah9h AhAc AhJh AhKh AhQc AhQs As8c As8d As8s AsAh AsQc AsQs Jc9h JcTh Jd9c Jd9d Jd9h Jd9s Jh9c Jh9d Jh9h Jh9s JhTc JhTd JhTh JhTs Js9h JsJc JsTh Kc9h KcJh KcQc KcQs KcTh Kd9h KdJh KdKc KdQc KdQs KdTh Kh2h Kh4h Kh5h Kh6h Kh9c Kh9d Kh9s KhJh KhKc KhKd KhQc KhQs KhTc KhTd KhTh KhTs Ks9h KsJh KsKc KsKd KsKh KsQc KsQs KsTh Qc4c Qc5c Qc6c Qc9c Qc9h Qc9s QcJc QcJs QcTc QcTs Qs4s Qs5s Qs9c Qs9h Qs9s QsJc QsJs QsTc QsTs Tc9c Tc9d Tc9h Tc9s Td9c Td9d Td9s Th9c Th9d Th9h Th9s ThTc Ts9c Ts9d Ts9h Ts9s TsTh'),
      buckets: [
        {
          actions: [
            'all_in'
          ],
          combos: expand('Ah5c Ah5d Ah5h Ah5s Ah6h Ah9h AhJh AhKh Jc9h JcTh Jh9c Jh9d Jh9h Jh9s JhTc JhTh JhTs Js9h JsTh Kc9h KcQc KcQs KcTh Kd9h KdQc KdQs Kh2h Kh4h Kh5h Kh6h Kh9c Kh9d Kh9s KhJh KhTc KhTd KhTh KhTs Ks9h KsQc KsQs KsTh QcJc QcJs QsJc QsJs Tc9c Tc9d Tc9h Tc9s Td9c Td9d Td9s Th9c Th9d Th9h Th9s Ts9c Ts9d Ts9h Ts9s')
        },
        {
          actions: [
            'bet_40pct'
          ],
          combos: expand('Ac8d Ah5c Ah5s AhAc AhQc AhQs As8d AsAh Jc9h Jd9c Jd9d Jd9s Jh9c Jh9s Js9h JsJc Kc9h KcQc KcTh Kd9h KdKc Kh9c Kh9s KhKd KhQc KhQs KhTc KhTd KhTs Ks9h KsKc KsKd KsQc KsTh Qc4c Qc5c Qc9c Qc9h Qc9s QcJc QcJs QcTc QcTs Qs4s Qs5s Qs9c Qs9h Qs9s QsJc QsJs QsTc QsTs Td9d Th9c Th9d Th9h Th9s')
        },
        {
          actions: [
            'check'
          ],
          combos: expand('3d3c 3s3c 3s3d 4s4c 7d6d 9d6d 9h9c 9h9d 9s9h Ac8c Ac8d Ac8s AcQc AcQs Ad7c Ad7d Ad7s Ah3h Ah4h Ah5d Ah5h Ah6c Ah6d Ah6h Ah8c Ah8d Ah8s As8c As8d As8s AsQc AsQs JcTh Jd9d Jd9h Jh9c Jh9d Jh9s JhTc JhTd JhTs JsJc JsTh KcJh KcQc KcQs KcTh KdJh KdQs KdTh Kh9c Kh9d Kh9s KhKc KhKd KhTc KhTd KhTs KsJh KsKh KsQc KsQs KsTh Qc4c Qc6c QcJc QcJs Tc9d ThTc Ts9c Ts9d TsTh')
        }
      ]
    },
    {
      position: 'CO',
      stackBb: 30,
      villainPosition: 'BTN',
      board: [
        'Qh',
        'Qd',
        '8h',
        'As',
        '7h'
      ],
      heroStackSize: 17.1,
      villainStackSize: 17.1,
      actionLine: 'preflop: CO raises 2.1bb, BTN calls 2.1bb; flop: CO bets 2.7bb, BTN calls 2.7bb; turn: CO bets 8.1bb, BTN calls 8.1bb',
      dealCombos: expand('4s4c 5d5c 5s5d 6h5h 8c6c 8s6s 9d8d Ac7c AcJc AcJh AcJs AcTd Ad9h AdKc AdKd AdKh AdKs AdTc AdTs Ah9h AhJh AhKh Jc8c Jc9h JcTc JcTd JcTh JcTs Jd9d JdTc JdTd JdTs Jh6h JhJd JhTc JhTh JhTs Js8s Js9h JsTc JsTd JsTh JsTs KcJd KcJh KcQc KcQs KcTh KdJc KdJd KdJs KdQc KdQs Kh2h Kh3h Kh4h Kh5h Kh6h KhJh KhQc KhQs KsJd KsJh KsQc KsQs KsTh Qc4c Qc5c Qc6c Qc7c Qc9c Qc9d Qc9h Qc9s QcJc QcJs QcTc QcTd QcTs Qs4s Qs5s Qs6s Qs7s Qs9c Qs9d Qs9h Qs9s QsJc QsJs QsTc QsTd QsTs Tc9c Tc9h Td9d Th6h Th9h Ts9h Ts9s'),
      buckets: [
        {
          actions: [
            'all_in'
          ],
          combos: expand('4s4c 5d5c 5s5d 8c6c 8s6s 9d8d Jc9h Jh6h JhTh KcJh KcTh Kh2h Kh3h Kh4h Kh5h Kh6h KhJh KsJh KsQs KsTh QcTc QcTs QsJc QsJs QsTc QsTs Tc9h Th6h Th9h Ts9h')
        },
        {
          actions: [
            'bet_40pct'
          ],
          combos: expand('4s4c 5d5c 5s5d 8c6c AdKc AdKd AdKh AdKs AdTc AdTs Jc9h JdTc JdTs Js9h KcJh KcQc KcQs KcTh KdJc KdJs KdQc KdQs KhQc KhQs KsJh KsQc KsQs KsTh Qc4c Qc5c Qc6c Qc7c Qc9c Qc9d Qc9h Qc9s QcJc QcJs QcTc QcTd QcTs Qs4s Qs5s Qs6s Qs7s Qs9c Qs9d Qs9h Qs9s QsJs QsTc QsTd QsTs Tc9c Tc9h Td9d Th9h Ts9h Ts9s')
        },
        {
          actions: [
            'check'
          ],
          combos: expand('6h5h Ac7c AcJc AcJh AcJs AcTd Ad9h AdKc AdKd AdKs AdTc AdTs Ah9h AhJh AhKh Jc8c JcTc JcTd JcTh JcTs Jd9d JdTc JdTd JdTs JhJd JhTc JhTs Js8s JsTc JsTd JsTh JsTs KcJd KdJc KdJd KdJs Kh2h Kh4h Kh5h Kh6h KhQs KsJd Qc9c Qc9d Qc9s Qs9c Qs9d Qs9s')
        }
      ]
    },
    {
      position: 'CO',
      stackBb: 30,
      villainPosition: 'BTN',
      board: [
        'Tc',
        '7d',
        '6s',
        '8s',
        'Kh'
      ],
      heroStackSize: 23.7,
      villainStackSize: 23.7,
      actionLine: 'preflop: CO raises 2.1bb, BTN calls 2.1bb; flop: CO bets 1.7bb, BTN calls 1.7bb; turn: CO bets 2.5bb, BTN calls 2.5bb',
      dealCombos: expand('5d4d 5s4s 6c5c 6d5d 6h6c 7c5c 7c6c 7h7c 7s5s 7s7c 7s7h 8c6c 8c7c 8d6d 8d8c 8h8c 8h8d 9c8c 9h7h 9h8h 9h9c 9h9d 9s7s 9s9h Ac6c Ac7c Ac7h Ac7s Ac8h Ac9d Ac9h Ac9s AcJc AcKd AcKs AcQc AcQd AcQh AcQs AcTd AcTh AcTs Ad6d Ad7h Ad7s Ad8d Ad9s AdAc AdJd AdKc AdKs AdQd AdQh AdQs AdTd AdTh AdTs Ah6h Ah8c Ah8d Ah8h Ah9d Ah9h Ah9s AhAc AhAd AhJh AhKc AhKs AhQh As6c As6h As7c As7h As7s As8c As8d As9c As9d As9s AsAc AsAd AsAh AsJs AsKc AsKd AsQd AsQh AsQs AsTd AsTh AsTs Jc7c Jc8c Jc9c JcTd JcTh JcTs Jd8d Jd9d Jd9h Jd9s JdTd Jh9d Jh9h Jh9s JhJc JhTh Js9d Js9h Js9s JsJh JsTs Kc7c Kc8c Kc8d Kc9c KcJc KcQc KcTd KcTs Kd8d Kd9d KdJd KdKc KdQd KdTh KdTs Ks8d Ks9s KsJs KsKc KsKd KsQs KsTd Qc6c Qc8c Qc9c QcTd QcTh QcTs Qd8d Qd9d QdJd QdTd Qh8h QhQd QhTd QhTh QhTs Qs9s QsJs QsQd QsQh QsTs Td8d Td9s Th7h Th9d Th9h Th9s Ts9d TsTd'),
      buckets: [
        {
          actions: [
            'bet_10pct'
          ],
          combos: expand('7c6c 8c6c 8c7c 8d6d 9s7s AcJc AcKd AcKs AcQc AdAc AdJd AdKc AdKs AhAc AhAd AhKc AhKs AhQh AsAc AsAd AsAh AsJs AsKc AsKd Jc7c Jc9c Jd9d Jd9h Jd9s Jh9h Js9d Js9h Js9s JsJh Kc7c Kc9c KcJc KcQc Kd9d KdJd KdKc KdQd KsJs KsQs Qc9c Qd9d Td8d')
        },
        {
          actions: [
            'bet_40pct'
          ],
          combos: expand('5d4d 5s4s 6c5c 6d5d 6h6c 7c5c 7h7c 7s7c 7s7h 8d8c 8h8c 8h8d 9c8c 9h7h 9h8h 9h9c 9h9d 9s7s 9s9h Ac9d Ac9h Ac9s AcJc AcQc AcQd AcQs Ad9s AdAc AdJd AdQd AdQs Ah6h Ah9d Ah9h Ah9s AhJh AhQh As9c As9d As9s AsAh AsJs AsQd AsQs Jc7c Jc9c Jd9d Jh9d Js9d Js9s Kc8c Kc8d KcTd KcTs Kd8d Kd9d KdKc KdTh KdTs Ks8d Ks9s KsKc KsKd KsQs KsTd Qc6c Qc9c Qd9d QdJd Qs9s QsJs Th7h Th9d Th9h Th9s Ts9d TsTd')
        },
        {
          actions: [
            'check'
          ],
          combos: expand('6c5c 7c5c 7c6c 7s5s 9c8c 9h8h Ac6c Ac7c Ac7h Ac7s Ac8h AcQh AcTd AcTh AcTs Ad6d Ad7h Ad7s Ad8d AdQh AdTd AdTh AdTs Ah6h Ah8c Ah8d Ah8h Ah9d Ah9h Ah9s AhAc AhAd AhKc AhKs As6c As6h As7c As7h As7s As8c As8d AsAh AsQh AsTd AsTh AsTs Jc7c Jc8c Jc9c JcTd JcTh JcTs Jd8d Jd9d Jd9h Jd9s JdTd Jh9d Jh9h Jh9s JhJc JhTh Js9s JsJh JsTs KcQc KdKc KdQd Qc8c QcTd QcTh QcTs Qd8d QdTd Qh8h QhQd QhTd QhTh QhTs QsQd QsQh QsTs Td8d Td9s Th9d Th9h Th9s Ts9d TsTd')
        }
      ]
    },
    {
      position: 'CO',
      stackBb: 30,
      villainPosition: 'BTN',
      board: [
        'Tc',
        '7d',
        '6s',
        'Qd',
        'Js'
      ],
      heroStackSize: 18.7,
      villainStackSize: 18.7,
      actionLine: 'preflop: CO raises 2.1bb, BTN calls 2.1bb; flop: CO bets 1.7bb, BTN calls 1.7bb; turn: CO bets 7.5bb, BTN calls 7.5bb',
      dealCombos: expand('3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5s4s 5s5c 5s5d 6h6c 9c8c 9h8h Ac2c Ac3c Ac4c Ac5c Ac5d Ac5h Ac5s Ac9d AcKd AcKs AcQc AcQh AcQs Ad5c Ad5h Ad5s Ad8d Ad8s AdAc AdJd AdKc AdKs AdQh AdQs AdTd AdTh Ah4h Ah5c Ah5d Ah5h Ah5s Ah8c Ah8d Ah8h AhAc AhAd AhKs As2s As3s As4s As5c As5d As5h As5s As9d As9s AsAc AsAd AsAh AsKd AsQh AsTd Jc9c Jd8d Jd9h Jd9s Jh6h Jh9d Jh9h Kc9c KcJc KcQc KcTd Kd8d KdJd KdKc KdTh KdTs Kh7h Kh9c Kh9d Kh9s KhKc KhKd Ks9s KsKc KsKd KsKh KsQs KsTd Qc6c Qc7c Qc8c Qc9c QcTd QcTh QcTs Qh8h Qh9h QhTd QhTh QhTs Qs9s QsTs Td8d Th7h Th9h Ts9d'),
      buckets: [
        {
          actions: [
            'bet_10pct'
          ],
          combos: expand('AcQc KcQc KcTd KhKd KsKh KsQs Qc8c Qc9c QcTh QcTs Qh8h Qs9s')
        },
        {
          actions: [
            'bet_40pct'
          ],
          combos: expand('3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5s4s 5s5c 5s5d 6h6c 9c8c 9h8h Ac2c Ac3c Ac4c Ac5c Ac5d Ac5h Ac5s Ac9d AcKd AcKs Ad5c Ad5h Ad5s Ad8d Ad8s AdAc AdKc AdKs AdTh Ah4h Ah5c Ah5d Ah5h Ah5s Ah8c Ah8d Ah8h AhAc AhAd AhKs As2s As3s As4s As5c As5d As5h As5s As9d As9s AsAc AsAd AsAh AsKd Jh6h Kc9c KcTd Kd8d KdKc KdTh KdTs Kh7h Kh9c Kh9d Kh9s Ks9s KsKc KsKd KsTd Qc6c Qc7c QcTd QhTd QhTh QhTs QsTs Td8d Th7h Th9h Ts9d')
        },
        {
          actions: [
            'check'
          ],
          combos: expand('AcKd AcKs AcQc AcQh AcQs AdJd AdQh AdQs AdTd AsQh AsTd Jc9c Jd8d Jd9h Jd9s Jh6h Jh9d Jh9h KcJc KdJd KdKc KdTs Kh9s KhKc KhKd KsKc KsKd KsKh KsQs Qc9c QcTs Qh8h Qh9h QhTh')
        }
      ]
    }
  ]
};

export default pack;
