// Generated by scripts/import-ct-curriculum.ts. Do not edit by hand.
import type { RangePack } from '../types';

const expand = (value: string): string[] => value.split(' ');

const pack: RangePack = {
  slug: 'out-of-position-c-bet-utg-btn-flop-baseline',
  title: 'Out-of-position c-bet: UTG vs BTN - Flop (100bb)',
  description: 'Board-aware continuation-bet and barrel practice out of position.',
  scenario: 'CBET_OOP',
  street: 'flop',
  tier: 'advanced',
  methodology: 'gto_cev',
  source: {
    kind: 'brand_neutralized_snapshot_config',
    capturedAt: '2026-07-18',
    path: 'research/ct-trainer-2026-07-18/',
    sha256: 'b8adc8eae6d5b3dbe19f15433794b625ccee58d2d27fdb6beb853d40657481d2'
  },
  cells: [
    {
      position: 'UTG',
      stackBb: 100,
      villainPosition: 'BTN',
      board: [
        '6d',
        '4h',
        '3c'
      ],
      heroStackSize: 97.7,
      villainStackSize: 97.7,
      actionLine: 'preflop: UTG raises 2.3bb, BTN calls 2.3bb',
      dealCombos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3h3d 3s3d 3s3h 4d4c 4s4c 4s4d 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6c5c 6h5h 6h6c 6s5s 6s6c 6s6h 7c6c 7d7c 7h6h 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8c7c 8d7d 8d8c 8h7h 8h8c 8h8d 8s7s 8s8c 8s8d 8s8h 9c8c 9d8d 9d9c 9h8h 9h9c 9h9d 9s8s 9s9c 9s9d 9s9h Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcKc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad3d Ad4d Ad5d Ad7d Ad8d Ad9d AdAc AdJc AdJd AdJh AdJs AdKc AdKd AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah3h Ah5h Ah6h Ah7h Ah8h Ah9h AhAc AhAd AhJc AhJd AhJh AhJs AhKc AhKd AhKh AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs As3s As4s As5s As6s As7s As8s As9s AsAc AsAd AsAh AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc9c JcTc JcTd JcTh JcTs Jd9d JdJc JdTc JdTd JdTh JdTs Jh9h JhJc JhJd JhTc JhTd JhTh JhTs Js9s JsJc JsJd JsJh JsTc JsTd JsTh JsTs Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc Kd8d Kd9d KdJc KdJd KdJh KdJs KdKc KdQc KdQd KdQh KdQs KdTd Kh8h Kh9h KhJc KhJd KhJh KhJs KhKc KhKd KhQc KhQd KhQh KhQs KhTh Ks8s Ks9s KsJc KsJd KsJh KsJs KsKc KsKd KsKh KsQc KsQd KsQh KsQs KsTs Qc9c QcJc QcJd QcJh QcJs QcTc Qd9d QdJc QdJd QdJh QdJs QdQc QdTd Qh9h QhJc QhJd QhJh QhJs QhQc QhQd QhTh Qs9s QsJc QsJd QsJh QsJs QsQc QsQd QsQh QsTs Tc8c Tc9c Td8d Td9d TdTc Th8h Th9h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh'),
      buckets: [
        {
          actions: [
            'check'
          ],
          combos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3h3d 3s3d 3s3h 4d4c 4s4c 4s4d 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6c5c 6h5h 6h6c 6s5s 6s6c 6s6h 7c6c 7d7c 7h6h 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8c7c 8d7d 8d8c 8h7h 8h8c 8h8d 8s7s 8s8c 8s8d 8s8h 9c8c 9d8d 9d9c 9h8h 9h9c 9h9d 9s8s 9s9c 9s9d 9s9h Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcKc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad3d Ad4d Ad5d Ad7d Ad8d Ad9d AdAc AdJc AdJd AdJh AdJs AdKc AdKd AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah3h Ah5h Ah6h Ah7h Ah8h Ah9h AhAc AhAd AhJc AhJd AhJh AhJs AhKc AhKd AhKh AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs As3s As4s As5s As6s As7s As8s As9s AsAc AsAd AsAh AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc9c JcTc JcTd JcTh JcTs Jd9d JdJc JdTc JdTd JdTh JdTs Jh9h JhJc JhJd JhTc JhTd JhTh JhTs Js9s JsJc JsJd JsJh JsTc JsTd JsTh JsTs Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc Kd8d Kd9d KdJc KdJd KdJh KdJs KdKc KdQc KdQd KdQh KdQs KdTd Kh8h Kh9h KhJc KhJd KhJh KhJs KhKc KhKd KhQc KhQd KhQh KhQs KhTh Ks8s Ks9s KsJc KsJd KsJh KsJs KsKc KsKd KsKh KsQc KsQd KsQh KsQs KsTs Qc9c QcJc QcJd QcJh QcJs QcTc Qd9d QdJc QdJd QdJh QdJs QdQc QdTd Qh9h QhJc QhJd QhJh QhJs QhQc QhQd QhTh Qs9s QsJc QsJd QsJh QsJs QsQc QsQd QsQh QsTs Tc8c Tc9c Td8d Td9d TdTc Th8h Th9h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh')
        }
      ]
    },
    {
      position: 'UTG',
      stackBb: 100,
      villainPosition: 'BTN',
      board: [
        '8s',
        '3s',
        '2s'
      ],
      heroStackSize: 97.7,
      villainStackSize: 97.7,
      actionLine: 'preflop: UTG raises 2.3bb, BTN calls 2.3bb',
      dealCombos: expand('2d2c 2h2c 2h2d 3d3c 3h3c 3h3d 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6c5c 6d5d 6d6c 6h5h 6h6c 6h6d 6s5s 6s6c 6s6d 6s6h 7c6c 7d6d 7d7c 7h6h 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8c7c 8d7d 8d8c 8h7h 8h8c 8h8d 9c8c 9d8d 9d9c 9h8h 9h9c 9h9d 9s9c 9s9d 9s9h Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcKc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad3d Ad4d Ad5d Ad6d Ad7d Ad8d Ad9d AdAc AdJc AdJd AdJh AdJs AdKc AdKd AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhAc AhAd AhJc AhJd AhJh AhJs AhKc AhKd AhKh AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs As4s As5s As6s As7s As9s AsAc AsAd AsAh AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc9c JcTc JcTd JcTh Jd9d JdJc JdTc JdTd JdTh Jh9h JhJc JhJd JhTc JhTd JhTh Js9s JsJc JsJd JsJh JsTc JsTd JsTh JsTs Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc Kd8d Kd9d KdJc KdJd KdJh KdJs KdKc KdQc KdQd KdQh KdQs KdTd Kh8h Kh9h KhJc KhJd KhJh KhJs KhKc KhKd KhQc KhQd KhQh KhQs KhTh Ks9s KsJc KsJd KsJh KsJs KsKc KsKd KsKh KsQc KsQd KsQh KsQs KsTs Qc9c QcJc QcJs QcTc Qd9d QdJd QdJs QdQc QdTd Qh9h QhJh QhJs QhQc QhQd QhTh Qs9s QsJs QsQc QsQd QsQh QsTs Tc8c Tc9c Td8d Td9d TdTc Th8h Th9h ThTc ThTd Ts9s TsTc TsTd TsTh'),
      buckets: [
        {
          actions: [
            'bet_25pct'
          ],
          combos: expand('2d2c 2h2c 2h2d 3d3c 3h3c 3h3d 4d4c 4h4c 4h4d 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6c5c 6d5d 6d6c 6h5h 6h6c 6h6d 6s6c 6s6d 6s6h 7c6c 7d6d 7d7c 7h6h 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8c7c 8d7d 8d8c 8h7h 8h8c 8h8d 9c8c 9d8d 9d9c 9h8h 9h9c 9h9d 9s9c 9s9d 9s9h Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcKc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh Ad3d Ad4d Ad5d Ad6d Ad7d Ad8d Ad9d AdAc AdJc AdJd AdJh AdJs AdKc AdKd AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhAc AhAd AhJc AhJd AhJh AhJs AhKc AhKd AhKh AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh As4s As5s As6s As7s As9s AsAc AsAd AsAh AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc9c JcTc JcTd JcTh Jd9d JdJc JdTc JdTd JdTh Jh9h JhJc JhJd JhTc JhTd JhTh Js9s JsJc JsJd JsJh JsTc JsTd JsTh JsTs Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc Kd8d Kd9d KdJc KdJd KdJh KdJs KdKc KdQc KdQd KdQh KdQs KdTd Kh8h Kh9h KhJc KhJd KhJh KhJs KhKc KhKd KhQc KhQd KhQh KhQs KhTh Ks9s KsJc KsJd KsJh KsJs KsKc KsKd KsKh KsQc KsQd KsQh KsQs KsTs Qc9c QcJc QcJs QcTc Qd9d QdJd QdJs QdQc QdTd Qh9h QhJh QhJs QhQc QhQd QhTh Qs9s QsJs QsQc QsQd QsQh QsTs Tc8c Tc9c Td8d Td9d TdTc Th8h Th9h ThTc ThTd Ts9s TsTc TsTd TsTh')
        },
        {
          actions: [
            'check'
          ],
          combos: expand('2d2c 2h2c 2h2d 3d3c 3h3c 3h3d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6c5c 6d5d 6d6c 6h5h 6h6c 6h6d 6s5s 6s6c 6s6d 6s6h 7c6c 7d6d 7d7c 7h6h 7h7c 7h7d 7s7c 7s7d 7s7h 8c7c 8d7d 8d8c 8h7h 8h8c 8h8d 9c8c 9d8d 9d9c 9h8h 9h9c 9h9d 9s9c 9s9d 9s9h Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcKc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad3d Ad4d Ad5d Ad6d Ad7d Ad8d Ad9d AdAc AdJc AdJd AdJh AdJs AdKc AdKd AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhAc AhAd AhJc AhJd AhJh AhJs AhKc AhKd AhKh AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs As4s As5s As6s As7s As9s AsAc AsAd AsAh AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTs Jc9c JcTc Jd9d JdJc JdTd Jh9h JhJc JhJd JhTh Js9s JsJc JsJd JsJh JsTs Kc8c Kc9c KcJc KcJd KcJh KcQc KcQd KcQh KcQs KcTc Kd8d Kd9d KdJc KdJd KdJh KdKc KdQc KdQd KdQh KdQs KdTd Kh8h Kh9h KhJc KhJd KhJh KhKc KhKd KhQc KhQd KhQh KhQs KhTh Ks9s KsJs KsKc KsKd KsKh KsQc KsQd KsQh KsQs KsTs Qc9c QcJc QcTc Qd9d QdJd QdQc QdTd Qh9h QhJh QhQc QhQd QhTh Qs9s QsJs QsQc QsQd QsQh QsTs Tc8c Tc9c Td8d Td9d TdTc Th8h Th9h ThTc ThTd Ts9s TsTc TsTd TsTh')
        }
      ]
    },
    {
      position: 'UTG',
      stackBb: 100,
      villainPosition: 'BTN',
      board: [
        '9h',
        '6d',
        '2h'
      ],
      heroStackSize: 97.7,
      villainStackSize: 97.7,
      actionLine: 'preflop: UTG raises 2.3bb, BTN calls 2.3bb',
      dealCombos: expand('2d2c 2s2c 2s2d 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6c5c 6h5h 6h6c 6s5s 6s6c 6s6h 7c6c 7d7c 7h6h 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8c7c 8d7d 8d8c 8h7h 8h8c 8h8d 8s7s 8s8c 8s8d 8s8h 9c8c 9d8d 9d9c 9s8s 9s9c 9s9d Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcKc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad3d Ad4d Ad5d Ad7d Ad8d Ad9d AdAc AdJc AdJd AdJh AdJs AdKc AdKd AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h AhAc AhAd AhJc AhJd AhJh AhJs AhKc AhKd AhKh AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs As3s As4s As5s As6s As7s As8s As9s AsAc AsAd AsAh AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc9c JcTc JcTd JcTh Jd9d JdJc JdTc JdTd JdTh JdTs JhJc JhJd JhTd JhTh Js9s JsJc JsJd JsJh JsTd JsTh JsTs Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc Kd8d Kd9d KdJc KdJd KdJh KdJs KdKc KdQc KdQd KdQh KdQs KdTd Kh8h KhJc KhJd KhJh KhJs KhKc KhKd KhQc KhQd KhQh KhQs KhTh Ks8s Ks9s KsJc KsJd KsJh KsJs KsKc KsKd KsKh KsQc KsQd KsQh KsQs KsTs Qc9c QcJc QcJd QcJs QcTc Qd9d QdJc QdJd QdJh QdJs QdQc QdTd QhJc QhJd QhJh QhJs QhQc QhQd QhTh Qs9s QsJc QsJd QsJs QsQc QsQd QsQh QsTs Tc8c Tc9c Td8d Td9d TdTc Th8h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh'),
      buckets: [
        {
          actions: [
            'bet_40pct'
          ],
          combos: expand('2d2c 2s2c 2s2d 3d3c 3h3d 3s3c 3s3d 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6c5c 6h6c 6s5s 6s6c 6s6h 7d7c 7h7c 7h7d 7s7c 7s7d 7s7h 8c7c 8d7d 8d8c 8h7h 8h8c 8h8d 8s7s 8s8c 8s8d 8s8h 9c8c 9d8d 9d9c 9s8s 9s9c 9s9d Ac5c Ac6c Ac7c Ac8c Ac9c AcJd AcJh AcKc AcKd AcKh AcQc AcQd AcQh AcTd AcTh Ad3d Ad4d Ad5d Ad7d Ad9d AdAc AdJh AdKc AdKd AdKh AdKs AdQd AdQh AdTc AdTh AdTs Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h AhAc AhAd AhJc AhJd AhJh AhJs AhKc AhKd AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs As5s As6s As7s As8s As9s AsAc AsAd AsAh AsJd AsJh AsKd AsKh AsKs AsQd AsQh AsQs AsTd AsTh Jc9c JcTc JcTd Jd9d JdJc JdTc JdTd JdTh JdTs JhJc JhTd JhTh Js9s JsJc JsJd JsJh JsTd JsTs Kc9c KcJd KcJh KcQc KcQd KcQh KcTc Kd8d Kd9d KdJd KdJh KdKc KdQc KdQd KdQh KdQs KdTd Kh8h KhJc KhJd KhJh KhJs KhKc KhQc KhQd KhQh KhQs KhTh Ks9s KsJd KsJh KsKc KsKd KsKh KsQd KsQh KsQs KsTs Qc9c QcJc QcJd QcTc Qd9d QdJc QdJd QdJh QdJs QdQc QdTd QhJd QhJh QhQc QhQd QhTh Qs9s QsJd QsJs QsQc QsQd QsQh QsTs Tc8c Tc9c Td8d Td9d TdTc Th8h ThTc Ts8s Ts9s TsTc TsTd TsTh')
        },
        {
          actions: [
            'check'
          ],
          combos: expand('2d2c 2s2c 2s2d 3d3c 3h3c 3h3d 3s3d 3s3h 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6c5c 6h5h 6h6c 6s5s 6s6h 7c6c 7d7c 7h6h 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8c7c 8d8c 8h7h 8h8c 8h8d 8s7s 8s8c 8s8d 8s8h 9d8d 9d9c 9s9c 9s9d Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcKc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTh AcTs Ad7d Ad8d Ad9d AdAc AdJc AdJd AdJh AdJs AdKc AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTs Ah4h Ah5h Ah6h Ah7h Ah8h AhAc AhAd AhJc AhJd AhJh AhJs AhKc AhKd AhKh AhKs AhQc AhQd AhQh AhQs AhTc AhTh AhTs As3s As4s As5s As6s As7s As8s As9s AsAc AsAd AsAh AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTc AsTh AsTs Jc9c JcTc JcTh Jd9d JdTd JhJc JhJd JhTh Js9s JsJc JsJh JsTh JsTs Kc8c Kc9c KcJc KcJs KcQc KcQd KcQh KcQs KcTc Kd9d KdJc KdJd KdJs KdKc KdQc KdQd KdQh KdQs KdTd Kh8h KhJc KhJs KhKc KhKd KhQc KhQd KhQh KhQs KhTh Ks8s Ks9s KsJc KsJs KsKc KsKd KsKh KsQc KsQd KsQh KsQs KsTs Qc9c QcJc QcJs QcTc Qd9d QdJd QdQc QdTd QhJc QhJh QhJs QhQc QhTh Qs9s QsJc QsJs QsQc QsQd QsQh QsTs Tc8c Tc9c Td9d TdTc Th8h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh')
        }
      ]
    },
    {
      position: 'UTG',
      stackBb: 100,
      villainPosition: 'BTN',
      board: [
        'Ac',
        'Kc',
        '3d'
      ],
      heroStackSize: 97.7,
      villainStackSize: 97.7,
      actionLine: 'preflop: UTG raises 2.3bb, BTN calls 2.3bb',
      dealCombos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3h3c 3s3c 3s3h 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6c5c 6d5d 6d6c 6h5h 6h6c 6h6d 6s5s 6s6c 6s6d 6s6h 7c6c 7d6d 7d7c 7h6h 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8c7c 8d7d 8d8c 8h7h 8h8c 8h8d 8s7s 8s8c 8s8d 8s8h 9c8c 9d8d 9d9c 9h8h 9h9c 9h9d 9s8s 9s9c 9s9d 9s9h Ad4d Ad5d Ad6d Ad7d Ad8d Ad9d AdJc AdJd AdJh AdJs AdKd AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhAd AhJc AhJd AhJh AhJs AhKd AhKh AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs As3s As4s As5s As6s As7s As8s As9s AsAd AsAh AsJc AsJd AsJh AsJs AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc9c JcTc JcTh JcTs Jd9d JdJc JdTc JdTd Jh9h JhJc JhJd JhTh JhTs Js9s JsJc JsJd JsJh JsTh JsTs Kd8d Kd9d KdJc KdJd KdJh KdJs KdQc KdQd KdQh KdQs KdTd Kh8h Kh9h KhJc KhJd KhJh KhJs KhKd KhQc KhQd KhQh KhQs KhTh Ks8s Ks9s KsJc KsJd KsJh KsJs KsKd KsKh KsQc KsQd KsQh KsQs KsTs Qc9c QcJc QcJd QcJh QcJs QcTc Qd9d QdJc QdJd QdJh QdJs QdQc QdTd Qh9h QhJc QhJd QhJh QhJs QhQc QhQd QhTh Qs9s QsJc QsJd QsJh QsJs QsQc QsQd QsQh QsTs Tc8c Tc9c Td8d Td9d TdTc Th8h Th9h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh'),
      buckets: [
        {
          actions: [
            'bet_103pct'
          ],
          combos: expand('2d2c 2h2c 2s2c 3h3c 3s3c 3s3h 4d4c 4h4c 4s4c 4s4h 5d5c 5h5c 5s5c 6c5c 6d6c 6h6c 6s6c 7d7c 7h7c 7s7c 8c7c 8d8c 8h8c 8s8c 9d9c 9h9c 9s9c Ad5d Ad6d Ad8d AdJc AdKd AdKh AdKs AdQc AdQd AdQh AdQs AdTh AdTs Ah3h Ah9h AhJc AhJh AhJs AhKd AhKh AhKs AhQc AhQd AhQh AhQs AhTh As3s As9s AsJc AsJh AsJs AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTs Jc9c JcTh JcTs JdJc JdTd JhTh JhTs JsTh JsTs Kd8d Kd9d KdTd Kh9h KhJh KhKd KhQc Ks9s KsJs KsKd KsKh KsQc Qc9c QcJc QcJd QcJh QcJs QcTc QdJc QdJd QdJh QdJs QdQc QdTd QhJd QhJh QhJs QhQc QhTh QsJd QsJh QsJs QsQc QsTs Tc8c Tc9c TdTc')
        },
        {
          actions: [
            'check'
          ],
          combos: expand('2h2d 2s2d 2s2h 4h4d 4s4d 4s4h 5d5c 5h5d 5s5d 5s5h 6c5c 6d5d 6d6c 6h5h 6h6d 6s5s 6s6d 6s6h 7c6c 7d6d 7d7c 7h6h 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8c7c 8d7d 8d8c 8h7h 8h8c 8h8d 8s7s 8s8c 8s8d 8s8h 9c8c 9d8d 9d9c 9h8h 9h9c 9h9d 9s8s 9s9c 9s9d 9s9h Ad4d Ad5d Ad7d Ad8d Ad9d AdJc AdJd AdJh AdJs AdKd AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhAd AhJd AhJs AhKd AhQc AhQd AhQs AhTc AhTd AhTh AhTs As4s As5s As6s As7s As8s As9s AsAd AsAh AsJd AsJh AsKd AsQc AsQd AsQh AsTc AsTd AsTh AsTs Jc9c JcTc Jd9d JdJc JdTc Jh9h JhJc JhJd JhTh Js9s JsJc JsJd JsJh JsTs KdJc KdJd KdJh KdJs KdQc KdQd KdQh KdQs KdTd Kh8h Kh9h KhJc KhJd KhJh KhJs KhKd KhQc KhQd KhQh KhQs KhTh Ks8s Ks9s KsJc KsJd KsJh KsJs KsKd KsKh KsQc KsQd KsQh KsQs KsTs Qc9c QcJc QcTc Qd9d QdQc QdTd Qh9h QhJc QhJh QhQc QhQd QhTh Qs9s QsJc QsJs QsQc QsQd QsQh QsTs Tc9c Td8d Td9d TdTc Th8h Th9h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh')
        }
      ]
    },
    {
      position: 'UTG',
      stackBb: 100,
      villainPosition: 'BTN',
      board: [
        'Ad',
        'Jh',
        'Th'
      ],
      heroStackSize: 97.7,
      villainStackSize: 97.7,
      actionLine: 'preflop: UTG raises 2.3bb, BTN calls 2.3bb',
      dealCombos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6c5c 6d5d 6d6c 6h5h 6h6c 6h6d 6s5s 6s6c 6s6d 6s6h 7c6c 7d6d 7d7c 7h6h 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8c7c 8d7d 8d8c 8h7h 8h8c 8h8d 8s7s 8s8c 8s8d 8s8h 9c8c 9d8d 9d9c 9h8h 9h9c 9h9d 9s8s 9s9c 9s9d 9s9h Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJs AcKc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTs Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhAc AhJc AhJd AhJs AhKc AhKd AhKh AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTs As3s As4s As5s As6s As7s As8s As9s AsAc AsAh AsJc AsJd AsJs AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTc AsTd AsTs Jc9c JcTc JcTd Jd9d JdJc JdTd Js9s JsJc JsJd JsTd JsTs Kc8c Kc9c KcJc KcJd KcJs KcQc KcQd KcQh KcQs KcTc Kd8d Kd9d KdJc KdJd KdJs KdKc KdQc KdQd KdQh KdQs KdTd Kh8h Kh9h KhJc KhJd KhJs KhKc KhKd KhQc KhQd KhQh KhQs Ks8s Ks9s KsJc KsJd KsJs KsKc KsKd KsKh KsQc KsQd KsQh KsQs KsTs Qc9c QcJc QcJd QcJs QcTc Qd9d QdJc QdJd QdJs QdQc QdTd Qh9h QhJc QhJd QhJs QhQc QhQd Qs9s QsJc QsJd QsJs QsQc QsQd QsQh QsTs Tc8c Tc9c Td8d Td9d TdTc Ts8s Ts9s TsTc TsTd'),
      buckets: [
        {
          actions: [
            'bet_25pct'
          ],
          combos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6d5d 6d6c 6h5h 6h6c 6h6d 6s6c 6s6d 6s6h 7d6d 7d7c 7h6h 7h7c 7h7d 7s7c 7s7d 7s7h 8c7c 8d7d 8d8c 8h7h 8h8c 8h8d 8s7s 8s8c 8s8d 8s8h 9c8c 9d8d 9d9c 9h8h 9h9c 9h9d 9s8s 9s9c 9s9d 9s9h Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJs AcKc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTs Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhAc AhJc AhJd AhJs AhKc AhKd AhKh AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTs As4s As5s As6s As7s As8s As9s AsAc AsAh AsJc AsJd AsJs AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTc AsTd AsTs Jc9c JcTc Jd9d JdJc JdTd Js9s JsJc JsJd JsTs Kc8c Kc9c KcJc KcJd KcJs KcQc KcQd KcQh KcQs KcTc Kd8d Kd9d KdJc KdJd KdJs KdKc KdQc KdQd KdQh KdQs KdTd Kh8h Kh9h KhJc KhJd KhJs KhKc KhKd KhQc KhQd KhQh KhQs Ks8s Ks9s KsJc KsJd KsJs KsKc KsKd KsKh KsQc KsQd KsQh KsQs KsTs Qc9c QcJc QcJd QcJs QcTc Qd9d QdJc QdJd QdJs QdQc QdTd Qh9h QhJc QhJd QhJs QhQc QhQd Qs9s QsJc QsJd QsJs QsQc QsQd QsQh QsTs Tc8c Tc9c Td8d Td9d TdTc Ts8s Ts9s TsTc TsTd')
        },
        {
          actions: [
            'check'
          ],
          combos: expand('2s2c 3d3c 3s3c 3s3d 4d4c 4s4c 4s4d 5d5c 5s5c 5s5d 6c5c 6d6c 6h5h 6h6d 6s5s 6s6c 6s6d 7c6c 7d7c 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8d8c 8h8c 8s8c 8s8d 8s8h 9d9c 9h8h 9h9c 9s9c 9s9d 9s9h Ac3c Ac4c Ac5c Ac6c Ac8c AcJc AcJd AcJs AcQc AcQd AcQh AcQs Ah5h Ah7h Ah8h Ah9h AhAc AhKc AhKd AhKs AhQc AhQs AhTc AhTs As3s As4s As5s As6s As8s AsAc AsAh AsJc AsJd AsJs AsQc AsQd AsQh AsQs JcTd Jd9d JdJc JdTd JsJd JsTd KcJc KcQc KcQh KcTc KdJc KdJs KdQh KhJc KhJs KhKc KhKd KhQh KsJs KsKh KsQh KsQs KsTs Qc9c QcJc QcTc QdQc QdTd Qh9h QhQc Qs9s QsJs QsQd QsQh QsTs Td8d Td9d TsTc')
        }
      ]
    },
    {
      position: 'UTG',
      stackBb: 100,
      villainPosition: 'BTN',
      board: [
        'Ah',
        '9d',
        '3c'
      ],
      heroStackSize: 97.7,
      villainStackSize: 97.7,
      actionLine: 'preflop: UTG raises 2.3bb, BTN calls 2.3bb',
      dealCombos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3h3d 3s3d 3s3h 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6c5c 6d5d 6d6c 6h5h 6h6c 6h6d 6s5s 6s6c 6s6d 6s6h 7c6c 7d6d 7d7c 7h6h 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8c7c 8d7d 8d8c 8h7h 8h8c 8h8d 8s7s 8s8c 8s8d 8s8h 9c8c 9h8h 9h9c 9s8s 9s9c 9s9h Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcKc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad3d Ad4d Ad5d Ad6d Ad7d Ad8d AdAc AdJc AdJd AdJh AdJs AdKc AdKd AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs As3s As4s As5s As6s As7s As8s As9s AsAc AsAd AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc9c JcTc JcTd JcTh JcTs JdJc JdTc JdTd JdTh JdTs Jh9h JhJc JhJd JhTc JhTd JhTh JhTs Js9s JsJc JsJd JsJh JsTc JsTd JsTh JsTs Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc Kd8d KdJc KdJd KdJh KdJs KdKc KdQc KdQd KdQh KdQs KdTd Kh8h Kh9h KhJc KhJd KhJh KhJs KhKc KhKd KhQc KhQd KhQh KhQs KhTh Ks8s Ks9s KsJc KsJd KsJh KsJs KsKc KsKd KsKh KsQc KsQd KsQh KsQs KsTs Qc9c QcJc QcJd QcJh QcJs QcTc QdJc QdJd QdJh QdJs QdQc QdTd Qh9h QhJc QhJd QhJh QhJs QhQc QhQd QhTh Qs9s QsJc QsJd QsJh QsJs QsQc QsQd QsQh QsTs Tc8c Tc9c Td8d TdTc Th8h Th9h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh'),
      buckets: [
        {
          actions: [
            'bet_25pct'
          ],
          combos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3h3d 3s3d 3s3h 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6c5c 6d5d 6d6c 6h5h 6h6c 6h6d 6s5s 6s6c 6s6d 6s6h 7c6c 7d6d 7d7c 7h6h 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8c7c 8d7d 8d8c 8h7h 8h8c 8h8d 8s7s 8s8c 8s8d 8s8h 9c8c 9h8h 9h9c 9s8s 9s9c 9s9h Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcKc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad3d Ad4d Ad5d Ad6d Ad7d Ad8d AdAc AdJc AdJd AdJh AdJs AdKc AdKd AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs As3s As4s As5s As6s As7s As8s As9s AsAc AsAd AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc9c JcTc JcTd JcTh JcTs JdJc JdTc JdTd JdTh JdTs Jh9h JhJc JhJd JhTc JhTd JhTh JhTs Js9s JsJc JsJd JsJh JsTc JsTd JsTh JsTs Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc Kd8d KdJc KdJd KdJh KdJs KdKc KdQc KdQd KdQh KdQs KdTd Kh8h Kh9h KhJc KhJd KhJh KhJs KhKc KhKd KhQc KhQd KhQh KhQs KhTh Ks8s Ks9s KsJc KsJd KsJh KsJs KsKc KsKd KsKh KsQc KsQd KsQh KsQs KsTs Qc9c QcJc QcJd QcJh QcJs QcTc QdJc QdJd QdJh QdJs QdQc QdTd Qh9h QhJc QhJd QhJh QhJs QhQc QhQd QhTh Qs9s QsJc QsJd QsJh QsJs QsQc QsQd QsQh QsTs Tc8c Tc9c Td8d TdTc Th8h Th9h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh')
        }
      ]
    },
    {
      position: 'UTG',
      stackBb: 100,
      villainPosition: 'BTN',
      board: [
        'As',
        'Ac',
        '7s'
      ],
      heroStackSize: 97.7,
      villainStackSize: 97.7,
      actionLine: 'preflop: UTG raises 2.3bb, BTN calls 2.3bb',
      dealCombos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6c5c 6d5d 6d6c 6h5h 6h6c 6h6d 6s5s 6s6c 6s6d 6s6h 7c6c 7d6d 7d7c 7h6h 7h7c 7h7d 8c7c 8d7d 8d8c 8h7h 8h8c 8h8d 8s8c 8s8d 8s8h 9c8c 9d8d 9d9c 9h8h 9h9c 9h9d 9s8s 9s9c 9s9d 9s9h Ad3d Ad4d Ad5d Ad6d Ad7d Ad8d Ad9d AdJc AdJd AdJh AdJs AdKc AdKd AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhAd AhJc AhJd AhJh AhJs AhKc AhKd AhKh AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs Jc9c JcTc JcTd JcTh JcTs Jd9d JdJc JdTc JdTd JdTh JdTs Jh9h JhJc JhJd JhTc JhTd JhTh JhTs Js9s JsJc JsJd JsJh JsTc JsTd JsTh JsTs Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc Kd8d Kd9d KdJc KdJd KdJh KdJs KdKc KdQc KdQd KdQh KdQs KdTd Kh8h Kh9h KhJc KhJd KhJh KhJs KhKc KhKd KhQc KhQd KhQh KhQs KhTh Ks8s Ks9s KsJc KsJd KsJh KsJs KsKc KsKd KsKh KsQc KsQd KsQh KsQs KsTs Qc9c QcJc QcJd QcJh QcJs QcTc Qd9d QdJc QdJd QdJh QdJs QdQc QdTd Qh9h QhJc QhJd QhJh QhJs QhQc QhQd QhTh Qs9s QsJc QsJd QsJh QsJs QsQc QsQd QsQh QsTs Tc8c Tc9c Td8d Td9d TdTc Th8h Th9h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh'),
      buckets: [
        {
          actions: [
            'bet_25pct'
          ],
          combos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6c5c 6d5d 6d6c 6h5h 6h6c 6h6d 6s5s 6s6c 6s6d 6s6h 7c6c 7d6d 7d7c 7h6h 7h7c 7h7d 8c7c 8d7d 8d8c 8h7h 8h8c 8h8d 8s8c 8s8d 8s8h 9c8c 9d8d 9d9c 9h8h 9h9c 9h9d 9s8s 9s9c 9s9d 9s9h Ad3d Ad4d Ad5d Ad6d Ad7d Ad8d Ad9d AdJc AdJd AdJh AdJs AdKc AdKd AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhAd AhJc AhJd AhJh AhJs AhKc AhKd AhKh AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs Jc9c JcTc JcTd JcTh JcTs Jd9d JdJc JdTc JdTd JdTh JdTs Jh9h JhJc JhJd JhTc JhTd JhTh JhTs Js9s JsJc JsJd JsJh JsTc JsTd JsTh JsTs Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc Kd8d Kd9d KdJc KdJd KdJh KdJs KdKc KdQc KdQd KdQh KdQs KdTd Kh8h Kh9h KhJc KhJd KhJh KhJs KhKc KhKd KhQc KhQd KhQh KhQs KhTh Ks8s Ks9s KsJc KsJd KsJh KsJs KsKc KsKd KsKh KsQc KsQd KsQh KsQs KsTs Qc9c QcJc QcJd QcJh QcJs QcTc Qd9d QdJc QdJd QdJh QdJs QdQc QdTd Qh9h QhJc QhJd QhJh QhJs QhQc QhQd QhTh Qs9s QsJc QsJd QsJh QsJs QsQc QsQd QsQh QsTs Tc8c Tc9c Td8d Td9d TdTc Th8h Th9h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh')
        }
      ]
    },
    {
      position: 'UTG',
      stackBb: 100,
      villainPosition: 'BTN',
      board: [
        'Jd',
        '6d',
        '2c'
      ],
      heroStackSize: 97.7,
      villainStackSize: 97.7,
      actionLine: 'preflop: UTG raises 2.3bb, BTN calls 2.3bb',
      dealCombos: expand('2h2d 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6c5c 6h5h 6h6c 6s5s 6s6c 6s6h 7c6c 7d7c 7h6h 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8c7c 8d7d 8d8c 8h7h 8h8c 8h8d 8s7s 8s8c 8s8d 8s8h 9c8c 9d8d 9d9c 9h8h 9h9c 9h9d 9s8s 9s9c 9s9d 9s9h Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJh AcJs AcKc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad3d Ad4d Ad5d Ad7d Ad8d Ad9d AdAc AdJc AdJh AdJs AdKc AdKd AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhAc AhAd AhJc AhJh AhJs AhKc AhKd AhKh AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs As3s As4s As5s As6s As7s As8s As9s AsAc AsAd AsAh AsJc AsJh AsJs AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc9c JcTc JcTh JcTs Jh9h JhJc JhTd JhTh Js9s JsJc JsJh JsTd JsTs Kc8c Kc9c KcJc KcJh KcJs KcQc KcQd KcQh KcQs KcTc Kd8d Kd9d KdJc KdJh KdJs KdKc KdQc KdQd KdQh KdQs KdTd Kh8h Kh9h KhJc KhJh KhJs KhKc KhKd KhQc KhQd KhQh KhQs KhTh Ks8s Ks9s KsJc KsJh KsJs KsKc KsKd KsKh KsQc KsQd KsQh KsQs KsTs Qc9c QcJc QcJh QcJs QcTc Qd9d QdJc QdJh QdJs QdQc QdTd Qh9h QhJc QhJh QhJs QhQc QhQd QhTh Qs9s QsJc QsJh QsJs QsQc QsQd QsQh QsTs Tc8c Tc9c Td8d Td9d TdTc Th8h Th9h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh'),
      buckets: [
        {
          actions: [
            'bet_25pct'
          ],
          combos: expand('2h2d 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6c5c 6h5h 6h6c 6s5s 6s6c 6s6h 7c6c 7d7c 7h7c 7h7d 7s7c 7s7d 8c7c 8d7d 8d8c 8h7h 8h8c 8h8d 8s7s 8s8c 8s8d 9c8c 9d8d 9d9c 9h8h 9h9c 9h9d 9s8s 9s9c 9s9d Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJh AcJs AcKc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad3d Ad4d Ad5d Ad7d Ad8d Ad9d AdAc AdJc AdJh AdJs AdKc AdKd AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah3h Ah4h Ah6h AhAc AhAd AhJc AhJh AhJs AhKc AhKd AhKh AhKs AhQc AhQd AhQh AhQs AhTd AhTh As3s As4s As6s AsAc AsAd AsAh AsJc AsJh AsJs AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTd AsTs Jc9c JcTc JcTh JcTs Jh9h JhJc JhTh Js9s JsJc JsJh JsTs Kc8c Kc9c KcJc KcJh KcJs KcQc KcQd KcQh KcQs KcTc Kd8d Kd9d KdKc KdQc KdQd KdQh KdQs KdTd KhJc KhJh KhJs KhKc KhKd KhQc KhQd KhQh KhQs KhTh KsJc KsJh KsJs KsKc KsKd KsKh KsQc KsQd KsQh KsQs KsTs Qc9c QcJc QcJh QcJs QcTc Qd9d QdJc QdQc QdTd Qh9h QhJc QhJh QhJs QhQc QhQd QhTh Qs9s QsJc QsJh QsJs QsQc QsQd QsQh QsTs Tc8c Tc9c Td8d Td9d TdTc Th9h ThTc ThTd Ts9s TsTc TsTd TsTh')
        },
        {
          actions: [
            'check'
          ],
          combos: expand('2h2d 2s2d 3d3c 3h3d 3s3d 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5h5d 5s5d 5s5h 6c5c 6h5h 6h6c 6s5s 6s6c 6s6h 7h6h 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8h7h 8h8d 8s7s 8s8d 8s8h 9h8h 9h9d 9s8s 9s9d 9s9h Ac6c AcJc AcJh AcJs AcKc AcKd AcQd AcQh AcQs AcTc AcTh AcTs Ad3d Ad4d Ad5d Ad7d Ad8d Ad9d AdAc AdKd AdKh AdKs AdQh AdQs AdTd AdTh AdTs Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhAc AhAd AhJc AhJh AhJs AhKd AhKh AhKs AhQd AhQh AhQs AhTc AhTh AhTs As3s As4s As5s As6s As7s As8s As9s AsAc AsAd AsAh AsJc AsJh AsJs AsKd AsKh AsKs AsQd AsQh AsQs AsTc AsTh AsTs Jh9h JhJc JhTd JhTh Js9s JsJc JsTd JsTs KcJc KcJh KcJs KcQc KcQh KcQs KcTc Kd8d KdJc KdJh KdJs KdKc KdQd KdQh KdQs KdTd Kh8h Kh9h KhKc KhKd KhQd KhQh KhQs KhTh Ks8s Ks9s KsKc KsKd KsKh KsQd KsQh KsQs KsTs QcJc QcTc Qd9d QdJh QdJs QdQc QdTd Qh9h QhJh QhQc Qs9s QsJs QsQc QsQh Td8d Td9d TdTc Th8h Th9h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh')
        }
      ]
    },
    {
      position: 'UTG',
      stackBb: 100,
      villainPosition: 'BTN',
      board: [
        'Js',
        '8s',
        '8d'
      ],
      heroStackSize: 97.7,
      villainStackSize: 97.7,
      actionLine: 'preflop: UTG raises 2.3bb, BTN calls 2.3bb',
      dealCombos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6c5c 6d5d 6d6c 6h5h 6h6c 6h6d 6s5s 6s6c 6s6d 6s6h 7c6c 7d6d 7d7c 7h6h 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8c7c 8h7h 8h8c 9c8c 9d9c 9h8h 9h9c 9h9d 9s9c 9s9d 9s9h Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcKc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad3d Ad4d Ad5d Ad6d Ad7d Ad9d AdAc AdJc AdJd AdJh AdKc AdKd AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhAc AhAd AhJc AhJd AhJh AhKc AhKd AhKh AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs As3s As4s As5s As6s As7s As9s AsAc AsAd AsAh AsJc AsJd AsJh AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc9c JcTc JcTd JcTs Jd9d JdJc JdTc JdTd JdTh Jh9h JhJc JhJd JhTd JhTh JhTs Kc8c Kc9c KcJc KcJd KcJh KcQc KcQd KcQh KcQs KcTc Kd9d KdJc KdJd KdJh KdKc KdQc KdQd KdQh KdQs KdTd Kh8h Kh9h KhJc KhJd KhJh KhKc KhKd KhQc KhQd KhQh KhQs KhTh Ks9s KsJc KsJd KsJh KsKc KsKd KsKh KsQc KsQd KsQh KsQs KsTs Qc9c QcJc QcJd QcJh QcTc Qd9d QdJc QdJd QdJh QdQc QdTd Qh9h QhJc QhJd QhJh QhQc QhQd QhTh Qs9s QsJc QsJd QsJh QsQc QsQd QsQh QsTs Tc8c Tc9c Td9d TdTc Th8h Th9h ThTc ThTd Ts9s TsTc TsTd TsTh'),
      buckets: [
        {
          actions: [
            'bet_25pct'
          ],
          combos: expand('2h2c 2s2c 2s2d 2s2h 3h3c 3s3c 3s3d 3s3h 4d4c 4h4c 4h4d 4s4c 4s4h 5d5c 5h5d 5s5c 5s5d 5s5h 6d6c 6h6d 6s6c 6s6d 6s6h 7d7c 7h7d 7s6s 7s7c 7s7d 7s7h 8c7c 8h7h 8h8c 9c8c 9d9c 9h8h 9h9d 9s9d Ac8c Ac9c AcJc AcJd AcJh AcKh AcKs AcQc AcQh AcTs Ad3d Ad4d Ad7d Ad9d AdAc AdKd AdKs AdQd AdQs AdTd AdTs Ah8h Ah9h AhAc AhAd AhJc AhJd AhJh AhKc AhKs AhQc AhQh AhTs As3s As4s As5s As6s As7s As9s AsAc AsAd AsAh AsJc AsJd AsJh AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsTc AsTd AsTh AsTs Jc9c JcTc Jd9d JdJc JdTc JdTd JdTh Jh9h JhJc JhJd JhTh Kc8c KcJc KcJd KcJh KcQc KcQd KcQh KcQs KcTc Kd9d KdKc KdQc KdQd KdQh KdQs KdTd Kh8h KhJc KhJd KhJh KhKc KhKd KhQc KhQd KhQh KhQs KhTh Ks9s KsKc KsKh KsQc KsQd KsQh KsQs KsTs Qc9c QcJc QcJd QcJh QcTc Qd9d QdQc QdTd Qh9h QhJc QhJd QhJh QhQc QhQd QhTh Qs9s QsQc QsQd QsQh QsTs Tc8c Tc9c Td9d TdTc Th8h Th9h ThTc ThTd Ts9s TsTd')
        },
        {
          actions: [
            'check'
          ],
          combos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3d 3s3c 3s3d 3s3h 4d4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6c5c 6d5d 6d6c 6h5h 6h6c 6h6d 6s5s 6s6c 6s6d 6s6h 7c6c 7d6d 7d7c 7h6h 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8c7c 8h7h 8h8c 9c8c 9d9c 9h8h 9h9c 9h9d 9s9c 9s9d 9s9h Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcKc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh Ad4d Ad5d Ad6d Ad7d AdAc AdJc AdJd AdJh AdKc AdKh AdQc AdQd AdQh AdTc AdTd AdTh Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhAc AhAd AhJc AhJd AhJh AhKc AhKd AhKh AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh As3s As4s As5s As6s As7s As9s AsAc AsAd AsAh AsJc AsJd AsJh AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTs Jc9c JcTc JcTd JcTs Jd9d JdJc JdTd Jh9h JhJc JhJd JhTd JhTh JhTs Kc8c Kc9c KcJc KcQc KcQd KcQh KcQs KcTc Kd9d KdJc KdJd KdJh KdKc KdQc KdQh KdQs KdTd Kh8h Kh9h KhJh KhKd KhQc KhQd KhQh KhQs KhTh Ks9s KsJc KsJd KsJh KsKc KsKd KsKh KsQs KsTs Qc9c QcJc QcTc Qd9d QdJc QdJd QdJh QdQc QdTd Qh9h QhJh QhQc QhQd QhTh Qs9s QsJc QsJd QsJh QsQc QsQd QsQh QsTs Tc8c Tc9c Td9d TdTc Th8h Th9h ThTc ThTd Ts9s TsTc TsTd TsTh')
        }
      ]
    },
    {
      position: 'UTG',
      stackBb: 100,
      villainPosition: 'BTN',
      board: [
        'Kc',
        '6c',
        '3s'
      ],
      heroStackSize: 97.7,
      villainStackSize: 97.7,
      actionLine: 'preflop: UTG raises 2.3bb, BTN calls 2.3bb',
      dealCombos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6d5d 6h5h 6h6d 6s5s 6s6d 6s6h 7d6d 7d7c 7h6h 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8c7c 8d7d 8d8c 8h7h 8h8c 8h8d 8s7s 8s8c 8s8d 8s8h 9c8c 9d8d 9d9c 9h8h 9h9c 9h9d 9s8s 9s9c 9s9d 9s9h Ac3c Ac4c Ac5c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad3d Ad4d Ad5d Ad6d Ad7d Ad8d Ad9d AdAc AdJc AdJd AdJh AdJs AdKd AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhAc AhAd AhJc AhJd AhJh AhJs AhKd AhKh AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs As4s As5s As6s As7s As8s As9s AsAc AsAd AsAh AsJc AsJd AsJh AsJs AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc9c JcTc JcTd JcTh JcTs Jd9d JdJc JdTc JdTd JdTh JdTs Jh9h JhJc JhJd JhTc JhTd JhTh JhTs Js9s JsJc JsJd JsJh JsTc JsTs Kd8d Kd9d KdJc KdJd KdJh KdJs KdQc KdQd KdQh KdQs KdTd Kh8h Kh9h KhJc KhJd KhJh KhJs KhKd KhQc KhQd KhQh KhQs KhTh Ks8s Ks9s KsJc KsJd KsJh KsJs KsKd KsKh KsQc KsQd KsQh KsQs KsTs Qc9c QcJc QcJd QcJh QcJs QcTc Qd9d QdJc QdJd QdJh QdJs QdQc QdTd Qh9h QhJc QhJd QhJh QhJs QhQc QhQd QhTh Qs9s QsJc QsJd QsJh QsJs QsQc QsQd QsQh QsTs Tc8c Tc9c Td8d Td9d TdTc Th8h Th9h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh'),
      buckets: [
        {
          actions: [
            'bet_25pct'
          ],
          combos: expand('2d2c 2h2c 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 4d4c 4h4c 4s4c 4s4d 4s4h 5d5c 5h5c 5s5c 5s5d 5s5h 6d5d 6h5h 6h6d 6s6d 6s6h 7d6d 7d7c 7h6h 7h7c 7s6s 7s7c 7s7d 7s7h 8c7c 8d7d 8d8c 8h7h 8h8c 8h8d 8s8c 8s8d 8s8h 9c8c 9d8d 9d9c 9h8h 9h9c 9s8s 9s9c 9s9d 9s9h Ac3c Ac4c Ac5c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad3d Ad4d Ad5d Ad6d Ad7d Ad8d Ad9d AdAc AdJc AdKd AdKh AdKs AdQc AdQd AdQs AdTc Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhAc AhAd AhJc AhKd AhKh AhKs AhQc AhQh AhQs AhTc As4s As5s As6s As7s As8s As9s AsAc AsAd AsAh AsJc AsJs AsKd AsKh AsKs AsQs AsTc AsTd AsTh AsTs Jc9c JcTc JcTd JcTh JcTs JdJc JdTc JdTd JhJc JhTc JhTh Js9s JsJc JsJd JsJh JsTc JsTs Kd8d Kd9d KdJd KdJh KdJs KdQc KdQd KdQh KdQs KdTd Kh8h Kh9h KhJd KhJh KhJs KhKd KhQc KhQd KhQh KhQs KhTh Ks9s KsJd KsJh KsJs KsKd KsKh KsQc KsQd KsQh KsQs KsTs Qc9c QcJc QcJd QcJh QcJs QcTc Qd9d QdJc QdJd QdQc QdTd Qh9h QhJc QhJh QhQc QhTh Qs9s QsJc QsJd QsJh QsJs QsQc QsQd QsQh Tc8c Tc9c Td8d Td9d TdTc Th8h Th9h ThTc Ts8s Ts9s TsTc TsTd TsTh')
        },
        {
          actions: [
            'check'
          ],
          combos: expand('2d2c 2h2c 2h2d 2s2d 2s2h 3d3c 3h3c 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6d5d 6h5h 6h6d 6s5s 6s6d 6s6h 7d6d 7d7c 7h6h 7h7c 7h7d 7s6s 7s7d 7s7h 8c7c 8d7d 8d8c 8h7h 8h8c 8h8d 8s7s 8s8d 8s8h 9c8c 9d8d 9d9c 9h8h 9h9c 9h9d 9s9d 9s9h Ac3c Ac4c Ac5c Ac7c Ac8c Ac9c AcJc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc Ad3d Ad4d Ad5d Ad6d Ad7d Ad8d Ad9d AdAc AdJd AdJh AdJs AdKd AdKh AdKs AdQc AdQd AdQh AdQs AdTd AdTh AdTs Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhAc AhAd AhJd AhJh AhJs AhKd AhKh AhKs AhQc AhQd AhQh AhQs AhTd AhTh AhTs As6s As7s As8s As9s AsAc AsAd AsAh AsJc AsJd AsJh AsJs AsKd AsKh AsQc AsQd AsQh AsQs AsTd AsTh AsTs JcTc Jd9d JdJc JdTd JdTh JdTs Jh9h JhJc JhJd JhTd JhTh JhTs JsJc JsJd JsJh JsTs Kd8d Kd9d KdJc KdJs KdQc KdQd KdQh KdTd Kh8h Kh9h KhJc KhJs KhQc KhQd KhQh KhTh Ks8s Ks9s KsJc KsJs KsKd KsKh KsQc KsQd KsQh KsQs KsTs Qc9c QcJc QcTc Qd9d QdJd QdJh QdJs QdQc QdTd Qh9h QhJd QhJh QhJs QhQc QhQd QhTh Qs9s QsJs QsQc QsQd QsQh QsTs Tc8c Tc9c Td8d Td9d TdTc Th8h Th9h ThTc ThTd Ts9s TsTc TsTd TsTh')
        }
      ]
    },
    {
      position: 'UTG',
      stackBb: 100,
      villainPosition: 'BTN',
      board: [
        'Kd',
        'Ts',
        '8h'
      ],
      heroStackSize: 97.7,
      villainStackSize: 97.7,
      actionLine: 'preflop: UTG raises 2.3bb, BTN calls 2.3bb',
      dealCombos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6c5c 6d5d 6d6c 6h5h 6h6c 6h6d 6s5s 6s6c 6s6d 6s6h 7c6c 7d6d 7d7c 7h6h 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8c7c 8d7d 8d8c 8s7s 8s8c 8s8d 9c8c 9d8d 9d9c 9h9c 9h9d 9s8s 9s9c 9s9d 9s9h Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcKc AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh Ad3d Ad4d Ad5d Ad6d Ad7d Ad8d Ad9d AdAc AdJc AdJd AdJh AdJs AdKc AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh Ah3h Ah4h Ah5h Ah6h Ah7h Ah9h AhAc AhAd AhJc AhJd AhJh AhJs AhKc AhKh AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh As3s As4s As5s As6s As7s As8s As9s AsAc AsAd AsAh AsJc AsJd AsJh AsJs AsKc AsKh AsKs AsQc AsQd AsQh AsQs AsTc AsTd AsTh Jc9c JcTc JcTh Jd9d JdJc JdTc JdTd JdTh Jh9h JhJc JhJd JhTc JhTh Js9s JsJc JsJd JsJh JsTc JsTh Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc Kh9h KhJc KhJd KhJh KhJs KhKc KhQc KhQd KhQh KhQs KhTh Ks8s Ks9s KsJc KsJd KsJh KsJs KsKc KsKh KsQc KsQd KsQh KsQs Qc9c QcJc QcJd QcJh QcJs QcTc Qd9d QdJc QdJd QdJh QdJs QdQc QdTd Qh9h QhJc QhJd QhJh QhJs QhQc QhQd QhTh Qs9s QsJc QsJd QsJh QsJs QsQc QsQd QsQh Tc8c Tc9c Td8d Td9d TdTc Th9h ThTc ThTd'),
      buckets: [
        {
          actions: [
            'bet_67pct'
          ],
          combos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6d6c 7c6c 7d6d 7h6h 7s6s 8c7c 8d8c 8s8c 8s8d 9c8c 9d8d 9s8s Ac7c Ac8c AcJc AcJd AcJh AcJs AcKc AcKh AcKs AcQc AcQd AcQh AcQs Ad7d Ad8d Ad9d AdAc AdJc AdJd AdJh AdJs AdKc AdKh AdKs AdQc AdQd AdQh AdQs AdTd Ah7h Ah9h AhAc AhAd AhJc AhJd AhJh AhJs AhKc AhKh AhKs AhQc AhQd AhQh AhQs AhTd AhTh As7s As9s AsAc AsAd AsAh AsJc AsJd AsJh AsJs AsKc AsKh AsKs AsQc AsQd AsQh AsQs AsTd Jc9c JcTc Jd9d JdJc Jh9h JhJc JhJd Js9s JsJc JsJd JsJh Kc8c KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc Kh9h KhJc KhJd KhJh KhJs KhKc KhQc KhQd KhQh KhQs KhTh Ks8s Ks9s KsJc KsJd KsJh KsJs KsKc KsKh KsQd KsQh KsQs Qc9c QcJc QcTc Qd9d QdJd QdQc Qh9h QhJh QhQc QhQd Qs9s QsJs QsQd QsQh Tc8c Tc9c Td8d Td9d TdTc Th9h ThTc ThTd')
        },
        {
          actions: [
            'check'
          ],
          combos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6c5c 6d5d 6d6c 6h5h 6h6c 6h6d 6s5s 6s6c 6s6d 6s6h 7d7c 7h7c 7h7d 7s7c 7s7d 7s7h 8c7c 8d7d 8d8c 8s7s 8s8c 8s8d 9d8d 9d9c 9h9c 9h9d 9s8s 9s9c 9s9d 9s9h Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJd AcJh AcJs AcKh AcKs AcQs AcTc AcTd AcTh Ad3d Ad4d Ad5d Ad6d Ad7d Ad8d Ad9d AdJh AdJs AdKh AdKs AdQc AdQh AdQs AdTc AdTd AdTh Ah3h Ah4h Ah5h Ah6h Ah7h Ah9h AhAc AhAd AhJd AhJh AhJs AhKs AhQc AhQd AhQs AhTc AhTd AhTh As3s As4s As5s As6s As7s As8s As9s AsAc AsAd AsAh AsJd AsJh AsKh AsQc AsQd AsQh AsTc AsTd AsTh Jc9c JcTc JcTh Jd9d JdJc JdTc JdTd JdTh Jh9h JhJc JhJd JhTc JhTh Js9s JsJc JsJd JsJh JsTc JsTh Kc9c KcJc KcJd KcJh KcQc KcQd KcQh KcQs Kh9h KhJc KhJh KhKc KhQc KhQd Ks9s KsJc KsJh KsJs KsKc KsKh KsQc KsQh KsQs Qc9c QcJc QcJd QcJh QcJs QcTc Qd9d QdJc QdJh QdJs QdQc QdTd Qh9h QhJc QhJd QhJh QhJs QhQc QhQd QhTh QsJc QsJd QsJh QsJs QsQc QsQd QsQh Tc9c Td9d TdTc Th9h ThTc ThTd')
        }
      ]
    },
    {
      position: 'UTG',
      stackBb: 100,
      villainPosition: 'BTN',
      board: [
        'Kh',
        'Jd',
        '4d'
      ],
      heroStackSize: 97.7,
      villainStackSize: 97.7,
      actionLine: 'preflop: UTG raises 2.3bb, BTN calls 2.3bb',
      dealCombos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4h4c 4s4c 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6c5c 6d5d 6d6c 6h5h 6h6c 6h6d 6s5s 6s6c 6s6d 6s6h 7c6c 7d6d 7d7c 7h6h 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8c7c 8d7d 8d8c 8h7h 8h8c 8h8d 8s7s 8s8c 8s8d 8s8h 9c8c 9d8d 9d9c 9h8h 9h9c 9h9d 9s8s 9s9c 9s9d 9s9h Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJh AcJs AcKc AcKd AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad3d Ad5d Ad6d Ad7d Ad8d Ad9d AdAc AdJc AdJh AdJs AdKc AdKd AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhAc AhAd AhJc AhJh AhJs AhKc AhKd AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs As3s As4s As5s As6s As7s As8s As9s AsAc AsAd AsAh AsJc AsJh AsJs AsKc AsKd AsKs AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc9c JcTc JcTh Jh9h JhJc JhTc JhTd JhTh JhTs Js9s JsJc JsJh JsTh JsTs Kc8c Kc9c KcJc KcJh KcJs KcQc KcQd KcQh KcQs KcTc Kd8d Kd9d KdJc KdJh KdJs KdKc KdQc KdQd KdQh KdQs KdTd Ks8s Ks9s KsJc KsJh KsJs KsKc KsKd KsQc KsQd KsQh KsQs KsTs Qc9c QcJc QcJh QcJs QcTc Qd9d QdJc QdJh QdJs QdQc QdTd Qh9h QhJc QhJh QhJs QhQc QhQd QhTh Qs9s QsJc QsJh QsJs QsQc QsQd QsQh QsTs Tc8c Tc9c Td8d Td9d TdTc Th8h Th9h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh'),
      buckets: [
        {
          actions: [
            'bet_67pct'
          ],
          combos: expand('2d2c 2h2d 2s2d 3d3c 3h3d 3s3d 4h4c 4s4c 4s4h 5d5c 5h5d 5s5d 6d6c 6h5h 6s6d 7d7c 7h6h 7s7d 8d7d 8d8c 8s8d 9d8d Ac4c AcJc AcKc AcKd AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad3d Ad5d Ad6d Ad7d Ad8d Ad9d AdAc AdJc AdJs AdKc AdKd AdKs AdQc AdQh AdQs AdTc AdTd AdTh AdTs Ah3h Ah4h Ah5h Ah6h AhAc AhAd AhJc AhJs AhKc AhKd AhKs AhQc AhQd AhQh AhQs AhTd As4s AsAc AsAd AsAh AsJs AsKc AsKd AsKs AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc9c JcTc Jh9h JhJc JhTc JhTh JhTs Js9s JsJc JsJh JsTs Kc9c KcJc KcJh KcJs KcQc KcQd KcQh KcQs Kd9d KdJc KdJh KdJs KdKc KdQc KdQd KdQh KdQs KdTd Ks9s KsJc KsJh KsJs KsKc KsKd KsQc KsQd KsQh KsQs QcTc Qd9d QdTd Qh9h QhQd QhTh QsTs Tc9c Td8d Td9d Th8h Th9h Ts9s')
        },
        {
          actions: [
            'check'
          ],
          combos: expand('2h2c 2s2c 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 5h5c 5h5d 5s5c 5s5h 6c5c 6d5d 6d6c 6h5h 6h6c 6h6d 6s5s 6s6c 6s6d 6s6h 7c6c 7d6d 7d7c 7h6h 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8c7c 8d7d 8d8c 8h7h 8h8c 8h8d 8s7s 8s8c 8s8d 8s8h 9c8c 9d8d 9d9c 9h8h 9h9c 9h9d 9s8s 9s9c 9s9d 9s9h Ac3c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJh AcJs AcKd AcKs AcQc AcQd AcQh AcQs AcTc Ad5d Ad6d Ad7d Ad8d Ad9d AdAc AdJc AdJh AdJs AdKc AdKd AdKs AdQd AdQh AdTc AdTd AdTh AdTs Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhAc AhAd AhJc AhJh AhJs AhKc AhKs AhQc AhQd AhQh AhQs AhTc AhTh AhTs As3s As5s As6s As7s As8s As9s AsAc AsAd AsAh AsJc AsJh AsJs AsKc AsKd AsQc AsQd AsQh AsQs AsTs Jc9c JcTc JcTh Jh9h JhJc JhTd JhTh Js9s JsJc JsJh JsTh JsTs Kc8c Kc9c KcJc KcJs KcQc KcQd KcQh KcQs KcTc Kd8d Kd9d KdKc KdQc KdQd KdQh KdQs KdTd Ks8s Ks9s KsJc KsJs KsKc KsKd KsQc KsQd KsQh KsQs KsTs Qc9c QcJc QcJh QcJs QcTc Qd9d QdJc QdJh QdJs QdQc QdTd QhJc QhJh QhJs QhQc QhQd QhTh Qs9s QsJc QsJh QsJs QsQc QsQd QsQh QsTs Tc8c Tc9c Td8d Td9d TdTc Th8h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh')
        }
      ]
    },
    {
      position: 'UTG',
      stackBb: 100,
      villainPosition: 'BTN',
      board: [
        'Qd',
        'Qc',
        'Js'
      ],
      heroStackSize: 97.7,
      villainStackSize: 97.7,
      actionLine: 'preflop: UTG raises 2.3bb, BTN calls 2.3bb',
      dealCombos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6c5c 6d5d 6d6c 6h5h 6h6c 6h6d 6s5s 6s6c 6s6d 6s6h 7c6c 7d6d 7d7c 7h6h 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8c7c 8d7d 8d8c 8h7h 8h8c 8h8d 8s7s 8s8c 8s8d 8s8h 9c8c 9d8d 9d9c 9h8h 9h9c 9h9d 9s8s 9s9c 9s9d 9s9h Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcKc AcKd AcKh AcKs AcQh AcQs AcTc AcTd AcTh AcTs Ad3d Ad4d Ad5d Ad6d Ad7d Ad8d Ad9d AdAc AdJc AdJd AdJh AdKc AdKd AdKh AdKs AdQh AdQs AdTc AdTd AdTh AdTs Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhAc AhAd AhJc AhJd AhJh AhKc AhKd AhKh AhKs AhQh AhQs AhTc AhTd AhTh AhTs As3s As4s As5s As6s As7s As8s As9s AsAc AsAd AsAh AsJc AsJd AsJh AsKc AsKd AsKh AsKs AsQh AsQs AsTc AsTd AsTh AsTs Jc9c JcTc JcTd JcTh JcTs Jd9d JdJc JdTc JdTd JdTh JdTs Jh9h JhJc JhJd JhTc JhTd JhTh JhTs Kc8c Kc9c KcJc KcJd KcJh KcQh KcQs KcTc Kd8d Kd9d KdJc KdJd KdJh KdKc KdQh KdQs KdTd Kh8h Kh9h KhJc KhJd KhJh KhKc KhKd KhQh KhQs KhTh Ks8s Ks9s KsJc KsJd KsJh KsKc KsKd KsKh KsQh KsQs KsTs Qh9h QhJc QhJd QhJh QhTh Qs9s QsJc QsJd QsJh QsQh QsTs Tc8c Tc9c Td8d Td9d TdTc Th8h Th9h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh'),
      buckets: [
        {
          actions: [
            'bet_25pct'
          ],
          combos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6c5c 6d5d 6d6c 6h5h 6h6c 6h6d 6s5s 6s6c 6s6d 6s6h 7c6c 7d6d 7d7c 7h6h 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8c7c 8d7d 8d8c 8h7h 8h8c 8h8d 8s7s 8s8c 8s8d 8s8h 9c8c 9d8d 9d9c 9h8h 9h9c 9h9d 9s8s 9s9c 9s9d 9s9h Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcKc AcKd AcKh AcKs AcQh AcQs AcTc AcTd AcTh AcTs Ad3d Ad4d Ad5d Ad6d Ad7d Ad8d Ad9d AdAc AdJc AdJd AdJh AdKc AdKd AdKh AdKs AdQh AdQs AdTc AdTd AdTh AdTs Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhAc AhAd AhJc AhJd AhJh AhKc AhKd AhKh AhKs AhQh AhQs AhTc AhTd AhTh AhTs As3s As4s As5s As6s As7s As8s As9s AsAc AsAd AsAh AsJc AsJd AsJh AsKc AsKd AsKh AsKs AsQh AsQs AsTc AsTd AsTh AsTs Jc9c JcTc JcTd JcTh JcTs Jd9d JdJc JdTc JdTd JdTh JdTs Jh9h JhJc JhJd JhTc JhTd JhTh JhTs Kc8c Kc9c KcJc KcJd KcJh KcQh KcQs KcTc Kd8d Kd9d KdJc KdJd KdJh KdKc KdQh KdQs KdTd Kh8h Kh9h KhJc KhJd KhJh KhKc KhKd KhQh KhQs KhTh Ks8s Ks9s KsJc KsJd KsJh KsKc KsKd KsKh KsQh KsQs KsTs Qh9h QhJc QhJd QhJh QhTh Qs9s QsJc QsJd QsJh QsQh QsTs Tc8c Tc9c Td8d Td9d TdTc Th8h Th9h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh')
        }
      ]
    },
    {
      position: 'UTG',
      stackBb: 100,
      villainPosition: 'BTN',
      board: [
        'Qh',
        '8h',
        '3h'
      ],
      heroStackSize: 97.7,
      villainStackSize: 97.7,
      actionLine: 'preflop: UTG raises 2.3bb, BTN calls 2.3bb',
      dealCombos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3s3c 3s3d 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6c5c 6d5d 6d6c 6h5h 6h6c 6h6d 6s5s 6s6c 6s6d 6s6h 7c6c 7d6d 7d7c 7h6h 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8c7c 8d7d 8d8c 8s7s 8s8c 8s8d 9c8c 9d8d 9d9c 9h9c 9h9d 9s8s 9s9c 9s9d 9s9h Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcKc AcKd AcKh AcKs AcQc AcQd AcQs AcTc AcTd AcTh AcTs Ad3d Ad4d Ad5d Ad6d Ad7d Ad8d Ad9d AdAc AdJc AdJd AdJh AdJs AdKc AdKd AdKh AdKs AdQc AdQd AdQs AdTc AdTd AdTh AdTs Ah4h Ah5h Ah6h Ah7h Ah9h AhAc AhAd AhJc AhJd AhJh AhJs AhKc AhKd AhKh AhKs AhQc AhQd AhQs AhTc AhTd AhTh AhTs As3s As4s As5s As6s As7s As8s As9s AsAc AsAd AsAh AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsKs AsQc AsQd AsQs AsTc AsTd AsTh AsTs Jc9c JcTc JcTh Jd9d JdJc JdTd JdTh Jh9h JhJc JhJd JhTc JhTd JhTh JhTs Js9s JsJc JsJd JsJh JsTh JsTs Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQs KcTc Kd8d Kd9d KdJc KdJd KdJh KdJs KdKc KdQc KdQd KdQs KdTd Kh9h KhJc KhJd KhJh KhJs KhKc KhKd KhQc KhQd KhQs KhTh Ks8s Ks9s KsJc KsJd KsJh KsJs KsKc KsKd KsKh KsQc KsQd KsQs KsTs Qc9c QcJc QcJd QcJh QcJs QcTc Qd9d QdJc QdJd QdJh QdJs QdQc QdTd Qs9s QsJc QsJd QsJh QsJs QsQc QsQd QsTs Tc8c Tc9c Td8d Td9d TdTc Th9h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh'),
      buckets: [
        {
          actions: [
            'bet_25pct'
          ],
          combos: expand('2d2c 2s2c 2s2d 3d3c 3s3c 3s3d 4d4c 4s4c 4s4d 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6d6c 6h6c 6h6d 6s6c 6s6d 6s6h 7h6h 7h7c 7h7d 7s7h 8c7c 8d7d 8d8c 8s7s 8s8c 8s8d 9c8c 9d8d 9d9c 9h9c 9h9d 9s8s 9s9c 9s9d 9s9h Ac3c Ac4c Ac5c Ac9c AcJc AcJd AcJh AcJs AcKd AcKh AcKs AcQc AcQd AcQs AcTc AcTd AcTs Ad3d Ad4d Ad5d Ad9d AdAc AdJc AdJd AdJh AdJs AdKc AdKh AdKs AdQc AdQd AdQs AdTc AdTd AdTs Ah4h Ah5h Ah6h Ah7h Ah9h AhAc AhAd AhJc AhJd AhJh AhJs AhKc AhKd AhKh AhKs AhQc AhQd AhQs AhTc AhTd AhTh AhTs As3s As4s As5s As9s AsAc AsAd AsAh AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsQc AsQd AsQs AsTc AsTd AsTs Jc9c JcTc Jd9d JdJc JdTd Jh9h JhJc JhJd JhTh Js9s JsJc JsJd JsJh JsTs Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQs KcTc Kd9d KdJc KdJd KdJh KdJs KdKc KdQc KdQd KdQs KdTd Kh9h KhJc KhJd KhJh KhJs KhKc KhKd KhQc KhQd KhQs KhTh Ks9s KsJc KsJd KsJh KsJs KsKc KsKd KsKh KsQc KsQd KsQs KsTs Qc9c QcJc QcTc Qd9d QdJd QdQc QdTd Qs9s QsJs QsQc QsQd QsTs Tc8c Tc9c Td8d Td9d TdTc Th9h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh')
        },
        {
          actions: [
            'check'
          ],
          combos: expand('2h2c 2h2d 2s2h 3d3c 3s3c 3s3d 4h4c 4h4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6c5c 6d5d 6d6c 6h5h 6h6c 6h6d 6s5s 6s6c 6s6d 6s6h 7c6c 7d6d 7d7c 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8d8c 8s8c 8s8d 9c8c 9d8d 9d9c 9h9c 9h9d 9s8s 9s9c 9s9d 9s9h Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcKc AcKd AcKh AcKs AcQc AcQd AcQs AcTc AcTh Ad4d Ad5d Ad6d Ad7d Ad8d Ad9d AdAc AdJc AdJd AdJh AdJs AdKc AdKd AdKh AdKs AdQc AdQd AdQs AdTd AdTh Ah4h Ah5h Ah6h Ah7h Ah9h AhAc AhAd AhJc AhJd AhJh AhJs AhKh AhQc AhQd AhQs AhTh As4s As5s As6s As7s As8s As9s AsAc AsAd AsAh AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsKs AsQc AsQd AsQs AsTh AsTs Jc9c JcTc JcTh Jd9d JdJc JdTd JdTh Jh9h JhJc JhJd JhTc JhTd JhTh JhTs Js9s JsJc JsJd JsJh JsTh JsTs Kc8c Kc9c KcJc KcQc KcQd KcQs KcTc Kd8d Kd9d KdJd KdKc KdQc KdQd KdQs KdTd Kh9h KhJc KhJd KhJh KhJs KhKc KhKd KhQc KhQd KhQs KhTh Ks8s Ks9s KsJs KsKc KsKd KsKh KsQc KsQd KsQs KsTs Qc9c QcJc QcJd QcJh QcJs QcTc Qd9d QdJc QdJd QdJh QdJs QdQc QdTd Qs9s QsJc QsJd QsJh QsJs QsQc QsQd QsTs Tc8c Tc9c Td8d Td9d TdTc Th9h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh')
        }
      ]
    },
    {
      position: 'UTG',
      stackBb: 100,
      villainPosition: 'BTN',
      board: [
        'Tc',
        '7d',
        '6s'
      ],
      heroStackSize: 97.7,
      villainStackSize: 97.7,
      actionLine: 'preflop: UTG raises 2.3bb, BTN calls 2.3bb',
      dealCombos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6c5c 6d5d 6d6c 6h5h 6h6c 6h6d 7c6c 7h6h 7h7c 7s7c 7s7h 8c7c 8d8c 8h7h 8h8c 8h8d 8s7s 8s8c 8s8d 8s8h 9c8c 9d8d 9d9c 9h8h 9h9c 9h9d 9s8s 9s9c 9s9d 9s9h Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcKc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTd AcTh AcTs Ad3d Ad4d Ad5d Ad6d Ad8d Ad9d AdAc AdJc AdJd AdJh AdJs AdKc AdKd AdKh AdKs AdQc AdQd AdQh AdQs AdTd AdTh AdTs Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhAc AhAd AhJc AhJd AhJh AhJs AhKc AhKd AhKh AhKs AhQc AhQd AhQh AhQs AhTd AhTh AhTs As3s As4s As5s As7s As8s As9s AsAc AsAd AsAh AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTd AsTh AsTs Jc9c Jd9d JdJc JdTd JdTs Jh9h JhJc JhJd JhTh Js9s JsJc JsJd JsJh JsTd JsTs Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQh KcQs Kd8d Kd9d KdJc KdJd KdJh KdJs KdKc KdQc KdQd KdQh KdQs KdTd Kh8h Kh9h KhJc KhJd KhJh KhJs KhKc KhKd KhQc KhQd KhQh KhQs KhTh Ks8s Ks9s KsJc KsJd KsJh KsJs KsKc KsKd KsKh KsQc KsQd KsQh KsQs KsTs Qc9c QcJc QcJd QcJh QcJs Qd9d QdJc QdJd QdJh QdJs QdQc QdTd Qh9h QhJc QhJd QhJh QhJs QhQc QhQd QhTh Qs9s QsJc QsJd QsJh QsJs QsQc QsQd QsQh QsTs Td8d Td9d Th8h Th9h ThTd Ts8s Ts9s TsTd TsTh'),
      buckets: [
        {
          actions: [
            'bet_25pct'
          ],
          combos: expand('4d4c 4s4c 4s4d 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6c5c 6d6c 6h6c 6h6d 7c6c 7h6h 7h7c 7s7c 7s7h 8c7c 8h8c 8h8d 8s8h 9c8c 9d8d 9d9c 9h8h 9h9c 9h9d 9s8s 9s9c 9s9d 9s9h Ac7c Ac8c Ac9c AcJc AcJh AcKc AcKd AcKh AcKs AcQc AcQh AcTd AcTh AcTs Ad8d Ad9d AdAc AdJd AdJh AdJs AdKc AdKh AdKs AdQc AdQd AdQh AdQs AdTd AdTs Ah6h Ah7h AhAc AhAd AhJh AhKh AhQc AhQd AhQh AhQs AhTd AhTh AhTs As7s As8s As9s AsAc AsAd AsAh AsJd AsJh AsJs AsKc AsKd AsKh AsQc AsQd AsQh AsQs AsTs Jc9c Jd9d JdTd JdTs Jh9h JhJc JhJd JhTh Js9s JsJd JsJh JsTd JsTs Kc8c Kc9c KcJc KcQc Kd8d Kd9d KdJd KdKc KdQd KdTd Kh8h Kh9h KhJd KhJh KhJs KhKc KhKd KhQc KhQd KhQs KhTh Ks8s Ks9s KsJs KsKc KsKd KsKh KsQs KsTs Qc9c QcJc Qd9d QdJd QdQc QdTd Qh9h QhJh QhQc QhQd QhTh Qs9s QsJs QsQc QsQd QsQh QsTs Td8d Td9d Th9h ThTd Ts8s Ts9s TsTd TsTh')
        },
        {
          actions: [
            'check'
          ],
          combos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6c5c 6d5d 6d6c 6h5h 6h6c 6h6d 7c6c 7h7c 7s7c 7s7h 8c7c 8d8c 8h7h 8h8c 8h8d 8s7s 8s8c 8s8d 8s8h 9c8c 9d8d 9d9c 9h8h 9h9c 9h9d 9s8s 9s9c 9s9d 9s9h Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcKc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTd AcTh Ad3d Ad4d Ad5d Ad6d Ad8d Ad9d AdAc AdJc AdJd AdJh AdJs AdKc AdKd AdKh AdKs AdQc AdQd AdQh AdQs AdTd AdTh AdTs Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhAc AhAd AhJc AhJd AhJh AhJs AhKc AhKd AhKs AhQc AhQd AhQh AhQs AhTd AhTh AhTs As3s As4s As5s As7s As8s As9s AsAc AsAd AsAh AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTd AsTh AsTs Jc9c Jd9d JdJc JdTd Jh9h JhJc JhJd JhTh Js9s JsJc JsJd JsJh JsTs Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQh KcQs Kd8d Kd9d KdJc KdJd KdJh KdJs KdKc KdQc KdQd KdQh KdQs KdTd Kh8h Kh9h KhJc KhJd KhJh KhJs KhKc KhKd KhQc KhQd KhQh KhQs KhTh Ks8s Ks9s KsJc KsJd KsJh KsJs KsKc KsKd KsKh KsQc KsQd KsQh KsQs KsTs Qc9c QcJc QcJd QcJh QcJs Qd9d QdJc QdJd QdJh QdJs QdQc QdTd Qh9h QhJc QhJd QhJh QhJs QhQc QhQd QhTh Qs9s QsJc QsJd QsJh QsJs QsQc QsQd QsQh QsTs Td8d Td9d Th8h Th9h ThTd Ts8s Ts9s TsTd TsTh')
        }
      ]
    }
  ]
};

export default pack;
