// Generated by scripts/import-ct-curriculum.ts. Do not edit by hand.
import type { RangePack } from '../types';

const expand = (value: string): string[] => value.split(' ');

const pack: RangePack = {
  slug: 'out-of-position-c-bet-utg-btn-flop-baseline-2',
  title: 'Out-of-position c-bet: UTG vs BTN - Flop (30bb)',
  description: 'Board-aware continuation-bet and barrel practice out of position.',
  scenario: 'CBET_OOP',
  street: 'flop',
  tier: 'advanced',
  methodology: 'gto_cev',
  source: {
    kind: 'brand_neutralized_snapshot_config',
    capturedAt: '2026-07-18',
    path: 'research/ct-trainer-2026-07-18/',
    sha256: 'e98ce5eab720f8b862956df80b68f55c27cc38053d99e94f31b162e047766a1c'
  },
  cells: [
    {
      position: 'UTG',
      stackBb: 30,
      villainPosition: 'BTN',
      board: [
        '6d',
        '4h',
        '3c'
      ],
      heroStackSize: 27.9,
      villainStackSize: 27.9,
      actionLine: 'preflop: UTG raises 2.1bb, BTN calls 2.1bb',
      dealCombos: expand('4d4c 4s4c 4s4d 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6h6c 6s6c 6s6h 7d7c 7h7c 7h7d 7s7c 7s7d 7s7h 8d8c 8h8c 8h8d 8s8c 8s8d 8s8h 9c8c 9d8d 9d9c 9h8h 9h9c 9h9d 9s8s 9s9c 9s9d 9s9h Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcKc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad3d Ad4d Ad5d Ad7d Ad8d Ad9d AdAc AdJc AdJd AdJh AdJs AdKc AdKd AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah3h Ah5h Ah6h Ah7h Ah8h Ah9h AhAc AhAd AhJc AhJd AhJh AhJs AhKc AhKd AhKh AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs As3s As4s As5s As6s As7s As8s As9s AsAc AsAd AsAh AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc9c JcTc JcTd JcTh JcTs Jd9d JdJc JdTc JdTd JdTh JdTs Jh9h JhJc JhJd JhTc JhTd JhTh JhTs Js9s JsJc JsJd JsJh JsTc JsTd JsTh JsTs Kc6c Kc7c Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc KcTd KcTh KcTs Kd7d Kd8d Kd9d KdJc KdJd KdJh KdJs KdKc KdQc KdQd KdQh KdQs KdTc KdTd KdTh KdTs Kh6h Kh7h Kh8h Kh9h KhJc KhJd KhJh KhJs KhKc KhKd KhQc KhQd KhQh KhQs KhTc KhTd KhTh KhTs Ks6s Ks7s Ks8s Ks9s KsJc KsJd KsJh KsJs KsKc KsKd KsKh KsQc KsQd KsQh KsQs KsTc KsTd KsTh KsTs Qc9c QcJc QcJd QcJh QcJs QcTc Qd9d QdJc QdJd QdJh QdJs QdQc QdTd Qh9h QhJc QhJd QhJh QhJs QhQc QhQd QhTh Qs9s QsJc QsJd QsJh QsJs QsQc QsQd QsQh QsTs Tc8c Tc9c Td8d Td9d TdTc Th8h Th9h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh'),
      buckets: [
        {
          actions: [
            'bet_40pct'
          ],
          combos: expand('4d4c 4s4c 4s4d 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6h6c 6s6c 6s6h 7d7c 7h7c 7h7d 7s7c 7s7h 8d8c 8h8c 8h8d 8s8c 8s8d 8s8h 9c8c 9d8d 9d9c 9h8h 9h9c 9h9d 9s8s 9s9c 9s9d 9s9h Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcKc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad3d Ad4d Ad5d Ad7d Ad8d Ad9d AdAc AdJc AdJd AdJh AdJs AdKc AdKd AdKh AdKs AdQd AdQs AdTc AdTd AdTh AdTs Ah3h Ah5h Ah6h Ah7h Ah8h Ah9h AhAc AhAd AhJc AhJd AhJh AhJs AhKc AhKd AhKh AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs As3s As5s As6s As7s As8s As9s AsAc AsAh AsJs AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsQs Jc9c JcTc Jd9d JdJc JdTd Jh9h JhJc JhJd JhTh JsJc JsJd JsJh Kc7c Kc8c Kc9c KcJc KcQc KcQs KcTc Kd7d Kd8d Kd9d KdJd KdKc KdQs KdTd Kh7h Kh8h Kh9h KhJh KhKc KhKd KhQh KhQs KhTh Ks7s Ks9s KsJc KsJd KsJh KsJs KsKc KsKd KsKh KsTs Qc9c QcJc QcTc Qd9d QdJd QdQc QdTd Qh9h QhJh QhQc QhQd QhTh QsQc QsQd QsQh Tc8c Tc9c Td8d Td9d TdTc Th8h Th9h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh')
        },
        {
          actions: [
            'check'
          ],
          combos: expand('4d4c 4s4c 4s4d 5d5c 5h5c 5h5d 6h6c 6s6c 6s6h 7h7c 7s7c 7s7d 7s7h 8d8c 8h8c 8h8d 8s8c 8s8d 8s8h 9c8c 9d8d 9d9c 9h8h 9h9c 9h9d 9s8s 9s9c 9s9d 9s9h Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcKc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad3d Ad5d Ad7d Ad8d Ad9d AdAc AdJc AdJd AdJh AdJs AdKc AdKd AdKh AdKs AdQc AdQd AdQh AdTc AdTd AdTh AdTs Ah3h Ah5h Ah6h Ah7h Ah8h Ah9h AhAc AhAd AhJc AhJd AhJh AhJs AhKc AhKd AhKh AhKs AhQc AhQd AhQh AhTc AhTd AhTh AhTs As3s As4s As5s As7s As9s AsAc AsAd AsAh AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsKs AsTc AsTd AsTh AsTs Jc9c JcTc JcTd JcTh JcTs Jd9d JdJc JdTc JdTd JdTh JdTs Jh9h JhJc JhJd JhTc JhTd JhTh JhTs Js9s JsJc JsJd JsJh JsTc JsTd JsTh JsTs Kc6c Kc7c Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc KcTd KcTh KcTs Kd7d Kd8d Kd9d KdJc KdJd KdJh KdJs KdKc KdQc KdQd KdQh KdQs KdTc KdTd KdTh KdTs Kh6h Kh7h Kh8h Kh9h KhJc KhJd KhJh KhJs KhKc KhKd KhQc KhQd KhQh KhQs KhTc KhTd KhTh KhTs Ks6s Ks8s Ks9s KsJc KsJd KsJh KsJs KsKc KsKd KsKh KsQc KsQd KsQh KsQs KsTc KsTd KsTh KsTs Qc9c QcJc QcJd QcJh QcJs QcTc Qd9d QdJc QdJd QdJh QdJs QdQc QdTd Qh9h QhJc QhJd QhJh QhJs QhQc QhQd QhTh Qs9s QsJc QsJd QsJh QsJs QsQc QsQd QsQh QsTs Tc8c Tc9c Td8d Td9d TdTc Th8h Th9h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh')
        }
      ]
    },
    {
      position: 'UTG',
      stackBb: 30,
      villainPosition: 'BTN',
      board: [
        '8s',
        '3s',
        '2s'
      ],
      heroStackSize: 27.9,
      villainStackSize: 27.9,
      actionLine: 'preflop: UTG raises 2.1bb, BTN calls 2.1bb',
      dealCombos: expand('4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6d6c 6h6c 6h6d 6s6c 6s6d 6s6h 7d7c 7h7c 7h7d 7s7c 7s7d 7s7h 8d8c 8h8c 8h8d 9c8c 9d8d 9d9c 9h8h 9h9c 9h9d 9s9c 9s9d 9s9h Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcKc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad3d Ad4d Ad5d Ad6d Ad7d Ad8d Ad9d AdAc AdJc AdJd AdJh AdJs AdKc AdKd AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhAc AhAd AhJc AhJd AhJh AhJs AhKc AhKd AhKh AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs As4s As5s As6s As7s As9s AsAc AsAd AsAh AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc9c JcTc JcTd JcTh JcTs Jd9d JdJc JdTc JdTd JdTh JdTs Jh9h JhJc JhJd JhTc JhTd JhTh JhTs Js9s JsJc JsJd JsJh JsTc JsTd JsTh JsTs Kc6c Kc7c Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc KcTd KcTh KcTs Kd6d Kd7d Kd8d Kd9d KdJc KdJd KdJh KdJs KdKc KdQc KdQd KdQh KdQs KdTc KdTd KdTh KdTs Kh6h Kh7h Kh8h Kh9h KhJc KhJd KhJh KhJs KhKc KhKd KhQc KhQd KhQh KhQs KhTc KhTd KhTh KhTs Ks6s Ks7s Ks9s KsJc KsJd KsJh KsJs KsKc KsKd KsKh KsQc KsQd KsQh KsQs KsTc KsTd KsTh KsTs Qc9c QcJc QcJd QcJh QcJs QcTc Qd9d QdJc QdJd QdJh QdJs QdQc QdTd Qh9h QhJc QhJd QhJh QhJs QhQc QhQd QhTh Qs9s QsJc QsJd QsJh QsJs QsQc QsQd QsQh QsTs Tc8c Tc9c Td8d Td9d TdTc Th8h Th9h ThTc ThTd Ts9s TsTc TsTd TsTh'),
      buckets: [
        {
          actions: [
            'bet_25pct'
          ],
          combos: expand('4d4c 4h4c 4h4d 5d5c 5h5c 5h5d 6s6c 6s6d 6s6h 7d7c 7h7c 7h7d 8d8c 8h8c 8h8d 9s9c 9s9d 9s9h Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcKd AcKh AcKs Ad3d Ad4d Ad5d Ad6d Ad7d Ad8d Ad9d AdKc AdKh AdKs Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhKc AhKd AhKs As4s As6s As7s As9s AsAc AsAd AsAh AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsTc AsTd AsTh Jc9c JcTc Jd9d JdJc JdTd Jh9h JhJc JhJd JhTh Kc8c KcJs KcQc KcQd KcQh KcQs Kd8d KdJs KdQc KdQd KdQh KdQs Kh8h KhJs KhQc KhQd KhQh KhQs Ks6s Ks9s KsJc KsJd KsJh KsKc KsKd KsKh KsTc KsTd KsTh Qc9c QcJd QcJh QcTc Qd9d QdJc QdJh QdQc QdTd Qh9h QhJc QhJd QhQc QhQd QhTh QsJs QsQc QsQd QsQh QsTs Tc8c Tc9c Td8d Td9d Th8h Th9h Ts9s TsTc TsTd TsTh')
        },
        {
          actions: [
            'check'
          ],
          combos: expand('4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6d6c 6h6c 6h6d 6s6c 6s6d 6s6h 7d7c 7h7c 7h7d 7s7c 7s7d 7s7h 8d8c 8h8c 8h8d 9c8c 9d8d 9d9c 9h8h 9h9c 9h9d 9s9c 9s9d 9s9h Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcKc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad3d Ad4d Ad5d Ad6d Ad7d Ad8d Ad9d AdAc AdJc AdJd AdJh AdJs AdKc AdKd AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhAc AhAd AhJc AhJd AhJh AhJs AhKc AhKd AhKh AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs As4s As5s As6s As7s As9s AsAc AsAd AsAh AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc9c JcTc JcTd JcTh JcTs Jd9d JdJc JdTc JdTd JdTh JdTs Jh9h JhJc JhJd JhTc JhTd JhTh JhTs Js9s JsJc JsJd JsJh JsTc JsTd JsTh JsTs Kc6c Kc7c Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc KcTd KcTh KcTs Kd6d Kd7d Kd8d Kd9d KdJc KdJd KdJh KdJs KdKc KdQc KdQd KdQh KdQs KdTc KdTd KdTh KdTs Kh6h Kh7h Kh8h Kh9h KhJc KhJd KhJh KhJs KhKc KhKd KhQc KhQd KhQh KhQs KhTc KhTd KhTh KhTs Ks6s Ks7s Ks9s KsJc KsJd KsJh KsJs KsKc KsKd KsKh KsQc KsQd KsQh KsQs KsTc KsTd KsTh KsTs Qc9c QcJc QcJd QcJh QcJs QcTc Qd9d QdJc QdJd QdJh QdJs QdQc QdTd Qh9h QhJc QhJd QhJh QhJs QhQc QhQd QhTh Qs9s QsJc QsJd QsJh QsJs QsQc QsQd QsQh QsTs Tc8c Tc9c Td8d Td9d TdTc Th8h Th9h ThTc ThTd Ts9s TsTc TsTd TsTh')
        }
      ]
    },
    {
      position: 'UTG',
      stackBb: 30,
      villainPosition: 'BTN',
      board: [
        '9h',
        '6d',
        '2h'
      ],
      heroStackSize: 27.9,
      villainStackSize: 27.9,
      actionLine: 'preflop: UTG raises 2.1bb, BTN calls 2.1bb',
      dealCombos: expand('4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6h6c 6s6c 6s6h 7d7c 7h7c 7h7d 7s7c 7s7d 7s7h 8d8c 8h8c 8h8d 8s8c 8s8d 8s8h 9c8c 9d8d 9d9c 9s8s 9s9c 9s9d Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcKc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad3d Ad4d Ad5d Ad7d Ad8d Ad9d AdAc AdJc AdJd AdJh AdJs AdKc AdKd AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h AhAc AhAd AhJc AhJd AhJh AhJs AhKc AhKd AhKh AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs As3s As4s As5s As6s As7s As8s As9s AsAc AsAd AsAh AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc9c JcTc JcTd JcTh JcTs Jd9d JdJc JdTc JdTd JdTh JdTs JhJc JhJd JhTc JhTd JhTh JhTs Js9s JsJc JsJd JsJh JsTc JsTd JsTh JsTs Kc6c Kc7c Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc KcTd KcTh KcTs Kd7d Kd8d Kd9d KdJc KdJd KdJh KdJs KdKc KdQc KdQd KdQh KdQs KdTc KdTd KdTh KdTs Kh6h Kh7h Kh8h KhJc KhJd KhJh KhJs KhKc KhKd KhQc KhQd KhQh KhQs KhTc KhTd KhTh KhTs Ks6s Ks7s Ks8s Ks9s KsJc KsJd KsJh KsJs KsKc KsKd KsKh KsQc KsQd KsQh KsQs KsTc KsTd KsTh KsTs Qc9c QcJc QcJd QcJh QcJs QcTc Qd9d QdJc QdJd QdJh QdJs QdQc QdTd QhJc QhJd QhJh QhJs QhQc QhQd QhTh Qs9s QsJc QsJd QsJh QsJs QsQc QsQd QsQh QsTs Tc8c Tc9c Td8d Td9d TdTc Th8h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh'),
      buckets: [
        {
          actions: [
            'bet_67pct'
          ],
          combos: expand('5h5c 5s5h 6s6c 7s7c 8h8c 8s8h 9c8c 9d9c 9s8s 9s9c 9s9d Ac9c AcJc AcJd AcJh AcKc AcKh AcKs AcQc AcQh AcQs AcTh Ad3d Ad4d Ad5d Ad7d Ad9d AdAc AdJc AdJh AdJs AdKd AdKh AdQc AdQh AdQs AdTh Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h AhAc AhAd AhJc AhJs AhKc AhKh AhKs AhQc AhQs AhTc AhTd AhTh AhTs As9s AsAc AsAd AsAh AsJd AsJh AsJs AsKc AsKh AsKs AsQc AsQh AsQs AsTh Jc9c JcTc JcTh Jd9d JdJc JdTd JdTh JhJc JhJd JhTc JhTd JhTh JhTs Js9s JsJc JsJd JsJh JsTh JsTs Kc9c KcJh KcQd KcQh KcTh Kd7d Kd8d Kd9d KdJd KdJh KdKc KdQc KdQd KdQs KdTd KdTh Kh7h Kh8h KhJc KhJd KhJh KhJs KhKc KhKd KhQc KhQd KhQh KhQs KhTc KhTd KhTh KhTs Ks9s KsJh KsKc KsKd KsKh KsQd KsQh KsTh Qc9c QcJd QcJh QcTc Qd9d QdJd QdJh QdQc QdTd QhJc QhJd QhJh QhJs QhQc QhQd QhTh Qs9s QsJd QsJh QsQc QsQd QsQh QsTs Tc8c Td8d Td9d TdTc Th8h ThTc ThTd Ts8s TsTc TsTd TsTh')
        },
        {
          actions: [
            'check'
          ],
          combos: expand('4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6h6c 6s6c 6s6h 7d7c 7h7c 7h7d 7s7c 7s7d 7s7h 8d8c 8h8c 8h8d 8s8c 8s8d 8s8h 9c8c 9d8d 9d9c 9s8s 9s9c 9s9d Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcKc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad3d Ad4d Ad5d Ad7d Ad8d Ad9d AdAc AdJc AdJd AdJh AdJs AdKc AdKd AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h AhAc AhAd AhJc AhJd AhJh AhJs AhKc AhKd AhKh AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs As3s As4s As5s As6s As7s As8s As9s AsAc AsAd AsAh AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc9c JcTc JcTd JcTs Jd9d JdJc JdTc JdTd JdTs JhJc JhJd JhTc JhTd JhTs Js9s JsJc JsJd JsJh JsTc JsTd JsTs Kc6c Kc7c Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc KcTd KcTh KcTs Kd7d Kd8d Kd9d KdJc KdJd KdJh KdJs KdKc KdQc KdQh KdQs KdTc KdTd KdTs Kh6h Kh7h Kh8h KhJc KhJd KhJh KhJs KhKc KhKd KhQc KhQd KhQh KhQs KhTc KhTd KhTh KhTs Ks6s Ks7s Ks8s Ks9s KsJc KsJd KsJh KsJs KsKd KsKh KsQc KsQd KsQh KsQs KsTc KsTd KsTh KsTs Qc9c QcJc QcJd QcJh QcJs QcTc Qd9d QdJc QdJd QdJh QdJs QdQc QdTd QhJc QhJd QhJh QhJs QhQc QhQd QhTh Qs9s QsJc QsJd QsJh QsJs QsQc QsQd QsQh QsTs Tc8c Tc9c Td8d Td9d TdTc Th8h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh')
        }
      ]
    },
    {
      position: 'UTG',
      stackBb: 30,
      villainPosition: 'BTN',
      board: [
        'Ac',
        'Kc',
        '3d'
      ],
      heroStackSize: 27.9,
      villainStackSize: 27.9,
      actionLine: 'preflop: UTG raises 2.1bb, BTN calls 2.1bb',
      dealCombos: expand('4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6d6c 6h6c 6h6d 6s6c 6s6d 6s6h 7d7c 7h7c 7h7d 7s7c 7s7d 7s7h 8d8c 8h8c 8h8d 8s8c 8s8d 8s8h 9c8c 9d8d 9d9c 9h8h 9h9c 9h9d 9s8s 9s9c 9s9d 9s9h Ad4d Ad5d Ad6d Ad7d Ad8d Ad9d AdJc AdJd AdJh AdJs AdKd AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhAd AhJc AhJd AhJh AhJs AhKd AhKh AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs As3s As4s As5s As6s As7s As8s As9s AsAd AsAh AsJc AsJd AsJh AsJs AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc9c JcTc JcTd JcTh JcTs Jd9d JdJc JdTc JdTd JdTh JdTs Jh9h JhJc JhJd JhTc JhTd JhTh JhTs Js9s JsJc JsJd JsJh JsTc JsTd JsTh JsTs Kd6d Kd7d Kd8d Kd9d KdJc KdJd KdJh KdJs KdQc KdQd KdQh KdQs KdTc KdTd KdTh KdTs Kh6h Kh7h Kh8h Kh9h KhJc KhJd KhJh KhJs KhKd KhQc KhQd KhQh KhQs KhTc KhTd KhTh KhTs Ks6s Ks7s Ks8s Ks9s KsJc KsJd KsJh KsJs KsKd KsKh KsQc KsQd KsQh KsQs KsTc KsTd KsTh KsTs Qc9c QcJc QcJd QcJh QcJs QcTc Qd9d QdJc QdJd QdJh QdJs QdQc QdTd Qh9h QhJc QhJd QhJh QhJs QhQc QhQd QhTh Qs9s QsJc QsJd QsJh QsJs QsQc QsQd QsQh QsTs Tc8c Tc9c Td8d Td9d TdTc Th8h Th9h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh'),
      buckets: [
        {
          actions: [
            'bet_103pct'
          ],
          combos: expand('4d4c 4h4c 4s4c 5d5c 5h5c 5s5c 6d6c 6h6c 6s6c 7d7c 7h7c 7s7c 8h8c 8s8c Ad6d Ad7d AdJh AdJs AdKd AdKh AdKs AdQc AdQd AdQh AdQs AdTh AdTs Ah3h Ah6h Ah8h Ah9h AhJc AhJd AhJh AhJs AhKd AhKh AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTs As3s As6s As8s As9s AsJc AsJd AsJh AsJs AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTc AsTd AsTh Jc9c JcTd JcTh JcTs JdTc JdTd JdTh JdTs JhTc JhTd JhTh JhTs JsTc JsTd JsTh JsTs Kd8d KdJh KdJs KdTh KdTs Kh9h KhJd KhJh KhQd KhQh KhQs KhTd Ks9s KsJd KsJs KsQd KsQh KsQs KsTd Qc9c QcJc QcJd QcJh QcJs QcTc QdJc QdJd QdJh QdJs QdTd QhJc QhJd QhJs QhTh QsJc QsJd QsJh QsTs Tc8c Tc9c TdTc ThTc TsTc')
        },
        {
          actions: [
            'check'
          ],
          combos: expand('4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6d6c 6h6c 6h6d 6s6c 6s6d 6s6h 7d7c 7h7c 7h7d 7s7c 7s7d 7s7h 8d8c 8h8c 8h8d 8s8c 8s8d 8s8h 9c8c 9d8d 9d9c 9h8h 9h9c 9h9d 9s8s 9s9c 9s9d 9s9h Ad4d Ad5d Ad6d Ad7d Ad8d Ad9d AdJc AdJd AdJh AdJs AdKd AdQc AdQh AdQs AdTc AdTd AdTh AdTs Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhAd AhJc AhJd AhJh AhJs AhKd AhKh AhKs AhQc AhQd AhTc AhTd AhTh AhTs As3s As4s As5s As6s As7s As8s As9s AsAd AsAh AsJc AsJd AsJh AsJs AsKd AsKh AsKs AsQc AsQd AsTc AsTd AsTh AsTs Jc9c JcTc Jd9d JdJc Jh9h JhJc JhJd JhTc Js9s JsJc JsJd JsJh JsTc Kd6d Kd7d Kd8d Kd9d KdJc KdJd KdJh KdJs KdQc KdQd KdQh KdQs KdTc KdTd KdTh KdTs Kh6h Kh7h Kh8h Kh9h KhJc KhJd KhJh KhJs KhKd KhQc KhQd KhQh KhQs KhTc KhTd KhTh KhTs Ks6s Ks7s Ks8s Ks9s KsJc KsJd KsJh KsJs KsKd KsKh KsQc KsQd KsQh KsQs KsTc KsTd KsTh KsTs Qc9c QcJc QcJh QcJs QcTc Qd9d QdJd QdJh QdJs QdQc Qh9h QhJd QhJh QhJs QhQc QhQd Qs9s QsJd QsJh QsJs QsQc QsQd QsQh Tc9c Td8d Td9d TdTc Th8h Th9h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh')
        }
      ]
    },
    {
      position: 'UTG',
      stackBb: 30,
      villainPosition: 'BTN',
      board: [
        'Ad',
        'Jh',
        'Th'
      ],
      heroStackSize: 27.9,
      villainStackSize: 27.9,
      actionLine: 'preflop: UTG raises 2.1bb, BTN calls 2.1bb',
      dealCombos: expand('4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6d6c 6h6c 6h6d 6s6c 6s6d 6s6h 7d7c 7h7c 7h7d 7s7c 7s7d 7s7h 8d8c 8h8c 8h8d 8s8c 8s8d 8s8h 9c8c 9d8d 9d9c 9h8h 9h9c 9h9d 9s8s 9s9c 9s9d 9s9h Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJs AcKc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTs Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhAc AhJc AhJd AhJs AhKc AhKd AhKh AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTs As3s As4s As5s As6s As7s As8s As9s AsAc AsAh AsJc AsJd AsJs AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTc AsTd AsTs Jc9c JcTc JcTd JcTs Jd9d JdJc JdTc JdTd JdTs Js9s JsJc JsJd JsTc JsTd JsTs Kc6c Kc7c Kc8c Kc9c KcJc KcJd KcJs KcQc KcQd KcQh KcQs KcTc KcTd KcTs Kd6d Kd7d Kd8d Kd9d KdJc KdJd KdJs KdKc KdQc KdQd KdQh KdQs KdTc KdTd KdTs Kh6h Kh7h Kh8h Kh9h KhJc KhJd KhJs KhKc KhKd KhQc KhQd KhQh KhQs KhTc KhTd KhTs Ks6s Ks7s Ks8s Ks9s KsJc KsJd KsJs KsKc KsKd KsKh KsQc KsQd KsQh KsQs KsTc KsTd KsTs Qc9c QcJc QcJd QcJs QcTc Qd9d QdJc QdJd QdJs QdQc QdTd Qh9h QhJc QhJd QhJs QhQc QhQd Qs9s QsJc QsJd QsJs QsQc QsQd QsQh QsTs Tc8c Tc9c Td8d Td9d TdTc Ts8s Ts9s TsTc TsTd'),
      buckets: [
        {
          actions: [
            'bet_25pct'
          ],
          combos: expand('4h4c 4s4h 5d5c 5h5c 5h5d 5s5d 5s5h 6h6c 6h6d 6s6c 6s6h 7h7c 7h7d 7s7c 7s7h 8d8c 8h8c 8h8d 8s8c 8s8d 8s8h 9c8c 9d8d 9h8h 9h9c 9h9d 9s8s 9s9h Ac5c Ac7c Ac8c Ac9c AcJc AcJd AcJs AcKc AcKd AcKh AcKs AcQc AcQd AcQs AcTc AcTd AcTs Ah3h Ah4h Ah6h Ah9h AhJc AhJd AhJs AhKc AhKd AhKh AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTs As5s As7s As8s As9s AsJc AsJd AsJs AsKc AsKd AsKh AsKs AsQc AsQd AsQs AsTc AsTd AsTs JcTc JcTd JdJc JsJc JsJd JsTd JsTs Kc7c Kc8c Kc9c KcJc KcJs KcQc KcQd KcQh KcQs KcTd KcTs Kd6d Kd7d Kd8d Kd9d KdJc KdJs KdKc KdQc KdQd KdQh KdQs KdTc KdTd KdTs Kh6h Kh7h Kh8h Kh9h KhJc KhJs KhKc KhKd KhQc KhQd KhQh KhQs Ks7s Ks8s Ks9s KsJc KsJs KsKc KsKd KsKh KsQc KsQd KsQh KsQs KsTc KsTd Qc9c QcJc QcJd QcJs QcTc Qd9d QdJc QdJs QdQc QdTd Qh9h QhJc QhJd QhJs QhQd Qs9s QsJc QsJd QsJs QsQc QsQd QsTs Tc9c Td8d Td9d TdTc Ts9s TsTc TsTd')
        },
        {
          actions: [
            'check'
          ],
          combos: expand('4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6d6c 6h6c 6h6d 6s6c 6s6d 6s6h 7d7c 7h7c 7s7c 7s7d 7s7h 8d8c 8h8c 8h8d 8s8c 8s8d 8s8h 9c8c 9d9c 9h8h 9h9c 9h9d 9s8s 9s9c 9s9d 9s9h Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJs AcKc AcKd AcKh AcKs AcQc AcQh AcQs AcTc AcTs Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhAc AhKc AhKd AhKh AhKs AhQc AhQd AhQs AhTc AhTd AhTs As3s As4s As5s As6s As7s As8s As9s AsAc AsAh AsJc AsJd AsJs AsKc AsKd AsKh AsKs AsQc AsQh AsQs AsTc AsTs Jc9c JcTc JcTd JcTs Jd9d JdJc JdTc JdTd JdTs Js9s JsJc JsJd JsTc JsTd JsTs Kc6c Kc7c Kc9c KcJc KcJd KcJs KcQc KcQd KcQh KcQs KcTc KcTs Kd6d Kd7d Kd9d KdJc KdJd KdJs KdKc KdQc KdQd KdQh KdQs KdTc KdTd KdTs Kh6h Kh7h Kh8h Kh9h KhJc KhJd KhJs KhKc KhKd KhQc KhQd KhQh KhQs KhTc KhTd KhTs Ks6s Ks7s Ks9s KsJc KsJd KsJs KsKc KsKd KsKh KsQc KsQd KsQh KsQs KsTc KsTs Qc9c QcJc QcJd QcJs QcTc QdJc QdJd QdJs QdQc QdTd Qh9h QhJc QhJd QhJs QhQc QhQd Qs9s QsJc QsJd QsJs QsQc QsQd QsQh QsTs Tc8c Tc9c Td8d Td9d TdTc Ts8s Ts9s TsTc TsTd')
        }
      ]
    },
    {
      position: 'UTG',
      stackBb: 30,
      villainPosition: 'BTN',
      board: [
        'Ah',
        '9d',
        '3c'
      ],
      heroStackSize: 27.9,
      villainStackSize: 27.9,
      actionLine: 'preflop: UTG raises 2.1bb, BTN calls 2.1bb',
      dealCombos: expand('4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6d6c 6h6c 6h6d 6s6c 6s6d 6s6h 7d7c 7h7c 7h7d 7s7c 7s7d 7s7h 8d8c 8h8c 8h8d 8s8c 8s8d 8s8h 9c8c 9h8h 9h9c 9s8s 9s9c 9s9h Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcKc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad3d Ad4d Ad5d Ad6d Ad7d Ad8d AdAc AdJc AdJd AdJh AdJs AdKc AdKd AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs As3s As4s As5s As6s As7s As8s As9s AsAc AsAd AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc9c JcTc JcTd JcTh JcTs JdJc JdTc JdTd JdTh JdTs Jh9h JhJc JhJd JhTc JhTd JhTh JhTs Js9s JsJc JsJd JsJh JsTc JsTd JsTh JsTs Kc6c Kc7c Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc KcTd KcTh KcTs Kd6d Kd7d Kd8d KdJc KdJd KdJh KdJs KdKc KdQc KdQd KdQh KdQs KdTc KdTd KdTh KdTs Kh6h Kh7h Kh8h Kh9h KhJc KhJd KhJh KhJs KhKc KhKd KhQc KhQd KhQh KhQs KhTc KhTd KhTh KhTs Ks6s Ks7s Ks8s Ks9s KsJc KsJd KsJh KsJs KsKc KsKd KsKh KsQc KsQd KsQh KsQs KsTc KsTd KsTh KsTs Qc9c QcJc QcJd QcJh QcJs QcTc QdJc QdJd QdJh QdJs QdQc QdTd Qh9h QhJc QhJd QhJh QhJs QhQc QhQd QhTh Qs9s QsJc QsJd QsJh QsJs QsQc QsQd QsQh QsTs Tc8c Tc9c Td8d TdTc Th8h Th9h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh'),
      buckets: [
        {
          actions: [
            'bet_25pct'
          ],
          combos: expand('4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6d6c 6h6c 6h6d 6s6c 6s6d 6s6h 7d7c 7h7c 7h7d 7s7c 7s7d 7s7h 8d8c 8h8c 8h8d 8s8c 8s8d 8s8h 9c8c 9h8h 9h9c 9s8s 9s9c 9s9h Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcKc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad3d Ad4d Ad5d Ad6d Ad7d Ad8d AdAc AdJc AdJd AdJh AdJs AdKc AdKd AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs As3s As4s As5s As6s As8s As9s AsAc AsAd AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc9c JcTc JcTd JcTh JcTs JdJc JdTc JdTd JdTh JdTs Jh9h JhJc JhJd JhTc JhTd JhTh JhTs Js9s JsJc JsJd JsJh JsTc JsTd JsTh JsTs Kc7c Kc8c Kc9c KcJc KcJs KcQc KcQs KcTc Kd7d Kd8d KdJd KdJs KdKc KdQd KdQs KdTd Kh7h Kh8h Kh9h KhJh KhJs KhKc KhKd KhQh KhQs KhTh Ks9s KsJc KsJd KsJh KsJs KsKc KsKd KsKh KsTc KsTd KsTh KsTs Qc9c QcJc QcJd QcJh QcJs QcTc QdJc QdJd QdJh QdJs QdQc QdTd Qh9h QhJc QhJd QhJh QhJs QhQc QhQd QhTh Qs9s QsJc QsJd QsJh QsJs QsQc QsQd QsQh QsTs Tc8c Tc9c Td8d TdTc Th8h Th9h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh')
        },
        {
          actions: [
            'check'
          ],
          combos: expand('4d4c 4h4c 4h4d 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6d6c 6h6c 6h6d 6s6c 6s6d 6s6h 7s7c 7s7d 7s7h 8s8c 8s8d 8s8h 9c8c 9h8h 9h9c 9s8s 9s9c 9s9h Ac4c Ac5c Ac6c Ac7c AcJc AcJd AcJh AcKd AcKh AcQc AcQh AcQs AcTc AcTd AcTh AcTs Ad4d Ad5d Ad6d Ad7d AdAc AdJc AdJd AdJh AdKc AdKh AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs As3s As5s As6s As7s As8s As9s AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsQs Jc9c JdJc Jh9h JhJc JhJd JhTs JsJc JsJh JsTs Kc6c Kc7c Kc8c Kc9c KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTd KcTh KcTs Kd6d Kd7d Kd8d KdJc KdJh KdJs KdKc KdQc KdQd KdQh KdQs KdTc KdTh KdTs Kh6h Kh7h Kh8h Kh9h KhJc KhJd KhJs KhKc KhKd KhQc KhQd KhQh KhQs KhTc KhTd KhTs Ks6s Ks7s Ks8s KsJc KsJd KsJh KsJs KsKc KsKd KsKh KsQc KsQd KsQh KsQs KsTc KsTd QcJc QcJs QcTc QdJd QdJs QdQc QdTd QhJh QhQc QhQd QhTh Qs9s QsJh QsJs QsQc QsQh QsTs Tc9c Th9h Ts9s TsTc TsTd TsTh')
        }
      ]
    },
    {
      position: 'UTG',
      stackBb: 30,
      villainPosition: 'BTN',
      board: [
        'As',
        'Ac',
        '7s'
      ],
      heroStackSize: 27.9,
      villainStackSize: 27.9,
      actionLine: 'preflop: UTG raises 2.1bb, BTN calls 2.1bb',
      dealCombos: expand('4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6d6c 6h6c 6h6d 6s6c 6s6d 6s6h 7d7c 7h7c 7h7d 8d8c 8h8c 8h8d 8s8c 8s8d 8s8h 9c8c 9d8d 9d9c 9h8h 9h9c 9h9d 9s8s 9s9c 9s9d 9s9h Ad3d Ad4d Ad5d Ad6d Ad7d Ad8d Ad9d AdJc AdJd AdJh AdJs AdKc AdKd AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhAd AhJc AhJd AhJh AhJs AhKc AhKd AhKh AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs Jc9c JcTc JcTd JcTh JcTs Jd9d JdJc JdTc JdTd JdTh JdTs Jh9h JhJc JhJd JhTc JhTd JhTh JhTs Js9s JsJc JsJd JsJh JsTc JsTd JsTh JsTs Kc6c Kc7c Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc KcTd KcTh KcTs Kd6d Kd7d Kd8d Kd9d KdJc KdJd KdJh KdJs KdKc KdQc KdQd KdQh KdQs KdTc KdTd KdTh KdTs Kh6h Kh7h Kh8h Kh9h KhJc KhJd KhJh KhJs KhKc KhKd KhQc KhQd KhQh KhQs KhTc KhTd KhTh KhTs Ks6s Ks8s Ks9s KsJc KsJd KsJh KsJs KsKc KsKd KsKh KsQc KsQd KsQh KsQs KsTc KsTd KsTh KsTs Qc9c QcJc QcJd QcJh QcJs QcTc Qd9d QdJc QdJd QdJh QdJs QdQc QdTd Qh9h QhJc QhJd QhJh QhJs QhQc QhQd QhTh Qs9s QsJc QsJd QsJh QsJs QsQc QsQd QsQh QsTs Tc8c Tc9c Td8d Td9d TdTc Th8h Th9h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh'),
      buckets: [
        {
          actions: [
            'bet_25pct'
          ],
          combos: expand('4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6d6c 6h6c 6h6d 6s6c 6s6d 6s6h 7d7c 7h7c 7h7d 8d8c 8h8c 8s8c 8s8d 8s8h 9c8c 9d8d 9d9c 9h8h 9h9c 9s8s 9s9c 9s9d 9s9h Ad3d Ad4d Ad5d Ad6d Ad7d Ad8d Ad9d AdJc AdJd AdJh AdJs AdKc AdKd AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhAd AhJc AhJd AhJh AhJs AhKc AhKd AhKh AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs Jc9c JcTc JcTd JcTh JcTs Jd9d JdJc JdTc JdTd JdTs Jh9h JhJc JhJd JhTc JhTh JhTs Js9s JsJc JsJd JsJh JsTc JsTd JsTh JsTs Kc6c Kc7c Kc8c Kc9c KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc KcTd KcTh KcTs Kd7d Kd8d KdJc KdJd KdJh KdJs KdKc KdQc KdQd KdQh KdQs KdTc KdTd KdTs Kh7h Kh8h KhJc KhJd KhJh KhJs KhKc KhKd KhQc KhQd KhQh KhQs KhTc KhTh KhTs Ks6s Ks8s Ks9s KsJc KsJd KsJh KsJs KsKd KsKh KsQc KsQd KsQh KsQs KsTc KsTd KsTh KsTs Qc9c QcJc QcJd QcJh QcJs QcTc Qd9d QdJc QdJd QdJh QdJs QdQc QdTd Qh9h QhJc QhJd QhJh QhJs QhQc QhQd QhTh Qs9s QsJc QsJd QsJh QsJs QsQc QsQd QsQh QsTs Tc8c Tc9c Td8d Td9d TdTc Th8h Th9h ThTc Ts8s Ts9s TsTc TsTd TsTh')
        },
        {
          actions: [
            'check'
          ],
          combos: expand('4s4c 4s4d 4s4h 5d5c 5h5c 5s5c 5s5d 5s5h 6d6c 6h6c 6h6d 6s6c 6s6d 6s6h 7d7c 7h7c 8d8c 8h8c 8h8d 8s8c 8s8d 8s8h 9c8c 9d8d 9h8h 9h9d 9s8s 9s9d 9s9h Ad3d Ad4d Ad5d Ad7d Ad8d Ad9d AdJc AdJs AdKd AdKh AdQh AdQs AdTd AdTh AdTs Ah3h Ah4h Ah5h Ah7h Ah8h Ah9h AhAd AhJc AhJs AhKd AhKh AhQd AhQs AhTd AhTh AhTs Jd9d JdJc JdTd JdTh Jh9h JhJc JhJd JhTd JhTh Js9s Kc7c KcJc KcJd KcJh KcQc KcQd KcQh KcTd KcTh Kd6d Kd7d Kd8d Kd9d KdJc KdJd KdJh KdJs KdKc KdQc KdQd KdQh KdQs KdTc KdTd KdTh KdTs Kh6h Kh7h Kh8h Kh9h KhJc KhJd KhJh KhJs KhKc KhQc KhQd KhQh KhQs KhTc KhTd KhTh KhTs Ks8s Ks9s KsJd KsJh KsKc KsQc KsQd KsQh KsQs KsTs QcJc QcTc Qd9d QdJd QdQc Qh9h QhJh QhQc QhQd Qs9s QsJd QsJh QsJs QsQc QsQd QsQh QsTs Td8d Td9d Th8h Th9h ThTd Ts9s TsTd TsTh')
        }
      ]
    },
    {
      position: 'UTG',
      stackBb: 30,
      villainPosition: 'BTN',
      board: [
        'Jd',
        '6d',
        '2c'
      ],
      heroStackSize: 27.9,
      villainStackSize: 27.9,
      actionLine: 'preflop: UTG raises 2.1bb, BTN calls 2.1bb',
      dealCombos: expand('4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6h6c 6s6c 6s6h 7d7c 7h7c 7h7d 7s7c 7s7d 7s7h 8d8c 8h8c 8h8d 8s8c 8s8d 8s8h 9c8c 9d8d 9d9c 9h8h 9h9c 9h9d 9s8s 9s9c 9s9d 9s9h Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJh AcJs AcKc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad3d Ad4d Ad5d Ad7d Ad8d Ad9d AdAc AdJc AdJh AdJs AdKc AdKd AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhAc AhAd AhJc AhJh AhJs AhKc AhKd AhKh AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs As3s As4s As5s As6s As7s As8s As9s AsAc AsAd AsAh AsJc AsJh AsJs AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc9c JcTc JcTd JcTh JcTs Jh9h JhJc JhTc JhTd JhTh JhTs Js9s JsJc JsJh JsTc JsTd JsTh JsTs Kc6c Kc7c Kc8c Kc9c KcJc KcJh KcJs KcQc KcQd KcQh KcQs KcTc KcTd KcTh KcTs Kd7d Kd8d Kd9d KdJc KdJh KdJs KdKc KdQc KdQd KdQh KdQs KdTc KdTd KdTh KdTs Kh6h Kh7h Kh8h Kh9h KhJc KhJh KhJs KhKc KhKd KhQc KhQd KhQh KhQs KhTc KhTd KhTh KhTs Ks6s Ks7s Ks8s Ks9s KsJc KsJh KsJs KsKc KsKd KsKh KsQc KsQd KsQh KsQs KsTc KsTd KsTh KsTs Qc9c QcJc QcJh QcJs QcTc Qd9d QdJc QdJh QdJs QdQc QdTd Qh9h QhJc QhJh QhJs QhQc QhQd QhTh Qs9s QsJc QsJh QsJs QsQc QsQd QsQh QsTs Tc8c Tc9c Td8d Td9d TdTc Th8h Th9h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh'),
      buckets: [
        {
          actions: [
            'bet_40pct'
          ],
          combos: expand('4h4c 4s4c 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6h6c 6s6c 6s6h 7h7d 7s7d 7s7h 8h8d 8s8d 9c8c 9d8d 9d9c 9h9c 9h9d 9s9c 9s9d Ac3c Ac4c Ac5c Ac6c Ac7c Ac9c AcJh AcJs AcKc AcKh AcKs AcQc AcQd AcQh AcQs AcTd AcTh AcTs Ad3d Ad4d Ad5d Ad7d Ad8d Ad9d AdAc AdJc AdJh AdJs AdKd AdKh AdKs AdQc AdQh AdQs AdTc AdTh AdTs Ah4h Ah6h AhAc AhAd AhJc AhJh AhJs AhKd AhKh AhKs AhQc AhQd AhTd As4s As6s AsAc AsAd AsAh AsJc AsJh AsJs AsKd AsKh AsKs AsQc AsQd AsTd JcTc Jh9h JhJc JhTh JhTs Js9s JsJc JsJh JsTh JsTs Kc7c Kc8c Kc9c KcJh KcJs KcQc KcQd KcQh KcQs KcTc KcTd Kd7d Kd8d Kd9d KdJc KdJh KdJs KdKc KdQc KdQd KdQh KdQs KdTc KdTd KdTh KdTs Kh9h KhJc KhJh KhJs KhKc KhKd KhQc KhQd KhQh KhQs KhTc KhTd KhTh Ks9s KsJc KsJh KsJs KsKc KsKd KsKh KsQc KsQd KsQh KsQs KsTc KsTd KsTs Qc9c QcJh QcJs QcTc Qd9d QdQc QdTd Qh9h QhJc QhJh QhJs QhQc QhQd QhTh Qs9s QsJc QsJh QsJs QsQc QsQd QsQh QsTs Tc8c Tc9c Td8d Td9d ThTc ThTd TsTc TsTd TsTh')
        },
        {
          actions: [
            'check'
          ],
          combos: expand('4d4c 4h4d 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6h6c 6s6c 6s6h 7d7c 7h7c 7s7c 7s7h 8d8c 8h8c 8s8c 8s8h 9d8d 9h8h 9h9c 9h9d 9s8s 9s9c 9s9d 9s9h Ac6c Ac8c Ac9c AcJc AcJh AcJs AcKc AcKd AcKh AcKs AcQd AcQh AcQs AcTc AcTh AcTs Ad3d Ad4d Ad7d Ad8d Ad9d AdAc AdJc AdKc AdKd AdKh AdKs AdQd AdQh AdQs AdTd AdTh AdTs Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhAc AhJc AhJh AhJs AhKc AhKd AhKh AhKs AhQd AhQh AhQs AhTc AhTd AhTh AhTs As3s As4s As5s As6s As7s As8s As9s AsAc AsAh AsJc AsJh AsJs AsKc AsKd AsKh AsKs AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc9c JcTc JcTd JcTh JcTs Jh9h JhJc JhTc JhTd JhTh Js9s JsJc JsTc JsTd JsTs Kc6c Kc8c KcJc KcJh KcJs KcTc KcTh KcTs Kd7d Kd8d Kd9d KdJc KdJh KdJs KdKc KdQc KdQd KdQh KdQs KdTd KdTh KdTs Kh6h Kh7h Kh8h Kh9h KhJh KhJs KhKc KhKd KhQd KhQh KhQs KhTc KhTh KhTs Ks6s Ks7s Ks8s Ks9s KsJh KsJs KsKc KsKd KsKh KsQd KsQh KsQs KsTc KsTh KsTs QcJc QcJh QcJs QcTc QdJc QdJh QdJs QdQc Qh9h QhJc QhQc QhTh Qs9s QsJc QsQc QsQh QsTs Td8d Td9d TdTc Th8h Th9h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh')
        }
      ]
    },
    {
      position: 'UTG',
      stackBb: 30,
      villainPosition: 'BTN',
      board: [
        'Js',
        '8s',
        '8d'
      ],
      heroStackSize: 27.9,
      villainStackSize: 27.9,
      actionLine: 'preflop: UTG raises 2.1bb, BTN calls 2.1bb',
      dealCombos: expand('4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6d6c 6h6c 6h6d 6s6c 6s6d 6s6h 7d7c 7h7c 7h7d 7s7c 7s7d 7s7h 8h8c 9c8c 9d9c 9h8h 9h9c 9h9d 9s9c 9s9d 9s9h Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcKc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad3d Ad4d Ad5d Ad6d Ad7d Ad9d AdAc AdJc AdJd AdJh AdKc AdKd AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhAc AhAd AhJc AhJd AhJh AhKc AhKd AhKh AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs As3s As4s As5s As6s As7s As9s AsAc AsAd AsAh AsJc AsJd AsJh AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc9c JcTc JcTd JcTh JcTs Jd9d JdJc JdTc JdTd JdTh JdTs Jh9h JhJc JhJd JhTc JhTd JhTh JhTs Kc6c Kc7c Kc8c Kc9c KcJc KcJd KcJh KcQc KcQd KcQh KcQs KcTc KcTd KcTh KcTs Kd6d Kd7d Kd9d KdJc KdJd KdJh KdKc KdQc KdQd KdQh KdQs KdTc KdTd KdTh KdTs Kh6h Kh7h Kh8h Kh9h KhJc KhJd KhJh KhKc KhKd KhQc KhQd KhQh KhQs KhTc KhTd KhTh KhTs Ks6s Ks7s Ks9s KsJc KsJd KsJh KsKc KsKd KsKh KsQc KsQd KsQh KsQs KsTc KsTd KsTh KsTs Qc9c QcJc QcJd QcJh QcTc Qd9d QdJc QdJd QdJh QdQc QdTd Qh9h QhJc QhJd QhJh QhQc QhQd QhTh Qs9s QsJc QsJd QsJh QsQc QsQd QsQh QsTs Tc8c Tc9c Td9d TdTc Th8h Th9h ThTc ThTd Ts9s TsTc TsTd TsTh'),
      buckets: [
        {
          actions: [
            'bet_25pct'
          ],
          combos: expand('4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6d6c 6h6c 6h6d 6s6c 6s6h 7h7c 7s7c 7s7d 7s7h 9c8c 9h8h 9h9c 9s9c 9s9h Ac8c Ac9c AcJc AcJd AcJh AcKc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad3d Ad4d Ad5d Ad6d Ad7d Ad9d AdAc AdJc AdJd AdJh AdKc AdKd AdKh AdKs AdQc AdQd AdQh AdQs AdTd AdTs Ah8h Ah9h AhAc AhAd AhJc AhJd AhJh AhKc AhKd AhKh AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs As3s As4s As5s As6s As7s As9s AsAc AsAd AsAh AsJc AsJd AsJh AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc9c JcTc JcTd JcTh JdJc JdTd Jh9h JhJc JhJd JhTc JhTd JhTh Kc8c Kc9c KcJc KcJd KcJh KcQc KcQd KcQh KcQs KcTc KcTs Kd7d Kd9d KdJd KdKc KdQc KdQd KdQh KdQs KdTd KdTs Kh8h Kh9h KhJc KhJd KhJh KhKc KhKd KhQc KhQd KhQh KhQs KhTh KhTs Ks6s Ks7s Ks9s KsJc KsJd KsJh KsKc KsKd KsKh KsQc KsQd KsQh KsQs KsTc KsTd KsTh KsTs Qc9c QcJc QcJh QcTc Qd9d QdQc QdTd Qh9h QhJc QhJh QhQc QhQd QhTh Qs9s QsJc QsJd QsJh QsQc QsQd QsQh QsTs Tc8c Tc9c Td9d TdTc Th8h Th9h ThTc ThTd Ts9s TsTc TsTd TsTh')
        },
        {
          actions: [
            'check'
          ],
          combos: expand('4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6d6c 6h6c 6h6d 6s6c 6s6d 6s6h 7d7c 7h7d 7s7c 7s7d 7s7h 8h8c 9c8c 9d9c 9h8h 9h9d 9s9c 9s9d 9s9h Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c AcJd AcJh AcKc AcKd AcKh AcQc AcQh AcQs AcTd AcTh Ad3d Ad4d Ad5d Ad6d AdAc AdJc AdJh AdKc AdKh AdKs AdQd AdQs AdTc AdTd AdTh AdTs Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h AhAc AhAd AhJc AhJd AhKc AhKd AhKh AhQc AhQh AhQs AhTc AhTd As6s As7s As9s AsAd AsJc AsJd AsJh AsKc AsKh AsKs AsQc AsQh AsQs AsTc AsTh AsTs Jc9c JcTc JcTs Jd9d JdJc JdTc JdTd JdTh JdTs Jh9h JhJc JhJd JhTh JhTs Kc6c Kc7c Kc8c Kc9c KcJh KcQc KcQh KcQs KcTc KcTd KcTh Kd6d KdJc KdJh KdTc KdTh Kh6h Kh7h Kh8h Kh9h KhJc KhQc KhQh KhQs KhTc KhTd KhTh KsJc KsJd KsJh KsKc KsKh KsQd KsQs Qc9c QcJd QcTc Qd9d QdJc QdJd QdJh QdQc Qh9h QhJd QhQc QhQd QhTh Tc8c Tc9c TdTc Th8h Th9h ThTc ThTd Ts9s TsTc TsTh')
        }
      ]
    },
    {
      position: 'UTG',
      stackBb: 30,
      villainPosition: 'BTN',
      board: [
        'Kc',
        '6c',
        '3s'
      ],
      heroStackSize: 27.9,
      villainStackSize: 27.9,
      actionLine: 'preflop: UTG raises 2.1bb, BTN calls 2.1bb',
      dealCombos: expand('4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6h6d 6s6d 6s6h 7d7c 7h7c 7h7d 7s7c 7s7d 7s7h 8d8c 8h8c 8h8d 8s8c 8s8d 8s8h 9c8c 9d8d 9d9c 9h8h 9h9c 9h9d 9s8s 9s9c 9s9d 9s9h Ac3c Ac4c Ac5c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad3d Ad4d Ad5d Ad6d Ad7d Ad8d Ad9d AdAc AdJc AdJd AdJh AdJs AdKd AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhAc AhAd AhJc AhJd AhJh AhJs AhKd AhKh AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs As4s As5s As6s As7s As8s As9s AsAc AsAd AsAh AsJc AsJd AsJh AsJs AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc9c JcTc JcTd JcTh JcTs Jd9d JdJc JdTc JdTd JdTh JdTs Jh9h JhJc JhJd JhTc JhTd JhTh JhTs Js9s JsJc JsJd JsJh JsTc JsTd JsTh JsTs Kd6d Kd7d Kd8d Kd9d KdJc KdJd KdJh KdJs KdQc KdQd KdQh KdQs KdTc KdTd KdTh KdTs Kh6h Kh7h Kh8h Kh9h KhJc KhJd KhJh KhJs KhKd KhQc KhQd KhQh KhQs KhTc KhTd KhTh KhTs Ks6s Ks7s Ks8s Ks9s KsJc KsJd KsJh KsJs KsKd KsKh KsQc KsQd KsQh KsQs KsTc KsTd KsTh KsTs Qc9c QcJc QcJd QcJh QcJs QcTc Qd9d QdJc QdJd QdJh QdJs QdQc QdTd Qh9h QhJc QhJd QhJh QhJs QhQc QhQd QhTh Qs9s QsJc QsJd QsJh QsJs QsQc QsQd QsQh QsTs Tc8c Tc9c Td8d Td9d TdTc Th8h Th9h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh'),
      buckets: [
        {
          actions: [
            'bet_40pct'
          ],
          combos: expand('4s4c 4s4d 4s4h 5h5d 5s5c 5s5d 5s5h 6h6d 6s6d 6s6h 7s7c 7s7d 7s7h 8d8c 8h8c 8s8c 9c8c 9d8d 9d9c 9h8h 9h9c 9s8s 9s9c Ac3c Ac4c Ac5c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad3d Ad4d Ad5d Ad6d Ad9d AdAc AdJc AdJs AdKd AdKh AdKs AdQc AdQs AdTc Ah3h Ah4h Ah5h Ah6h Ah9h AhAc AhJc AhJs AhKd AhKh AhKs AhQc AhQs AhTc As4s As5s As7s As8s As9s AsAc AsAd AsAh AsJc AsJd AsJh AsKd AsKh AsKs AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc9c JcTc JcTd JcTh JcTs JdJc JdTc JhJc JhJd JhTc Js9s JsTc JsTs Kd6d Kd7d Kd8d Kd9d KdJd KdJh KdJs KdQc KdQd KdQh KdQs KdTd KdTh Kh6h Kh7h Kh8h Kh9h KhJd KhJh KhJs KhKd KhQc KhQd KhQh KhQs KhTd KhTh Ks7s KsJc KsJd KsJh KsJs KsKd KsKh KsQc KsQd KsQh KsTd KsTh KsTs Qc9c QcJc QcJd QcJh QcJs QcTc QdJc QdJd QdJh QdJs QdQc QdTd QhJc QhJd QhJh QhJs QhQc QhQd QhTh Qs9s QsJc QsJd QsJh QsJs QsQd QsQh QsTs Tc8c Tc9c TdTc ThTc Ts8s Ts9s TsTc TsTd TsTh')
        },
        {
          actions: [
            'check'
          ],
          combos: expand('4d4c 4h4c 4h4d 4s4c 5d5c 5h5c 5h5d 5s5c 6s6d 6s6h 7d7c 7h7c 7h7d 7s7c 8d8c 8h8c 8h8d 8s8c 8s8d 8s8h 9c8c 9d8d 9h8h 9h9d 9s8s 9s9c 9s9d 9s9h Ac3c Ac4c Ac5c Ac7c Ac8c AcJc AcJd AcJh AcJs AcKd AcKh AcQc AcQd AcQh AcTc AcTd AcTh Ad3d Ad4d Ad5d Ad6d Ad7d Ad8d Ad9d AdJd AdJh AdJs AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhAd AhJd AhJh AhJs AhKd AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs As5s As6s As9s AsAc AsAd AsAh AsJd AsJh AsJs AsKd AsKh AsKs AsQc AsQs AsTd AsTh AsTs Jc9c Jd9d JdTd JdTh JdTs Jh9h JhTd JhTh JhTs Js9s JsJc JsJd JsJh JsTd JsTh Kd7d Kd8d Kd9d KdJc KdJs KdQd KdQh KdTc KdTs Kh7h Kh8h Kh9h KhJc KhJs KhQd KhQh KhTc KhTs Ks6s Ks7s Ks8s Ks9s KsJc KsKd KsKh KsQd KsQh KsQs KsTc KsTs Qc9c QcJc QcJd QcJh QcTc Qd9d QdJd QdJh QdTd Qh9h QhJd QhJh QhQd QhTh QsJs QsQc QsQd QsQh Tc8c Tc9c Td8d Td9d Th8h Th9h ThTd TsTc TsTd TsTh')
        }
      ]
    },
    {
      position: 'UTG',
      stackBb: 30,
      villainPosition: 'BTN',
      board: [
        'Kd',
        'Ts',
        '8h'
      ],
      heroStackSize: 27.9,
      villainStackSize: 27.9,
      actionLine: 'preflop: UTG raises 2.1bb, BTN calls 2.1bb',
      dealCombos: expand('4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6d6c 6h6c 6h6d 6s6c 6s6d 6s6h 7d7c 7h7c 7h7d 7s7c 7s7d 7s7h 8d8c 8s8c 8s8d 9c8c 9d8d 9d9c 9h9c 9h9d 9s8s 9s9c 9s9d 9s9h Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcKc AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh Ad3d Ad4d Ad5d Ad6d Ad7d Ad8d Ad9d AdAc AdJc AdJd AdJh AdJs AdKc AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh Ah3h Ah4h Ah5h Ah6h Ah7h Ah9h AhAc AhAd AhJc AhJd AhJh AhJs AhKc AhKh AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh As3s As4s As5s As6s As7s As8s As9s AsAc AsAd AsAh AsJc AsJd AsJh AsJs AsKc AsKh AsKs AsQc AsQd AsQh AsQs AsTc AsTd AsTh Jc9c JcTc JcTd JcTh Jd9d JdJc JdTc JdTd JdTh Jh9h JhJc JhJd JhTc JhTd JhTh Js9s JsJc JsJd JsJh JsTc JsTd JsTh Kc6c Kc7c Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc KcTd KcTh Kh6h Kh7h Kh9h KhJc KhJd KhJh KhJs KhKc KhQc KhQd KhQh KhQs KhTc KhTd KhTh Ks6s Ks7s Ks8s Ks9s KsJc KsJd KsJh KsJs KsKc KsKh KsQc KsQd KsQh KsQs KsTc KsTd KsTh Qc9c QcJc QcJd QcJh QcJs QcTc Qd9d QdJc QdJd QdJh QdJs QdQc QdTd Qh9h QhJc QhJd QhJh QhJs QhQc QhQd QhTh Qs9s QsJc QsJd QsJh QsJs QsQc QsQd QsQh Tc8c Tc9c Td8d Td9d TdTc Th9h ThTc ThTd'),
      buckets: [
        {
          actions: [
            'bet_40pct'
          ],
          combos: expand('4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6d6c 6h6c 6h6d 6s6c 6s6d 6s6h 7d7c 7h7c 7h7d 7s7c 7s7d 7s7h 8d8c 8s8c 8s8d 9c8c 9d8d 9d9c 9h9c 9h9d 9s8s 9s9c 9s9d 9s9h Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcKc AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh Ad3d Ad4d Ad5d Ad6d Ad7d Ad8d Ad9d AdAc AdJc AdJd AdJh AdJs AdKc AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh Ah3h Ah4h Ah5h Ah6h Ah7h Ah9h AhAc AhAd AhJc AhJd AhJh AhJs AhKc AhKh AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh As3s As4s As5s As6s As7s As8s As9s AsAc AsAd AsAh AsJc AsJd AsJh AsJs AsKc AsKh AsKs AsQc AsQd AsQh AsQs AsTc AsTd AsTh Jc9c JcTc Jd9d JdJc JdTd Jh9h JhJc JhJd JhTc JhTh Js9s JsJc JsJd JsJh JsTc Kc6c Kc7c Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc KcTd KcTh Kh6h Kh7h Kh9h KhJc KhJd KhJh KhJs KhKc KhQc KhQd KhQh KhQs KhTc KhTd KhTh Ks6s Ks7s Ks8s Ks9s KsJc KsJd KsJh KsJs KsKc KsKh KsQc KsQd KsQh KsQs KsTc KsTd KsTh Qc9c QcJc QcJd QcJh QcJs QcTc Qd9d QdJc QdJd QdJh QdJs QdQc QdTd Qh9h QhJc QhJd QhJh QhJs QhQc QhQd QhTh Qs9s QsJc QsJd QsJh QsJs QsQc QsQd QsQh Tc8c Tc9c Td8d Td9d TdTc Th9h ThTc ThTd')
        },
        {
          actions: [
            'check'
          ],
          combos: expand('5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6d6c 6h6c 6h6d 6s6c 6s6d 6s6h 7d7c 7h7c 7h7d 7s7c 7s7d 7s7h 8d8c 8s8c 8s8d 9c8c 9d9c 9h9d 9s9c 9s9d 9s9h Ac3c Ac4c Ac5c Ac6c Ac8c AcTc AcTh Ad3d Ad4d Ad5d Ad6d Ad8d AdJs AdKh AdQh AdQs AdTc AdTh Ah3h Ah4h Ah5h Ah6h AhJd AhQd AhQh AhQs AhTc AhTd As3s As4s As5s As6s As8s AsJd AsQd AsQh AsQs AsTc AsTd AsTh JcTd JcTh Jd9d JdTc JdTd JdTh JhJd JhTd JhTh Js9s JsJd JsTc JsTd JsTh Kc9c KcJc KcQc Kh9h KhJc KhKc KsJc KsKc KsKh KsQc QcTc QdJs QdQc QdTd Qh9h QhJd QhJs QhQc QhQd QhTh QsJd QsJh QsQc QsQd TdTc ThTc ThTd')
        }
      ]
    },
    {
      position: 'UTG',
      stackBb: 30,
      villainPosition: 'BTN',
      board: [
        'Kh',
        'Jd',
        '4d'
      ],
      heroStackSize: 27.9,
      villainStackSize: 27.9,
      actionLine: 'preflop: UTG raises 2.1bb, BTN calls 2.1bb',
      dealCombos: expand('4h4c 4s4c 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6d6c 6h6c 6h6d 6s6c 6s6d 6s6h 7d7c 7h7c 7h7d 7s7c 7s7d 7s7h 8d8c 8h8c 8h8d 8s8c 8s8d 8s8h 9c8c 9d8d 9d9c 9h8h 9h9c 9h9d 9s8s 9s9c 9s9d 9s9h Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJh AcJs AcKc AcKd AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad3d Ad5d Ad6d Ad7d Ad8d Ad9d AdAc AdJc AdJh AdJs AdKc AdKd AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhAc AhAd AhJc AhJh AhJs AhKc AhKd AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs As3s As4s As5s As6s As7s As8s As9s AsAc AsAd AsAh AsJc AsJh AsJs AsKc AsKd AsKs AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc9c JcTc JcTd JcTh JcTs Jh9h JhJc JhTc JhTd JhTh JhTs Js9s JsJc JsJh JsTc JsTd JsTh JsTs Kc6c Kc7c Kc8c Kc9c KcJc KcJh KcJs KcQc KcQd KcQh KcQs KcTc KcTd KcTh KcTs Kd6d Kd7d Kd8d Kd9d KdJc KdJh KdJs KdKc KdQc KdQd KdQh KdQs KdTc KdTd KdTh KdTs Ks6s Ks7s Ks8s Ks9s KsJc KsJh KsJs KsKc KsKd KsQc KsQd KsQh KsQs KsTc KsTd KsTh KsTs Qc9c QcJc QcJh QcJs QcTc Qd9d QdJc QdJh QdJs QdQc QdTd Qh9h QhJc QhJh QhJs QhQc QhQd QhTh Qs9s QsJc QsJh QsJs QsQc QsQd QsQh QsTs Tc8c Tc9c Td8d Td9d TdTc Th8h Th9h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh'),
      buckets: [
        {
          actions: [
            'bet_40pct'
          ],
          combos: expand('4h4c 4s4c 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6d6c 6h6c 6h6d 6s6c 6s6d 6s6h 7d7c 7h7d 7s7c 7s7d 8d8c 8s8d 9d8d 9d9c 9h8h 9h9d 9s9d Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c AcJc AcJs AcKc AcKd AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad3d Ad5d Ad6d Ad7d Ad8d Ad9d AdAc AdJc AdJs AdKc AdKd AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhAc AhAd AhJc AhJh AhJs AhKc AhKd AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTs As3s As4s As5s As6s As7s As8s AsAc AsAd AsAh AsJc AsJs AsKc AsKd AsKs AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc9c JcTc Jh9h JhJc JhTc JhTs Js9s JsJc JsJh JsTs Kc6c Kc7c Kc8c Kc9c KcJc KcJh KcJs KcQc KcQd KcQh KcQs KcTc KcTh KcTs Kd7d Kd9d KdJc KdJh KdJs KdKc KdQc KdQd KdQh KdQs KdTc KdTd KdTh KdTs Ks6s Ks7s Ks8s Ks9s KsJc KsJh KsJs KsKc KsKd KsQc KsQd KsQh KsQs KsTc KsTh KsTs Qc9c QcJc QcJh QcJs QcTc Qd9d QdQc QdTd Qh9h QhJc QhJh QhJs QhQc QhQd QhTh Qs9s QsJc QsJh QsJs QsQd QsQh QsTs Tc9c Td8d TdTc Th8h Th9h ThTc ThTd Ts9s TsTd TsTh')
        },
        {
          actions: [
            'check'
          ],
          combos: expand('4h4c 4s4c 4s4h 5h5c 5h5d 5s5c 5s5h 6d6c 6h6c 6h6d 6s6c 6s6d 6s6h 7d7c 7h7c 7h7d 7s7c 7s7d 7s7h 8d8c 8h8c 8h8d 8s8c 8s8d 8s8h 9c8c 9d9c 9h8h 9h9c 9h9d 9s8s 9s9c 9s9d 9s9h Ac3c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJh AcJs AcKs AcQc AcQs AcTd Ad6d Ad7d Ad8d AdAc AdJc AdJh AdJs AdKc AdKs AdQc AdQd AdQs AdTc AdTd AdTh AdTs Ah3h Ah8h Ah9h AhAd AhKc AhKd AhKs AhQc AhQh AhQs AhTc AhTd AhTh AhTs As3s As5s As6s As7s As8s As9s AsAc AsAd AsJc AsJh AsJs AsKc AsQc AsQs AsTd Jc9c JcTc JcTd JcTh JcTs Jh9h JhJc JhTd JhTh Js9s JsJc JsJh JsTc JsTd JsTh JsTs Kc7c Kc8c KcJc KcJs KcQc KcQd KcQh KcTd KcTs Kd6d Kd7d Kd8d Kd9d KdJc KdJs KdKc KdQh KdTc KdTh KdTs Ks7s Ks8s KsJc KsJs KsKc KsKd KsQd KsQh KsQs KsTc KsTd QcJc QcJh QcJs QcTc Qd9d QdJc QdJh QdJs QdQc QhJc QhJh QhJs QsJc QsJh QsJs QsQc QsQd QsTs Tc8c Td9d TdTc Th9h ThTc Ts8s TsTc TsTd TsTh')
        }
      ]
    },
    {
      position: 'UTG',
      stackBb: 30,
      villainPosition: 'BTN',
      board: [
        'Qd',
        'Qc',
        'Js'
      ],
      heroStackSize: 27.9,
      villainStackSize: 27.9,
      actionLine: 'preflop: UTG raises 2.1bb, BTN calls 2.1bb',
      dealCombos: expand('4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6d6c 6h6c 6h6d 6s6c 6s6d 6s6h 7d7c 7h7c 7h7d 7s7c 7s7d 7s7h 8d8c 8h8c 8h8d 8s8c 8s8d 8s8h 9c8c 9d8d 9d9c 9h8h 9h9c 9h9d 9s8s 9s9c 9s9d 9s9h Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcKc AcKd AcKh AcKs AcQh AcQs AcTc AcTd AcTh AcTs Ad3d Ad4d Ad5d Ad6d Ad7d Ad8d Ad9d AdAc AdJc AdJd AdJh AdKc AdKd AdKh AdKs AdQh AdQs AdTc AdTd AdTh AdTs Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhAc AhAd AhJc AhJd AhJh AhKc AhKd AhKh AhKs AhQh AhQs AhTc AhTd AhTh AhTs As3s As4s As5s As6s As7s As8s As9s AsAc AsAd AsAh AsJc AsJd AsJh AsKc AsKd AsKh AsKs AsQh AsQs AsTc AsTd AsTh AsTs Jc9c JcTc JcTd JcTh JcTs Jd9d JdJc JdTc JdTd JdTh JdTs Jh9h JhJc JhJd JhTc JhTd JhTh JhTs Kc6c Kc7c Kc8c Kc9c KcJc KcJd KcJh KcQh KcQs KcTc KcTd KcTh KcTs Kd6d Kd7d Kd8d Kd9d KdJc KdJd KdJh KdKc KdQh KdQs KdTc KdTd KdTh KdTs Kh6h Kh7h Kh8h Kh9h KhJc KhJd KhJh KhKc KhKd KhQh KhQs KhTc KhTd KhTh KhTs Ks6s Ks7s Ks8s Ks9s KsJc KsJd KsJh KsKc KsKd KsKh KsQh KsQs KsTc KsTd KsTh KsTs Qh9h QhJc QhJd QhJh QhTh Qs9s QsJc QsJd QsJh QsQh QsTs Tc8c Tc9c Td8d Td9d TdTc Th8h Th9h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh'),
      buckets: [
        {
          actions: [
            'bet_25pct'
          ],
          combos: expand('4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6d6c 6h6c 6h6d 6s6c 6s6d 6s6h 7d7c 7h7c 7h7d 7s7c 7s7d 7s7h 8d8c 8h8c 8h8d 8s8c 8s8d 8s8h 9c8c 9d8d 9d9c 9h8h 9h9c 9h9d 9s8s 9s9c 9s9d 9s9h Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcKc AcKd AcKh AcKs AcQh AcQs AcTc AcTd AcTh AcTs Ad3d Ad4d Ad5d Ad6d Ad7d Ad8d Ad9d AdAc AdJc AdJd AdJh AdKc AdKd AdKh AdKs AdQh AdQs AdTc AdTd AdTh AdTs Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhAc AhAd AhJc AhJd AhJh AhKc AhKd AhKh AhKs AhQh AhQs AhTc AhTd AhTh AhTs As3s As4s As5s As6s As7s As8s As9s AsAc AsAd AsAh AsJc AsJd AsJh AsKc AsKd AsKh AsKs AsQh AsQs AsTc AsTd AsTh AsTs Jc9c JcTc JcTd JcTh JcTs Jd9d JdJc JdTc JdTd JdTh JdTs Jh9h JhJc JhJd JhTc JhTd JhTh JhTs Kc6c Kc7c Kc8c Kc9c KcJc KcJd KcJh KcQh KcQs KcTc KcTd KcTh KcTs Kd6d Kd7d Kd8d Kd9d KdJc KdJd KdJh KdKc KdQh KdQs KdTc KdTd KdTh KdTs Kh6h Kh7h Kh8h Kh9h KhJc KhJd KhJh KhKc KhKd KhQh KhQs KhTc KhTd KhTh KhTs Ks6s Ks7s Ks8s Ks9s KsJc KsJd KsJh KsKc KsKd KsKh KsQh KsQs KsTc KsTd KsTh KsTs Qh9h QhJc QhJd QhJh QhTh Qs9s QsJc QsJd QsJh QsQh QsTs Tc8c Tc9c Td8d Td9d TdTc Th8h Th9h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh')
        },
        {
          actions: [
            'check'
          ],
          combos: expand('4d4c 4s4c 4s4d 5d5c 5s5c 5s5d 6d6c 6s6c 6s6d 7h7c 7h7d 7s7c 7s7d 7s7h 8h8c 8h8d 8s8h 9d9c 9s9c 9s9d Ac5c Ac7c Ac8c AcTd AcTs Ad5d Ad7d Ad8d AdTc AdTs Ah5h Ah6h Ah7h Ah8h AhKh AhKs AhTc AhTd AhTs As8s AsAh JcTs JdJc JdTs Jh9h KcJd KdJc Kh7h KhQh KhQs KhTs KsJc KsJd QhJh QhTh QsJh QsQh TdTc Th8h TsTc TsTd')
        }
      ]
    },
    {
      position: 'UTG',
      stackBb: 30,
      villainPosition: 'BTN',
      board: [
        'Qh',
        '8h',
        '3h'
      ],
      heroStackSize: 27.9,
      villainStackSize: 27.9,
      actionLine: 'preflop: UTG raises 2.1bb, BTN calls 2.1bb',
      dealCombos: expand('4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6d6c 6h6c 6h6d 6s6c 6s6d 6s6h 7d7c 7h7c 7h7d 7s7c 7s7d 7s7h 8d8c 8s8c 8s8d 9c8c 9d8d 9d9c 9h9c 9h9d 9s8s 9s9c 9s9d 9s9h Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcKc AcKd AcKh AcKs AcQc AcQd AcQs AcTc AcTd AcTh AcTs Ad3d Ad4d Ad5d Ad6d Ad7d Ad8d Ad9d AdAc AdJc AdJd AdJh AdJs AdKc AdKd AdKh AdKs AdQc AdQd AdQs AdTc AdTd AdTh AdTs Ah4h Ah5h Ah6h Ah7h Ah9h AhAc AhAd AhJc AhJd AhJh AhJs AhKc AhKd AhKh AhKs AhQc AhQd AhQs AhTc AhTd AhTh AhTs As3s As4s As5s As6s As7s As8s As9s AsAc AsAd AsAh AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsKs AsQc AsQd AsQs AsTc AsTd AsTh AsTs Jc9c JcTc JcTd JcTh JcTs Jd9d JdJc JdTc JdTd JdTh JdTs Jh9h JhJc JhJd JhTc JhTd JhTh JhTs Js9s JsJc JsJd JsJh JsTc JsTd JsTh JsTs Kc6c Kc7c Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQs KcTc KcTd KcTh KcTs Kd6d Kd7d Kd8d Kd9d KdJc KdJd KdJh KdJs KdKc KdQc KdQd KdQs KdTc KdTd KdTh KdTs Kh6h Kh7h Kh9h KhJc KhJd KhJh KhJs KhKc KhKd KhQc KhQd KhQs KhTc KhTd KhTh KhTs Ks6s Ks7s Ks8s Ks9s KsJc KsJd KsJh KsJs KsKc KsKd KsKh KsQc KsQd KsQs KsTc KsTd KsTh KsTs Qc9c QcJc QcJd QcJh QcJs QcTc Qd9d QdJc QdJd QdJh QdJs QdQc QdTd Qs9s QsJc QsJd QsJh QsJs QsQc QsQd QsTs Tc8c Tc9c Td8d Td9d TdTc Th9h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh'),
      buckets: [
        {
          actions: [
            'bet_25pct'
          ],
          combos: expand('4d4c 4s4c 4s4d 5d5c 5s5c 5s5d 6d6c 6s6c 6s6d 7d7c 7s7c 7s7d 8d8c 8s8c 8s8d 9c8c 9d8d 9h9c 9h9d 9s8s 9s9h Ac3c Ac4c Ac5c Ac9c AcJd AcJh AcJs AcKh AcQc AcQd AcQs AcTc AcTd AcTs Ad3d Ad4d Ad5d Ad9d AdAc AdJc AdJh AdJs AdKh AdQc AdQd AdQs AdTc AdTd AdTs Ah4h Ah6h Ah7h Ah9h AhAc AhAd AhKc AhKd AhKh AhKs AhQc AhQd AhQs AhTc AhTd AhTh AhTs As3s As4s As5s As9s AsAc AsAd AsAh AsJc AsJd AsJh AsKh AsQc AsQd AsQs AsTc AsTd AsTs Jc9c JcTc JcTd JcTs Jd9d JdJc JdTc JdTd JdTs Jh9h JhJc JhJd JhTh Js9s JsJc JsJd JsJh JsTc JsTd JsTs Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcTc KcTh Kd8d Kd9d KdJc KdJd KdJh KdJs KdKc KdQd KdTd KdTh Kh6h Kh7h Kh9h KhJc KhJd KhJh KhJs KhKc KhKd KhQc KhQd KhQs KhTc KhTd KhTh KhTs Ks8s Ks9s KsJc KsJd KsJh KsJs KsKc KsKd KsKh KsQs KsTh KsTs Qc9c QcJc Qd9d QdJd QdQc Qs9s QsJs QsQc QsQd Tc8c Tc9c Td8d Td9d Th9h ThTc ThTd Ts8s Ts9s TsTh')
        },
        {
          actions: [
            'check'
          ],
          combos: expand('4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6d6c 6h6c 6h6d 6s6c 6s6d 6s6h 7d7c 7h7c 7h7d 7s7c 7s7d 7s7h 8d8c 8s8c 8s8d 9c8c 9d8d 9d9c 9h9c 9h9d 9s8s 9s9c 9s9d 9s9h Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcKc AcKd AcKh AcKs AcQc AcQd AcQs AcTc AcTd AcTh AcTs Ad3d Ad4d Ad5d Ad6d Ad7d Ad8d Ad9d AdAc AdJc AdJd AdJh AdJs AdKc AdKd AdKh AdKs AdQc AdQd AdQs AdTc AdTd AdTh AdTs Ah4h Ah5h Ah6h Ah7h Ah9h AhAc AhAd AhJc AhJd AhJh AhJs AhKc AhKd AhKh AhKs AhQc AhQd AhQs AhTc AhTd AhTh AhTs As3s As4s As5s As6s As7s As8s As9s AsAc AsAd AsAh AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsKs AsQc AsQd AsQs AsTc AsTd AsTh AsTs Jc9c JcTc JcTh Jd9d JdJc JdTd JdTh Jh9h JhJc JhJd JhTc JhTd JhTh JhTs Js9s JsJc JsJd JsJh JsTh JsTs Kc6c Kc7c Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQs KcTc KcTd KcTh KcTs Kd6d Kd7d Kd8d Kd9d KdJc KdJd KdJh KdJs KdKc KdQc KdQd KdQs KdTc KdTd KdTh KdTs Kh6h Kh7h Kh9h KhJc KhJd KhJh KhJs KhKc KhKd KhQc KhQd KhQs KhTh Ks6s Ks7s Ks8s Ks9s KsJc KsJd KsJh KsJs KsKc KsKd KsKh KsQc KsQd KsQs KsTc KsTd KsTh KsTs Qc9c QcJc QcJd QcJh QcJs QcTc Qd9d QdJc QdJd QdJh QdJs QdQc QdTd Qs9s QsJc QsJd QsJh QsJs QsQc QsQd QsTs Tc8c Tc9c Td8d Td9d TdTc Th9h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh')
        }
      ]
    },
    {
      position: 'UTG',
      stackBb: 30,
      villainPosition: 'BTN',
      board: [
        'Tc',
        '7d',
        '6s'
      ],
      heroStackSize: 27.9,
      villainStackSize: 27.9,
      actionLine: 'preflop: UTG raises 2.1bb, BTN calls 2.1bb',
      dealCombos: expand('4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6d6c 6h6c 6h6d 7h7c 7s7c 7s7h 8d8c 8h8c 8h8d 8s8c 8s8d 8s8h 9c8c 9d8d 9d9c 9h8h 9h9c 9h9d 9s8s 9s9c 9s9d 9s9h Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcKc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTd AcTh AcTs Ad3d Ad4d Ad5d Ad6d Ad8d Ad9d AdAc AdJc AdJd AdJh AdJs AdKc AdKd AdKh AdKs AdQc AdQd AdQh AdQs AdTd AdTh AdTs Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhAc AhAd AhJc AhJd AhJh AhJs AhKc AhKd AhKh AhKs AhQc AhQd AhQh AhQs AhTd AhTh AhTs As3s As4s As5s As7s As8s As9s AsAc AsAd AsAh AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTd AsTh AsTs Jc9c JcTd JcTh JcTs Jd9d JdJc JdTd JdTh JdTs Jh9h JhJc JhJd JhTd JhTh JhTs Js9s JsJc JsJd JsJh JsTd JsTh JsTs Kc6c Kc7c Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTd KcTh KcTs Kd6d Kd8d Kd9d KdJc KdJd KdJh KdJs KdKc KdQc KdQd KdQh KdQs KdTd KdTh KdTs Kh6h Kh7h Kh8h Kh9h KhJc KhJd KhJh KhJs KhKc KhKd KhQc KhQd KhQh KhQs KhTd KhTh KhTs Ks7s Ks8s Ks9s KsJc KsJd KsJh KsJs KsKc KsKd KsKh KsQc KsQd KsQh KsQs KsTd KsTh KsTs Qc9c QcJc QcJd QcJh QcJs Qd9d QdJc QdJd QdJh QdJs QdQc QdTd Qh9h QhJc QhJd QhJh QhJs QhQc QhQd QhTh Qs9s QsJc QsJd QsJh QsJs QsQc QsQd QsQh QsTs Td8d Td9d Th8h Th9h ThTd Ts8s Ts9s TsTd TsTh'),
      buckets: [
        {
          actions: [
            'bet_40pct'
          ],
          combos: expand('4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6d6c 6h6c 6h6d 7h7c 7s7c 7s7h 8d8c 8h8c 8h8d 8s8c 8s8d 8s8h 9c8c 9d8d 9d9c 9h8h 9h9c 9h9d 9s8s 9s9c 9s9d 9s9h Ac6c Ac7c Ac8c AcJc AcJd AcJh AcJs AcKc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTd AcTh AcTs Ad6d Ad8d Ad9d AdAc AdJc AdJd AdJh AdJs AdKc AdKd AdKh AdKs AdQc AdQd AdQh AdQs AdTd AdTh AdTs Ah6h Ah7h Ah8h Ah9h AhAc AhAd AhJc AhJd AhJh AhJs AhKc AhKd AhKh AhKs AhQc AhQd AhQh AhQs AhTd AhTh AhTs As7s As8s As9s AsAc AsAd AsAh AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTd AsTh AsTs Jc9c Jd9d JdJc JdTd Jh9h JhJc JhJd JhTd JhTh JhTs Js9s JsJc JsJd JsJh JsTs Kc7c Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTd KcTh KcTs Kd8d Kd9d KdJc KdJd KdJh KdJs KdKc KdQc KdQd KdQh KdQs KdTd KdTh KdTs Kh8h Kh9h KhJc KhJd KhJh KhJs KhKc KhKd KhQc KhQd KhQh KhQs KhTd KhTh KhTs Ks7s Ks8s Ks9s KsJc KsJd KsJh KsJs KsKc KsKd KsKh KsQc KsQd KsQh KsQs KsTd KsTh KsTs Qc9c QcJc QcJd QcJh QcJs Qd9d QdJc QdJd QdJh QdJs QdQc QdTd Qh9h QhJc QhJd QhJh QhJs QhQc QhQd QhTh Qs9s QsJc QsJd QsJh QsJs QsQc QsQd QsQh QsTs Td8d Td9d Th8h Th9h ThTd Ts8s Ts9s TsTd TsTh')
        },
        {
          actions: [
            'check'
          ],
          combos: expand('4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6d6c 6h6c 6h6d 7h7c 7s7c 7s7h 8d8c 8h8c 8h8d 8s8c 8s8d 8s8h 9c8c 9d9c 9h9c 9h9d 9s9c 9s9d 9s9h Ac3c Ac4c Ac5c Ac6c Ac8c Ac9c AcJc AcJd AcJh AcJs AcKd AcKh AcKs AcQd AcQh AcQs AcTd AcTh AcTs Ad3d Ad4d Ad5d Ad6d Ad8d Ad9d AdAc AdJc AdJd AdJh AdJs AdKc AdKh AdKs AdQc AdQh AdQs AdTd AdTh AdTs Ah3h Ah4h Ah5h Ah6h Ah7h Ah9h AhAc AhAd AhJc AhJd AhJh AhJs AhKc AhKd AhKh AhKs AhQc AhQd AhQs AhTh As3s As4s As5s As8s As9s AsAc AsAd AsAh AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsQc AsQd AsQh AsTd AsTh AsTs Jc9c JcTd JcTh JcTs Jd9d JdJc JdTd JdTh JdTs Jh9h JhJd Js9s JsJc JsJd JsJh JsTd JsTh JsTs Kc6c KcJd KcJh KcJs KcQd KcQh KcQs KcTh Kd6d Kd8d Kd9d KdJc KdJh KdJs KdQc KdQh KdQs KdTd KdTh Kh6h Kh7h KhJc KhJd KhJh KhJs KhKc KhKd KhQc KhQd KhQs Ks8s Ks9s KsJc KsJd KsJh KsKh KsQc KsQd KsQh KsTh KsTs Qc9c QcJd QcJh QcJs Qd9d QdJc QdJh QdJs QdQc QdTd QhJc QhJd QhJh QhJs QhQc QhQd Qs9s QsJc QsJd QsJh QsQc QsQd QsQh QsTs Td8d Td9d Th8h Th9h ThTd Ts8s Ts9s TsTh')
        }
      ]
    }
  ]
};

export default pack;
