// Generated by scripts/import-ct-curriculum.ts. Do not edit by hand.
import type { RangePack } from '../types';

const expand = (value: string): string[] => value.split(' ');

const pack: RangePack = {
  slug: 'squeeze-btn-hj-co-baseline',
  title: 'Squeeze: BTN vs HJ+CO (100/50/25bb)',
  description: 'Preflop squeeze practice after an open and a cold caller.',
  scenario: 'FACING_RAISE',
  street: 'preflop',
  tier: 'advanced',
  methodology: 'gto_cev',
  source: {
    kind: 'brand_neutralized_snapshot_config',
    capturedAt: '2026-07-18',
    path: 'research/ct-trainer-2026-07-18/',
    sha256: '5b9656ad935cba6e612ac6affd42949f86697a36a8f1a2f954b0402ed43f1e4f'
  },
  cells: [
    {
      position: 'BTN',
      stackBb: 25,
      heroStackSize: 25,
      villainStackSize: 22.9,
      actionLine: 'preflop: HJ raises 2.1bb, CO calls 2.1bb',
      buckets: [
        {
          actions: [
            'all_in'
          ],
          combos: expand('7d7c 7h7c 7h7d 7s7c 7s7d 7s7h 8d8c 8h8c 8h8d 8s8c 8s8d 8s8h 9d9c 9h9c 9h9d 9s9c 9s9d 9s9h Ac4c Ac5c Ac8c AcJc AcJd AcJh AcJs AcKc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc Ad4d Ad5d Ad8d AdJc AdJd AdJh AdJs AdKc AdKd AdKh AdKs AdQc AdQd AdQh AdQs AdTd Ah4h Ah5h Ah8h AhJc AhJd AhJh AhJs AhKc AhKd AhKh AhKs AhQc AhQd AhQh AhQs AhTh As4s As5s As8s AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTs JdJc JhJc JhJd JsJc JsJd JsJh KcJc KcQc KcTc KdJd KdQd KdTd KhJh KhQh KhTh KsJs KsQs KsTs QcJc QcTc QdJd QdQc QdTd QhJh QhQc QhQd QhTh QsJs QsQc QsQd QsQh QsTs TdTc ThTc ThTd TsTc TsTd TsTh')
        },
        {
          actions: [
            'call'
          ],
          combos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6d6c 6h6c 6h6d 6s6c 6s6d 6s6h 7d7c 7h7c 7h7d 7s7c 7s7d 7s7h 9c8c 9d8d 9h8h 9s8s Ac4c Ac7c Ac8c Ac9c AcJd AcJh AcJs AcTc Ad4d Ad7d Ad8d Ad9d AdJc AdJh AdJs AdTd Ah4h Ah7h Ah8h Ah9h AhJc AhJd AhJs AhTh As4s As7s As8s As9s AsJc AsJd AsJh AsTs JcTc JdTd JhTh JsTs Kc9c KcJc KcQd KcQh KcQs Kd9d KdJd KdQc KdQh KdQs Kh9h KhJh KhQc KhQd KhQs Ks9s KsJs KsQc KsQd KsQh QcJc QcTc QdJd QdTd QhJh QhTh QsJs QsTs Tc9c Td9d Th9h Ts9s')
        },
        {
          actions: [
            'fold'
          ],
          combos: expand('6c5c 6d5d 6h5h 6s5s 7c5c 7c6c 7d5d 7d6d 7h5h 7h6h 7s5s 7s6s 8c6c 8c7c 8d6d 8d7d 8h6h 8h7h 8s6s 8s7s 9c7c 9c8c 9d7d 9d8d 9h7h 9h8h 9s7s 9s8s Ac2c Ac3c Ac4c Ac6c Ac8d Ac8h Ac8s Ac9d Ac9h Ac9s AcTd AcTh AcTs Ad2d Ad3d Ad4d Ad6d Ad8c Ad8h Ad8s Ad9c Ad9h Ad9s AdTc AdTh AdTs Ah2h Ah3h Ah4h Ah6h Ah8c Ah8d Ah8s Ah9c Ah9d Ah9s AhTc AhTd AhTs As2s As3s As4s As6s As8c As8d As8h As9c As9d As9h AsTc AsTd AsTh Jc8c Jc9c JcTc JcTd JcTh JcTs Jd8d Jd9d JdTc JdTd JdTh JdTs Jh8h Jh9h JhTc JhTd JhTh JhTs Js8s Js9s JsTc JsTd JsTh JsTs Kc8c Kc9c KcJd KcJh KcJs KcTd KcTh KcTs Kd8d Kd9d KdJc KdJh KdJs KdTc KdTh KdTs Kh8h Kh9h KhJc KhJd KhJs KhTc KhTd KhTs Ks8s Ks9s KsJc KsJd KsJh KsTc KsTd KsTh Qc8c Qc9c QcJd QcJh QcJs QcTd QcTh QcTs Qd8d Qd9d QdJc QdJh QdJs QdTc QdTh QdTs Qh8h Qh9h QhJc QhJd QhJs QhTc QhTd QhTs Qs8s Qs9s QsJc QsJd QsJh QsTc QsTd QsTh Tc8c Tc9c Td8d Td9d Th8h Th9h Ts8s Ts9s')
        },
        {
          actions: [
            'raise_6_1'
          ],
          combos: expand('6d6c 6h6c 6h6d 6s6c 6s6d 6s6h 7d7c 7h7c 7h7d 7s7c 7s7d 7s7h 9d9c 9h9c 9h9d 9s9c 9s9d 9s9h Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcKc AcQc AcTd AcTh AcTs Ad7d Ad8d Ad9d AdAc AdJc AdJd AdJh AdJs AdKd AdQd AdTc AdTh AdTs Ah7h Ah8h Ah9h AhAc AhAd AhJc AhJd AhJh AhJs AhKh AhQh AhTc AhTd AhTs As7s As8s As9s AsAc AsAd AsAh AsJc AsJd AsJh AsJs AsKs AsQs AsTc AsTd AsTh JcTc JdJc JdTd JhJc JhJd JhTh JsJc JsJd JsJh JsTs Kc9c KcQd KcQh KcQs Kd9d KdKc KdQc KdQh KdQs Kh9h KhKc KhKd KhQc KhQd KhQs Ks9s KsKc KsKd KsKh KsQc KsQd KsQh QcJc QdJd QdQc QhJh QhQc QhQd QsJs QsQc QsQd QsQh TdTc ThTc ThTd TsTc TsTd TsTh')
        }
      ]
    },
    {
      position: 'BTN',
      stackBb: 50,
      heroStackSize: 50,
      villainStackSize: 47.7,
      actionLine: 'preflop: HJ raises 2.3bb, CO calls 2.3bb',
      buckets: [
        {
          actions: [
            'all_in'
          ],
          combos: expand('AcKd AcKh AcKs AcQd AcQh AcQs AdKc AdKh AdKs AdQc AdQh AdQs AhKc AhKd AhKs AhQc AhQd AhQs AsKc AsKd AsKh AsQc AsQd AsQh JdJc JhJc JhJd JsJc JsJd JsJh KcJc KcQc KdJd KdQd KhJh KhQh KsJs KsQs QcJc QdJd QhJh QsJs TdTc ThTc ThTd TsTc TsTd TsTh')
        },
        {
          actions: [
            'call'
          ],
          combos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5d5c 5h5c 5h5d 5s5c 5s5d 5s5h 6c5c 6d5d 6d6c 6h5h 6h6c 6h6d 6s5s 6s6c 6s6d 6s6h 7c6c 7d6d 7d7c 7h6h 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8c7c 8d7d 8d8c 8h7h 8h8c 8h8d 8s7s 8s8c 8s8d 8s8h 9c7c 9c8c 9d7d 9d8d 9d9c 9h7h 9h8h 9h9c 9h9d 9s7s 9s8s 9s9c 9s9d 9s9h Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcQd AcQh AcQs AcTc Ad3d Ad4d Ad5d Ad6d Ad7d Ad8d Ad9d AdJc AdJd AdJh AdJs AdQc AdQh AdQs AdTd Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhJc AhJd AhJh AhJs AhQc AhQd AhQs AhTh As3s As4s As5s As6s As7s As8s As9s AsJc AsJd AsJh AsJs AsQc AsQd AsQh AsTs Jc9c JcTc Jd9d JdTd Jh9h JhTh Js9s JsTs Kc7c Kc8c Kc9c KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc Kd7d Kd8d Kd9d KdJc KdJh KdJs KdQc KdQd KdQh KdQs KdTd Kh7h Kh8h Kh9h KhJc KhJd KhJs KhQc KhQd KhQh KhQs KhTh Ks7s Ks8s Ks9s KsJc KsJd KsJh KsQc KsQd KsQh KsQs KsTs Qc9c QcTc Qd9d QdTd Qh9h QhTh Qs9s QsTs Tc8c Tc9c Td8d Td9d Th8h Th9h Ts8s Ts9s')
        },
        {
          actions: [
            'fold'
          ],
          combos: expand('5c4c 5d4d 5h4h 5s4s 6c5c 6d5d 6h5h 6s5s 7c5c 7c6c 7d5d 7d6d 7h5h 7h6h 7s5s 7s6s 8c6c 8c7c 8d6d 8d7d 8h6h 8h7h 8s6s 8s7s 9c6c 9c7c 9d6d 9d7d 9h6h 9h7h 9s6s 9s7s Ac2c Ac3c Ac6c Ac8d Ac8h Ac8s Ac9d Ac9h Ac9s AcTd AcTh AcTs Ad2d Ad3d Ad6d Ad8c Ad8h Ad8s Ad9c Ad9h Ad9s AdTc AdTh AdTs Ah2h Ah3h Ah6h Ah8c Ah8d Ah8s Ah9c Ah9d Ah9s AhTc AhTd AhTs As2s As3s As6s As8c As8d As8h As9c As9d As9h AsTc AsTd AsTh Jc7c Jc8c JcTd JcTh JcTs Jd7d Jd8d JdTc JdTh JdTs Jh7h Jh8h JhTc JhTd JhTs Js7s Js8s JsTc JsTd JsTh Kc7c Kc8c KcJd KcJh KcJs KcTd KcTh KcTs Kd7d Kd8d KdJc KdJh KdJs KdTc KdTh KdTs Kh7h Kh8h KhJc KhJd KhJs KhTc KhTd KhTs Ks7s Ks8s KsJc KsJd KsJh KsTc KsTd KsTh Qc7c Qc8c QcJd QcJh QcJs QcTd QcTh QcTs Qd7d Qd8d QdJc QdJh QdJs QdTc QdTh QdTs Qh7h Qh8h QhJc QhJd QhJs QhTc QhTd QhTs Qs7s Qs8s QsJc QsJd QsJh QsTc QsTd QsTh Tc7c Tc8c Td7d Td8d Th7h Th8h Ts7s Ts8s')
        },
        {
          actions: [
            'raise_8'
          ],
          combos: expand('7d7c 7h7c 7h7d 7s7c 7s7d 7s7h 8d8c 8h8c 8h8d 8s8c 8s8d 8s8h 9c8c 9d8d 9d9c 9h8h 9h9c 9h9d 9s8s 9s9c 9s9d 9s9h Ac5c Ac7c Ac8c Ac9c AcJd AcJh AcJs AcKc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad5d Ad7d Ad8d Ad9d AdAc AdJc AdJh AdJs AdKc AdKd AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah5h Ah7h Ah8h Ah9h AhAc AhAd AhJc AhJd AhJs AhKc AhKd AhKh AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs As5s As7s As8s As9s AsAc AsAd AsAh AsJc AsJd AsJh AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc9c JcTc Jd9d JdJc JdTd Jh9h JhJc JhJd JhTh Js9s JsJc JsJd JsJh JsTs Kc9c KcJd KcJh KcJs KcQd KcQh KcQs KcTc Kd9d KdJc KdJh KdJs KdKc KdQc KdQh KdQs KdTd Kh9h KhJc KhJd KhJs KhKc KhKd KhQc KhQd KhQs KhTh Ks9s KsJc KsJd KsJh KsKc KsKd KsKh KsQc KsQd KsQh KsTs Qc9c QcTc Qd9d QdQc QdTd Qh9h QhQc QhQd QhTh Qs9s QsQc QsQd QsQh QsTs Tc9c Td9d Th9h Ts9s')
        }
      ]
    },
    {
      position: 'BTN',
      stackBb: 100,
      heroStackSize: 100,
      villainStackSize: 97.7,
      actionLine: 'preflop: HJ raises 2.3bb, CO calls 2.3bb',
      buckets: [
        {
          actions: [
            'call'
          ],
          combos: expand('2d2c 2h2c 2h2d 2s2c 2s2d 2s2h 3d3c 3h3c 3h3d 3s3c 3s3d 3s3h 4d4c 4h4c 4h4d 4s4c 4s4d 4s4h 5c3c 5c4c 5d3d 5d4d 5d5c 5h3h 5h4h 5h5c 5h5d 5s3s 5s4s 5s5c 5s5d 5s5h 6c4c 6c5c 6d4d 6d5d 6d6c 6h4h 6h5h 6h6c 6h6d 6s4s 6s5s 6s6c 6s6d 6s6h 7c5c 7c6c 7d5d 7d6d 7d7c 7h5h 7h6h 7h7c 7h7d 7s5s 7s6s 7s7c 7s7d 7s7h 8c6c 8c7c 8d6d 8d7d 8d8c 8h6h 8h7h 8h8c 8h8d 8s6s 8s7s 8s8c 8s8d 8s8h 9c7c 9c8c 9d7d 9d8d 9d9c 9h7h 9h8h 9h9c 9h9d 9s7s 9s8s 9s9c 9s9d 9s9h Ac2c Ac3c Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad2d Ad3d Ad4d Ad5d Ad6d Ad7d Ad8d Ad9d AdJc AdJd AdJh AdJs AdQc AdQh AdQs AdTc AdTd AdTh AdTs Ah2h Ah3h Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhJc AhJd AhJh AhJs AhQc AhQd AhQs AhTc AhTd AhTh AhTs As2s As3s As4s As5s As6s As7s As8s As9s AsJc AsJd AsJh AsJs AsQc AsQd AsQh AsTc AsTd AsTh AsTs Jc8c Jc9c JcTc JcTd JcTh JcTs Jd8d Jd9d JdTc JdTd JdTh JdTs Jh8h Jh9h JhTc JhTd JhTh JhTs Js8s Js9s JsTc JsTd JsTh JsTs Kc5c Kc6c Kc7c Kc8c Kc9c KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc Kd5d Kd6d Kd7d Kd8d Kd9d KdJc KdJh KdJs KdQc KdQd KdQh KdQs KdTd Kh5h Kh6h Kh7h Kh8h Kh9h KhJc KhJd KhJs KhQc KhQd KhQh KhQs KhTh Ks5s Ks6s Ks7s Ks8s Ks9s KsJc KsJd KsJh KsQc KsQd KsQh KsQs KsTs Qc8c Qc9c QcJc QcJd QcJh QcJs QcTc QcTd QcTh QcTs Qd8d Qd9d QdJc QdJd QdJh QdJs QdTc QdTd QdTh QdTs Qh8h Qh9h QhJc QhJd QhJh QhJs QhTc QhTd QhTh QhTs Qs8s Qs9s QsJc QsJd QsJh QsJs QsTc QsTd QsTh QsTs Tc8c Tc9c Td8d Td9d TdTc Th8h Th9h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh')
        },
        {
          actions: [
            'fold'
          ],
          combos: expand('4c3c 4d3d 4h3h 4s3s 5c3c 5d3d 5h3h 5s3s 6c4c 6d4d 6h4h 6s4s 7c5c 7d5d 7h5h 7s5s 8c6c 8d6d 8h6h 8s6s 9c6c 9c7c 9d6d 9d7d 9h6h 9h7h 9s6s 9s7s Ac8d Ac8h Ac8s Ac9d Ac9h Ac9s AcTd AcTh AcTs Ad8c Ad8h Ad8s Ad9c Ad9h Ad9s AdTc AdTh AdTs Ah8c Ah8d Ah8s Ah9c Ah9d Ah9s AhTc AhTd AhTs As8c As8d As8h As9c As9d As9h AsTc AsTd AsTh Jc7c Jc8c Jc9d Jc9h Jc9s JcTd JcTh JcTs Jd7d Jd8d Jd9c Jd9h Jd9s JdTc JdTh JdTs Jh7h Jh8h Jh9c Jh9d Jh9s JhTc JhTd JhTs Js7s Js8s Js9c Js9d Js9h JsTc JsTd JsTh Kc4c Kc5c Kc6c Kc7c Kc8c Kc9d Kc9h Kc9s KcJd KcJh KcJs KcTd KcTh KcTs Kd4d Kd5d Kd6d Kd7d Kd8d Kd9c Kd9h Kd9s KdJc KdJh KdJs KdTc KdTh KdTs Kh4h Kh5h Kh6h Kh7h Kh8h Kh9c Kh9d Kh9s KhJc KhJd KhJs KhTc KhTd KhTs Ks4s Ks5s Ks6s Ks7s Ks8s Ks9c Ks9d Ks9h KsJc KsJd KsJh KsTc KsTd KsTh Qc7c Qc8c Qc9d Qc9h Qc9s QcJd QcJh QcJs QcTd QcTh QcTs Qd7d Qd8d Qd9c Qd9h Qd9s QdJc QdJh QdJs QdTc QdTh QdTs Qh7h Qh8h Qh9c Qh9d Qh9s QhJc QhJd QhJs QhTc QhTd QhTs Qs7s Qs8s Qs9c Qs9d Qs9h QsJc QsJd QsJh QsTc QsTd QsTh Tc7c Tc9d Tc9h Tc9s Td7d Td9c Td9h Td9s Th7h Th9c Th9d Th9s Ts7s Ts9c Ts9d Ts9h')
        },
        {
          actions: [
            'raise_8_5'
          ],
          combos: expand('5c4c 5d4d 5h4h 5s4s 6c5c 6d5d 6d6c 6h5h 6h6c 6h6d 6s5s 6s6c 6s6d 6s6h 7c6c 7d6d 7d7c 7h6h 7h7c 7h7d 7s6s 7s7c 7s7d 7s7h 8c7c 8d7d 8d8c 8h7h 8h8c 8h8d 8s7s 8s8c 8s8d 8s8h 9c8c 9d8d 9d9c 9h8h 9h9c 9h9d 9s8s 9s9c 9s9d 9s9h Ac4c Ac5c Ac6c Ac7c Ac8c Ac9c AcJc AcJd AcJh AcJs AcKc AcKd AcKh AcKs AcQc AcQd AcQh AcQs AcTc AcTd AcTh AcTs Ad4d Ad5d Ad6d Ad7d Ad8d Ad9d AdAc AdJc AdJd AdJh AdJs AdKc AdKd AdKh AdKs AdQc AdQd AdQh AdQs AdTc AdTd AdTh AdTs Ah4h Ah5h Ah6h Ah7h Ah8h Ah9h AhAc AhAd AhJc AhJd AhJh AhJs AhKc AhKd AhKh AhKs AhQc AhQd AhQh AhQs AhTc AhTd AhTh AhTs As4s As5s As6s As7s As8s As9s AsAc AsAd AsAh AsJc AsJd AsJh AsJs AsKc AsKd AsKh AsKs AsQc AsQd AsQh AsQs AsTc AsTd AsTh AsTs Jc8c Jc9c JcTc JcTd JcTh JcTs Jd8d Jd9d JdJc JdTc JdTd JdTh JdTs Jh8h Jh9h JhJc JhJd JhTc JhTd JhTh JhTs Js8s Js9s JsJc JsJd JsJh JsTc JsTd JsTh JsTs Kc6c Kc7c Kc8c Kc9c KcJc KcJd KcJh KcJs KcQc KcQd KcQh KcQs KcTc Kd6d Kd7d Kd8d Kd9d KdJc KdJd KdJh KdJs KdKc KdQc KdQd KdQh KdQs KdTd Kh6h Kh7h Kh8h Kh9h KhJc KhJd KhJh KhJs KhKc KhKd KhQc KhQd KhQh KhQs KhTh Ks6s Ks7s Ks8s Ks9s KsJc KsJd KsJh KsJs KsKc KsKd KsKh KsQc KsQd KsQh KsQs KsTs Qc9c QcJc QcJd QcJh QcJs QcTc Qd9d QdJc QdJd QdJh QdJs QdQc QdTd Qh9h QhJc QhJd QhJh QhJs QhQc QhQd QhTh Qs9s QsJc QsJd QsJh QsJs QsQc QsQd QsQh QsTs Tc8c Tc9c Td8d Td9d TdTc Th8h Th9h ThTc ThTd Ts8s Ts9s TsTc TsTd TsTh')
        }
      ]
    }
  ]
};

export default pack;
