// Generated by scripts/import-ct-curriculum.ts. Do not edit by hand.
import type { RangePackRegistryEntry } from './types';

export const RANGE_PACK_REGISTRY: RangePackRegistryEntry[] = [
  {
    slug: 'big-blind-defense-bb-btn-baseline',
    title: 'Big blind defense: BB vs BTN (100/50/25/15bb)',
    description: 'Big blind response practice across stack depths and open sizes.',
    scenario: 'BB_VS_RAISE',
    tier: 'blind_battles',
    methodology: 'gto_cev',
    cellCount: 4,
    bucketCount: 14,
    comboCount: 6810,
    distinctComboCount: 5304,
    source: {
      kind: 'brand_neutralized_snapshot_config',
      capturedAt: '2026-07-18',
      path: 'research/ct-trainer-2026-07-18/',
      sha256: '8e9dca92bac1192760bf35aa3038626a48cad0b8581956f1d6895eac73d6e483'
    },
    chunk: './packs/big-blind-defense-bb-btn-baseline.generated'
  },
  {
    slug: 'big-blind-defense-bb-btn-exploit',
    title: 'Big blind defense: BB vs BTN (80/30bb)',
    description: 'Big blind response practice across stack depths and open sizes.',
    scenario: 'BB_VS_RAISE',
    tier: 'blind_battles',
    methodology: 'mda_exploit',
    cellCount: 2,
    bucketCount: 7,
    comboCount: 2954,
    distinctComboCount: 2330,
    source: {
      kind: 'brand_neutralized_snapshot_config',
      capturedAt: '2026-07-18',
      path: 'research/ct-trainer-2026-07-18/',
      sha256: '4a352365153a2beb28b880296c4ac1cf9b07198b63556110b5ede6fb70748839'
    },
    chunk: './packs/big-blind-defense-bb-btn-exploit.generated'
  },
  {
    slug: 'big-blind-defense-bb-co-baseline',
    title: 'Big blind defense: BB vs CO (100/50/25/15bb)',
    description: 'Big blind response practice across stack depths and open sizes.',
    scenario: 'BB_VS_RAISE',
    tier: 'blind_battles',
    methodology: 'gto_cev',
    cellCount: 4,
    bucketCount: 14,
    comboCount: 5974,
    distinctComboCount: 4836,
    source: {
      kind: 'brand_neutralized_snapshot_config',
      capturedAt: '2026-07-18',
      path: 'research/ct-trainer-2026-07-18/',
      sha256: 'e72e79931b33d2e6991fbe6e752d4a59160ebbe24a6379e60036c4037fda34c4'
    },
    chunk: './packs/big-blind-defense-bb-co-baseline.generated'
  },
  {
    slug: 'big-blind-defense-bb-hj-baseline',
    title: 'Big blind defense: BB vs HJ (100/50/25/15bb)',
    description: 'Big blind response practice across stack depths and open sizes.',
    scenario: 'BB_VS_RAISE',
    tier: 'blind_battles',
    methodology: 'gto_cev',
    cellCount: 4,
    bucketCount: 14,
    comboCount: 5828,
    distinctComboCount: 4788,
    source: {
      kind: 'brand_neutralized_snapshot_config',
      capturedAt: '2026-07-18',
      path: 'research/ct-trainer-2026-07-18/',
      sha256: 'd66d43eac313a8efa9a3b0db12c5b81e12709d214f4798fe3f4fdb3a1fe04097'
    },
    chunk: './packs/big-blind-defense-bb-hj-baseline.generated'
  },
  {
    slug: 'big-blind-defense-bb-utg-baseline',
    title: 'Big blind defense: BB vs UTG (100/50/25/15bb)',
    description: 'Big blind response practice across stack depths and open sizes.',
    scenario: 'BB_VS_RAISE',
    tier: 'blind_battles',
    methodology: 'gto_cev',
    cellCount: 4,
    bucketCount: 13,
    comboCount: 5466,
    distinctComboCount: 4680,
    source: {
      kind: 'brand_neutralized_snapshot_config',
      capturedAt: '2026-07-18',
      path: 'research/ct-trainer-2026-07-18/',
      sha256: '741b3a13f31be327bbccaab33535b2dbf33caf4ceae598f8c335fe2e0c5c58d3'
    },
    chunk: './packs/big-blind-defense-bb-utg-baseline.generated'
  },
  {
    slug: 'blind-battle-bb-sb-vs-jam-baseline',
    title: 'Blind battle: BB vs SB — vs jam (10bb)',
    description: 'Small-blind and big-blind preflop practice for heads-up blind battles.',
    scenario: 'BLIND_WAR',
    tier: 'blind_battles',
    methodology: 'gto_cev',
    cellCount: 1,
    bucketCount: 2,
    comboCount: 766,
    distinctComboCount: 754,
    source: {
      kind: 'brand_neutralized_snapshot_config',
      capturedAt: '2026-07-18',
      path: 'research/ct-trainer-2026-07-18/',
      sha256: '7fbe151b3d1fa409bcd358ecef8fd7f7ba75b8b9d08c1014080c05ff08293973'
    },
    chunk: './packs/blind-battle-bb-sb-vs-jam-baseline.generated'
  },
  {
    slug: 'blind-battle-bb-sb-vs-limp-exploit',
    title: 'Blind battle: BB vs SB — vs limp (60/30/15bb)',
    description: 'Small-blind and big-blind preflop practice for heads-up blind battles.',
    scenario: 'BLIND_WAR',
    tier: 'blind_battles',
    methodology: 'mda_exploit',
    cellCount: 3,
    bucketCount: 9,
    comboCount: 6502,
    distinctComboCount: 3978,
    source: {
      kind: 'brand_neutralized_snapshot_config',
      capturedAt: '2026-07-18',
      path: 'research/ct-trainer-2026-07-18/',
      sha256: 'fb2757a4e4aeb931a0850faed1cd5d3de0f9df37a672e471f24bf0d033cc14c6'
    },
    chunk: './packs/blind-battle-bb-sb-vs-limp-exploit.generated'
  },
  {
    slug: 'blind-battle-bb-sb-vs-limp-exploit-2',
    title: 'Blind battle: BB vs SB — vs limp (100/50/30/20bb)',
    description: 'Small-blind and big-blind preflop practice for heads-up blind battles.',
    scenario: 'BLIND_WAR',
    tier: 'blind_battles',
    methodology: 'mda_exploit',
    cellCount: 4,
    bucketCount: 10,
    comboCount: 8718,
    distinctComboCount: 5304,
    source: {
      kind: 'brand_neutralized_snapshot_config',
      capturedAt: '2026-07-18',
      path: 'research/ct-trainer-2026-07-18/',
      sha256: '241e8ce2a77f7b890d15a0d825089002b693cc6f341feb07f7227b278aaf1890'
    },
    chunk: './packs/blind-battle-bb-sb-vs-limp-exploit-2.generated'
  },
  {
    slug: 'blind-battle-bb-sb-vs-open-baseline',
    title: 'Blind battle: BB vs SB — vs open (60/30/15bb)',
    description: 'Small-blind and big-blind preflop practice for heads-up blind battles.',
    scenario: 'BLIND_WAR',
    tier: 'blind_battles',
    methodology: 'gto_cev',
    cellCount: 3,
    bucketCount: 11,
    comboCount: 5232,
    distinctComboCount: 3978,
    source: {
      kind: 'brand_neutralized_snapshot_config',
      capturedAt: '2026-07-18',
      path: 'research/ct-trainer-2026-07-18/',
      sha256: '5e07d5fd39c5f4f2b145f3c6788d1e4576d56149a4155e5f558b99d583db6ab7'
    },
    chunk: './packs/blind-battle-bb-sb-vs-open-baseline.generated'
  },
  {
    slug: 'blind-battle-sb-bb-sb-open-baseline',
    title: 'Blind battle: SB vs BB — sb open (60/30/15bb)',
    description: 'Small-blind and big-blind preflop practice for heads-up blind battles.',
    scenario: 'BLIND_WAR',
    tier: 'blind_battles',
    methodology: 'gto_cev',
    cellCount: 3,
    bucketCount: 11,
    comboCount: 6178,
    distinctComboCount: 3978,
    source: {
      kind: 'brand_neutralized_snapshot_config',
      capturedAt: '2026-07-18',
      path: 'research/ct-trainer-2026-07-18/',
      sha256: '3732dde89f7249066b58b90648d75b545543ddf59e23c0bf1f6b328feb694d4d'
    },
    chunk: './packs/blind-battle-sb-bb-sb-open-baseline.generated'
  },
  {
    slug: 'blind-battle-sb-bb-sb-open-exploit',
    title: 'Blind battle: SB vs BB — sb open (100-10bb)',
    description: 'Small-blind and big-blind preflop practice for heads-up blind battles.',
    scenario: 'BLIND_WAR',
    tier: 'blind_battles',
    methodology: 'mda_exploit',
    cellCount: 5,
    bucketCount: 17,
    comboCount: 9870,
    distinctComboCount: 6462,
    source: {
      kind: 'brand_neutralized_snapshot_config',
      capturedAt: '2026-07-18',
      path: 'research/ct-trainer-2026-07-18/',
      sha256: 'f7f784f605557f2a9fb4d8e831919dce452743c5d5e2274ff5b447bd119ae73c'
    },
    chunk: './packs/blind-battle-sb-bb-sb-open-exploit.generated'
  },
  {
    slug: 'blind-battle-sb-bb-vs-3-bet-baseline',
    title: 'Blind battle: SB vs BB — vs 3-bet (100/50/25bb)',
    description: 'Small-blind and big-blind preflop practice for heads-up blind battles.',
    scenario: 'BLIND_WAR',
    tier: 'blind_battles',
    methodology: 'gto_cev',
    cellCount: 3,
    bucketCount: 10,
    comboCount: 2630,
    distinctComboCount: 2222,
    source: {
      kind: 'brand_neutralized_snapshot_config',
      capturedAt: '2026-07-18',
      path: 'research/ct-trainer-2026-07-18/',
      sha256: '2dff1d7fc9eef2a1a3f3612ec854082f755a6a8488deff46ff6f493520085cc0'
    },
    chunk: './packs/blind-battle-sb-bb-vs-3-bet-baseline.generated'
  },
  {
    slug: 'blind-battle-sb-bb-vs-3-bet-jam-baseline',
    title: 'Blind battle: SB vs BB — vs 3-bet jam (25/20/15bb)',
    description: 'Small-blind and big-blind preflop practice for heads-up blind battles.',
    scenario: 'BLIND_WAR',
    tier: 'blind_battles',
    methodology: 'gto_cev',
    cellCount: 3,
    bucketCount: 6,
    comboCount: 2052,
    distinctComboCount: 2028,
    source: {
      kind: 'brand_neutralized_snapshot_config',
      capturedAt: '2026-07-18',
      path: 'research/ct-trainer-2026-07-18/',
      sha256: 'baf865d68b5297d3ddf5e9b0d508d403414342231dd1b71e1cfb0ad1e3f5879e'
    },
    chunk: './packs/blind-battle-sb-bb-vs-3-bet-jam-baseline.generated'
  },
  {
    slug: 'blind-battle-sb-bb-vs-iso-raise-baseline',
    title: 'Blind battle: SB vs BB — vs iso-raise (60/30/15bb)',
    description: 'Small-blind and big-blind preflop practice for heads-up blind battles.',
    scenario: 'BLIND_WAR',
    tier: 'blind_battles',
    methodology: 'gto_cev',
    cellCount: 3,
    bucketCount: 11,
    comboCount: 4026,
    distinctComboCount: 3128,
    source: {
      kind: 'brand_neutralized_snapshot_config',
      capturedAt: '2026-07-18',
      path: 'research/ct-trainer-2026-07-18/',
      sha256: 'f9c494ada484645947fb5d9df7d4f20086ec62cbc0eec03b01e2820841fe5a1b'
    },
    chunk: './packs/blind-battle-sb-bb-vs-iso-raise-baseline.generated'
  },
  {
    slug: 'facing-a-3-bet-btn-sb-baseline',
    title: 'Facing a 3-bet: BTN vs SB (100/50/25bb)',
    description: 'Preflop practice after facing a 3-bet, kept separate from imported-hand grading.',
    scenario: 'FACING_3BET',
    tier: 'advanced',
    methodology: 'gto_cev',
    cellCount: 3,
    bucketCount: 10,
    comboCount: 2556,
    distinctComboCount: 2100,
    source: {
      kind: 'brand_neutralized_snapshot_config',
      capturedAt: '2026-07-18',
      path: 'research/ct-trainer-2026-07-18/',
      sha256: '6f6e96fff9b03acd7e22a072ed306e3e73bb5e428695a192dfc51841ed04b3ab'
    },
    chunk: './packs/facing-a-3-bet-btn-sb-baseline.generated'
  },
  {
    slug: 'facing-a-3-bet-btn-sb-vs-3-bet-jam-baseline',
    title: 'Facing a 3-bet: BTN vs SB — vs 3-bet jam (25/20/14bb)',
    description: 'Preflop practice after facing a 3-bet, kept separate from imported-hand grading.',
    scenario: 'FACING_3BET',
    tier: 'advanced',
    methodology: 'gto_cev',
    cellCount: 3,
    bucketCount: 6,
    comboCount: 1370,
    distinctComboCount: 1370,
    source: {
      kind: 'brand_neutralized_snapshot_config',
      capturedAt: '2026-07-18',
      path: 'research/ct-trainer-2026-07-18/',
      sha256: '1de8a2e3124e4033099574a9711afd278ae017a2490e0ee0577d3fefcf86569d'
    },
    chunk: './packs/facing-a-3-bet-btn-sb-vs-3-bet-jam-baseline.generated'
  },
  {
    slug: 'facing-a-3-bet-co-btn-baseline',
    title: 'Facing a 3-bet: CO vs BTN (100/50/25bb)',
    description: 'Preflop practice after facing a 3-bet, kept separate from imported-hand grading.',
    scenario: 'FACING_3BET',
    tier: 'advanced',
    methodology: 'gto_cev',
    cellCount: 3,
    bucketCount: 11,
    comboCount: 2044,
    distinctComboCount: 1520,
    source: {
      kind: 'brand_neutralized_snapshot_config',
      capturedAt: '2026-07-18',
      path: 'research/ct-trainer-2026-07-18/',
      sha256: '7e801bb95007cf71d7c6ce99984d2f284731c5c61f980c0043830555c571731f'
    },
    chunk: './packs/facing-a-3-bet-co-btn-baseline.generated'
  },
  {
    slug: 'facing-a-3-bet-co-btn-vs-3-bet-jam-baseline',
    title: 'Facing a 3-bet: CO vs BTN — vs 3-bet jam (25/20/14bb)',
    description: 'Preflop practice after facing a 3-bet, kept separate from imported-hand grading.',
    scenario: 'FACING_3BET',
    tier: 'advanced',
    methodology: 'gto_cev',
    cellCount: 3,
    bucketCount: 6,
    comboCount: 1170,
    distinctComboCount: 1140,
    source: {
      kind: 'brand_neutralized_snapshot_config',
      capturedAt: '2026-07-18',
      path: 'research/ct-trainer-2026-07-18/',
      sha256: 'f493ef03af32a50bf9f9287b4e0851855b2a8c937f45fdd05592663f05a2df0a'
    },
    chunk: './packs/facing-a-3-bet-co-btn-vs-3-bet-jam-baseline.generated'
  },
  {
    slug: 'facing-a-3-bet-hj-bb-vs-3-bet-jam-baseline',
    title: 'Facing a 3-bet: HJ vs BB — vs 3-bet jam (25/20/14bb)',
    description: 'Preflop practice after facing a 3-bet, kept separate from imported-hand grading.',
    scenario: 'FACING_3BET',
    tier: 'advanced',
    methodology: 'gto_cev',
    cellCount: 3,
    bucketCount: 6,
    comboCount: 1048,
    distinctComboCount: 1014,
    source: {
      kind: 'brand_neutralized_snapshot_config',
      capturedAt: '2026-07-18',
      path: 'research/ct-trainer-2026-07-18/',
      sha256: 'd90f4ed547ab9570741e4bbd95ad2eefea0965d51fc2fb066151dc611dab18bd'
    },
    chunk: './packs/facing-a-3-bet-hj-bb-vs-3-bet-jam-baseline.generated'
  },
  {
    slug: 'facing-a-3-bet-utg-co-baseline',
    title: 'Facing a 3-bet: UTG vs CO (100/50/25bb)',
    description: 'Preflop practice after facing a 3-bet, kept separate from imported-hand grading.',
    scenario: 'FACING_3BET',
    tier: 'advanced',
    methodology: 'gto_cev',
    cellCount: 3,
    bucketCount: 11,
    comboCount: 1160,
    distinctComboCount: 794,
    source: {
      kind: 'brand_neutralized_snapshot_config',
      capturedAt: '2026-07-18',
      path: 'research/ct-trainer-2026-07-18/',
      sha256: 'ca9bac5b739807a91b3479eafed0f54fcb39c55b1d9e2480dbcc8cc11360de1e'
    },
    chunk: './packs/facing-a-3-bet-utg-co-baseline.generated'
  },
  {
    slug: 'facing-an-open-btn-co-vs-jam-baseline',
    title: 'Facing an open: BTN vs CO — vs jam (10bb)',
    description: 'Preflop response practice when another player opens first.',
    scenario: 'FACING_RAISE',
    tier: 'foundational',
    methodology: 'gto_cev',
    cellCount: 1,
    bucketCount: 2,
    comboCount: 414,
    distinctComboCount: 414,
    source: {
      kind: 'brand_neutralized_snapshot_config',
      capturedAt: '2026-07-18',
      path: 'research/ct-trainer-2026-07-18/',
      sha256: 'ca7ada642390239294d2032288edc85dbeb146c2cc3340efae9f65eea3cb3e58'
    },
    chunk: './packs/facing-an-open-btn-co-vs-jam-baseline.generated'
  },
  {
    slug: 'facing-an-open-btn-co-vs-open-baseline',
    title: 'Facing an open: BTN vs CO — vs open (100/50/25/15bb)',
    description: 'Preflop response practice when another player opens first.',
    scenario: 'FACING_RAISE',
    tier: 'foundational',
    methodology: 'gto_cev',
    cellCount: 4,
    bucketCount: 13,
    comboCount: 3452,
    distinctComboCount: 2488,
    source: {
      kind: 'brand_neutralized_snapshot_config',
      capturedAt: '2026-07-18',
      path: 'research/ct-trainer-2026-07-18/',
      sha256: '75d3c2e5f0938221ed27d8d095d850fa5c5a1c391be2fed5b9825d3727506dd4'
    },
    chunk: './packs/facing-an-open-btn-co-vs-open-baseline.generated'
  },
  {
    slug: 'facing-an-open-btn-co-vs-open-exploit',
    title: 'Facing an open: BTN vs CO — vs open (30bb)',
    description: 'Preflop response practice when another player opens first.',
    scenario: 'FACING_RAISE',
    tier: 'foundational',
    methodology: 'mda_exploit',
    cellCount: 1,
    bucketCount: 3,
    comboCount: 584,
    distinctComboCount: 478,
    source: {
      kind: 'brand_neutralized_snapshot_config',
      capturedAt: '2026-07-18',
      path: 'research/ct-trainer-2026-07-18/',
      sha256: 'b6f8b9f295a21fffc2335cdd9e110c2fbb2f754013d5863662324d45f092d750'
    },
    chunk: './packs/facing-an-open-btn-co-vs-open-exploit.generated'
  },
  {
    slug: 'facing-an-open-co-hj-vs-open-baseline',
    title: 'Facing an open: CO vs HJ — vs open (100/50/25/15bb)',
    description: 'Preflop response practice when another player opens first.',
    scenario: 'FACING_RAISE',
    tier: 'foundational',
    methodology: 'gto_cev',
    cellCount: 4,
    bucketCount: 13,
    comboCount: 2818,
    distinctComboCount: 1912,
    source: {
      kind: 'brand_neutralized_snapshot_config',
      capturedAt: '2026-07-18',
      path: 'research/ct-trainer-2026-07-18/',
      sha256: '243bb0645be2ba0e0c4ebf244ecdf030ad9ce4c5c3e2092349b42fc43b7c963e'
    },
    chunk: './packs/facing-an-open-co-hj-vs-open-baseline.generated'
  },
  {
    slug: 'facing-an-open-hj-lj-vs-open-baseline',
    title: 'Facing an open: HJ vs LJ — vs open (100/50/25/15bb)',
    description: 'Preflop response practice when another player opens first.',
    scenario: 'FACING_RAISE',
    tier: 'foundational',
    methodology: 'gto_cev',
    cellCount: 4,
    bucketCount: 13,
    comboCount: 2374,
    distinctComboCount: 1592,
    source: {
      kind: 'brand_neutralized_snapshot_config',
      capturedAt: '2026-07-18',
      path: 'research/ct-trainer-2026-07-18/',
      sha256: 'cefe5e5b9973aa4b126c1fcfca7b9868b5ff5aba0c21a8d888afc11c30975c29'
    },
    chunk: './packs/facing-an-open-hj-lj-vs-open-baseline.generated'
  },
  {
    slug: 'facing-an-open-sb-btn-vs-open-baseline',
    title: 'Facing an open: SB vs BTN — vs open (100/50/25/15bb)',
    description: 'Preflop response practice when another player opens first.',
    scenario: 'FACING_RAISE',
    tier: 'foundational',
    methodology: 'gto_cev',
    cellCount: 4,
    bucketCount: 13,
    comboCount: 3398,
    distinctComboCount: 2496,
    source: {
      kind: 'brand_neutralized_snapshot_config',
      capturedAt: '2026-07-18',
      path: 'research/ct-trainer-2026-07-18/',
      sha256: '0e3377ea9379f1452de67487ea289feac19d0f4d4c537afcc2b068d3c52ec576'
    },
    chunk: './packs/facing-an-open-sb-btn-vs-open-baseline.generated'
  },
  {
    slug: 'facing-an-open-sb-btn-vs-open-exploit',
    title: 'Facing an open: SB vs BTN — vs open (80/30bb)',
    description: 'Preflop response practice when another player opens first.',
    scenario: 'FACING_RAISE',
    tier: 'foundational',
    methodology: 'mda_exploit',
    cellCount: 2,
    bucketCount: 7,
    comboCount: 1474,
    distinctComboCount: 1012,
    source: {
      kind: 'brand_neutralized_snapshot_config',
      capturedAt: '2026-07-18',
      path: 'research/ct-trainer-2026-07-18/',
      sha256: '5885ae5d6e06ec760f0f81a1f44090e16bcea8f4df28a5f19da62bdca435d6d9'
    },
    chunk: './packs/facing-an-open-sb-btn-vs-open-exploit.generated'
  },
  {
    slug: 'facing-an-open-sb-utg-vs-open-baseline',
    title: 'Facing an open: SB vs UTG — vs open (100/50/25/15bb)',
    description: 'Preflop response practice when another player opens first.',
    scenario: 'FACING_RAISE',
    tier: 'foundational',
    methodology: 'gto_cev',
    cellCount: 4,
    bucketCount: 13,
    comboCount: 2588,
    distinctComboCount: 1944,
    source: {
      kind: 'brand_neutralized_snapshot_config',
      capturedAt: '2026-07-18',
      path: 'research/ct-trainer-2026-07-18/',
      sha256: '246c91191d987405cd173dd083905bb0b54c68938606e485c2477f09c99f18e8'
    },
    chunk: './packs/facing-an-open-sb-utg-vs-open-baseline.generated'
  },
  {
    slug: 'facing-an-open-utgplus1-lj-hj-co-btn-sb-utg-lj-hj-co-btn-vs-open-pko-70pct-left-baseline',
    title: 'Facing an open: UTG+1/LJ/HJ/CO/BTN/SB vs UTG+LJ+HJ+CO+BTN — vs open (66-34bb) — ICM PKO 70% Left',
    description: 'Preflop response practice when another player opens first.',
    scenario: 'FACING_RAISE',
    tier: 'foundational',
    methodology: 'gto_cev',
    stageContext: 'Tournament ICM context: PKO 70% Left',
    cellCount: 16,
    bucketCount: 49,
    comboCount: 5202,
    distinctComboCount: 2059,
    source: {
      kind: 'brand_neutralized_snapshot_config',
      capturedAt: '2026-07-18',
      path: 'research/ct-trainer-2026-07-18/',
      sha256: '8a22144e77583cfff27d062776a5486403713a5cdb13c0a84b4dc6899409c29a'
    },
    chunk: './packs/facing-an-open-utgplus1-lj-hj-co-btn-sb-utg-lj-hj-co-btn-vs-open-pko-70pct-left-baseline.generated'
  },
  {
    slug: 'facing-an-open-utgplus1-utg-vs-open-baseline',
    title: 'Facing an open: UTG+1 vs UTG — vs open (100/50/25/15bb)',
    description: 'Preflop response practice when another player opens first.',
    scenario: 'FACING_RAISE',
    tier: 'foundational',
    methodology: 'gto_cev',
    cellCount: 4,
    bucketCount: 14,
    comboCount: 1936,
    distinctComboCount: 1272,
    source: {
      kind: 'brand_neutralized_snapshot_config',
      capturedAt: '2026-07-18',
      path: 'research/ct-trainer-2026-07-18/',
      sha256: 'e8fdaadbdc3ebdcfd935dc4bddc43f287a84ea42dddca016a473f82527be5292'
    },
    chunk: './packs/facing-an-open-utgplus1-utg-vs-open-baseline.generated'
  },
  {
    slug: 'multiway-big-blind-defense-bb-btn-sb-baseline',
    title: 'Multiway big blind defense: BB vs BTN+SB (100/25bb)',
    description: 'Big blind defense practice in multiway raised pots.',
    scenario: 'BB_VS_RAISE_MULTIWAY',
    tier: 'blind_battles',
    methodology: 'gto_cev',
    cellCount: 2,
    bucketCount: 7,
    comboCount: 3268,
    distinctComboCount: 2652,
    source: {
      kind: 'brand_neutralized_snapshot_config',
      capturedAt: '2026-07-18',
      path: 'research/ct-trainer-2026-07-18/',
      sha256: '33da7719c9ea0fc54cd352e30e0f2fed0d15f04db2f64594e5c214a66ad744ed'
    },
    chunk: './packs/multiway-big-blind-defense-bb-btn-sb-baseline.generated'
  },
  {
    slug: 'multiway-big-blind-defense-bb-co-btn-baseline',
    title: 'Multiway big blind defense: BB vs CO+BTN (100/25bb)',
    description: 'Big blind defense practice in multiway raised pots.',
    scenario: 'BB_VS_RAISE_MULTIWAY',
    tier: 'blind_battles',
    methodology: 'gto_cev',
    cellCount: 2,
    bucketCount: 7,
    comboCount: 2540,
    distinctComboCount: 2148,
    source: {
      kind: 'brand_neutralized_snapshot_config',
      capturedAt: '2026-07-18',
      path: 'research/ct-trainer-2026-07-18/',
      sha256: '1783957f6341a1e35c1ad2f619cc2c6c7c4b02c87aedc8a7c929a6f8df3e7ce5'
    },
    chunk: './packs/multiway-big-blind-defense-bb-co-btn-baseline.generated'
  },
  {
    slug: 'multiway-big-blind-defense-bb-co-sb-baseline',
    title: 'Multiway big blind defense: BB vs CO+SB (100/25bb)',
    description: 'Big blind defense practice in multiway raised pots.',
    scenario: 'BB_VS_RAISE_MULTIWAY',
    tier: 'blind_battles',
    methodology: 'gto_cev',
    cellCount: 2,
    bucketCount: 6,
    comboCount: 2634,
    distinctComboCount: 2304,
    source: {
      kind: 'brand_neutralized_snapshot_config',
      capturedAt: '2026-07-18',
      path: 'research/ct-trainer-2026-07-18/',
      sha256: '05371d38b02675b97318a76fdcc0c52571da5299d42716880f3a8fa113eb0c58'
    },
    chunk: './packs/multiway-big-blind-defense-bb-co-sb-baseline.generated'
  },
  {
    slug: 'multiway-big-blind-defense-bb-utg-lj-baseline',
    title: 'Multiway big blind defense: BB vs UTG+LJ (100/25bb)',
    description: 'Big blind defense practice in multiway raised pots.',
    scenario: 'BB_VS_RAISE_MULTIWAY',
    tier: 'blind_battles',
    methodology: 'gto_cev',
    cellCount: 2,
    bucketCount: 8,
    comboCount: 2332,
    distinctComboCount: 1956,
    source: {
      kind: 'brand_neutralized_snapshot_config',
      capturedAt: '2026-07-18',
      path: 'research/ct-trainer-2026-07-18/',
      sha256: '2a42eeaaafc5849fefd7a6d648967f86aba285ce808fdd38b07b16c8be0cb23b'
    },
    chunk: './packs/multiway-big-blind-defense-bb-utg-lj-baseline.generated'
  },
  {
    slug: 'multiway-big-blind-defense-bb-utgplus1-hj-baseline',
    title: 'Multiway big blind defense: BB vs UTG+1+HJ (100/25bb)',
    description: 'Big blind defense practice in multiway raised pots.',
    scenario: 'BB_VS_RAISE_MULTIWAY',
    tier: 'blind_battles',
    methodology: 'gto_cev',
    cellCount: 2,
    bucketCount: 8,
    comboCount: 1132,
    distinctComboCount: 892,
    source: {
      kind: 'brand_neutralized_snapshot_config',
      capturedAt: '2026-07-18',
      path: 'research/ct-trainer-2026-07-18/',
      sha256: 'e41f859da4c30eeba297e12563ee114c60aa5f860abb6480bd845695523aa79b'
    },
    chunk: './packs/multiway-big-blind-defense-bb-utgplus1-hj-baseline.generated'
  },
  {
    slug: 'open-raising-hj-co-btn-bb-late-seats-baseline',
    title: 'Open-raising: HJ/CO/BTN vs BB — late seats (100/50/25/15bb)',
    description: 'Preflop opener practice across positions and stack depths.',
    scenario: 'RFI',
    tier: 'foundational',
    methodology: 'gto_cev',
    cellCount: 12,
    bucketCount: 27,
    comboCount: 10466,
    distinctComboCount: 9592,
    source: {
      kind: 'brand_neutralized_snapshot_config',
      capturedAt: '2026-07-18',
      path: 'research/ct-trainer-2026-07-18/',
      sha256: '00690c65d063938bbaffeaaa45f8692f6646d4c8d32f7eeff13a0c62e6a165e0'
    },
    chunk: './packs/open-raising-hj-co-btn-bb-late-seats-baseline.generated'
  },
  {
    slug: 'open-raising-utg-lj-hj-co-btn-bb-exploit',
    title: 'Open-raising: UTG/LJ/HJ/CO/BTN vs BB (50bb)',
    description: 'Preflop opener practice across positions and stack depths.',
    scenario: 'RFI',
    tier: 'foundational',
    methodology: 'mda_exploit',
    cellCount: 5,
    bucketCount: 10,
    comboCount: 2224,
    distinctComboCount: 1872,
    source: {
      kind: 'brand_neutralized_snapshot_config',
      capturedAt: '2026-07-18',
      path: 'research/ct-trainer-2026-07-18/',
      sha256: '469782b7a134800af83c0b1d62c2f75418186e9029fcf04e298b165bb5378a9a'
    },
    chunk: './packs/open-raising-utg-lj-hj-co-btn-bb-exploit.generated'
  },
  {
    slug: 'open-raising-utg-lj-hj-co-btn-sb-bb-short-stack-baseline',
    title: 'Open-raising: UTG/LJ/HJ/CO/BTN/SB vs BB — short stack (10bb)',
    description: 'Preflop opener practice across positions and stack depths.',
    scenario: 'RFI',
    tier: 'foundational',
    methodology: 'gto_cev',
    cellCount: 6,
    bucketCount: 12,
    comboCount: 8166,
    distinctComboCount: 7928,
    source: {
      kind: 'brand_neutralized_snapshot_config',
      capturedAt: '2026-07-18',
      path: 'research/ct-trainer-2026-07-18/',
      sha256: 'c2c9721854ec1792e36d1421eb0842cd2e2f7fa15cbbbad7d9ef87e84b777689'
    },
    chunk: './packs/open-raising-utg-lj-hj-co-btn-sb-bb-short-stack-baseline.generated'
  },
  {
    slug: 'open-raising-utg-utgplus1-lj-bb-early-seats-baseline',
    title: 'Open-raising: UTG/UTG+1/LJ vs BB — early seats (100/50/25/15bb)',
    description: 'Preflop opener practice across positions and stack depths.',
    scenario: 'RFI',
    tier: 'foundational',
    methodology: 'gto_cev',
    cellCount: 12,
    bucketCount: 27,
    comboCount: 6050,
    distinctComboCount: 5328,
    source: {
      kind: 'brand_neutralized_snapshot_config',
      capturedAt: '2026-07-18',
      path: 'research/ct-trainer-2026-07-18/',
      sha256: '7f0840dc5e16a71dec60eb628ec56b0b35940bc770f49c00195b3ac7b265e25d'
    },
    chunk: './packs/open-raising-utg-utgplus1-lj-bb-early-seats-baseline.generated'
  },
  {
    slug: 'open-raising-utg-utgplus1-lj-hj-co-btn-bb-pko-70pct-left-baseline',
    title: 'Open-raising: UTG/UTG+1/LJ/HJ/CO/BTN vs BB (50bb) — ICM PKO 70% Left',
    description: 'Preflop opener practice across positions and stack depths.',
    scenario: 'RFI',
    tier: 'foundational',
    methodology: 'gto_cev',
    stageContext: 'Tournament ICM context: PKO 70% Left',
    cellCount: 6,
    bucketCount: 12,
    comboCount: 585,
    distinctComboCount: 528,
    source: {
      kind: 'brand_neutralized_snapshot_config',
      capturedAt: '2026-07-18',
      path: 'research/ct-trainer-2026-07-18/',
      sha256: '882adb8fa45477ccebd829edb6d617a36e32ff31b9e91bcb429ff309b01b3d92'
    },
    chunk: './packs/open-raising-utg-utgplus1-lj-hj-co-btn-bb-pko-70pct-left-baseline.generated'
  },
  {
    slug: 'open-raising-utg-utgplus1-lj-hj-co-btn-bb-vanilla-50pct-left-baseline',
    title: 'Open-raising: UTG/UTG+1/LJ/HJ/CO/BTN vs BB (50-15bb) — ICM Vanilla 50% Left',
    description: 'Preflop opener practice across positions and stack depths.',
    scenario: 'RFI',
    tier: 'foundational',
    methodology: 'gto_cev',
    stageContext: 'Tournament ICM context: Vanilla 50% Left',
    cellCount: 6,
    bucketCount: 13,
    comboCount: 727,
    distinctComboCount: 678,
    source: {
      kind: 'brand_neutralized_snapshot_config',
      capturedAt: '2026-07-18',
      path: 'research/ct-trainer-2026-07-18/',
      sha256: 'a1caa377c71f43b305240f0c176df2742f4cc0e2a10d286b1a760431cedded74'
    },
    chunk: './packs/open-raising-utg-utgplus1-lj-hj-co-btn-bb-vanilla-50pct-left-baseline.generated'
  },
  {
    slug: 'squeeze-bb-co-btn-baseline',
    title: 'Squeeze: BB vs CO+BTN (100/25bb)',
    description: 'Preflop squeeze practice after an open and a cold caller.',
    scenario: 'FACING_RAISE',
    tier: 'advanced',
    methodology: 'gto_cev',
    cellCount: 2,
    bucketCount: 5,
    comboCount: 1272,
    distinctComboCount: 1000,
    source: {
      kind: 'brand_neutralized_snapshot_config',
      capturedAt: '2026-07-18',
      path: 'research/ct-trainer-2026-07-18/',
      sha256: '2f97d3828a49e7a82c658786bea465415bbfeacca36c5eb49e0e6893e5252bc4'
    },
    chunk: './packs/squeeze-bb-co-btn-baseline.generated'
  },
  {
    slug: 'squeeze-btn-hj-co-baseline',
    title: 'Squeeze: BTN vs HJ+CO (100/50/25bb)',
    description: 'Preflop squeeze practice after an open and a cold caller.',
    scenario: 'FACING_RAISE',
    tier: 'advanced',
    methodology: 'gto_cev',
    cellCount: 3,
    bucketCount: 11,
    comboCount: 1890,
    distinctComboCount: 1182,
    source: {
      kind: 'brand_neutralized_snapshot_config',
      capturedAt: '2026-07-18',
      path: 'research/ct-trainer-2026-07-18/',
      sha256: '5b9656ad935cba6e612ac6affd42949f86697a36a8f1a2f954b0402ed43f1e4f'
    },
    chunk: './packs/squeeze-btn-hj-co-baseline.generated'
  },
  {
    slug: 'squeeze-hj-utg-lj-baseline',
    title: 'Squeeze: HJ vs UTG+LJ (100/50/25bb)',
    description: 'Preflop squeeze practice after an open and a cold caller.',
    scenario: 'FACING_RAISE',
    tier: 'advanced',
    methodology: 'gto_cev',
    cellCount: 3,
    bucketCount: 11,
    comboCount: 1474,
    distinctComboCount: 914,
    source: {
      kind: 'brand_neutralized_snapshot_config',
      capturedAt: '2026-07-18',
      path: 'research/ct-trainer-2026-07-18/',
      sha256: 'ddef514be79e56ef68120873638e76b4cacf0518843d2cefde706426a7c60445'
    },
    chunk: './packs/squeeze-hj-utg-lj-baseline.generated'
  },
  {
    slug: 'squeeze-sb-co-btn-baseline',
    title: 'Squeeze: SB vs CO+BTN (100/50/25bb)',
    description: 'Preflop squeeze practice after an open and a cold caller.',
    scenario: 'FACING_RAISE',
    tier: 'advanced',
    methodology: 'gto_cev',
    cellCount: 3,
    bucketCount: 11,
    comboCount: 1970,
    distinctComboCount: 1294,
    source: {
      kind: 'brand_neutralized_snapshot_config',
      capturedAt: '2026-07-18',
      path: 'research/ct-trainer-2026-07-18/',
      sha256: '1bec09222f16e48d4451afb577afad886899aa4f609e60245e0451e180452bf3'
    },
    chunk: './packs/squeeze-sb-co-btn-baseline.generated'
  }
];
