#!/usr/bin/env tsx
/**
 * Regenerate the reports index in docs/reports/README.md from each report's
 * YAML frontmatter.
 *
 * Scans docs/reports/*.md (active) and docs/reports/archive/*.md (archived),
 * excludes README.md, and writes a status dashboard between
 * <!-- BEGIN:AUTOGEN:reports-index --> / <!-- END:AUTOGEN:reports-index -->.
 *
 * Each report MUST carry frontmatter `status: open | in_progress | resolved |
 * superseded` (+ `date:`, optional `related:`, `superseded_by:`). A report with
 * no status is a hard error — every report must be classified. The display title
 * is derived from the report's first `# ` heading (no title-drift).
 *
 * Churn-free by construction: derived only from frontmatter + filenames, never
 * from a commit SHA or the current date, so `docs:check` does not fail per-commit.
 *
 * Usage:
 *   tsx scripts/regen-reports-index.ts          # rewrite README in place
 *   tsx scripts/regen-reports-index.ts --check  # exit 1 if README is stale
 */
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const REPO_ROOT = join(__dirname, '..');
const REPORTS_DIR = join(REPO_ROOT, 'docs', 'reports');
const ARCHIVE_DIR = join(REPORTS_DIR, 'archive');
const README_PATH = join(REPORTS_DIR, 'README.md');

const CHECK = process.argv.includes('--check');

const STATUSES = ['open', 'in_progress', 'resolved', 'superseded'] as const;
type Status = (typeof STATUSES)[number];

interface ReportMeta {
  rel: string; // path relative to docs/reports/ used for links
  status: Status;
  title: string;
  date: string;
  related: string[];
  supersededBy: string | null;
}

function isStatus(v: string): v is Status {
  return (STATUSES as readonly string[]).includes(v);
}

function frontmatter(raw: string): { fm: string; body: string } | null {
  if (!raw.startsWith('---')) return null;
  const end = raw.indexOf('\n---', 3);
  if (end === -1) return null;
  const after = raw.indexOf('\n', end + 1);
  return { fm: raw.slice(3, end), body: after === -1 ? '' : raw.slice(after + 1) };
}

function scalar(fm: string, key: string): string | null {
  const m = new RegExp(`^\\s*${key}:\\s*(.+?)\\s*$`, 'm').exec(fm);
  return m ? m[1]! : null;
}

function list(fm: string, key: string): string[] {
  const v = scalar(fm, key);
  if (!v) return [];
  return v
    .replace(/^\[|\]$/g, '')
    .split(',')
    .map((s) => s.trim().replace(/^['"]|['"]$/g, ''))
    .filter(Boolean);
}

function h1Title(body: string, fallback: string): string {
  const m = /^#\s+(.+?)\s*$/m.exec(body);
  return m ? m[1]! : fallback;
}

function collect(dir: string, relPrefix: string): ReportMeta[] {
  if (!existsSync(dir)) return [];
  const out: ReportMeta[] = [];
  for (const file of readdirSync(dir)) {
    if (!file.endsWith('.md') || file === 'README.md') continue;
    const raw = readFileSync(join(dir, file), 'utf-8');
    const parsed = frontmatter(raw);
    const status = parsed && scalar(parsed.fm, 'status');
    if (!parsed || !status || !isStatus(status)) {
      console.error(
        `docs/reports/${relPrefix}${file}: missing or invalid \`status\` frontmatter ` +
          `(expected one of ${STATUSES.join(' | ')}). Every report must be classified.`,
      );
      process.exit(2);
    }
    out.push({
      rel: `${relPrefix}${file}`,
      status,
      title: h1Title(parsed.body, file),
      date: scalar(parsed.fm, 'date') ?? '—',
      related: list(parsed.fm, 'related'),
      supersededBy: scalar(parsed.fm, 'superseded_by'),
    });
  }
  return out;
}

function notes(r: ReportMeta): string {
  const parts: string[] = [];
  if (r.supersededBy) parts.push(`→ \`${r.supersededBy}\``);
  if (r.related.length) parts.push(r.related.join(', '));
  return parts.join(' · ') || '—';
}

function section(label: string, reports: ReportMeta[], noteHeader: string): string {
  const rows = [...reports].sort((a, b) => b.date.localeCompare(a.date));
  const lines = [`### ${label} (${rows.length})`, ''];
  if (rows.length === 0) {
    lines.push('_None._');
    return lines.join('\n');
  }
  lines.push(`| Date | Report | ${noteHeader} |`, '|---|---|---|');
  for (const r of rows) lines.push(`| ${r.date} | [${r.title}](${r.rel}) | ${notes(r)} |`);
  return lines.join('\n');
}

function indexBlock(): string {
  const active = collect(REPORTS_DIR, '');
  const archived = collect(ARCHIVE_DIR, 'archive/');
  const all = [...active, ...archived];
  const by = (s: Status) => all.filter((r) => r.status === s);
  return [
    '_Regenerated by `npm run docs:update`; enforced by `docs:check`. Do not edit by hand._',
    '',
    '**Active** — `docs/reports/`',
    '',
    section('🔴 Open', by('open'), 'Notes'),
    '',
    section('🟡 In progress', by('in_progress'), 'Notes'),
    '',
    '**Archived** — `docs/reports/archive/`',
    '',
    section('✅ Resolved', by('resolved'), 'Closed by'),
    '',
    section('🗄 Superseded', by('superseded'), 'Superseded by · notes'),
  ].join('\n');
}

const BEGIN = '<!-- BEGIN:AUTOGEN:reports-index -->';
const END = '<!-- END:AUTOGEN:reports-index -->';

const current = readFileSync(README_PATH, 'utf-8');
const re = new RegExp(`${BEGIN}[\\s\\S]*?${END}`);
if (!re.test(current)) {
  console.error(`Missing marker block in ${README_PATH}. Add:\n${BEGIN}\n\n${END}`);
  process.exit(2);
}
const next = current.replace(re, `${BEGIN}\n${indexBlock()}\n${END}`);

if (CHECK) {
  if (current !== next) {
    console.error('docs/reports/README.md index is stale. Run: npm run docs:update');
    process.exit(1);
  }
  process.exit(0);
}

if (current !== next) {
  writeFileSync(README_PATH, next, 'utf-8');
  console.log('docs/reports/README.md index updated.');
} else {
  console.log('docs/reports/README.md index already up to date.');
}
